create extension if not exists pgcrypto;

create table if not exists public.repair_prices (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  issue text not null,
  price text not null default '',
  turnaround_time text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint repair_prices_unique unique (brand, model, issue)
);

create table if not exists public.repair_intakes (
  id bigint generated by default as identity primary key,
  source_type text not null default 'quote',
  customer_name text not null,
  customer_phone text not null default '',
  customer_email text not null default '',
  contact_method text not null default 'Phone',
  device_type text not null default '',
  device_model text not null default '',
  quoted_price text not null default '',
  repair_issue text not null default '',
  estimated_time text not null default '',
  password_type text not null default 'text',
  password_text text not null default '',
  pattern_value text not null default '',
  password_none_reason text,
  device_id_type text not null default 'imei',
  device_id_imei text not null default '',
  device_id_sn text not null default '',
  device_id_unavailable_reason text,
  testable text not null default 'yes',
  test_profile text not null default 'mobile',
  cannot_test_reason text,
  test_notes text,
  test_results_json jsonb not null default '[]'::jsonb,
  quote_data_json jsonb not null default '{}'::jsonb,
  intake_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.apple_model_map (
  id bigint generated by default as identity primary key,
  a_number text not null unique,
  family_key text not null,
  model_name text not null,
  linked_price_list_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_config (
  id boolean primary key default true,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.admin_config (id, password_hash)
values (true, crypt('008009', gen_salt('bf')))
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists repair_prices_set_updated_at on public.repair_prices;
create trigger repair_prices_set_updated_at
before update on public.repair_prices
for each row
execute function public.set_updated_at();

drop trigger if exists repair_intakes_set_updated_at on public.repair_intakes;
create trigger repair_intakes_set_updated_at
before update on public.repair_intakes
for each row
execute function public.set_updated_at();

drop trigger if exists apple_model_map_set_updated_at on public.apple_model_map;
create trigger apple_model_map_set_updated_at
before update on public.apple_model_map
for each row
execute function public.set_updated_at();

drop trigger if exists admin_config_set_updated_at on public.admin_config;
create trigger admin_config_set_updated_at
before update on public.admin_config
for each row
execute function public.set_updated_at();

alter table public.repair_prices enable row level security;
alter table public.repair_intakes enable row level security;
alter table public.apple_model_map enable row level security;
alter table public.admin_config enable row level security;

drop policy if exists repair_prices_select_all on public.repair_prices;
create policy repair_prices_select_all
on public.repair_prices
for select
to anon, authenticated
using (true);

drop policy if exists repair_intakes_insert_all on public.repair_intakes;
create policy repair_intakes_insert_all
on public.repair_intakes
for insert
to anon, authenticated
with check (true);

drop policy if exists apple_model_map_select_all on public.apple_model_map;
create policy apple_model_map_select_all
on public.apple_model_map
for select
to anon, authenticated
using (true);

drop policy if exists admin_config_no_access on public.admin_config;
create policy admin_config_no_access
on public.admin_config
for select
to authenticated
using (false);

create or replace function public.save_repair_prices(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
begin
  if jsonb_typeof(payload) <> 'array' then
    raise exception 'Payload must be a JSON array';
  end if;

  delete from public.repair_prices;

  for item in select * from jsonb_array_elements(payload)
  loop
    insert into public.repair_prices (brand, model, issue, price, turnaround_time)
    values (
      coalesce(trim(item->>'brand'), ''),
      coalesce(trim(item->>'model'), ''),
      coalesce(trim(item->>'issue'), ''),
      coalesce(trim(item->>'price'), ''),
      coalesce(trim(item->>'time'), '')
    );
  end loop;

  return jsonb_build_object(
    'ok', true,
    'saved', jsonb_array_length(payload)
  );
end;
$$;

create or replace function public.save_apple_model_map(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  family_key text;
  family_payload jsonb;
  entry record;
begin
  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  delete from public.apple_model_map;

  for family_key, family_payload in
    select key, value
    from jsonb_each(payload)
  loop
    if jsonb_typeof(family_payload) <> 'object' then
      continue;
    end if;

    for entry in
      select key, value
      from jsonb_each_text(family_payload)
    loop
      insert into public.apple_model_map (a_number, family_key, model_name)
      values (entry.key, family_key, entry.value);
    end loop;
  end loop;

  return jsonb_build_object('ok', true);
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.repair_prices to anon, authenticated;
grant insert on public.repair_intakes to anon, authenticated;
grant select on public.apple_model_map to anon, authenticated;
grant execute on function public.save_repair_prices(jsonb) to anon, authenticated;
grant execute on function public.save_apple_model_map(jsonb) to anon, authenticated;
