create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.repair_prices (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  issue text not null,
  price text not null default '',
  cny_cost_price numeric(12,2),
  aud_cost_price_ex_gst numeric(12,2),
  aud_cost_price_inc_gst numeric(12,2),
  cost_basis_currency text,
  fx_rate_cny_to_aud numeric(12,6),
  fx_source text,
  fx_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint repair_prices_unique unique (brand, model, issue)
);

alter table public.repair_prices
  add column if not exists cny_cost_price numeric(12,2),
  add column if not exists aud_cost_price_ex_gst numeric(12,2),
  add column if not exists aud_cost_price_inc_gst numeric(12,2),
  add column if not exists cost_basis_currency text,
  add column if not exists fx_rate_cny_to_aud numeric(12,6),
  add column if not exists fx_source text,
  add column if not exists fx_updated_at timestamptz;

alter table public.repair_prices
  drop column if exists aud_cost_price,
  drop column if exists turnaround_time;

create table if not exists public.repair_intakes (
  id bigint generated by default as identity primary key,
  source_type text not null default 'quote',
  customer_name text not null,
  customer_phone text not null default '',
  customer_email text not null default '',
  contact_method text not null default 'Phone',
  device_type text not null default '',
  device_model text not null default '',
  quoted_price text not null default '',
  repair_issue text not null default '',
  estimated_time text not null default '',
  password_type text not null default 'text',
  password_text text not null default '',
  pattern_value text not null default '',
  password_none_reason text,
  device_id_type text not null default 'imei',
  device_id_imei text not null default '',
  device_id_sn text not null default '',
  device_id_unavailable_reason text,
  testable text not null default 'yes',
  test_profile text not null default 'mobile',
  cannot_test_reason text,
  test_notes text,
  test_results_json jsonb not null default '[]'::jsonb,
  quote_data_json jsonb not null default '{}'::jsonb,
  intake_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.apple_model_map (
  id bigint generated by default as identity primary key,
  a_number text not null unique,
  family_key text not null,
  model_name text not null,
  linked_price_list_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_config (
  id boolean primary key default true,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_sessions (
  id bigint generated by default as identity primary key,
  session_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  login_email text not null unique,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id bigint generated by default as identity primary key,
  admin_user_id bigint not null references public.admin_users(id) on delete cascade,
  session_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

insert into public.admin_config (id, password_hash)
values (true, extensions.crypt('123456', extensions.gen_salt('bf')))
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists repair_prices_set_updated_at on public.repair_prices;
create trigger repair_prices_set_updated_at
before update on public.repair_prices
for each row
execute function public.set_updated_at();

drop trigger if exists repair_intakes_set_updated_at on public.repair_intakes;
create trigger repair_intakes_set_updated_at
before update on public.repair_intakes
for each row
execute function public.set_updated_at();

drop trigger if exists apple_model_map_set_updated_at on public.apple_model_map;
create trigger apple_model_map_set_updated_at
before update on public.apple_model_map
for each row
execute function public.set_updated_at();

drop trigger if exists admin_config_set_updated_at on public.admin_config;
create trigger admin_config_set_updated_at
before update on public.admin_config
for each row
execute function public.set_updated_at();

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row
execute function public.set_updated_at();

alter table public.repair_prices enable row level security;
alter table public.repair_intakes enable row level security;
alter table public.apple_model_map enable row level security;
alter table public.admin_config enable row level security;
alter table public.staff_sessions enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_sessions enable row level security;

drop policy if exists repair_prices_select_all on public.repair_prices;
create policy repair_prices_select_all
on public.repair_prices
for select
to anon, authenticated
using (true);

drop policy if exists repair_intakes_insert_all on public.repair_intakes;
create policy repair_intakes_insert_all
on public.repair_intakes
for insert
to anon, authenticated
with check (true);

drop policy if exists apple_model_map_select_all on public.apple_model_map;
create policy apple_model_map_select_all
on public.apple_model_map
for select
to anon, authenticated
using (true);

drop policy if exists admin_config_no_access on public.admin_config;
create policy admin_config_no_access
on public.admin_config
for select
to anon, authenticated
using (false);

drop policy if exists staff_sessions_no_access on public.staff_sessions;
create policy staff_sessions_no_access
on public.staff_sessions
for select
to anon, authenticated
using (false);

drop policy if exists admin_users_no_access on public.admin_users;
create policy admin_users_no_access
on public.admin_users
for select
to anon, authenticated
using (false);

drop policy if exists admin_sessions_no_access on public.admin_sessions;
create policy admin_sessions_no_access
on public.admin_sessions
for select
to anon, authenticated
using (false);

create or replace function public.is_valid_staff_session(session_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') = '' then
    return false;
  end if;

  delete from public.staff_sessions
  where expires_at <= now();

  delete from public.admin_sessions
  where expires_at <= now();

  return exists (
    select 1
    from public.staff_sessions
    where expires_at > now()
      and extensions.crypt(session_token, session_hash) = session_hash
  ) or exists (
    select 1
    from public.admin_sessions
    where expires_at > now()
      and extensions.crypt(session_token, session_hash) = session_hash
  );
end;
$$;

create or replace function public.is_valid_admin_session(session_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') = '' then
    return false;
  end if;

  delete from public.admin_sessions
  where expires_at <= now();

  return exists (
    select 1
    from public.admin_sessions
    where expires_at > now()
      and extensions.crypt(session_token, session_hash) = session_hash
  );
end;
$$;

create or replace function public.create_staff_session(input_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
  issued_token text;
  session_expires_at timestamptz;
begin
  stored_hash := (
    select password_hash
    from public.admin_config
    where id = true
  );

  if stored_hash is null or extensions.crypt(input_password, stored_hash) <> stored_hash then
    return jsonb_build_object('ok', false, 'message', 'Incorrect password');
  end if;

  delete from public.staff_sessions
  where expires_at <= now();

  issued_token := encode(extensions.gen_random_bytes(24), 'hex');
  session_expires_at := now() + interval '12 hours';

  insert into public.staff_sessions (session_hash, expires_at)
  values (extensions.crypt(issued_token, extensions.gen_salt('bf')), session_expires_at);

  return jsonb_build_object(
    'ok', true,
    'session_token', issued_token,
    'expires_at', session_expires_at
  );
end;
$$;

create or replace function public.verify_staff_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return jsonb_build_object('ok', public.is_valid_staff_session(session_token));
end;
$$;

create or replace function public.bootstrap_admin_user(login_email text, input_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(bootstrap_admin_user.login_email), '') = '' then
    raise exception 'Login email is required';
  end if;

  if length(coalesce(input_password, '')) < 8 then
    raise exception 'Password must be at least 8 characters';
  end if;

  if exists (select 1 from public.admin_users) then
    raise exception 'Admin user already exists';
  end if;

  insert into public.admin_users (login_email, password_hash, active)
  values (
    lower(trim(bootstrap_admin_user.login_email)),
    extensions.crypt(input_password, extensions.gen_salt('bf')),
    true
  );

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.create_admin_session(login_email text, input_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_record public.admin_users%rowtype;
  issued_token text;
  session_expires_at timestamptz;
begin
  select *
  into admin_record
  from public.admin_users
  where active = true
    and admin_users.login_email = lower(coalesce(trim(create_admin_session.login_email), ''));

  if not found then
    return jsonb_build_object('ok', false, 'message', 'Incorrect email or password');
  end if;

  if extensions.crypt(input_password, admin_record.password_hash) <> admin_record.password_hash then
    return jsonb_build_object('ok', false, 'message', 'Incorrect email or password');
  end if;

  delete from public.admin_sessions
  where expires_at <= now();

  issued_token := encode(extensions.gen_random_bytes(24), 'hex');
  session_expires_at := now() + interval '12 hours';

  insert into public.admin_sessions (admin_user_id, session_hash, expires_at)
  values (
    admin_record.id,
    extensions.crypt(issued_token, extensions.gen_salt('bf')),
    session_expires_at
  );

  return jsonb_build_object(
    'ok', true,
    'session_token', issued_token,
    'expires_at', session_expires_at,
    'login_email', admin_record.login_email
  );
end;
$$;

create or replace function public.verify_admin_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return jsonb_build_object('ok', public.is_valid_admin_session(session_token));
end;
$$;

create or replace function public.revoke_admin_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') <> '' then
    delete from public.admin_sessions
    where extensions.crypt(session_token, session_hash) = session_hash;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.change_admin_account_password(session_token text, new_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_admin_id bigint;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if length(coalesce(new_password, '')) < 8 then
    raise exception 'Password must be at least 8 characters';
  end if;

  select admin_user_id
  into target_admin_id
  from public.admin_sessions
  where expires_at > now()
    and extensions.crypt(session_token, session_hash) = session_hash
  order by id desc
  limit 1;

  if target_admin_id is null then
    raise exception 'Admin session not found';
  end if;

  update public.admin_users
  set password_hash = extensions.crypt(new_password, extensions.gen_salt('bf'))
  where id = target_admin_id;

  delete from public.admin_sessions
  where admin_user_id = target_admin_id;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.revoke_staff_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') <> '' then
    delete from public.staff_sessions
    where extensions.crypt(session_token, session_hash) = session_hash;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.change_staff_password(session_token text, new_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if length(coalesce(new_password, '')) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  update public.admin_config
  set password_hash = extensions.crypt(new_password, extensions.gen_salt('bf'))
  where id = true;

  delete from public.staff_sessions
  where true;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.upsert_repair_price(session_token text, row_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_brand text;
  row_model text;
  row_issue text;
  row_price text;
  row_cny_cost_price numeric(12,2);
  row_aud_cost_price_ex_gst numeric(12,2);
  row_aud_cost_price_inc_gst numeric(12,2);
  row_cost_basis_currency text;
  row_fx_rate_cny_to_aud numeric(12,6);
  row_fx_source text;
  row_fx_updated_at timestamptz;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if jsonb_typeof(row_payload) <> 'object' then
    raise exception 'Row payload must be a JSON object';
  end if;

  row_brand := coalesce(trim(row_payload->>'brand'), '');
  row_model := coalesce(trim(row_payload->>'model'), '');
  row_issue := coalesce(trim(row_payload->>'issue'), '');
  row_price := coalesce(trim(row_payload->>'price'), '');
  row_cost_basis_currency := upper(coalesce(trim(row_payload->>'cost_basis_currency'), ''));
  row_fx_source := coalesce(trim(row_payload->>'fx_source'), '');

  if coalesce(trim(row_payload->>'cny_cost_price'), '') <> '' then
    row_cny_cost_price := (row_payload->>'cny_cost_price')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'aud_cost_price_ex_gst'), '') <> '' then
    row_aud_cost_price_ex_gst := (row_payload->>'aud_cost_price_ex_gst')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'aud_cost_price_inc_gst'), '') <> '' then
    row_aud_cost_price_inc_gst := (row_payload->>'aud_cost_price_inc_gst')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'fx_rate_cny_to_aud'), '') <> '' then
    row_fx_rate_cny_to_aud := (row_payload->>'fx_rate_cny_to_aud')::numeric(12,6);
  end if;

  if coalesce(trim(row_payload->>'fx_updated_at'), '') <> '' then
    row_fx_updated_at := (row_payload->>'fx_updated_at')::timestamptz;
  end if;

  if row_brand = '' or row_model = '' or row_issue = '' then
    raise exception 'Brand, model, and issue are required';
  end if;

  insert into public.repair_prices (
    brand,
    model,
    issue,
    price,
    cny_cost_price,
    aud_cost_price_ex_gst,
    aud_cost_price_inc_gst,
    cost_basis_currency,
    fx_rate_cny_to_aud,
    fx_source,
    fx_updated_at
  )
  values (
    row_brand,
    row_model,
    row_issue,
    row_price,
    row_cny_cost_price,
    row_aud_cost_price_ex_gst,
    row_aud_cost_price_inc_gst,
    row_cost_basis_currency,
    row_fx_rate_cny_to_aud,
    row_fx_source,
    row_fx_updated_at
  )
  on conflict (brand, model, issue) do update
  set
    price = excluded.price,
    cny_cost_price = excluded.cny_cost_price,
    aud_cost_price_ex_gst = excluded.aud_cost_price_ex_gst,
    aud_cost_price_inc_gst = excluded.aud_cost_price_inc_gst,
    cost_basis_currency = excluded.cost_basis_currency,
    fx_rate_cny_to_aud = excluded.fx_rate_cny_to_aud,
    fx_source = excluded.fx_source,
    fx_updated_at = excluded.fx_updated_at,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'brand', row_brand,
    'model', row_model,
    'issue', row_issue
  );
end;
$$;

create or replace function public.delete_repair_price(session_token text, target_brand text, target_model text, target_issue text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  delete from public.repair_prices
  where brand = coalesce(trim(target_brand), '')
    and model = coalesce(trim(target_model), '')
    and issue = coalesce(trim(target_issue), '');

  get diagnostics deleted_count = row_count;

  return jsonb_build_object('ok', true, 'deleted', deleted_count);
end;
$$;

drop function if exists public.save_repair_prices(jsonb);
create or replace function public.save_repair_prices(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if jsonb_typeof(payload) <> 'array' then
    raise exception 'Payload must be a JSON array';
  end if;

  delete from public.repair_prices
  where true;

  for item in select * from jsonb_array_elements(payload)
  loop
    insert into public.repair_prices (
      brand,
      model,
      issue,
      price,
      cny_cost_price,
      aud_cost_price_ex_gst,
      aud_cost_price_inc_gst,
      cost_basis_currency,
      fx_rate_cny_to_aud,
      fx_source,
      fx_updated_at
    )
    values (
      coalesce(trim(item->>'brand'), ''),
      coalesce(trim(item->>'model'), ''),
      coalesce(trim(item->>'issue'), ''),
      coalesce(trim(item->>'price'), ''),
      case when coalesce(trim(item->>'cny_cost_price'), '') = '' then null else (item->>'cny_cost_price')::numeric(12,2) end,
      case when coalesce(trim(item->>'aud_cost_price_ex_gst'), '') = '' then null else (item->>'aud_cost_price_ex_gst')::numeric(12,2) end,
      case when coalesce(trim(item->>'aud_cost_price_inc_gst'), '') = '' then null else (item->>'aud_cost_price_inc_gst')::numeric(12,2) end,
      nullif(upper(coalesce(trim(item->>'cost_basis_currency'), '')), ''),
      case when coalesce(trim(item->>'fx_rate_cny_to_aud'), '') = '' then null else (item->>'fx_rate_cny_to_aud')::numeric(12,6) end,
      nullif(coalesce(trim(item->>'fx_source'), ''), ''),
      case when coalesce(trim(item->>'fx_updated_at'), '') = '' then null else (item->>'fx_updated_at')::timestamptz end
    )
    on conflict (brand, model, issue) do update
    set
      price = excluded.price,
      cny_cost_price = excluded.cny_cost_price,
      aud_cost_price_ex_gst = excluded.aud_cost_price_ex_gst,
      aud_cost_price_inc_gst = excluded.aud_cost_price_inc_gst,
      cost_basis_currency = excluded.cost_basis_currency,
      fx_rate_cny_to_aud = excluded.fx_rate_cny_to_aud,
      fx_source = excluded.fx_source,
      fx_updated_at = excluded.fx_updated_at,
      updated_at = now();
  end loop;

  return jsonb_build_object(
    'ok', true,
    'saved', jsonb_array_length(payload)
  );
end;
$$;

drop function if exists public.save_apple_model_map(jsonb);
create or replace function public.save_apple_model_map(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  family_key text;
  family_payload jsonb;
  entry record;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  delete from public.apple_model_map
  where true;

  for family_key, family_payload in
    select key, value
    from jsonb_each(payload)
  loop
    if jsonb_typeof(family_payload) <> 'object' then
      continue;
    end if;

    for entry in
      select key, value
      from jsonb_each_text(family_payload)
    loop
      insert into public.apple_model_map (a_number, family_key, model_name)
      values (entry.key, family_key, entry.value)
      on conflict (a_number) do update
      set
        family_key = excluded.family_key,
        model_name = excluded.model_name,
        updated_at = now();
    end loop;
  end loop;

  return jsonb_build_object('ok', true);
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.repair_prices to anon, authenticated;
grant insert on public.repair_intakes to anon, authenticated;
grant select on public.apple_model_map to anon, authenticated;
grant execute on function public.is_valid_staff_session(text) to anon, authenticated;
grant execute on function public.create_staff_session(text) to anon, authenticated;
grant execute on function public.verify_staff_session(text) to anon, authenticated;
grant execute on function public.revoke_staff_session(text) to anon, authenticated;
grant execute on function public.change_staff_password(text, text) to anon, authenticated;
grant execute on function public.is_valid_admin_session(text) to anon, authenticated;
grant execute on function public.bootstrap_admin_user(text, text) to anon, authenticated;
grant execute on function public.create_admin_session(text, text) to anon, authenticated;
grant execute on function public.verify_admin_session(text) to anon, authenticated;
grant execute on function public.revoke_admin_session(text) to anon, authenticated;
grant execute on function public.change_admin_account_password(text, text) to anon, authenticated;
grant execute on function public.upsert_repair_price(text, jsonb) to anon, authenticated;
grant execute on function public.delete_repair_price(text, text, text, text) to anon, authenticated;
grant execute on function public.save_repair_prices(text, jsonb) to anon, authenticated;
grant execute on function public.save_apple_model_map(text, jsonb) to anon, authenticated;

create table if not exists public.store_locations (
  id bigint generated by default as identity primary key,
  store_code text not null unique,
  store_name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_directory (
  id bigint generated by default as identity primary key,
  display_name text not null unique,
  email text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lcd_inventory_items (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.store_locations(id) on delete cascade,
  model_name text not null,
  variant_name text not null,
  current_qty integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lcd_inventory_items_unique unique (store_id, model_name, variant_name)
);

create table if not exists public.daily_report_submissions (
  id bigint generated by default as identity primary key,
  report_code text unique,
  report_date date not null default current_date,
  store_id bigint not null references public.store_locations(id),
  staff_id bigint not null references public.staff_directory(id),
  store_name text not null,
  staff_name text not null,
  notes text not null default '',
  total_amount numeric(12,2) not null default 0,
  repair_count integer not null default 0,
  lcd_adjustment_count integer not null default 0,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_report_repairs (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.daily_report_submissions(id) on delete cascade,
  line_order integer not null default 1,
  model_and_color text not null default '',
  problem_and_parts_used text not null default '',
  tech_name text not null default '',
  invoice_number text not null default '',
  amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_report_lcd_lines (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.daily_report_submissions(id) on delete cascade,
  line_order integer not null default 1,
  lcd_inventory_item_id bigint not null references public.lcd_inventory_items(id),
  model_name text not null,
  variant_name text not null,
  action_type text not null,
  quantity integer not null,
  stock_before integer not null,
  stock_after integer not null,
  created_at timestamptz not null default now(),
  constraint daily_report_lcd_lines_action_type_check
    check (action_type in ('sold', 'send_to_other', 'faulty', 'broken')),
  constraint daily_report_lcd_lines_quantity_check
    check (quantity > 0)
);

drop trigger if exists store_locations_set_updated_at on public.store_locations;
create trigger store_locations_set_updated_at
before update on public.store_locations
for each row
execute function public.set_updated_at();

drop trigger if exists staff_directory_set_updated_at on public.staff_directory;
create trigger staff_directory_set_updated_at
before update on public.staff_directory
for each row
execute function public.set_updated_at();

drop trigger if exists lcd_inventory_items_set_updated_at on public.lcd_inventory_items;
create trigger lcd_inventory_items_set_updated_at
before update on public.lcd_inventory_items
for each row
execute function public.set_updated_at();

drop trigger if exists daily_report_submissions_set_updated_at on public.daily_report_submissions;
create trigger daily_report_submissions_set_updated_at
before update on public.daily_report_submissions
for each row
execute function public.set_updated_at();

alter table public.store_locations enable row level security;
alter table public.staff_directory enable row level security;
alter table public.lcd_inventory_items enable row level security;
alter table public.daily_report_submissions enable row level security;
alter table public.daily_report_repairs enable row level security;
alter table public.daily_report_lcd_lines enable row level security;

drop policy if exists store_locations_no_access on public.store_locations;
create policy store_locations_no_access
on public.store_locations
for select
to anon, authenticated
using (false);

drop policy if exists staff_directory_no_access on public.staff_directory;
create policy staff_directory_no_access
on public.staff_directory
for select
to anon, authenticated
using (false);

drop policy if exists lcd_inventory_items_no_access on public.lcd_inventory_items;
create policy lcd_inventory_items_no_access
on public.lcd_inventory_items
for select
to anon, authenticated
using (false);

drop policy if exists daily_report_submissions_no_access on public.daily_report_submissions;
create policy daily_report_submissions_no_access
on public.daily_report_submissions
for select
to anon, authenticated
using (false);

drop policy if exists daily_report_repairs_no_access on public.daily_report_repairs;
create policy daily_report_repairs_no_access
on public.daily_report_repairs
for select
to anon, authenticated
using (false);

drop policy if exists daily_report_lcd_lines_no_access on public.daily_report_lcd_lines;
create policy daily_report_lcd_lines_no_access
on public.daily_report_lcd_lines
for select
to anon, authenticated
using (false);

insert into public.store_locations (store_code, store_name, sort_order, active)
values
  ('toowong', 'Toowong Village Shopping Centre', 1, true),
  ('parkridge', 'Park Ridge Town Centre', 2, true),
  ('brassall', 'Brassall Shopping Centre', 3, true),
  ('fairfield', 'Fairfield Gardens Shopping Centre', 4, true),
  ('northlakes', 'Westfield North Lakes Shopping Centre', 5, true)
on conflict (store_code) do update
set
  store_name = excluded.store_name,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = now();

insert into public.staff_directory (display_name, email, active)
values
  ('Andy', 'shangzelin2001@gmail.com', true),
  ('Bonnie', 'bonniechiu1212aabb@gmail.com', true),
  ('Fiona', 'yingmccoy@gmail.com', true),
  ('Henry Ang', 'henryang98@gmail.com', true),
  ('JANAPHY', 'janaphy0530@hotmail.com', true),
  ('Joanna Chen', '824195774@qq.com', true),
  ('Steven T', 'steven_troya@hotmail.com', true)
on conflict (display_name) do update
set
  email = excluded.email,
  active = excluded.active,
  updated_at = now();

with lcd_seed (model_name, variant_name, toowong_qty) as (
  values
    ('Galaxy S10', 'LCD', 0),
    ('Galaxy S10 5G', 'LCD', 0),
    ('Galaxy S10 E', 'LCD', 0),
    ('Galaxy S10+', 'LCD', 0),
    ('Galaxy S20', 'LCD', 1),
    ('Galaxy S20 Ultra', 'LCD', 1),
    ('Galaxy S20+', 'LCD', 1),
    ('Galaxy S20FE', 'LCD', 0),
    ('Galaxy S21', 'LCD', 1),
    ('Galaxy S21 PLUS', 'LCD', 1),
    ('Galaxy S21 Ultra', 'LCD', 1),
    ('Galaxy S21FE', 'LCD', 0),
    ('Galaxy S22', 'LCD', 0),
    ('Galaxy S22 plus', 'LCD', 0),
    ('Galaxy S22 Ultra', 'LCD', 0),
    ('Galaxy S23', 'LCD', 1),
    ('Galaxy S23 FE', 'LCD', 0),
    ('Galaxy S23 Plus', 'LCD', 0),
    ('Galaxy S23 Ultra', 'LCD', 0),
    ('Galaxy S24', 'LCD', 1),
    ('Galaxy S24 FE', 'LCD', 0),
    ('Galaxy S24 Plus', 'LCD', 0),
    ('Galaxy S24 Ultra', 'LCD', 0),
    ('Galaxy S25', 'LCD', 0),
    ('Galaxy S25 FE', 'LCD', 0),
    ('Galaxy S25 Plus', 'LCD', 0),
    ('Galaxy S25 Ultra', 'LCD', 0),
    ('Galaxy S7 Edge', 'LCD', 0),
    ('Galaxy S8', 'LCD', 0),
    ('Galaxy S8 Plus', 'LCD', 0),
    ('Galaxy S9', 'LCD', 0),
    ('Galaxy S9 Plus', 'LCD', 0),
    ('iPad 10th', 'LCD', 1),
    ('iPad 10th', 'Touch', 11),
    ('iPad 2', 'Black Touch', 0),
    ('iPad 2', 'LCD', 0),
    ('iPad 2', 'White Touch', 0),
    ('iPad 3/4', 'Black Touch', 0),
    ('iPad 3/4', 'LCD', 0),
    ('iPad 3/4', 'White Touch', 0),
    ('iPad 6th Gen', 'Black', 2),
    ('iPad 6th Gen', 'LCD(9.7)', 1),
    ('iPad 6th Gen', 'White', 0),
    ('iPad 7,8,9 Gen(10.2)', 'Black', 6),
    ('iPad 7,8,9 Gen(10.2)', 'LCD', 1),
    ('iPad 7,8,9 Gen(10.2)', 'White', 4),
    ('iPad Air 4/ Air 5', 'Black', 1),
    ('iPad Air1 / iPad 5th', 'Black Touch', 1),
    ('iPad Air1 / iPad 5th', 'White Touch', 1),
    ('iPad Mini 3', 'Black Touch', 0),
    ('iPad Mini 3', 'White Touch', 0),
    ('iPad Mini 4', 'Black', 0),
    ('iPad Mini 4', 'White', 0),
    ('Ipad Mini 5', 'Black', 0),
    ('Ipad Mini 5', 'White', 0),
    ('iPad Mini1/2', 'Black Touch', 0),
    ('iPad Mini1/2', 'Mini 1 LCD', 0),
    ('iPad Mini1/2', 'Mini 2/3 LCD', 0),
    ('iPad Mini1/2', 'White Touch', 0),
    ('iPad Pro 11 (2018) / (2020)', 'Black', 0),
    ('iPad Pro 11 (2021) / (2022)', 'Black', 0),
    ('iPad Pro 12.9 (2018) / (2020)', 'Black', 0),
    ('iPad Pro 12.9 (2021) / (2022)', 'Black', 0),
    ('Iphone 11', 'LCD', 3),
    ('Iphone 11 Pro', 'LCD', 2),
    ('Iphone 11 Pro', 'OLED', 1),
    ('Iphone 11 Pro Max', 'LCD', 2),
    ('Iphone 11 Pro Max', 'OLED', 0),
    ('Iphone 12', 'LCD', 2),
    ('Iphone 12', 'OLED', 3),
    ('Iphone 12 Mini', 'LCD', 0),
    ('Iphone 12 Mini', 'OLED', 1),
    ('Iphone 12 Pro Max', 'LCD', 2),
    ('Iphone 12 Pro Max', 'OLED', 2),
    ('Iphone 13', 'LCD', 0),
    ('Iphone 13', 'OLED', 1),
    ('Iphone 13', 'ORI', 0),
    ('Iphone 13 Mini', 'LCD', 1),
    ('Iphone 13 Mini', 'OLED', 0),
    ('Iphone 13 Pro', 'LCD', 1),
    ('Iphone 13 Pro', 'OLED', 1),
    ('Iphone 13 Pro', 'ORI', 1),
    ('Iphone 13 Pro Max', 'LCD', 2),
    ('Iphone 13 Pro Max', 'OLED', 2),
    ('Iphone 13 Pro Max', 'ORI', 0),
    ('iPhone 14', 'LCD', 1),
    ('iPhone 14', 'OLED', 2),
    ('iPhone 14', 'ORI', 0),
    ('iPhone 14 Plus', 'LCD', 1),
    ('iPhone 14 Plus', 'OLED', 0),
    ('iPhone 14 Plus', 'ORI', 0),
    ('iPhone 14 Pro', 'LCD', 2),
    ('iPhone 14 Pro', 'OLED', 2),
    ('iPhone 14 Pro', 'ORI', 0),
    ('iPhone 14 Pro Max', 'LCD', 3),
    ('iPhone 14 Pro Max', 'OLED', 2),
    ('iPhone 14 Pro Max', 'ORI', 0),
    ('iPhone 15', 'LCD', 1),
    ('iPhone 15', 'OLED', 0),
    ('iPhone 15', 'ORI', 0),
    ('iPhone 15 Plus', 'LCD', 1),
    ('iPhone 15 Plus', 'OLED', 0),
    ('iPhone 15 Plus', 'ORI', 0),
    ('iPhone 15 Pro', 'LCD', 1),
    ('iPhone 15 Pro', 'OLED', 1),
    ('iPhone 15 Pro', 'ORI', 0),
    ('iPhone 15 Pro Max', 'LCD', 2),
    ('iPhone 15 Pro Max', 'OLED', 2),
    ('iPhone 15 Pro Max', 'ORI', 0),
    ('iPhone 16', 'LCD', 1),
    ('iPhone 16', 'OLED', 1),
    ('iPhone 16', 'ORI', 0),
    ('iPhone 16 Plus', 'LCD', 1),
    ('iPhone 16 Plus', 'OLED', 0),
    ('iPhone 16 Plus', 'ORI', 0),
    ('iPhone 16 Pro', 'LCD', 1),
    ('iPhone 16 Pro', 'OLED', 0),
    ('iPhone 16 Pro', 'ORI', 0),
    ('iPhone 16 Pro Max', 'LCD', 1),
    ('iPhone 16 Pro Max', 'OLED', 1),
    ('iPhone 16 Pro Max', 'ORI', 0),
    ('IPhone 16E', 'LCD', 0),
    ('iPhone 5', 'Black', 0),
    ('iPhone 5', 'White', 1),
    ('iPhone 5C', 'Black', 2),
    ('iPhone 5S/SE', 'Black', 0),
    ('iPhone 5S/SE', 'White', 0),
    ('iPhone 6', 'Black', 0),
    ('iPhone 6', 'White', 0),
    ('iPhone 6 plus', 'Black', 1),
    ('iPhone 6 plus', 'White', 1),
    ('iPhone 6S', 'Black', 0),
    ('iPhone 6S', 'White', 0),
    ('iPhone 6S plus', 'Black', 1),
    ('iPhone 6S plus', 'White', 0),
    ('iPhone 7', 'Black', 1),
    ('iPhone 7', 'White', 0),
    ('iPhone 7 plus', 'Black', 1),
    ('iPhone 7 plus', 'White', 2),
    ('iPhone 8', 'Black', 1),
    ('iPhone 8', 'White', 0),
    ('iPhone 8 plus', 'Black', 0),
    ('iPhone 8 plus', 'White', 1),
    ('iPhone X', 'LCD', 0),
    ('iPhone X', 'OLED', 1),
    ('iPhone XR', 'LCD', 4),
    ('iPhone XS', 'LCD', 0),
    ('iPhone XS', 'OLED', 1),
    ('iPhone Xs Max', 'LCD', 1),
    ('iPhone Xs Max', 'OLED', 1),
    ('Note 10', 'LCD', 0),
    ('Note 10 Plus', 'LCD', 0),
    ('Note 20', 'LCD', 0),
    ('Note 20 Ultra', 'LCD', 0),
    ('Note 8', 'LCD', 0),
    ('Note 9', 'LCD', 0),
    ('Oppo A2pro/A3 pro/reno 11/F21 p+', 'Standard', 2),
    ('Pixel 8', 'LCD', 0),
    ('Pixel 8 Pro', 'LCD', 0),
    ('Pixel 8A', 'LCD', 0),
    ('Pixel 9', 'LCD', 0),
    ('Pixel 9 Pro', 'LCD', 0),
    ('Pixel 9 Pro XL', 'LCD', 0),
    ('Pixel 9A', 'LCD', 1)
)
insert into public.lcd_inventory_items (store_id, model_name, variant_name, current_qty, active)
select
  stores.id,
  lcd_seed.model_name,
  lcd_seed.variant_name,
  case when stores.store_code = 'toowong' then lcd_seed.toowong_qty else 0 end,
  true
from public.store_locations stores
cross join lcd_seed
on conflict (store_id, model_name, variant_name) do update
set
  current_qty = excluded.current_qty,
  active = excluded.active,
  updated_at = now();

create or replace function public.get_daily_report_setup(session_token text, target_store_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  stores_payload jsonb;
  staff_payload jsonb;
  inventory_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'store_code', store_code,
        'store_name', store_name
      )
      order by sort_order, store_name
    ),
    '[]'::jsonb
  )
  into stores_payload
  from public.store_locations
  where active = true;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', id,
        'display_name', display_name,
        'email', email
      )
      order by display_name
    ),
    '[]'::jsonb
  )
  into staff_payload
  from public.staff_directory
  where active = true;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', lcd.id,
        'model_name', lcd.model_name,
        'variant_name', lcd.variant_name,
        'current_qty', lcd.current_qty
      )
      order by lcd.model_name, lcd.variant_name
    ),
    '[]'::jsonb
  )
  into inventory_payload
  from public.lcd_inventory_items lcd
  join public.store_locations stores on stores.id = lcd.store_id
  where lcd.active = true
    and stores.active = true
    and (
      target_store_code is null
      or target_store_code = ''
      or stores.store_code = target_store_code
    );

  return jsonb_build_object(
    'ok', true,
    'stores', stores_payload,
    'staff', staff_payload,
    'lcd_items', inventory_payload
  );
end;
$$;

create or replace function public.get_lcd_inventory(session_token text, target_store_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  items_payload jsonb;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', lcd.id,
        'store_id', stores.id,
        'store_code', stores.store_code,
        'store_name', stores.store_name,
        'model_name', lcd.model_name,
        'variant_name', lcd.variant_name,
        'current_qty', lcd.current_qty,
        'active', lcd.active,
        'updated_at', lcd.updated_at
      )
      order by stores.sort_order, stores.store_name, lcd.model_name, lcd.variant_name
    ),
    '[]'::jsonb
  )
  into items_payload
  from public.lcd_inventory_items lcd
  join public.store_locations stores on stores.id = lcd.store_id
  where (
    coalesce(target_store_code, '') = ''
    or stores.store_code = target_store_code
  );

  return jsonb_build_object('ok', true, 'items', items_payload);
end;
$$;

create or replace function public.upsert_lcd_inventory_item(session_token text, row_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_store public.store_locations%rowtype;
  row_model_name text;
  row_variant_name text;
  row_current_qty integer;
  row_active boolean;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if jsonb_typeof(row_payload) <> 'object' then
    raise exception 'Row payload must be a JSON object';
  end if;

  select *
  into target_store
  from public.store_locations
  where store_code = coalesce(trim(row_payload->>'store_code'), '');

  if not found then
    raise exception 'Store not found';
  end if;

  row_model_name := coalesce(trim(row_payload->>'model_name'), '');
  row_variant_name := coalesce(trim(row_payload->>'variant_name'), '');
  row_current_qty := coalesce(nullif(trim(row_payload->>'current_qty'), ''), '0')::integer;
  row_active := coalesce((row_payload->>'active')::boolean, true);

  if row_model_name = '' or row_variant_name = '' then
    raise exception 'Model and variant are required';
  end if;

  if row_current_qty < 0 then
    raise exception 'Quantity cannot be negative';
  end if;

  insert into public.lcd_inventory_items (
    store_id,
    model_name,
    variant_name,
    current_qty,
    active
  )
  values (
    target_store.id,
    row_model_name,
    row_variant_name,
    row_current_qty,
    row_active
  )
  on conflict (store_id, model_name, variant_name) do update
  set
    current_qty = excluded.current_qty,
    active = excluded.active,
    updated_at = now();

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.delete_lcd_inventory_item(session_token text, target_store_code text, target_model_name text, target_variant_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  delete from public.lcd_inventory_items lcd
  using public.store_locations stores
  where stores.id = lcd.store_id
    and stores.store_code = coalesce(trim(target_store_code), '')
    and lcd.model_name = coalesce(trim(target_model_name), '')
    and lcd.variant_name = coalesce(trim(target_variant_name), '');

  get diagnostics deleted_count = row_count;

  return jsonb_build_object('ok', true, 'deleted', deleted_count);
end;
$$;

create or replace function public.submit_daily_report(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  report_date_value date;
  report_notes text;
  repair_lines jsonb;
  lcd_lines jsonb;
  repair_line jsonb;
  lcd_line jsonb;
  created_report_id bigint;
  created_report_code text;
  total_amount_value numeric(12,2) := 0;
  repair_count_value integer := 0;
  lcd_count_value integer := 0;
  line_index integer := 0;
  inventory_row public.lcd_inventory_items%rowtype;
  line_quantity integer;
  line_amount numeric(12,2);
  line_action text;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  select *
  into selected_store
  from public.store_locations
  where active = true
    and store_code = coalesce(trim(payload->>'store_code'), '');

  if not found then
    raise exception 'Store not found';
  end if;

  select *
  into selected_staff
  from public.staff_directory
  where active = true
    and display_name = coalesce(trim(payload->>'staff_name'), '');

  if not found then
    raise exception 'Staff member not found';
  end if;

  report_date_value := coalesce(nullif(payload->>'report_date', '')::date, current_date);
  report_notes := coalesce(trim(payload->>'notes'), '');
  repair_lines := coalesce(payload->'repair_lines', '[]'::jsonb);
  lcd_lines := coalesce(payload->'lcd_lines', '[]'::jsonb);

  if jsonb_typeof(repair_lines) <> 'array' then
    raise exception 'Repair lines must be an array';
  end if;

  if jsonb_typeof(lcd_lines) <> 'array' then
    raise exception 'LCD lines must be an array';
  end if;

  insert into public.daily_report_submissions (
    report_date,
    store_id,
    staff_id,
    store_name,
    staff_name,
    notes
  )
  values (
    report_date_value,
    selected_store.id,
    selected_staff.id,
    selected_store.store_name,
    selected_staff.display_name,
    report_notes
  )
  returning id into created_report_id;

  created_report_code := 'DR-' || to_char(report_date_value, 'YYYYMMDD') || '-' || lpad(created_report_id::text, 5, '0');

  line_index := 0;
  for repair_line in
    select value
    from jsonb_array_elements(repair_lines)
  loop
    if jsonb_typeof(repair_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(repair_line->>'model_and_color'), '') = ''
      and coalesce(trim(repair_line->>'problem_and_parts_used'), '') = ''
      and coalesce(trim(repair_line->>'invoice_number'), '') = ''
      and coalesce(trim(repair_line->>'amount'), '') = '' then
      continue;
    end if;

    line_index := line_index + 1;
    line_amount := case
      when coalesce(trim(repair_line->>'amount'), '') = '' then 0
      else regexp_replace(repair_line->>'amount', '[^0-9.\-]', '', 'g')::numeric(12,2)
    end;

    insert into public.daily_report_repairs (
      report_id,
      line_order,
      model_and_color,
      problem_and_parts_used,
      tech_name,
      invoice_number,
      amount
    )
    values (
      created_report_id,
      line_index,
      coalesce(trim(repair_line->>'model_and_color'), ''),
      coalesce(trim(repair_line->>'problem_and_parts_used'), ''),
      coalesce(nullif(trim(repair_line->>'tech_name'), ''), selected_staff.display_name),
      coalesce(trim(repair_line->>'invoice_number'), ''),
      line_amount
    );

    total_amount_value := total_amount_value + coalesce(line_amount, 0);
    repair_count_value := repair_count_value + 1;
  end loop;

  line_index := 0;
  for lcd_line in
    select value
    from jsonb_array_elements(lcd_lines)
  loop
    if jsonb_typeof(lcd_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(lcd_line->>'inventory_item_id'), '') = '' then
      continue;
    end if;

    line_action := coalesce(trim(lcd_line->>'action_type'), '');
    if line_action not in ('sold', 'send_to_other', 'faulty', 'broken') then
      raise exception 'Invalid LCD action type';
    end if;

    line_quantity := coalesce(nullif(trim(lcd_line->>'quantity'), ''), '0')::integer;
    if line_quantity <= 0 then
      raise exception 'LCD quantity must be greater than 0';
    end if;

    select *
    into inventory_row
    from public.lcd_inventory_items
    where id = (lcd_line->>'inventory_item_id')::bigint
      and store_id = selected_store.id
      and active = true
    for update;

    if not found then
      raise exception 'LCD inventory item not found for the selected store';
    end if;

    if inventory_row.current_qty < line_quantity then
      raise exception 'Not enough stock for % (%)', inventory_row.model_name, inventory_row.variant_name;
    end if;

    line_index := line_index + 1;

    update public.lcd_inventory_items
    set current_qty = current_qty - line_quantity
    where id = inventory_row.id;

    insert into public.daily_report_lcd_lines (
      report_id,
      line_order,
      lcd_inventory_item_id,
      model_name,
      variant_name,
      action_type,
      quantity,
      stock_before,
      stock_after
    )
    values (
      created_report_id,
      line_index,
      inventory_row.id,
      inventory_row.model_name,
      inventory_row.variant_name,
      line_action,
      line_quantity,
      inventory_row.current_qty,
      inventory_row.current_qty - line_quantity
    );

    lcd_count_value := lcd_count_value + 1;
  end loop;

  update public.daily_report_submissions
  set
    report_code = created_report_code,
    total_amount = total_amount_value,
    repair_count = repair_count_value,
    lcd_adjustment_count = lcd_count_value
  where id = created_report_id;

  return jsonb_build_object(
    'ok', true,
    'report_id', created_report_id,
    'report_code', created_report_code,
    'total_amount', total_amount_value,
    'repair_count', repair_count_value,
    'lcd_adjustment_count', lcd_count_value
  );
end;
$$;

create or replace function public.get_daily_reports(session_token text, target_date text default null, target_store_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reports_payload jsonb;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', report.id,
        'report_code', report.report_code,
        'report_date', report.report_date,
        'store_name', report.store_name,
        'staff_name', report.staff_name,
        'notes', report.notes,
        'total_amount', report.total_amount,
        'repair_count', report.repair_count,
        'lcd_adjustment_count', report.lcd_adjustment_count,
        'submitted_at', report.submitted_at,
        'repair_lines', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'line_order', repair.line_order,
              'model_and_color', repair.model_and_color,
              'problem_and_parts_used', repair.problem_and_parts_used,
              'tech_name', repair.tech_name,
              'invoice_number', repair.invoice_number,
              'amount', repair.amount
            )
            order by repair.line_order
          )
          from public.daily_report_repairs repair
          where repair.report_id = report.id
        ), '[]'::jsonb),
        'lcd_lines', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'line_order', lcd.line_order,
              'model_name', lcd.model_name,
              'variant_name', lcd.variant_name,
              'action_type', lcd.action_type,
              'quantity', lcd.quantity,
              'stock_before', lcd.stock_before,
              'stock_after', lcd.stock_after
            )
            order by lcd.line_order
          )
          from public.daily_report_lcd_lines lcd
          where lcd.report_id = report.id
        ), '[]'::jsonb)
      )
      order by report.report_date desc, report.submitted_at desc, report.id desc
    ),
    '[]'::jsonb
  )
  into reports_payload
  from public.daily_report_submissions report
  join public.store_locations stores on stores.id = report.store_id
  where (
      coalesce(target_date, '') = ''
      or report.report_date = target_date::date
    )
    and (
      coalesce(target_store_code, '') = ''
      or stores.store_code = target_store_code
    );

  return jsonb_build_object('ok', true, 'reports', reports_payload);
end;
$$;

grant execute on function public.get_daily_report_setup(text, text) to anon, authenticated;
grant execute on function public.submit_daily_report(text, jsonb) to anon, authenticated;
grant execute on function public.get_daily_reports(text, text, text) to anon, authenticated;

alter table public.daily_report_submissions
  add column if not exists faulty_broken_lines_json jsonb not null default '[]'::jsonb,
  add column if not exists device_sales_lines_json jsonb not null default '[]'::jsonb,
  add column if not exists device_buyback_lines_json jsonb not null default '[]'::jsonb,
  add column if not exists end_of_day_json jsonb not null default '{}'::jsonb,
  add column if not exists cash_expense_lines_json jsonb not null default '[]'::jsonb,
  add column if not exists customer_tracking_json jsonb not null default '{}'::jsonb,
  add column if not exists missing_sales_lines_json jsonb not null default '[]'::jsonb;

create table if not exists public.daily_report_drafts (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.store_locations(id) on delete cascade,
  staff_id bigint not null references public.staff_directory(id) on delete cascade,
  report_date date not null default current_date,
  store_name text not null,
  staff_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_report_drafts_unique unique (store_id, staff_id, report_date)
);

drop trigger if exists daily_report_drafts_set_updated_at on public.daily_report_drafts;
create trigger daily_report_drafts_set_updated_at
before update on public.daily_report_drafts
for each row
execute function public.set_updated_at();

alter table public.daily_report_drafts enable row level security;

drop policy if exists daily_report_drafts_no_access on public.daily_report_drafts;
create policy daily_report_drafts_no_access
on public.daily_report_drafts
for select
to anon, authenticated
using (false);

create or replace function public.save_daily_report_draft(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  report_date_value date;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  select *
  into selected_store
  from public.store_locations
  where active = true
    and store_code = coalesce(trim(payload->>'store_code'), '');

  if not found then
    raise exception 'Store not found';
  end if;

  select *
  into selected_staff
  from public.staff_directory
  where active = true
    and display_name = coalesce(trim(payload->>'staff_name'), '');

  if not found then
    raise exception 'Staff member not found';
  end if;

  report_date_value := coalesce(nullif(payload->>'report_date', '')::date, current_date);

  if exists (
    select 1
    from public.daily_report_submissions report
    where report.store_id = selected_store.id
      and report.report_date = report_date_value
  ) then
    delete from public.daily_report_drafts
    where store_id = selected_store.id
      and report_date = report_date_value;
    raise exception 'A report for this store and date has already been submitted';
  end if;

  insert into public.daily_report_drafts (
    store_id,
    staff_id,
    report_date,
    store_name,
    staff_name,
    payload
  )
  values (
    selected_store.id,
    selected_staff.id,
    report_date_value,
    selected_store.store_name,
    selected_staff.display_name,
    payload
  )
  on conflict (store_id, staff_id, report_date) do update
  set
    payload = excluded.payload,
    store_name = excluded.store_name,
    staff_name = excluded.staff_name,
    updated_at = now();

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.get_daily_report_draft(session_token text, target_store_code text, target_staff_name text, target_date text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  draft_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  select draft.payload
  into draft_payload
  from public.daily_report_drafts draft
  join public.store_locations stores on stores.id = draft.store_id
  join public.staff_directory staff on staff.id = draft.staff_id
  where stores.store_code = coalesce(trim(target_store_code), '')
    and staff.display_name = coalesce(trim(target_staff_name), '')
    and draft.report_date = coalesce(nullif(target_date, '')::date, current_date)
  order by draft.updated_at desc
  limit 1;

  return jsonb_build_object(
    'ok', true,
    'has_draft', draft_payload is not null,
    'draft', coalesce(draft_payload, '{}'::jsonb)
  );
end;
$$;

create or replace function public.submit_daily_report(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  report_date_value date;
  report_notes text;
  repair_lines jsonb;
  lcd_lines jsonb;
  faulty_broken_lines jsonb;
  device_sales_lines jsonb;
  device_buyback_lines jsonb;
  end_of_day_json jsonb;
  cash_expense_lines jsonb;
  customer_tracking_json jsonb;
  missing_sales_lines jsonb;
  repair_line jsonb;
  lcd_line jsonb;
  created_report_id bigint;
  created_report_code text;
  total_amount_value numeric(12,2) := 0;
  repair_count_value integer := 0;
  lcd_count_value integer := 0;
  line_index integer := 0;
  inventory_row public.lcd_inventory_items%rowtype;
  line_quantity integer;
  line_amount numeric(12,2);
  line_action text;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  select *
  into selected_store
  from public.store_locations
  where active = true
    and store_code = coalesce(trim(payload->>'store_code'), '');

  if not found then
    raise exception 'Store not found';
  end if;

  select *
  into selected_staff
  from public.staff_directory
  where active = true
    and display_name = coalesce(trim(payload->>'staff_name'), '');

  if not found then
    raise exception 'Staff member not found';
  end if;

  report_date_value := coalesce(nullif(payload->>'report_date', '')::date, current_date);
  report_notes := coalesce(trim(payload->>'notes'), '');
  repair_lines := coalesce(payload->'repair_lines', '[]'::jsonb);
  lcd_lines := coalesce(payload->'lcd_lines', '[]'::jsonb);
  faulty_broken_lines := coalesce(payload->'faulty_broken_lines', '[]'::jsonb);
  device_sales_lines := coalesce(payload->'device_sales_lines', '[]'::jsonb);
  device_buyback_lines := coalesce(payload->'device_buyback_lines', '[]'::jsonb);
  end_of_day_json := coalesce(payload->'end_of_day', '{}'::jsonb);
  cash_expense_lines := coalesce(payload->'cash_expense_lines', '[]'::jsonb);
  customer_tracking_json := coalesce(payload->'customer_tracking', '{}'::jsonb);
  missing_sales_lines := coalesce(payload->'missing_sales_lines', '[]'::jsonb);

  if jsonb_typeof(repair_lines) <> 'array' then
    raise exception 'Repair lines must be an array';
  end if;
  if jsonb_typeof(lcd_lines) <> 'array' then
    raise exception 'LCD lines must be an array';
  end if;
  if jsonb_typeof(faulty_broken_lines) <> 'array' then
    raise exception 'Faulty and broken lines must be an array';
  end if;
  if jsonb_typeof(device_sales_lines) <> 'array' then
    raise exception 'Device sales lines must be an array';
  end if;
  if jsonb_typeof(device_buyback_lines) <> 'array' then
    raise exception 'Device buyback lines must be an array';
  end if;
  if jsonb_typeof(cash_expense_lines) <> 'array' then
    raise exception 'Cash expense lines must be an array';
  end if;
  if jsonb_typeof(missing_sales_lines) <> 'array' then
    raise exception 'Missing sales lines must be an array';
  end if;
  if jsonb_typeof(end_of_day_json) <> 'object' then
    raise exception 'End of day data must be an object';
  end if;
  if jsonb_typeof(customer_tracking_json) <> 'object' then
    raise exception 'Customer tracking data must be an object';
  end if;

  insert into public.daily_report_submissions (
    report_date,
    store_id,
    staff_id,
    store_name,
    staff_name,
    notes,
    faulty_broken_lines_json,
    device_sales_lines_json,
    device_buyback_lines_json,
    end_of_day_json,
    cash_expense_lines_json,
    customer_tracking_json,
    missing_sales_lines_json
  )
  values (
    report_date_value,
    selected_store.id,
    selected_staff.id,
    selected_store.store_name,
    selected_staff.display_name,
    report_notes,
    faulty_broken_lines,
    device_sales_lines,
    device_buyback_lines,
    end_of_day_json,
    cash_expense_lines,
    customer_tracking_json,
    missing_sales_lines
  )
  returning id into created_report_id;

  created_report_code := 'DR-' || to_char(report_date_value, 'YYYYMMDD') || '-' || lpad(created_report_id::text, 5, '0');

  line_index := 0;
  for repair_line in
    select value
    from jsonb_array_elements(repair_lines)
  loop
    if jsonb_typeof(repair_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(repair_line->>'model_and_color'), '') = ''
      and coalesce(trim(repair_line->>'problem_and_parts_used'), '') = ''
      and coalesce(trim(repair_line->>'invoice_number'), '') = ''
      and coalesce(trim(repair_line->>'amount'), '') = '' then
      continue;
    end if;

    line_index := line_index + 1;
    line_amount := case
      when coalesce(trim(repair_line->>'amount'), '') = '' then 0
      else regexp_replace(repair_line->>'amount', '[^0-9.\-]', '', 'g')::numeric(12,2)
    end;

    insert into public.daily_report_repairs (
      report_id,
      line_order,
      model_and_color,
      problem_and_parts_used,
      tech_name,
      invoice_number,
      amount
    )
    values (
      created_report_id,
      line_index,
      coalesce(trim(repair_line->>'model_and_color'), ''),
      coalesce(trim(repair_line->>'problem_and_parts_used'), ''),
      coalesce(nullif(trim(repair_line->>'tech_name'), ''), selected_staff.display_name),
      coalesce(trim(repair_line->>'invoice_number'), ''),
      line_amount
    );

    total_amount_value := total_amount_value + coalesce(line_amount, 0);
    repair_count_value := repair_count_value + 1;
  end loop;

  line_index := 0;
  for lcd_line in
    select value
    from jsonb_array_elements(lcd_lines)
  loop
    if jsonb_typeof(lcd_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(lcd_line->>'inventory_item_id'), '') = '' then
      continue;
    end if;

    line_action := coalesce(trim(lcd_line->>'action_type'), '');
    if line_action not in ('sold', 'send_to_other', 'faulty', 'broken') then
      raise exception 'Invalid LCD action type';
    end if;

    line_quantity := coalesce(nullif(trim(lcd_line->>'quantity'), ''), '0')::integer;
    if line_quantity <= 0 then
      raise exception 'LCD quantity must be greater than 0';
    end if;

    select *
    into inventory_row
    from public.lcd_inventory_items
    where id = (lcd_line->>'inventory_item_id')::bigint
      and store_id = selected_store.id
      and active = true
    for update;

    if not found then
      raise exception 'LCD inventory item not found for the selected store';
    end if;

    if inventory_row.current_qty < line_quantity then
      raise exception 'Not enough stock for % (%)', inventory_row.model_name, inventory_row.variant_name;
    end if;

    line_index := line_index + 1;

    update public.lcd_inventory_items
    set current_qty = current_qty - line_quantity
    where id = inventory_row.id;

    insert into public.daily_report_lcd_lines (
      report_id,
      line_order,
      lcd_inventory_item_id,
      model_name,
      variant_name,
      action_type,
      quantity,
      stock_before,
      stock_after
    )
    values (
      created_report_id,
      line_index,
      inventory_row.id,
      inventory_row.model_name,
      inventory_row.variant_name,
      line_action,
      line_quantity,
      inventory_row.current_qty,
      inventory_row.current_qty - line_quantity
    );

    lcd_count_value := lcd_count_value + 1;
  end loop;

  update public.daily_report_submissions
  set
    report_code = created_report_code,
    total_amount = total_amount_value,
    repair_count = repair_count_value,
    lcd_adjustment_count = lcd_count_value
  where id = created_report_id;

  delete from public.daily_report_drafts
  where store_id = selected_store.id
    and staff_id = selected_staff.id
    and report_date = report_date_value;

  return jsonb_build_object(
    'ok', true,
    'report_id', created_report_id,
    'report_code', created_report_code,
    'total_amount', total_amount_value,
    'repair_count', repair_count_value,
    'lcd_adjustment_count', lcd_count_value
  );
end;
$$;

create or replace function public.get_daily_reports(session_token text, target_date text default null, target_store_code text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reports_payload jsonb;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', report.id,
        'report_code', report.report_code,
        'report_date', report.report_date,
        'store_name', report.store_name,
        'staff_name', report.staff_name,
        'notes', report.notes,
        'total_amount', report.total_amount,
        'repair_count', report.repair_count,
        'lcd_adjustment_count', report.lcd_adjustment_count,
        'submitted_at', report.submitted_at,
        'faulty_broken_lines', report.faulty_broken_lines_json,
        'device_sales_lines', report.device_sales_lines_json,
        'device_buyback_lines', report.device_buyback_lines_json,
        'end_of_day', report.end_of_day_json,
        'cash_expense_lines', report.cash_expense_lines_json,
        'customer_tracking', report.customer_tracking_json,
        'missing_sales_lines', report.missing_sales_lines_json,
        'repair_lines', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'line_order', repair.line_order,
              'model_and_color', repair.model_and_color,
              'problem_and_parts_used', repair.problem_and_parts_used,
              'tech_name', repair.tech_name,
              'invoice_number', repair.invoice_number,
              'amount', repair.amount
            )
            order by repair.line_order
          )
          from public.daily_report_repairs repair
          where repair.report_id = report.id
        ), '[]'::jsonb),
        'lcd_lines', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'line_order', lcd.line_order,
              'model_name', lcd.model_name,
              'variant_name', lcd.variant_name,
              'action_type', lcd.action_type,
              'quantity', lcd.quantity,
              'stock_before', lcd.stock_before,
              'stock_after', lcd.stock_after
            )
            order by lcd.line_order
          )
          from public.daily_report_lcd_lines lcd
          where lcd.report_id = report.id
        ), '[]'::jsonb)
      )
      order by report.report_date desc, report.submitted_at desc, report.id desc
    ),
    '[]'::jsonb
  )
  into reports_payload
  from public.daily_report_submissions report
  join public.store_locations stores on stores.id = report.store_id
  where (
      coalesce(target_date, '') = ''
      or report.report_date = target_date::date
    )
    and (
      coalesce(target_store_code, '') = ''
      or stores.store_code = target_store_code
    );

  return jsonb_build_object('ok', true, 'reports', reports_payload);
end;
$$;

grant execute on function public.save_daily_report_draft(text, jsonb) to anon, authenticated;
grant execute on function public.get_daily_report_draft(text, text, text, text) to anon, authenticated;
grant execute on function public.submit_daily_report(text, jsonb) to anon, authenticated;
grant execute on function public.get_daily_reports(text, text, text) to anon, authenticated;

alter table public.daily_report_submissions
  add column if not exists submission_source text not null default 'staff',
  add column if not exists auto_submitted boolean not null default false;

create or replace function public.submit_daily_report_internal(
  payload jsonb,
  submission_source_value text default 'staff',
  auto_submitted_value boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  report_date_value date;
  report_notes text;
  repair_lines jsonb;
  lcd_lines jsonb;
  faulty_broken_lines jsonb;
  device_sales_lines jsonb;
  device_buyback_lines jsonb;
  end_of_day_json jsonb;
  cash_expense_lines jsonb;
  customer_tracking_json jsonb;
  missing_sales_lines jsonb;
  repair_line jsonb;
  lcd_line jsonb;
  created_report_id bigint;
  created_report_code text;
  total_amount_value numeric(12,2) := 0;
  repair_count_value integer := 0;
  lcd_count_value integer := 0;
  line_index integer := 0;
  inventory_row public.lcd_inventory_items%rowtype;
  line_quantity integer;
  line_amount numeric(12,2);
  line_action text;
begin
  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  select *
  into selected_store
  from public.store_locations
  where active = true
    and store_code = coalesce(trim(payload->>'store_code'), '');

  if not found then
    raise exception 'Store not found';
  end if;

  select *
  into selected_staff
  from public.staff_directory
  where active = true
    and display_name = coalesce(trim(payload->>'staff_name'), '');

  if not found then
    raise exception 'Staff member not found';
  end if;

  report_date_value := coalesce(nullif(payload->>'report_date', '')::date, current_date);
  report_notes := coalesce(trim(payload->>'notes'), '');
  repair_lines := coalesce(payload->'repair_lines', '[]'::jsonb);
  lcd_lines := coalesce(payload->'lcd_lines', '[]'::jsonb);
  faulty_broken_lines := coalesce(payload->'faulty_broken_lines', '[]'::jsonb);
  device_sales_lines := coalesce(payload->'device_sales_lines', '[]'::jsonb);
  device_buyback_lines := coalesce(payload->'device_buyback_lines', '[]'::jsonb);
  end_of_day_json := coalesce(payload->'end_of_day', '{}'::jsonb);
  cash_expense_lines := coalesce(payload->'cash_expense_lines', '[]'::jsonb);
  customer_tracking_json := coalesce(payload->'customer_tracking', '{}'::jsonb);
  missing_sales_lines := coalesce(payload->'missing_sales_lines', '[]'::jsonb);

  if jsonb_typeof(repair_lines) <> 'array' then
    raise exception 'Repair lines must be an array';
  end if;
  if jsonb_typeof(lcd_lines) <> 'array' then
    raise exception 'LCD lines must be an array';
  end if;
  if jsonb_typeof(faulty_broken_lines) <> 'array' then
    raise exception 'Faulty and broken lines must be an array';
  end if;
  if jsonb_typeof(device_sales_lines) <> 'array' then
    raise exception 'Device sales lines must be an array';
  end if;
  if jsonb_typeof(device_buyback_lines) <> 'array' then
    raise exception 'Device buyback lines must be an array';
  end if;
  if jsonb_typeof(cash_expense_lines) <> 'array' then
    raise exception 'Cash expense lines must be an array';
  end if;
  if jsonb_typeof(missing_sales_lines) <> 'array' then
    raise exception 'Missing sales lines must be an array';
  end if;
  if jsonb_typeof(end_of_day_json) <> 'object' then
    raise exception 'End of day data must be an object';
  end if;
  if jsonb_typeof(customer_tracking_json) <> 'object' then
    raise exception 'Customer tracking data must be an object';
  end if;

  if exists (
    select 1
    from public.daily_report_submissions existing_report
    where existing_report.store_id = selected_store.id
      and existing_report.report_date = report_date_value
  ) then
    raise exception 'A report for this store and date has already been submitted';
  end if;

  insert into public.daily_report_submissions (
    report_date,
    store_id,
    staff_id,
    store_name,
    staff_name,
    notes,
    faulty_broken_lines_json,
    device_sales_lines_json,
    device_buyback_lines_json,
    end_of_day_json,
    cash_expense_lines_json,
    customer_tracking_json,
    missing_sales_lines_json,
    submission_source,
    auto_submitted
  )
  values (
    report_date_value,
    selected_store.id,
    selected_staff.id,
    selected_store.store_name,
    selected_staff.display_name,
    report_notes,
    faulty_broken_lines,
    device_sales_lines,
    device_buyback_lines,
    end_of_day_json,
    cash_expense_lines,
    customer_tracking_json,
    missing_sales_lines,
    coalesce(nullif(trim(submission_source_value), ''), 'staff'),
    auto_submitted_value
  )
  returning id into created_report_id;

  created_report_code := 'DR-' || to_char(report_date_value, 'YYYYMMDD') || '-' || lpad(created_report_id::text, 5, '0');

  line_index := 0;
  for repair_line in
    select value
    from jsonb_array_elements(repair_lines)
  loop
    if jsonb_typeof(repair_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(repair_line->>'model_and_color'), '') = ''
      and coalesce(trim(repair_line->>'problem_and_parts_used'), '') = ''
      and coalesce(trim(repair_line->>'invoice_number'), '') = ''
      and coalesce(trim(repair_line->>'amount'), '') = '' then
      continue;
    end if;

    line_index := line_index + 1;
    line_amount := case
      when coalesce(trim(repair_line->>'amount'), '') = '' then 0
      else regexp_replace(repair_line->>'amount', '[^0-9.\-]', '', 'g')::numeric(12,2)
    end;

    insert into public.daily_report_repairs (
      report_id,
      line_order,
      model_and_color,
      problem_and_parts_used,
      tech_name,
      invoice_number,
      amount
    )
    values (
      created_report_id,
      line_index,
      coalesce(trim(repair_line->>'model_and_color'), ''),
      coalesce(trim(repair_line->>'problem_and_parts_used'), ''),
      coalesce(nullif(trim(repair_line->>'tech_name'), ''), selected_staff.display_name),
      coalesce(trim(repair_line->>'invoice_number'), ''),
      line_amount
    );

    total_amount_value := total_amount_value + coalesce(line_amount, 0);
    repair_count_value := repair_count_value + 1;
  end loop;

  line_index := 0;
  for lcd_line in
    select value
    from jsonb_array_elements(lcd_lines)
  loop
    if jsonb_typeof(lcd_line) <> 'object' then
      continue;
    end if;

    if coalesce(trim(lcd_line->>'inventory_item_id'), '') = '' then
      continue;
    end if;

    line_action := coalesce(trim(lcd_line->>'action_type'), '');
    if line_action not in ('sold', 'send_to_other', 'faulty', 'broken') then
      raise exception 'Invalid LCD action type';
    end if;

    line_quantity := coalesce(nullif(trim(lcd_line->>'quantity'), ''), '0')::integer;
    if line_quantity <= 0 then
      raise exception 'LCD quantity must be greater than 0';
    end if;

    select *
    into inventory_row
    from public.lcd_inventory_items
    where id = (lcd_line->>'inventory_item_id')::bigint
      and store_id = selected_store.id
      and active = true
    for update;

    if not found then
      raise exception 'LCD inventory item not found for the selected store';
    end if;

    if inventory_row.current_qty < line_quantity then
      raise exception 'Not enough stock for % (%)', inventory_row.model_name, inventory_row.variant_name;
    end if;

    line_index := line_index + 1;

    update public.lcd_inventory_items
    set current_qty = current_qty - line_quantity
    where id = inventory_row.id;

    insert into public.daily_report_lcd_lines (
      report_id,
      line_order,
      lcd_inventory_item_id,
      model_name,
      variant_name,
      action_type,
      quantity,
      stock_before,
      stock_after
    )
    values (
      created_report_id,
      line_index,
      inventory_row.id,
      inventory_row.model_name,
      inventory_row.variant_name,
      line_action,
      line_quantity,
      inventory_row.current_qty,
      inventory_row.current_qty - line_quantity
    );

    lcd_count_value := lcd_count_value + 1;
  end loop;

  update public.daily_report_submissions
  set
    report_code = created_report_code,
    total_amount = total_amount_value,
    repair_count = repair_count_value,
    lcd_adjustment_count = lcd_count_value
  where id = created_report_id;

  delete from public.daily_report_drafts
  where store_id = selected_store.id
    and report_date = report_date_value;

  return jsonb_build_object(
    'ok', true,
    'report_id', created_report_id,
    'report_code', created_report_code,
    'total_amount', total_amount_value,
    'repair_count', repair_count_value,
    'lcd_adjustment_count', lcd_count_value,
    'submission_source', coalesce(nullif(trim(submission_source_value), ''), 'staff'),
    'auto_submitted', auto_submitted_value
  );
end;
$$;

create or replace function public.submit_daily_report(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  return public.submit_daily_report_internal(payload, 'staff', false);
end;
$$;

create or replace function public.list_daily_report_drafts(
  session_token text,
  target_store_code text,
  target_date text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_store public.store_locations%rowtype;
  target_date_value date;
  drafts_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  target_date_value := coalesce(nullif(target_date, '')::date, current_date);

  select *
  into selected_store
  from public.store_locations
  where active = true
    and store_code = coalesce(trim(target_store_code), '');

  if not found then
    return jsonb_build_object('ok', true, 'drafts', '[]'::jsonb, 'submitted_today', false);
  end if;

  delete from public.daily_report_drafts draft
  where draft.store_id = selected_store.id
    and draft.report_date = target_date_value
    and exists (
      select 1
      from public.daily_report_submissions report
      where report.store_id = draft.store_id
        and report.report_date = draft.report_date
    );

  delete from public.daily_report_drafts
  where report_date < current_date;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', draft.id,
        'staff_name', draft.staff_name,
        'store_name', draft.store_name,
        'report_date', draft.report_date,
        'updated_at', draft.updated_at,
        'payload', draft.payload
      )
      order by draft.updated_at desc, draft.id desc
    ),
    '[]'::jsonb
  )
  into drafts_payload
  from public.daily_report_drafts draft
  where draft.store_id = selected_store.id
    and draft.report_date = target_date_value;

  return jsonb_build_object(
    'ok', true,
    'submitted_today', exists (
      select 1
      from public.daily_report_submissions report
      where report.store_id = selected_store.id
        and report.report_date = target_date_value
    ),
    'drafts', drafts_payload
  );
end;
$$;

create or replace function public.rollover_daily_report_drafts(target_date date default current_date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  draft_record record;
  processed_count integer := 0;
  deleted_count integer := 0;
begin
  for draft_record in
    select distinct on (draft.store_id, draft.report_date)
      draft.*
    from public.daily_report_drafts draft
    where draft.report_date < target_date
    order by draft.store_id, draft.report_date, draft.updated_at desc, draft.id desc
  loop
    if exists (
      select 1
      from public.daily_report_submissions report
      where report.store_id = draft_record.store_id
        and report.report_date = draft_record.report_date
    ) then
      delete from public.daily_report_drafts
      where id = draft_record.id;
      deleted_count := deleted_count + 1;
      continue;
    end if;

    perform public.submit_daily_report_internal(draft_record.payload, 'midnight-rollover', true);
    processed_count := processed_count + 1;

    delete from public.daily_report_drafts
    where store_id = draft_record.store_id
      and report_date = draft_record.report_date;
  end loop;

  delete from public.daily_report_drafts
  where report_date < target_date;

  return jsonb_build_object(
    'ok', true,
    'auto_submitted', processed_count,
    'deleted', deleted_count
  );
end;
$$;

do $$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    null;
  end;

  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    begin
      perform cron.unschedule(jobid)
      from cron.job
      where jobname = 'techm8_daily_report_midnight_rollover';
    exception when others then
      null;
    end;

    begin
      perform cron.schedule(
        'techm8_daily_report_midnight_rollover',
        '0 0 * * *',
        $cron$select public.rollover_daily_report_drafts(current_date);$cron$
      );
    exception when others then
      null;
    end;
  end if;
end;
$$;

grant execute on function public.submit_daily_report_internal(jsonb, text, boolean) to anon, authenticated;
grant execute on function public.list_daily_report_drafts(text, text, text) to anon, authenticated;
grant execute on function public.rollover_daily_report_drafts(date) to anon, authenticated;
grant execute on function public.get_lcd_inventory(text, text) to anon, authenticated;
grant execute on function public.upsert_lcd_inventory_item(text, jsonb) to anon, authenticated;
grant execute on function public.delete_lcd_inventory_item(text, text, text, text) to anon, authenticated;
