create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.repair_prices (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  issue text not null,
  price text not null default '',
  cny_cost_price numeric(12,2),
  aud_cost_price_ex_gst numeric(12,2),
  aud_cost_price_inc_gst numeric(12,2),
  cost_basis_currency text,
  fx_rate_cny_to_aud numeric(12,6),
  fx_source text,
  fx_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint repair_prices_unique unique (brand, model, issue)
);

alter table public.repair_prices
  add column if not exists cny_cost_price numeric(12,2),
  add column if not exists aud_cost_price_ex_gst numeric(12,2),
  add column if not exists aud_cost_price_inc_gst numeric(12,2),
  add column if not exists cost_basis_currency text,
  add column if not exists fx_rate_cny_to_aud numeric(12,6),
  add column if not exists fx_source text,
  add column if not exists fx_updated_at timestamptz;

alter table public.repair_prices
  drop column if exists aud_cost_price,
  drop column if exists turnaround_time;

create table if not exists public.repair_intakes (
  id bigint generated by default as identity primary key,
  source_type text not null default 'quote',
  customer_name text not null,
  customer_phone text not null default '',
  customer_email text not null default '',
  contact_method text not null default 'Phone',
  device_type text not null default '',
  device_model text not null default '',
  quoted_price text not null default '',
  repair_issue text not null default '',
  estimated_time text not null default '',
  password_type text not null default 'text',
  password_text text not null default '',
  pattern_value text not null default '',
  password_none_reason text,
  device_id_type text not null default 'imei',
  device_id_imei text not null default '',
  device_id_sn text not null default '',
  device_id_unavailable_reason text,
  testable text not null default 'yes',
  test_profile text not null default 'mobile',
  cannot_test_reason text,
  test_notes text,
  test_results_json jsonb not null default '[]'::jsonb,
  quote_data_json jsonb not null default '{}'::jsonb,
  intake_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.apple_model_map (
  id bigint generated by default as identity primary key,
  a_number text not null unique,
  family_key text not null,
  model_name text not null,
  linked_price_list_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_config (
  id boolean primary key default true,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_sessions (
  id bigint generated by default as identity primary key,
  session_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

insert into public.admin_config (id, password_hash)
values (true, extensions.crypt('123456', extensions.gen_salt('bf')))
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists repair_prices_set_updated_at on public.repair_prices;
create trigger repair_prices_set_updated_at
before update on public.repair_prices
for each row
execute function public.set_updated_at();

drop trigger if exists repair_intakes_set_updated_at on public.repair_intakes;
create trigger repair_intakes_set_updated_at
before update on public.repair_intakes
for each row
execute function public.set_updated_at();

drop trigger if exists apple_model_map_set_updated_at on public.apple_model_map;
create trigger apple_model_map_set_updated_at
before update on public.apple_model_map
for each row
execute function public.set_updated_at();

drop trigger if exists admin_config_set_updated_at on public.admin_config;
create trigger admin_config_set_updated_at
before update on public.admin_config
for each row
execute function public.set_updated_at();

alter table public.repair_prices enable row level security;
alter table public.repair_intakes enable row level security;
alter table public.apple_model_map enable row level security;
alter table public.admin_config enable row level security;
alter table public.staff_sessions enable row level security;

drop policy if exists repair_prices_select_all on public.repair_prices;
create policy repair_prices_select_all
on public.repair_prices
for select
to anon, authenticated
using (true);

drop policy if exists repair_intakes_insert_all on public.repair_intakes;
create policy repair_intakes_insert_all
on public.repair_intakes
for insert
to anon, authenticated
with check (true);

drop policy if exists apple_model_map_select_all on public.apple_model_map;
create policy apple_model_map_select_all
on public.apple_model_map
for select
to anon, authenticated
using (true);

drop policy if exists admin_config_no_access on public.admin_config;
create policy admin_config_no_access
on public.admin_config
for select
to anon, authenticated
using (false);

drop policy if exists staff_sessions_no_access on public.staff_sessions;
create policy staff_sessions_no_access
on public.staff_sessions
for select
to anon, authenticated
using (false);

create or replace function public.is_valid_staff_session(session_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') = '' then
    return false;
  end if;

  delete from public.staff_sessions
  where expires_at <= now();

  return exists (
    select 1
    from public.staff_sessions
    where expires_at > now()
      and extensions.crypt(session_token, session_hash) = session_hash
  );
end;
$$;

create or replace function public.create_staff_session(input_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
  issued_token text;
  session_expires_at timestamptz;
begin
  stored_hash := (
    select password_hash
    from public.admin_config
    where id = true
  );

  if stored_hash is null or extensions.crypt(input_password, stored_hash) <> stored_hash then
    return jsonb_build_object('ok', false, 'message', 'Incorrect password');
  end if;

  delete from public.staff_sessions
  where expires_at <= now();

  issued_token := encode(extensions.gen_random_bytes(24), 'hex');
  session_expires_at := now() + interval '12 hours';

  insert into public.staff_sessions (session_hash, expires_at)
  values (extensions.crypt(issued_token, extensions.gen_salt('bf')), session_expires_at);

  return jsonb_build_object(
    'ok', true,
    'session_token', issued_token,
    'expires_at', session_expires_at
  );
end;
$$;

create or replace function public.verify_staff_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return jsonb_build_object('ok', public.is_valid_staff_session(session_token));
end;
$$;

create or replace function public.revoke_staff_session(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(session_token), '') <> '' then
    delete from public.staff_sessions
    where extensions.crypt(session_token, session_hash) = session_hash;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.change_staff_password(session_token text, new_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if length(coalesce(new_password, '')) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  update public.admin_config
  set password_hash = extensions.crypt(new_password, extensions.gen_salt('bf'))
  where id = true;

  delete from public.staff_sessions
  where true;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.upsert_repair_price(session_token text, row_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_brand text;
  row_model text;
  row_issue text;
  row_price text;
  row_cny_cost_price numeric(12,2);
  row_aud_cost_price_ex_gst numeric(12,2);
  row_aud_cost_price_inc_gst numeric(12,2);
  row_cost_basis_currency text;
  row_fx_rate_cny_to_aud numeric(12,6);
  row_fx_source text;
  row_fx_updated_at timestamptz;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(row_payload) <> 'object' then
    raise exception 'Row payload must be a JSON object';
  end if;

  row_brand := coalesce(trim(row_payload->>'brand'), '');
  row_model := coalesce(trim(row_payload->>'model'), '');
  row_issue := coalesce(trim(row_payload->>'issue'), '');
  row_price := coalesce(trim(row_payload->>'price'), '');
  row_cost_basis_currency := upper(coalesce(trim(row_payload->>'cost_basis_currency'), ''));
  row_fx_source := coalesce(trim(row_payload->>'fx_source'), '');

  if coalesce(trim(row_payload->>'cny_cost_price'), '') <> '' then
    row_cny_cost_price := (row_payload->>'cny_cost_price')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'aud_cost_price_ex_gst'), '') <> '' then
    row_aud_cost_price_ex_gst := (row_payload->>'aud_cost_price_ex_gst')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'aud_cost_price_inc_gst'), '') <> '' then
    row_aud_cost_price_inc_gst := (row_payload->>'aud_cost_price_inc_gst')::numeric(12,2);
  end if;

  if coalesce(trim(row_payload->>'fx_rate_cny_to_aud'), '') <> '' then
    row_fx_rate_cny_to_aud := (row_payload->>'fx_rate_cny_to_aud')::numeric(12,6);
  end if;

  if coalesce(trim(row_payload->>'fx_updated_at'), '') <> '' then
    row_fx_updated_at := (row_payload->>'fx_updated_at')::timestamptz;
  end if;

  if row_brand = '' or row_model = '' or row_issue = '' then
    raise exception 'Brand, model, and issue are required';
  end if;

  insert into public.repair_prices (
    brand,
    model,
    issue,
    price,
    cny_cost_price,
    aud_cost_price_ex_gst,
    aud_cost_price_inc_gst,
    cost_basis_currency,
    fx_rate_cny_to_aud,
    fx_source,
    fx_updated_at
  )
  values (
    row_brand,
    row_model,
    row_issue,
    row_price,
    row_cny_cost_price,
    row_aud_cost_price_ex_gst,
    row_aud_cost_price_inc_gst,
    row_cost_basis_currency,
    row_fx_rate_cny_to_aud,
    row_fx_source,
    row_fx_updated_at
  )
  on conflict (brand, model, issue) do update
  set
    price = excluded.price,
    cny_cost_price = excluded.cny_cost_price,
    aud_cost_price_ex_gst = excluded.aud_cost_price_ex_gst,
    aud_cost_price_inc_gst = excluded.aud_cost_price_inc_gst,
    cost_basis_currency = excluded.cost_basis_currency,
    fx_rate_cny_to_aud = excluded.fx_rate_cny_to_aud,
    fx_source = excluded.fx_source,
    fx_updated_at = excluded.fx_updated_at,
    updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'brand', row_brand,
    'model', row_model,
    'issue', row_issue
  );
end;
$$;

create or replace function public.delete_repair_price(session_token text, target_brand text, target_model text, target_issue text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  delete from public.repair_prices
  where brand = coalesce(trim(target_brand), '')
    and model = coalesce(trim(target_model), '')
    and issue = coalesce(trim(target_issue), '');

  get diagnostics deleted_count = row_count;

  return jsonb_build_object('ok', true, 'deleted', deleted_count);
end;
$$;

drop function if exists public.save_repair_prices(jsonb);
create or replace function public.save_repair_prices(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(payload) <> 'array' then
    raise exception 'Payload must be a JSON array';
  end if;

  delete from public.repair_prices
  where true;

  for item in select * from jsonb_array_elements(payload)
  loop
    insert into public.repair_prices (
      brand,
      model,
      issue,
      price,
      cny_cost_price,
      aud_cost_price_ex_gst,
      aud_cost_price_inc_gst,
      cost_basis_currency,
      fx_rate_cny_to_aud,
      fx_source,
      fx_updated_at
    )
    values (
      coalesce(trim(item->>'brand'), ''),
      coalesce(trim(item->>'model'), ''),
      coalesce(trim(item->>'issue'), ''),
      coalesce(trim(item->>'price'), ''),
      case when coalesce(trim(item->>'cny_cost_price'), '') = '' then null else (item->>'cny_cost_price')::numeric(12,2) end,
      case when coalesce(trim(item->>'aud_cost_price_ex_gst'), '') = '' then null else (item->>'aud_cost_price_ex_gst')::numeric(12,2) end,
      case when coalesce(trim(item->>'aud_cost_price_inc_gst'), '') = '' then null else (item->>'aud_cost_price_inc_gst')::numeric(12,2) end,
      nullif(upper(coalesce(trim(item->>'cost_basis_currency'), '')), ''),
      case when coalesce(trim(item->>'fx_rate_cny_to_aud'), '') = '' then null else (item->>'fx_rate_cny_to_aud')::numeric(12,6) end,
      nullif(coalesce(trim(item->>'fx_source'), ''), ''),
      case when coalesce(trim(item->>'fx_updated_at'), '') = '' then null else (item->>'fx_updated_at')::timestamptz end
    )
    on conflict (brand, model, issue) do update
    set
      price = excluded.price,
      cny_cost_price = excluded.cny_cost_price,
      aud_cost_price_ex_gst = excluded.aud_cost_price_ex_gst,
      aud_cost_price_inc_gst = excluded.aud_cost_price_inc_gst,
      cost_basis_currency = excluded.cost_basis_currency,
      fx_rate_cny_to_aud = excluded.fx_rate_cny_to_aud,
      fx_source = excluded.fx_source,
      fx_updated_at = excluded.fx_updated_at,
      updated_at = now();
  end loop;

  return jsonb_build_object(
    'ok', true,
    'saved', jsonb_array_length(payload)
  );
end;
$$;

drop function if exists public.save_apple_model_map(jsonb);
create or replace function public.save_apple_model_map(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  family_key text;
  family_payload jsonb;
  entry record;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  delete from public.apple_model_map
  where true;

  for family_key, family_payload in
    select key, value
    from jsonb_each(payload)
  loop
    if jsonb_typeof(family_payload) <> 'object' then
      continue;
    end if;

    for entry in
      select key, value
      from jsonb_each_text(family_payload)
    loop
      insert into public.apple_model_map (a_number, family_key, model_name)
      values (entry.key, family_key, entry.value)
      on conflict (a_number) do update
      set
        family_key = excluded.family_key,
        model_name = excluded.model_name,
        updated_at = now();
    end loop;
  end loop;

  return jsonb_build_object('ok', true);
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.repair_prices to anon, authenticated;
grant insert on public.repair_intakes to anon, authenticated;
grant select on public.apple_model_map to anon, authenticated;
grant execute on function public.is_valid_staff_session(text) to anon, authenticated;
grant execute on function public.create_staff_session(text) to anon, authenticated;
grant execute on function public.verify_staff_session(text) to anon, authenticated;
grant execute on function public.revoke_staff_session(text) to anon, authenticated;
grant execute on function public.change_staff_password(text, text) to anon, authenticated;
grant execute on function public.upsert_repair_price(text, jsonb) to anon, authenticated;
grant execute on function public.delete_repair_price(text, text, text, text) to anon, authenticated;
grant execute on function public.save_repair_prices(text, jsonb) to anon, authenticated;
grant execute on function public.save_apple_model_map(text, jsonb) to anon, authenticated;
