create table if not exists public.pos_category_taxonomy (
  id bigint generated by default as identity primary key,
  category_name text not null,
  subcategory_name text not null,
  category_sort integer not null default 0,
  subcategory_sort integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_name, subcategory_name)
);

insert into public.pos_category_taxonomy (
  category_name,
  subcategory_name,
  category_sort,
  subcategory_sort,
  active
)
values
  ('Phone Cases', 'Apple iPhone', 10, 10, true),
  ('Phone Cases', 'Samsung Galaxy', 10, 20, true),
  ('Phone Cases', 'Google Pixel', 10, 30, true),
  ('Phone Cases', 'Other & Universal', 10, 40, true),
  ('Tablet Cases', 'Apple iPad', 20, 10, true),
  ('Tablet Cases', 'Samsung Galaxy Tab', 20, 20, true),
  ('Tablet Cases', 'Other & Universal', 20, 30, true),
  ('Screen Protection', 'Phone Screen Protection', 30, 10, true),
  ('Screen Protection', 'Tablet Screen Protection', 30, 20, true),
  ('Screen Protection', 'Watch & Lens Protection', 30, 30, true),
  ('Cables & Adapters', 'Charging & Data Cables', 40, 10, true),
  ('Cables & Adapters', 'Display & Computer Cables', 40, 20, true),
  ('Cables & Adapters', 'Network Cables', 40, 30, true),
  ('Cables & Adapters', 'Audio Cables & Adapters', 40, 40, true),
  ('Cables & Adapters', 'OTG & Card Readers', 40, 50, true),
  ('Cables & Adapters', 'Car Connectivity', 40, 60, true),
  ('Charging & Power', 'Wall Chargers', 50, 10, true),
  ('Charging & Power', 'Wireless Chargers', 50, 20, true),
  ('Charging & Power', 'Car Chargers', 50, 30, true),
  ('Charging & Power', 'Laptop Chargers', 50, 40, true),
  ('Charging & Power', 'Power Banks', 50, 50, true),
  ('Audio', 'Wired Earphones & Headphones', 60, 10, true),
  ('Audio', 'Wireless Earbuds & Headphones', 60, 20, true),
  ('Audio', 'Headsets', 60, 30, true),
  ('Audio', 'Speakers', 60, 40, true),
  ('Audio', 'Microphones', 60, 50, true),
  ('Mounts & Holders', 'Vehicle Mounts', 70, 10, true),
  ('Mounts & Holders', 'Phone & Tablet Stands', 70, 20, true),
  ('Mounts & Holders', 'Laptop Stands', 70, 30, true),
  ('Mounts & Holders', 'Monitor Mounts', 70, 40, true),
  ('Mounts & Holders', 'Selfie Sticks & Live Stands', 70, 50, true),
  ('Mounts & Holders', 'Wallets, Card Holders & Grips', 70, 60, true),
  ('Watch Accessories', 'Watch Bands', 80, 10, true),
  ('Watch Accessories', 'Watch Cases', 80, 20, true),
  ('Computer & Gaming', 'PC Components', 90, 10, true),
  ('Computer & Gaming', 'Input & Office Peripherals', 90, 20, true),
  ('Computer & Gaming', 'Hubs & Docks', 90, 30, true),
  ('Computer & Gaming', 'Networking', 90, 40, true),
  ('Computer & Gaming', 'Storage', 90, 50, true),
  ('Computer & Gaming', 'Consoles & Controllers', 90, 60, true),
  ('Computer & Gaming', 'Gaming & Simulation', 90, 70, true),
  ('Other Electronics', 'Drones & Accessories', 100, 10, true),
  ('Other Electronics', 'Personal Fans', 100, 20, true),
  ('Other Electronics', 'Lighting & Clocks', 100, 30, true),
  ('Other Electronics', 'Earbud Cases', 100, 40, true),
  ('Other Electronics', 'Tracker Cases', 100, 50, true),
  ('Other Electronics', 'Other Electronics', 100, 60, true)
on conflict (category_name, subcategory_name) do update
set
  category_sort = excluded.category_sort,
  subcategory_sort = excluded.subcategory_sort,
  active = excluded.active,
  updated_at = now();

alter table public.products
  add column if not exists pos_category_id bigint references public.pos_category_taxonomy(id) on delete set null;

alter table public.product_groups
  add column if not exists pos_category_id bigint references public.pos_category_taxonomy(id) on delete set null;

create index if not exists products_pos_category_id_idx on public.products (pos_category_id);
create index if not exists product_groups_pos_category_id_idx on public.product_groups (pos_category_id);

create table if not exists public.pos_stocktake_changes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  product_group_id bigint references public.product_groups(id) on delete set null,
  store_id bigint not null references public.stores(id) on delete restrict,
  staff_name text not null,
  old_pos_category_id bigint references public.pos_category_taxonomy(id) on delete set null,
  new_pos_category_id bigint not null references public.pos_category_taxonomy(id) on delete restrict,
  old_quantity integer not null,
  new_quantity integer not null,
  created_at timestamptz not null default now()
);

create index if not exists pos_stocktake_changes_store_created_idx
  on public.pos_stocktake_changes (store_id, created_at desc);
create index if not exists pos_stocktake_changes_product_created_idx
  on public.pos_stocktake_changes (product_id, created_at desc);

alter table public.pos_category_taxonomy enable row level security;
alter table public.pos_stocktake_changes enable row level security;

revoke all on table public.pos_category_taxonomy from public, anon, authenticated;
revoke all on table public.pos_stocktake_changes from public, anon, authenticated;

create or replace function public.apply_pos_stocktake_update(
  target_product_id bigint,
  target_store_slug text,
  target_pos_category_id bigint,
  target_quantity integer,
  target_staff_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_product public.products%rowtype;
  selected_group public.product_groups%rowtype;
  selected_store public.stores%rowtype;
  selected_taxonomy public.pos_category_taxonomy%rowtype;
  previous_category_id bigint;
  previous_quantity integer := 0;
begin
  if target_quantity is null or target_quantity < 0 or target_quantity > 1000000 then
    raise exception 'Stock quantity must be between 0 and 1000000';
  end if;

  if coalesce(trim(target_staff_name), '') = '' then
    raise exception 'Staff name is required';
  end if;

  select *
  into selected_product
  from public.products
  where id = target_product_id
    and is_pos_visible = true
  for update;

  if selected_product.id is null then
    raise exception 'POS product not found';
  end if;

  select *
  into selected_store
  from public.stores
  where slug = trim(target_store_slug)
    and is_active = true;

  if selected_store.id is null then
    raise exception 'Active store not found';
  end if;

  select *
  into selected_taxonomy
  from public.pos_category_taxonomy
  where id = target_pos_category_id
    and active = true;

  if selected_taxonomy.id is null then
    raise exception 'Active POS category not found';
  end if;

  if selected_product.product_group_id is not null then
    select *
    into selected_group
    from public.product_groups
    where id = selected_product.product_group_id
    for update;

    previous_category_id := selected_group.pos_category_id;

    update public.product_groups
    set
      pos_category_id = selected_taxonomy.id,
      updated_at = now()
    where id = selected_group.id;
  else
    previous_category_id := selected_product.pos_category_id;

    update public.products
    set
      pos_category_id = selected_taxonomy.id,
      updated_at = now()
    where id = selected_product.id;
  end if;

  select coalesce(inventory.quantity, 0)
  into previous_quantity
  from public.product_store_inventory inventory
  where inventory.product_id = selected_product.id
    and inventory.store_id = selected_store.id
  for update;

  previous_quantity := coalesce(previous_quantity, 0);

  insert into public.product_store_inventory (product_id, store_id, quantity, updated_at)
  values (selected_product.id, selected_store.id, target_quantity, now())
  on conflict (product_id, store_id) do update
  set
    quantity = excluded.quantity,
    updated_at = now();

  update public.products
  set
    stock_quantity = (
      select coalesce(sum(inventory.quantity), 0)::integer
      from public.product_store_inventory inventory
      where inventory.product_id = selected_product.id
    ),
    updated_at = now()
  where id = selected_product.id;

  insert into public.pos_stocktake_changes (
    product_id,
    product_group_id,
    store_id,
    staff_name,
    old_pos_category_id,
    new_pos_category_id,
    old_quantity,
    new_quantity
  )
  values (
    selected_product.id,
    selected_product.product_group_id,
    selected_store.id,
    trim(target_staff_name),
    previous_category_id,
    selected_taxonomy.id,
    previous_quantity,
    target_quantity
  );

  return jsonb_build_object(
    'ok', true,
    'product_id', selected_product.id,
    'product_group_id', selected_product.product_group_id,
    'store_slug', selected_store.slug,
    'store_name', selected_store.name,
    'quantity', target_quantity,
    'total_stock', (
      select products.stock_quantity
      from public.products
      where products.id = selected_product.id
    ),
    'previous_quantity', previous_quantity,
    'pos_category_id', selected_taxonomy.id,
    'category', selected_taxonomy.category_name,
    'subcategory', selected_taxonomy.subcategory_name
  );
end;
$$;

revoke all on function public.apply_pos_stocktake_update(bigint, text, bigint, integer, text) from public, anon, authenticated;
grant execute on function public.apply_pos_stocktake_update(bigint, text, bigint, integer, text) to service_role;
