insert into public.pos_category_taxonomy (
  category_name,
  subcategory_name,
  category_sort,
  subcategory_sort,
  active
)
values
  ('Computer & Gaming', 'Keyboards, Mice & Accessories', 90, 20, true),
  ('Computer & Gaming', 'Other Computer Accessories', 90, 25, true)
on conflict (category_name, subcategory_name) do update
set
  category_sort = excluded.category_sort,
  subcategory_sort = excluded.subcategory_sort,
  active = true,
  updated_at = now();

update public.pos_category_taxonomy
set active = false, updated_at = now()
where category_name = 'Computer & Gaming'
  and subcategory_name = 'Input & Office Peripherals';

with target_category as (
  select id
  from public.pos_category_taxonomy
  where category_name = 'Computer & Gaming'
    and subcategory_name = 'Keyboards, Mice & Accessories'
    and active = true
)
update public.products product
set
  pos_category_id = target_category.id,
  source_metadata = jsonb_set(
    jsonb_set(coalesce(product.source_metadata, '{}'::jsonb), '{pos_main_category}', '"Computer & Gaming"'::jsonb, true),
    '{pos_subcategory}',
    '"Keyboards, Mice & Accessories"'::jsonb,
    true
  ),
  updated_at = now()
from target_category
where product.is_pos_visible = true
  and product.source_system = 'repairdesk_computer_products'
  and coalesce(product.source_metadata->>'pos_subcategory', '') = 'Input & Office Peripherals'
  and product.name not ilike '%webcam%';

with target_category as (
  select id
  from public.pos_category_taxonomy
  where category_name = 'Computer & Gaming'
    and subcategory_name = 'Other Computer Accessories'
    and active = true
)
update public.products product
set
  pos_category_id = target_category.id,
  source_metadata = jsonb_set(
    jsonb_set(coalesce(product.source_metadata, '{}'::jsonb), '{pos_main_category}', '"Computer & Gaming"'::jsonb, true),
    '{pos_subcategory}',
    '"Other Computer Accessories"'::jsonb,
    true
  ),
  updated_at = now()
from target_category
where product.is_pos_visible = true
  and product.source_system = 'repairdesk_computer_products'
  and (
    coalesce(product.source_metadata->>'pos_subcategory', '') = 'Laptop Bags & Sleeves'
    or (
      coalesce(product.source_metadata->>'pos_subcategory', '') = 'Input & Office Peripherals'
      and product.name ilike '%webcam%'
    )
  );

alter table public.products
  add column if not exists pos_sort_order integer;

alter table public.product_groups
  add column if not exists pos_sort_order integer;

alter table public.products
  drop constraint if exists products_pos_sort_order_check;

alter table public.products
  add constraint products_pos_sort_order_check
  check (pos_sort_order is null or pos_sort_order between 0 and 1000000);

alter table public.product_groups
  drop constraint if exists product_groups_pos_sort_order_check;

alter table public.product_groups
  add constraint product_groups_pos_sort_order_check
  check (pos_sort_order is null or pos_sort_order between 0 and 1000000);

create index if not exists products_pos_category_sort_idx
  on public.products (pos_category_id, pos_sort_order, id)
  where is_pos_visible = true;

create index if not exists product_groups_pos_category_sort_idx
  on public.product_groups (pos_category_id, pos_sort_order, id)
  where is_pos_visible = true;

create table if not exists public.pos_catalog_order_changes (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('categories', 'subcategories', 'products')),
  target_type text not null check (target_type in ('category', 'subcategory', 'product', 'group')),
  target_id bigint,
  target_key text,
  old_sort_order integer,
  new_sort_order integer not null,
  changed_by_staff text not null,
  created_at timestamptz not null default now()
);

create index if not exists pos_catalog_order_changes_created_idx
  on public.pos_catalog_order_changes (created_at desc);

alter table public.pos_catalog_order_changes enable row level security;
revoke all on table public.pos_catalog_order_changes from public, anon, authenticated;

create or replace function public.apply_pos_catalog_arrangement(
  target_scope text,
  target_rows jsonb,
  target_staff_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_value jsonb;
  selected_scope text := lower(trim(coalesce(target_scope, '')));
  selected_staff text := trim(coalesce(target_staff_name, ''));
  selected_type text;
  selected_key text;
  selected_id bigint;
  selected_order integer;
  previous_order integer;
  affected_rows integer;
  changed_rows integer := 0;
begin
  if lower(selected_staff) <> 'bowen' then
    raise exception 'Only Bowen can arrange the POS catalogue';
  end if;

  if selected_scope not in ('categories', 'subcategories', 'products') then
    raise exception 'Invalid catalogue arrangement scope';
  end if;

  if target_rows is null or jsonb_typeof(target_rows) <> 'array' then
    raise exception 'Catalogue arrangement rows must be an array';
  end if;

  if jsonb_array_length(target_rows) > 1000 then
    raise exception 'Too many catalogue arrangement rows';
  end if;

  for row_value in select value from jsonb_array_elements(target_rows)
  loop
    selected_type := lower(trim(coalesce(row_value->>'target_type', '')));
    selected_key := trim(coalesce(row_value->>'target_key', ''));
    selected_id := nullif(row_value->>'target_id', '')::bigint;
    selected_order := nullif(row_value->>'sort_order', '')::integer;

    if selected_order is null or selected_order < 0 or selected_order > 1000000 then
      raise exception 'Invalid catalogue sort order';
    end if;

    if selected_scope = 'categories' then
      if selected_type <> 'category' or selected_key = '' then
        raise exception 'A category name is required';
      end if;

      select min(category_sort)
      into previous_order
      from public.pos_category_taxonomy
      where category_name = selected_key
        and active = true;

      update public.pos_category_taxonomy
      set category_sort = selected_order, updated_at = now()
      where category_name = selected_key
        and active = true;

      get diagnostics affected_rows = row_count;
      if affected_rows = 0 then
        raise exception 'Active POS category not found: %', selected_key;
      end if;

      insert into public.pos_catalog_order_changes (
        scope, target_type, target_key, old_sort_order, new_sort_order, changed_by_staff
      ) values (
        selected_scope, selected_type, selected_key, previous_order, selected_order, selected_staff
      );
    elsif selected_scope = 'subcategories' then
      if selected_type <> 'subcategory' or selected_id is null then
        raise exception 'A subcategory id is required';
      end if;

      select subcategory_sort
      into previous_order
      from public.pos_category_taxonomy
      where id = selected_id
        and active = true;

      update public.pos_category_taxonomy
      set subcategory_sort = selected_order, updated_at = now()
      where id = selected_id
        and active = true;

      get diagnostics affected_rows = row_count;
      if affected_rows = 0 then
        raise exception 'Active POS subcategory not found: %', selected_id;
      end if;

      insert into public.pos_catalog_order_changes (
        scope, target_type, target_id, old_sort_order, new_sort_order, changed_by_staff
      ) values (
        selected_scope, selected_type, selected_id, previous_order, selected_order, selected_staff
      );
    else
      if selected_type not in ('product', 'group') or selected_id is null then
        raise exception 'A product or group id is required';
      end if;

      if selected_type = 'group' then
        select pos_sort_order
        into previous_order
        from public.product_groups
        where id = selected_id
          and is_pos_visible = true;

        update public.product_groups
        set pos_sort_order = selected_order, updated_at = now()
        where id = selected_id
          and is_pos_visible = true;
      else
        select pos_sort_order
        into previous_order
        from public.products
        where id = selected_id
          and is_pos_visible = true;

        update public.products
        set pos_sort_order = selected_order, updated_at = now()
        where id = selected_id
          and is_pos_visible = true;
      end if;

      get diagnostics affected_rows = row_count;
      if affected_rows = 0 then
        raise exception 'Visible POS % not found: %', selected_type, selected_id;
      end if;

      insert into public.pos_catalog_order_changes (
        scope, target_type, target_id, old_sort_order, new_sort_order, changed_by_staff
      ) values (
        selected_scope, selected_type, selected_id, previous_order, selected_order, selected_staff
      );
    end if;

    changed_rows := changed_rows + 1;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'scope', selected_scope,
    'changed', changed_rows,
    'staff_name', selected_staff
  );
end;
$$;

revoke all on function public.apply_pos_catalog_arrangement(text, jsonb, text) from public, anon, authenticated;
grant execute on function public.apply_pos_catalog_arrangement(text, jsonb, text) to service_role;
