-- RepairDesk 124 rows -> 109 unique style/size combinations.
-- Add 48 missing source variants and 3 explicitly requested size counterparts.
-- Existing products/prices/inventory are never updated. New inventory starts at zero.
begin;

create temporary table band_completion_input on commit drop as
select * from jsonb_to_recordset($bands$
[
  {
    "sku": "TM8-WB-10343",
    "source_id": "10343",
    "original_name": "38/40 Fabric Apple Watch Band Pink",
    "original_sku": "10343489",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 2,
    "source_retail": 30,
    "group_code": "TM8-GRP-WB-FABRIC-PINK",
    "group_slug": "watch-band-fabric-pink",
    "group_name": "Fabric Apple Watch Band - Pink",
    "color": "Pink",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.55102300%201748228684.jpg",
    "reference_sku": "TM8-WB-10374",
    "reference_price": 30,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10372",
    "source_id": "10372",
    "original_name": "42/44 Silicone Apple Watch Blue Flower",
    "original_sku": "10372518",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-BLUE-FLOWER",
    "group_slug": "watch-band-silicone-blue-flower",
    "group_name": "Silicone Apple Watch Band - Blue Flower",
    "color": "Blue Flower",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.10230500%201748228476.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10371",
    "source_id": "10371",
    "original_name": "38/40 Silicone Apple Watch Blue Flower",
    "original_sku": "10371517",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-BLUE-FLOWER",
    "group_slug": "watch-band-silicone-blue-flower",
    "group_name": "Silicone Apple Watch Band - Blue Flower",
    "color": "Blue Flower",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.10230500%201748228476.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10370",
    "source_id": "10370",
    "original_name": "42/44 Silicone Apple Watch Purple Flower",
    "original_sku": "10370516",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-PURPLE-FLOWER",
    "group_slug": "watch-band-silicone-purple-flower",
    "group_name": "Silicone Apple Watch Band - Purple Flower",
    "color": "Purple Flower",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.02676000%201748228399.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10369",
    "source_id": "10369",
    "original_name": "38/40 Silicone Apple Watch Purple Flower",
    "original_sku": "10369515",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-PURPLE-FLOWER",
    "group_slug": "watch-band-silicone-purple-flower",
    "group_name": "Silicone Apple Watch Band - Purple Flower",
    "color": "Purple Flower",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.02676000%201748228399.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10368",
    "source_id": "10368",
    "original_name": "42/44 Silicone Apple Watch Rosewood",
    "original_sku": "10368514",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-ROSEWOOD",
    "group_slug": "watch-band-silicone-rosewood",
    "group_name": "Silicone Apple Watch Band - Rosewood",
    "color": "Rosewood",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.63604000%201748228338.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10367",
    "source_id": "10367",
    "original_name": "38/40 Silicone Apple Watch Rosewood",
    "original_sku": "10367513",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-ROSEWOOD",
    "group_slug": "watch-band-silicone-rosewood",
    "group_name": "Silicone Apple Watch Band - Rosewood",
    "color": "Rosewood",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.63604000%201748228338.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10366",
    "source_id": "10366",
    "original_name": "42/44 Silicone Apple Watch Black Flower",
    "original_sku": "10366512",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-BLACK-FLOWER",
    "group_slug": "watch-band-silicone-black-flower",
    "group_name": "Silicone Apple Watch Band - Black Flower",
    "color": "Black Flower",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.87457100%201748228204.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10365",
    "source_id": "10365",
    "original_name": "38/40 Silicone Apple Watch Black Flower",
    "original_sku": "10365511",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-BLACK-FLOWER",
    "group_slug": "watch-band-silicone-black-flower",
    "group_name": "Silicone Apple Watch Band - Black Flower",
    "color": "Black Flower",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.87457100%201748228204.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10364",
    "source_id": "10364",
    "original_name": "42/44 Silicone Apple Watch Ivory",
    "original_sku": "10364510",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-IVORY",
    "group_slug": "watch-band-silicone-ivory",
    "group_name": "Silicone Apple Watch Band - Ivory",
    "color": "Ivory",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.92408700%201748228135.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10363",
    "source_id": "10363",
    "original_name": "38/40 Silicone Apple Watch Ivory",
    "original_sku": "10363508",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3,
    "source_retail": 39,
    "group_code": "TM8-GRP-WB-SILICONE-IVORY",
    "group_slug": "watch-band-silicone-ivory",
    "group_name": "Silicone Apple Watch Band - Ivory",
    "color": "Ivory",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.92408700%201748228135.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10361",
    "source_id": "10361",
    "original_name": "42/44 Ocean Band Ivory",
    "original_sku": "10361507",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-IVORY",
    "group_slug": "watch-band-ocean-ivory",
    "group_name": "Ocean Band - Ivory",
    "color": "Ivory",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.35784300%201748224320.jpg",
    "reference_sku": "TM8-WB-10360",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10359",
    "source_id": "10359",
    "original_name": "42/44 Ocean Band Blue",
    "original_sku": "10359505",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-BLUE",
    "group_slug": "watch-band-ocean-blue",
    "group_name": "Ocean Band - Blue",
    "color": "Blue",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.51151200%201748224305.jpg",
    "reference_sku": "TM8-WB-8933",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10358",
    "source_id": "10358",
    "original_name": "38/40 Ocean Band Blue",
    "original_sku": "10358504",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-BLUE",
    "group_slug": "watch-band-ocean-blue",
    "group_name": "Ocean Band - Blue",
    "color": "Blue",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.51151200%201748224305.jpg",
    "reference_sku": "TM8-WB-8933",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10357",
    "source_id": "10357",
    "original_name": "42/44 Ocean Band Mint Green",
    "original_sku": "10357503",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-MINT-GREEN",
    "group_slug": "watch-band-ocean-mint-green",
    "group_name": "Ocean Band - Mint Green",
    "color": "Mint Green",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.28418000%201748224242.jpg",
    "reference_sku": "TM8-WB-8933",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10356",
    "source_id": "10356",
    "original_name": "38/40 Ocean Band Mint Green",
    "original_sku": "10356502",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-MINT-GREEN",
    "group_slug": "watch-band-ocean-mint-green",
    "group_name": "Ocean Band - Mint Green",
    "color": "Mint Green",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.28418000%201748224242.jpg",
    "reference_sku": "TM8-WB-8933",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10355",
    "source_id": "10355",
    "original_name": "42/44 Ocean Band Pink",
    "original_sku": "10355501",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 2,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-PINK",
    "group_slug": "watch-band-ocean-pink",
    "group_name": "Ocean Band - Pink",
    "color": "Pink",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.50054500%201748224116.jpg",
    "reference_sku": "TM8-WB-10354",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10351",
    "source_id": "10351",
    "original_name": "42/44 Magnetic Apple Watch Bands Yellow",
    "original_sku": "10351497",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-YELLOW",
    "group_slug": "watch-band-magnetic-yellow",
    "group_name": "Magnetic Apple Watch Band - Yellow",
    "color": "Yellow",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.55239100%201748223713.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10350",
    "source_id": "10350",
    "original_name": "38/40 Magnetic Apple Watch Bands Yellow",
    "original_sku": "10350496",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-YELLOW",
    "group_slug": "watch-band-magnetic-yellow",
    "group_name": "Magnetic Apple Watch Band - Yellow",
    "color": "Yellow",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.55239100%201748223713.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10349",
    "source_id": "10349",
    "original_name": "42/44 Magnetic Apple Watch Bands Gray",
    "original_sku": "10349495",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-GRAY",
    "group_slug": "watch-band-magnetic-gray",
    "group_name": "Magnetic Apple Watch Band - Gray",
    "color": "Gray",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.53577600%201748223653.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10348",
    "source_id": "10348",
    "original_name": "38/40 Magnetic Apple Watch Bands Gray",
    "original_sku": "10348494",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-GRAY",
    "group_slug": "watch-band-magnetic-gray",
    "group_name": "Magnetic Apple Watch Band - Gray",
    "color": "Gray",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.53577600%201748223653.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10345",
    "source_id": "10345",
    "original_name": "42/44 Magnetic Apple Watch Bands Blue& Pink",
    "original_sku": "10345491",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-BLUE-PINK",
    "group_slug": "watch-band-magnetic-blue-pink",
    "group_name": "Magnetic Apple Watch Band - Blue & Pink",
    "color": "Blue & Pink",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.30319000%201748223306.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-10344",
    "source_id": "10344",
    "original_name": "38/40 Magnetic Apple Watch Bands Blue& Pink",
    "original_sku": "10344490",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 6,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-BLUE-PINK",
    "group_slug": "watch-band-magnetic-blue-pink",
    "group_name": "Magnetic Apple Watch Band - Blue & Pink",
    "color": "Blue & Pink",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/0.30319000%201748223306.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8934",
    "source_id": "8934",
    "original_name": "42/44 Ocean Band Black",
    "original_sku": "8934431",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 0,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-BLACK",
    "group_slug": "watch-band-ocean-black",
    "group_name": "Ocean Band - Black",
    "color": "Black",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1704958198.jpg",
    "reference_sku": "TM8-WB-8933",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8929",
    "source_id": "8929",
    "original_name": "38/40 Ocean Band White",
    "original_sku": "8929426",
    "source_category": "9.1 Watch Band > Ocean Band",
    "source_cost": 0,
    "source_retail": 40,
    "group_code": "TM8-GRP-WB-OCEAN-WHITE",
    "group_slug": "watch-band-ocean-white",
    "group_name": "Ocean Band - White",
    "color": "White",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1704958109.jpg",
    "reference_sku": "TM8-WB-8930",
    "reference_price": 40,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8899",
    "source_id": "8899",
    "original_name": "42/44 Fabric Apple Watch Band Yellow Green",
    "original_sku": "8899836",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 0,
    "source_retail": 30,
    "group_code": "TM8-GRP-WB-FABRIC-YELLOW-GREEN",
    "group_slug": "watch-band-fabric-yellow-green",
    "group_name": "Fabric Apple Watch Band - Yellow Green",
    "color": "Yellow Green",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834825.jpg",
    "reference_sku": "TM8-WB-10341",
    "reference_price": 30,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8897",
    "source_id": "8897",
    "original_name": "42/44 Sport Apple Watch Band Black Green",
    "original_sku": "8897413",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLACK-GREEN",
    "group_slug": "watch-band-sport-black-green",
    "group_name": "Sport Apple Watch Band - Black Green",
    "color": "Black Green",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834132.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8896",
    "source_id": "8896",
    "original_name": "38/40 Sport Apple Watch Band Black Green",
    "original_sku": "8896412",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLACK-GREEN",
    "group_slug": "watch-band-sport-black-green",
    "group_name": "Sport Apple Watch Band - Black Green",
    "color": "Black Green",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834132.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8895",
    "source_id": "8895",
    "original_name": "42/44 Sport Apple Watch Band Blue",
    "original_sku": "8895411",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLUE",
    "group_slug": "watch-band-sport-blue",
    "group_name": "Sport Apple Watch Band - Blue",
    "color": "Blue",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834070.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8894",
    "source_id": "8894",
    "original_name": "38/40 Sport Apple Watch Band Blue",
    "original_sku": "8894410",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLUE",
    "group_slug": "watch-band-sport-blue",
    "group_name": "Sport Apple Watch Band - Blue",
    "color": "Blue",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834070.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8893",
    "source_id": "8893",
    "original_name": "42/44 Sport Apple Watch Band Black Red",
    "original_sku": "8893409",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLACK-RED",
    "group_slug": "watch-band-sport-black-red",
    "group_name": "Sport Apple Watch Band - Black Red",
    "color": "Black Red",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703832515.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8892",
    "source_id": "8892",
    "original_name": "38/40 Sport Apple Watch Band Black Red",
    "original_sku": "8892408",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-BLACK-RED",
    "group_slug": "watch-band-sport-black-red",
    "group_name": "Sport Apple Watch Band - Black Red",
    "color": "Black Red",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703832515.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8891",
    "source_id": "8891",
    "original_name": "38/40 Sport Apple Watch Band Navy Pink",
    "original_sku": "8891407",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-NAVY-PINK",
    "group_slug": "watch-band-sport-navy-pink",
    "group_name": "Sport Apple Watch Band - Navy Pink",
    "color": "Navy Pink",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703831194.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8890",
    "source_id": "8890",
    "original_name": "42/44 Sport Apple Watch Band Navy Pink",
    "original_sku": "8890406",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-NAVY-PINK",
    "group_slug": "watch-band-sport-navy-pink",
    "group_name": "Sport Apple Watch Band - Navy Pink",
    "color": "Navy Pink",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703831194.jpg",
    "reference_sku": "TM8-WB-6122",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8889",
    "source_id": "8889",
    "original_name": "38/40 Silicone Apple Watch Band Rainbow",
    "original_sku": "8889405",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SILICONE-RAINBOW",
    "group_slug": "watch-band-silicone-rainbow",
    "group_name": "Silicone Apple Watch Band - Rainbow",
    "color": "Rainbow",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703830468.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8888",
    "source_id": "8888",
    "original_name": "42/44 Silicone Apple Watch Band Rainbow",
    "original_sku": "8888404",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SILICONE-RAINBOW",
    "group_slug": "watch-band-silicone-rainbow",
    "group_name": "Silicone Apple Watch Band - Rainbow",
    "color": "Rainbow",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703830468.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8479",
    "source_id": "8479",
    "original_name": "38/40 Magnetic Apple Watch Bands Purple Pink",
    "original_sku": "8479187",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 0,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-PURPLE-PINK",
    "group_slug": "watch-band-magnetic-purple-pink",
    "group_name": "Magnetic Apple Watch Band - Purple Pink",
    "color": "Purple Pink",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1691120917.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8284",
    "source_id": "8284",
    "original_name": "42/44 Fabric Apple Watch Band Unity",
    "original_sku": "8284149",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 3,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-FABRIC-UNITY",
    "group_slug": "watch-band-fabric-unity",
    "group_name": "Fabric Apple Watch Band - Unity",
    "color": "Unity",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/168532351142458003.jpg",
    "reference_sku": "TM8-WB-8279",
    "reference_price": 35,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8283",
    "source_id": "8283",
    "original_name": "38/40 Fabric Apple Watch Band Unity",
    "original_sku": "8283148",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 3,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-FABRIC-UNITY",
    "group_slug": "watch-band-fabric-unity",
    "group_name": "Fabric Apple Watch Band - Unity",
    "color": "Unity",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/168532351142458003.jpg",
    "reference_sku": "TM8-WB-8279",
    "reference_price": 35,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8282",
    "source_id": "8282",
    "original_name": "42/44 Fabric Apple Watch Band Navy Blue",
    "original_sku": "8282147",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 2,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-FABRIC-NAVY-BLUE",
    "group_slug": "watch-band-fabric-navy-blue",
    "group_name": "Fabric Apple Watch Band - Navy Blue",
    "color": "Navy Blue",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/168532355242458001.jpg",
    "reference_sku": "TM8-WB-10341",
    "reference_price": 30,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-8281",
    "source_id": "8281",
    "original_name": "38/40 Fabric Apple Watch Band Navy Blue",
    "original_sku": "8281146",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 2,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-FABRIC-NAVY-BLUE",
    "group_slug": "watch-band-fabric-navy-blue",
    "group_name": "Fabric Apple Watch Band - Navy Blue",
    "color": "Navy Blue",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/168532355242458001.jpg",
    "reference_sku": "TM8-WB-10341",
    "reference_price": 30,
    "reference_cost": 2,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-7821",
    "source_id": "7821",
    "original_name": "42/44 Magnetic Apple Watch Bands Rainbow",
    "original_sku": "7821495",
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": 0,
    "source_retail": 45,
    "group_code": "TM8-GRP-WB-MAGNETIC-RAINBOW",
    "group_slug": "watch-band-magnetic-rainbow",
    "group_name": "Magnetic Apple Watch Band - Rainbow",
    "color": "Rainbow",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1675561755.jpg",
    "reference_sku": "TM8-WB-7820",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-7762",
    "source_id": "7762",
    "original_name": "42/44 Silicone Apple Watch Band Yellow",
    "original_sku": "776229",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 0,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SILICONE-YELLOW",
    "group_slug": "watch-band-silicone-yellow",
    "group_name": "Silicone Apple Watch Band - Yellow",
    "color": "Yellow",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1674961755.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-6137",
    "source_id": "6137",
    "original_name": "42/44 Silicone Apple Watch Band White/Gray",
    "original_sku": "00000000038",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3.85,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SILICONE-WHITE-GRAY",
    "group_slug": "watch-band-silicone-white-gray",
    "group_name": "Silicone Apple Watch Band - White/Gray",
    "color": "White/Gray",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/164197439042455847.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-6136",
    "source_id": "6136",
    "original_name": "38/40 Silicone Apple Watch Band White/Gray",
    "original_sku": "00000000037",
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": 3.85,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SILICONE-WHITE-GRAY",
    "group_slug": "watch-band-silicone-white-gray",
    "group_name": "Silicone Apple Watch Band - White/Gray",
    "color": "White/Gray",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/164197439042455847.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-6131",
    "source_id": "6131",
    "original_name": "42/44 Sport Apple Watch Band Mint",
    "original_sku": "00000000032",
    "source_category": "9.1 Watch Band > Sport Band",
    "source_cost": 3.85,
    "source_retail": 35,
    "group_code": "TM8-GRP-WB-SPORT-MINT",
    "group_slug": "watch-band-sport-mint",
    "group_name": "Sport Apple Watch Band - Mint",
    "color": "Mint",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/164197406842455840.jpg",
    "reference_sku": "TM8-WB-6130",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-6118",
    "source_id": "6118",
    "original_name": "38/40 Fabric Apple Watch Band White",
    "original_sku": "00000000019",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 4.94,
    "source_retail": 30,
    "group_code": "TM8-GRP-WB-FABRIC-WHITE",
    "group_slug": "watch-band-fabric-white",
    "group_name": "Fabric Apple Watch Band - White",
    "color": "White",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/164197178742455829.jpg",
    "reference_sku": "TM8-WB-6119",
    "reference_price": 30,
    "reference_cost": 4.95,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-6113",
    "source_id": "6113",
    "original_name": "42/44 Fabric Apple Watch Band Rainbow",
    "original_sku": "00000000014",
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": 4.95,
    "source_retail": 30,
    "group_code": "TM8-GRP-WB-FABRIC-RAINBOW",
    "group_slug": "watch-band-fabric-rainbow",
    "group_name": "Fabric Apple Watch Band - Rainbow",
    "color": "Rainbow",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1641971152.jpg",
    "reference_sku": "TM8-WB-6112",
    "reference_price": 30,
    "reference_cost": 4.95,
    "synthetic": false
  },
  {
    "sku": "TM8-WB-FABRIC-YELLOW-GREEN-3840",
    "source_id": null,
    "original_name": null,
    "original_sku": null,
    "source_category": "9.1 Watch Band > Fabric Band",
    "source_cost": null,
    "source_retail": null,
    "group_code": "TM8-GRP-WB-FABRIC-YELLOW-GREEN",
    "group_slug": "watch-band-fabric-yellow-green",
    "group_name": "Fabric Apple Watch Band - Yellow Green",
    "color": "Yellow Green",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1703834825.jpg",
    "reference_sku": "TM8-WB-10341",
    "reference_price": 30,
    "reference_cost": 2,
    "synthetic": true,
    "counterpart_source_id": "8899"
  },
  {
    "sku": "TM8-WB-MAGNETIC-PURPLE-PINK-4244",
    "source_id": null,
    "original_name": null,
    "original_sku": null,
    "source_category": "9.1 Watch Band > Magnetic Band",
    "source_cost": null,
    "source_retail": null,
    "group_code": "TM8-GRP-WB-MAGNETIC-PURPLE-PINK",
    "group_slug": "watch-band-magnetic-purple-pink",
    "group_name": "Magnetic Apple Watch Band - Purple Pink",
    "color": "Purple Pink",
    "size": "42/44mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1691120917.jpg",
    "reference_sku": "TM8-WB-6100",
    "reference_price": 45,
    "reference_cost": 6.05,
    "synthetic": true,
    "counterpart_source_id": "8479"
  },
  {
    "sku": "TM8-WB-SILICONE-YELLOW-3840",
    "source_id": null,
    "original_name": null,
    "original_sku": null,
    "source_category": "9.1 Watch Band > Silicone",
    "source_cost": null,
    "source_retail": null,
    "group_code": "TM8-GRP-WB-SILICONE-YELLOW",
    "group_slug": "watch-band-silicone-yellow",
    "group_name": "Silicone Apple Watch Band - Yellow",
    "color": "Yellow",
    "size": "38/40mm",
    "image": "https://dghyt15qon7us.cloudfront.net/images/productTheme/Inventory/small/1674961755.jpg",
    "reference_sku": "TM8-WB-6134",
    "reference_price": 35,
    "reference_cost": 3.85,
    "synthetic": true,
    "counterpart_source_id": "7762"
  }
]
$bands$::jsonb) as x(
  sku text, source_id text, original_name text, original_sku text,
  source_category text, source_cost numeric, source_retail numeric,
  group_code text, group_slug text, group_name text, color text, size text,
  image text, reference_sku text, reference_price numeric, reference_cost numeric,
  synthetic boolean, counterpart_source_id text
);

create temporary table band_products_before on commit drop as
select p.id, to_jsonb(p) as snapshot from public.products p
join public.product_groups g on g.id = p.product_group_id
where g.product_family = 'watch_band';
create temporary table band_inventory_before on commit drop as
select i.id, to_jsonb(i) as snapshot from public.product_store_inventory i
join band_products_before b on b.id = i.product_id;

do $$
begin
  if (select count(*) from band_completion_input) <> 51
     or (select count(distinct sku) from band_completion_input) <> 51 then
    raise exception 'Expected 51 unique additions';
  end if;
  if exists (
    select 1 from band_completion_input i
    left join public.products p on p.sku = i.reference_sku
    left join public.product_groups g on g.id = p.product_group_id
    where p.id is null or g.product_family <> 'watch_band'
      or p.retail_price <> i.reference_price or p.cost_price <> i.reference_cost
      or p.retail_price <= 0
  ) then raise exception 'Live POS pricing reference changed; review before importing'; end if;
  if exists (select 1 from band_completion_input i join public.products p on p.sku = i.sku)
  then raise exception 'An addition already exists; reconcile instead of overwriting'; end if;
  if exists (
    select 1 from band_completion_input i join public.product_groups g on g.code = i.group_code
    where g.product_family <> 'watch_band'
  ) then raise exception 'Group code belongs to another product family'; end if;
end $$;

insert into public.product_groups (
  code, slug, name, category_id, product_family, main_image_url, status,
  is_pos_visible, is_visible, pos_category_id, pos_sort_order
)
select distinct on (i.group_code)
  i.group_code, i.group_slug, i.group_name, p.category_id, 'watch_band',
  i.image, 'active', true, false, p.pos_category_id, g.pos_sort_order + 1
from band_completion_input i
join public.products p on p.sku = i.reference_sku
join public.product_groups g on g.id = p.product_group_id
where not exists (select 1 from public.product_groups existing where existing.code = i.group_code)
order by i.group_code, i.size;

insert into public.products (
  sku, slug, name, brand, model, category_id, pos_category_id,
  short_description, condition_label, compatibility, cost_price, retail_price,
  image_url, stock_quantity, is_visible, is_pos_visible, upc, product_group_id,
  variant_name, variant_color, source_system, source_external_id,
  source_category_path, import_status, source_metadata
)
select
  i.sku, lower(i.sku), i.group_name || ' - ' || i.size, p.brand, i.group_name,
  g.category_id, g.pos_category_id,
  i.group_name || '. Size: ' || i.size || '.', p.condition_label,
  'Apple Watch cases compatible with ' || replace(i.size, 'mm', ' mm'),
  case when i.source_cost > 0 then i.source_cost else p.cost_price end,
  p.retail_price, i.image, 0, false, true, i.original_sku, g.id,
  i.size, i.color, 'repairdesk_watch_bands', i.source_id,
  i.source_category, 'active',
  jsonb_build_object(
    'original_name', i.original_name, 'original_sku', i.original_sku,
    'source_retail_price', i.source_retail, 'source_cost_price', i.source_cost,
    'watch_band_size', i.size, 'watch_band_color', i.color,
    'watch_band_family', split_part(i.source_category, ' > ', 2),
    'inventory_assignment', 'none', 'proposed_stock', 0,
    'image_status', 'available', 'image_source', 'repairdesk_same_style_color',
    'cost_status', case when i.source_cost > 0 then 'valid' else 'inferred_same_series' end,
    'cost_source', case when i.source_cost > 0 then 'repairdesk_source' else 'new_pos_reference' end,
    'price_source', 'new_pos_reference', 'price_reference_sku', i.reference_sku,
    'user_requested_size_counterpart', i.synthetic,
    'counterpart_source_id', i.counterpart_source_id,
    'import_batch', 'watch_band_completion_20260911'
  )
from band_completion_input i
join public.products p on p.sku = i.reference_sku
join public.product_groups g on g.code = i.group_code;

insert into public.product_store_inventory (product_id, store_id, quantity)
select p.id, s.id, 0 from band_completion_input i
join public.products p on p.sku = i.sku
cross join public.stores s
on conflict (product_id, store_id) do nothing;

do $$
begin
  if exists (
    select 1 from band_products_before b left join public.products p on p.id = b.id
    where to_jsonb(p) is distinct from b.snapshot
  ) or exists (
    select 1 from band_inventory_before b left join public.product_store_inventory i on i.id = b.id
    where to_jsonb(i) is distinct from b.snapshot
  ) then raise exception 'Existing watch-band products or stock changed'; end if;
  if (
    select count(*) from public.products p join band_completion_input i on i.sku = p.sku
    where p.stock_quantity = 0 and p.is_pos_visible and not p.is_visible
      and p.import_status = 'active' and p.retail_price = i.reference_price
      and p.cost_price > 0 and coalesce(p.image_url, '') <> ''
  ) <> 51 then raise exception 'Addition validation failed'; end if;
  if exists (
    select 1 from band_completion_input i join public.products p on p.sku = i.sku
    cross join public.stores s
    left join public.product_store_inventory inv on inv.product_id = p.id and inv.store_id = s.id
    where inv.id is null or inv.quantity <> 0
  ) then raise exception 'New variants must have independent zero stock in every location'; end if;
  if (select count(*) from public.product_groups where product_family = 'watch_band') <> 56
    or (select count(*) from public.products p join public.product_groups g on g.id = p.product_group_id
        where g.product_family = 'watch_band') <> 112
    or exists (
      select g.id from public.product_groups g
      left join public.products p on p.product_group_id = g.id and p.is_pos_visible and p.import_status = 'active'
      where g.product_family = 'watch_band'
      group by g.id having count(p.id) <> 2
        or count(*) filter (where p.variant_name = '38/40mm') <> 1
        or count(*) filter (where p.variant_name = '42/44mm') <> 1
    ) then raise exception 'Expected 56 groups with exactly two visible sizes each'; end if;
end $$;

commit;
