-- Second-hand devices on the public website.
--
-- These are deliberately not `products`. A product is a repeatable SKU with a
-- quantity per store; a second-hand device is one physical thing, its stock is
-- always one, and when it sells it is gone rather than reordered. Putting them
-- in `products` would mean every stock, grouping and variant rule had to grow a
-- special case.
--
-- The POS project owns the device. This project owns the listing: what the
-- public sees, its images, and whether it is visible. `device_code` is the link,
-- and `source_version` makes a late-arriving update lose to a newer one instead
-- of overwriting it.
--
-- Nothing here may carry an IMEI, a serial number, or anything about the
-- seller. The check constraint below is the last line of that rule.

begin;

create table if not exists public.used_device_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  device_category text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now())
);

insert into public.used_device_categories (slug, name, device_category, sort_order) values
  ('used-phones', 'Used Phones', 'Phone', 10),
  ('used-tablets', 'Used Tablets', 'Tablet', 20),
  ('used-laptops', 'Used Laptops', 'Laptop', 30),
  ('used-watches', 'Used Watches', 'Watch', 40),
  ('used-game-consoles', 'Used Game Consoles', 'Game Console', 50),
  ('used-other', 'Other Used Devices', 'Other', 60)
on conflict (device_category) do nothing;

create table if not exists public.used_device_listings (
  id bigint generated by default as identity primary key,
  device_code text not null unique,
  store_code text not null default '',
  category_id bigint not null references public.used_device_categories(id) on delete restrict,
  slug text not null unique,
  title text not null,
  brand text not null,
  model text not null,
  storage text not null default '',
  color text not null default '',
  condition_grade text not null,
  condition_summary text not null default '',
  battery_health integer check (battery_health is null or battery_health between 0 and 100),
  price numeric(12,2) not null check (price > 0),
  description text not null default '',
  highlights jsonb not null default '[]'::jsonb,
  images jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published', 'withdrawn', 'sold')),
  source_version bigint not null default 0,
  published_at timestamptz,
  withdrawn_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  -- A published listing has to have something to show.
  constraint used_device_listings_published_needs_image
    check (status <> 'published' or jsonb_array_length(images) > 0),
  -- No device identifier ever reaches a public page. Fifteen digits in a row is
  -- an IMEI however it got there.
  constraint used_device_listings_no_identifier
    check (
      (title || ' ' || description || ' ' || condition_summary) !~ '[0-9]{15}'
    )
);

create index if not exists used_device_listings_public_idx
  on public.used_device_listings (category_id, published_at desc)
  where status = 'published';

create index if not exists used_device_listings_brand_idx
  on public.used_device_listings (lower(brand))
  where status = 'published';

alter table public.used_device_categories enable row level security;
alter table public.used_device_listings enable row level security;

revoke all on public.used_device_categories from public, anon, authenticated;
revoke all on public.used_device_listings from public, anon, authenticated;
grant all on public.used_device_categories to service_role;
grant all on public.used_device_listings to service_role;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('used-device-listing-images', 'used-device-listing-images', true, 3145728, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

-- The storefront reads through these two. They return published rows only and
-- never expose the device code's identifiers or the store's internal ids.
create or replace function public.get_used_device_listings(
  category_slug text default '',
  brand_filter text default '',
  result_limit integer default 60,
  result_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  category_value text := trim(coalesce(category_slug, ''));
  brand_value text := trim(coalesce(brand_filter, ''));
  safe_limit integer := least(greatest(coalesce(result_limit, 60), 1), 200);
  safe_offset integer := greatest(coalesce(result_offset, 0), 0);
  rows_payload jsonb;
  total_count integer;
begin
  select count(*) into total_count
  from public.used_device_listings listing
  join public.used_device_categories category on category.id = listing.category_id
  where listing.status = 'published'
    and (category_value = '' or category.slug = category_value)
    and (brand_value = '' or lower(listing.brand) = lower(brand_value));

  select coalesce(jsonb_agg(to_jsonb(row_data) order by row_data.published_at desc), '[]'::jsonb)
  into rows_payload
  from (
    select
      listing.slug, listing.title, listing.brand, listing.model, listing.storage,
      listing.color, listing.condition_grade, listing.condition_summary,
      listing.battery_health, listing.price, listing.description,
      listing.highlights, listing.images, listing.published_at,
      category.slug as category_slug, category.name as category_name
    from public.used_device_listings listing
    join public.used_device_categories category on category.id = listing.category_id
    where listing.status = 'published'
      and (category_value = '' or category.slug = category_value)
      and (brand_value = '' or lower(listing.brand) = lower(brand_value))
    order by listing.published_at desc
    limit safe_limit offset safe_offset
  ) row_data;

  return jsonb_build_object(
    'ok', true,
    'total', total_count,
    'limit', safe_limit,
    'offset', safe_offset,
    'categories', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'slug', category.slug,
        'name', category.name,
        'count', (
          select count(*) from public.used_device_listings counted
          where counted.category_id = category.id and counted.status = 'published'
        )
      ) order by category.sort_order), '[]'::jsonb)
      from public.used_device_categories category
      where category.active
    ),
    'listings', rows_payload
  );
end;
$$;

create or replace function public.get_used_device_listing(listing_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  select to_jsonb(row_data) into result
  from (
    select
      listing.slug, listing.title, listing.brand, listing.model, listing.storage,
      listing.color, listing.condition_grade, listing.condition_summary,
      listing.battery_health, listing.price, listing.description,
      listing.highlights, listing.images, listing.published_at,
      category.slug as category_slug, category.name as category_name
    from public.used_device_listings listing
    join public.used_device_categories category on category.id = listing.category_id
    where listing.status = 'published'
      and listing.slug = trim(coalesce(listing_slug, ''))
  ) row_data;

  if result is null then
    return jsonb_build_object('ok', false, 'message', 'Listing not found');
  end if;
  return jsonb_build_object('ok', true, 'listing', result);
end;
$$;

-- Written only by the publish pipeline, which holds the service key.
create or replace function public.upsert_used_device_listing(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  device_code_value text := trim(coalesce(payload->>'device_code', ''));
  version_value bigint := coalesce(nullif(payload->>'source_version', '')::bigint, 0);
  status_value text := coalesce(nullif(trim(payload->>'status'), ''), 'published');
  category_row public.used_device_categories%rowtype;
  existing public.used_device_listings%rowtype;
  listing_row public.used_device_listings%rowtype;
  slug_value text;
begin
  if device_code_value = '' then raise exception 'device_code is required'; end if;
  if status_value not in ('draft', 'published', 'withdrawn', 'sold') then raise exception 'Invalid listing status'; end if;

  select * into category_row from public.used_device_categories
  where device_category = trim(coalesce(payload->>'device_category', '')) and active;
  if not found then raise exception 'No website category for this device type'; end if;

  select * into existing from public.used_device_listings where device_code = device_code_value for update;

  -- A slow retry must never undo a newer state.
  if found and existing.source_version > version_value then
    return jsonb_build_object('ok', true, 'skipped', true, 'reason', 'A newer version is already published',
      'slug', existing.slug, 'status', existing.status);
  end if;

  slug_value := coalesce(nullif(trim(payload->>'slug'), ''), existing.slug,
    lower(regexp_replace(
      trim(coalesce(payload->>'title', device_code_value)) || '-' || right(device_code_value, 6),
      '[^a-zA-Z0-9]+', '-', 'g')));
  slug_value := trim(both '-' from slug_value);

  insert into public.used_device_listings (
    device_code, store_code, category_id, slug, title, brand, model, storage, color,
    condition_grade, condition_summary, battery_health, price, description,
    highlights, images, status, source_version, published_at, withdrawn_at, updated_at
  ) values (
    device_code_value,
    trim(coalesce(payload->>'store_code', '')),
    category_row.id,
    slug_value,
    trim(coalesce(payload->>'title', '')),
    trim(coalesce(payload->>'brand', '')),
    trim(coalesce(payload->>'model', '')),
    trim(coalesce(payload->>'storage', '')),
    trim(coalesce(payload->>'color', '')),
    trim(coalesce(payload->>'condition_grade', '')),
    trim(coalesce(payload->>'condition_summary', '')),
    nullif(payload->>'battery_health', '')::integer,
    round(coalesce(nullif(payload->>'price', '')::numeric, 0), 2),
    coalesce(payload->>'description', ''),
    case when jsonb_typeof(payload->'highlights') = 'array' then payload->'highlights' else '[]'::jsonb end,
    case when jsonb_typeof(payload->'images') = 'array' then payload->'images' else '[]'::jsonb end,
    status_value,
    version_value,
    case when status_value = 'published' then timezone('utc'::text, now()) else null end,
    case when status_value in ('withdrawn', 'sold') then timezone('utc'::text, now()) else null end,
    timezone('utc'::text, now())
  )
  on conflict (device_code) do update set
    store_code = excluded.store_code,
    category_id = excluded.category_id,
    title = excluded.title,
    brand = excluded.brand,
    model = excluded.model,
    storage = excluded.storage,
    color = excluded.color,
    condition_grade = excluded.condition_grade,
    condition_summary = excluded.condition_summary,
    battery_health = excluded.battery_health,
    price = excluded.price,
    description = excluded.description,
    highlights = excluded.highlights,
    images = excluded.images,
    status = excluded.status,
    source_version = excluded.source_version,
    -- The first publish date is the listing's age and is kept.
    published_at = case
      when excluded.status = 'published' then coalesce(public.used_device_listings.published_at, excluded.published_at)
      else public.used_device_listings.published_at
    end,
    withdrawn_at = excluded.withdrawn_at,
    updated_at = timezone('utc'::text, now())
  returning * into listing_row;

  return jsonb_build_object('ok', true, 'slug', listing_row.slug, 'status', listing_row.status,
    'source_version', listing_row.source_version);
end;
$$;

create or replace function public.withdraw_used_device_listing(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  device_code_value text := trim(coalesce(payload->>'device_code', ''));
  version_value bigint := coalesce(nullif(payload->>'source_version', '')::bigint, 0);
  status_value text := coalesce(nullif(trim(payload->>'status'), ''), 'withdrawn');
  listing_row public.used_device_listings%rowtype;
begin
  if device_code_value = '' then raise exception 'device_code is required'; end if;
  if status_value not in ('withdrawn', 'sold') then raise exception 'A listing can only be withdrawn or marked sold'; end if;

  update public.used_device_listings
  set status = status_value,
      source_version = greatest(source_version, version_value),
      withdrawn_at = timezone('utc'::text, now()),
      updated_at = timezone('utc'::text, now())
  where device_code = device_code_value
    and source_version <= version_value
  returning * into listing_row;

  if not found then
    return jsonb_build_object('ok', true, 'skipped', true, 'reason', 'No listing to withdraw, or a newer version already applied');
  end if;
  return jsonb_build_object('ok', true, 'slug', listing_row.slug, 'status', listing_row.status);
end;
$$;

revoke all on function public.get_used_device_listings(text, text, integer, integer) from public;
revoke all on function public.get_used_device_listing(text) from public;
revoke all on function public.upsert_used_device_listing(jsonb) from public, anon, authenticated;
revoke all on function public.withdraw_used_device_listing(jsonb) from public, anon, authenticated;

-- The storefront reads with the publishable key; only the pipeline writes.
grant execute on function public.get_used_device_listings(text, text, integer, integer) to anon, authenticated, service_role;
grant execute on function public.get_used_device_listing(text) to anon, authenticated, service_role;
grant execute on function public.upsert_used_device_listing(jsonb) to service_role;
grant execute on function public.withdraw_used_device_listing(jsonb) to service_role;

comment on table public.used_device_listings is
  'One public listing per second-hand device. Owned by the publish pipeline; device_code links back to pos_used_devices in the staff/POS project.';

commit;
