create sequence if not exists public.stock_transfer_number_seq;

create table if not exists public.stock_transfers (
  id bigint generated by default as identity primary key,
  transfer_number text not null unique default (
    'TRF-' || to_char(timezone('Australia/Brisbane', now()), 'YYYYMMDD') || '-'
    || lpad(nextval('public.stock_transfer_number_seq')::text, 6, '0')
  ),
  client_request_key uuid not null unique,
  request_fingerprint text not null,
  source_store_id bigint not null references public.stores(id) on delete restrict,
  destination_store_id bigint not null references public.stores(id) on delete restrict,
  status text not null default 'in_transit'
    check (status in ('in_transit', 'partially_received', 'completed', 'completed_with_issues', 'returned')),
  dispatched_by text not null,
  dispatch_note text,
  dispatched_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  check (source_store_id <> destination_store_id)
);

create table if not exists public.stock_transfer_items (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.stock_transfers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  sku_snapshot text not null,
  name_snapshot text not null,
  barcode_snapshot text,
  variant_snapshot text,
  dispatched_quantity integer not null check (dispatched_quantity > 0),
  received_good_quantity integer not null default 0 check (received_good_quantity >= 0),
  received_damaged_quantity integer not null default 0 check (received_damaged_quantity >= 0),
  missing_quantity integer not null default 0 check (missing_quantity >= 0),
  returned_quantity integer not null default 0 check (returned_quantity >= 0),
  source_quantity_before integer not null check (source_quantity_before >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (transfer_id, product_id),
  check (
    received_good_quantity + received_damaged_quantity + missing_quantity + returned_quantity
    <= dispatched_quantity
  )
);

create table if not exists public.stock_transfer_receipts (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.stock_transfers(id) on delete cascade,
  receipt_key uuid not null unique,
  request_fingerprint text not null,
  receipt_type text not null check (receipt_type in ('receive', 'return')),
  received_by text not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_transfer_receipt_items (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.stock_transfer_receipts(id) on delete cascade,
  transfer_item_id bigint not null references public.stock_transfer_items(id) on delete restrict,
  good_quantity integer not null default 0 check (good_quantity >= 0),
  damaged_quantity integer not null default 0 check (damaged_quantity >= 0),
  missing_quantity integer not null default 0 check (missing_quantity >= 0),
  returned_quantity integer not null default 0 check (returned_quantity >= 0),
  created_at timestamptz not null default now(),
  unique (receipt_id, transfer_item_id),
  check (good_quantity + damaged_quantity + missing_quantity + returned_quantity > 0)
);

create table if not exists public.stock_transfer_photos (
  id uuid primary key default gen_random_uuid(),
  transfer_id bigint not null references public.stock_transfers(id) on delete cascade,
  receipt_key uuid not null,
  receipt_id bigint references public.stock_transfer_receipts(id) on delete set null,
  category text not null default 'receipt' check (category in ('receipt', 'issue', 'return')),
  storage_path text not null unique,
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  file_size integer not null check (file_size > 0 and file_size <= 5242880),
  uploaded_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  movement_key text not null unique,
  movement_type text not null check (movement_type in ('transfer_out', 'transfer_in', 'transfer_return')),
  product_id bigint not null references public.products(id) on delete restrict,
  store_id bigint not null references public.stores(id) on delete restrict,
  quantity_delta integer not null check (quantity_delta <> 0),
  quantity_before integer not null check (quantity_before >= 0),
  quantity_after integer not null check (quantity_after >= 0),
  transfer_id bigint not null references public.stock_transfers(id) on delete restrict,
  transfer_item_id bigint not null references public.stock_transfer_items(id) on delete restrict,
  receipt_id bigint references public.stock_transfer_receipts(id) on delete restrict,
  actor_staff_name text not null,
  created_at timestamptz not null default now(),
  check (quantity_after = quantity_before + quantity_delta)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'product_store_inventory_quantity_nonnegative'
      and conrelid = 'public.product_store_inventory'::regclass
  ) then
    alter table public.product_store_inventory
      add constraint product_store_inventory_quantity_nonnegative check (quantity >= 0);
  end if;
end
$$;

create index if not exists stock_transfers_status_dispatched_idx
  on public.stock_transfers (status, dispatched_at desc);
create index if not exists stock_transfers_source_status_idx
  on public.stock_transfers (source_store_id, status, dispatched_at desc);
create index if not exists stock_transfers_destination_status_idx
  on public.stock_transfers (destination_store_id, status, dispatched_at desc);
create index if not exists stock_transfer_items_transfer_idx
  on public.stock_transfer_items (transfer_id, id);
create index if not exists stock_transfer_items_product_idx
  on public.stock_transfer_items (product_id, created_at desc);
create index if not exists stock_transfer_receipts_transfer_idx
  on public.stock_transfer_receipts (transfer_id, created_at desc);
create index if not exists stock_transfer_receipt_items_transfer_item_idx
  on public.stock_transfer_receipt_items (transfer_item_id, created_at desc);
create index if not exists stock_transfer_photos_receipt_idx
  on public.stock_transfer_photos (transfer_id, receipt_key, created_at);
create index if not exists stock_transfer_photos_pending_idx
  on public.stock_transfer_photos (receipt_key, created_at)
  where receipt_id is null;
create index if not exists inventory_movements_product_store_idx
  on public.inventory_movements (product_id, store_id, created_at desc);
create index if not exists inventory_movements_transfer_idx
  on public.inventory_movements (transfer_id, created_at);
create index if not exists inventory_movements_receipt_idx
  on public.inventory_movements (receipt_id)
  where receipt_id is not null;
create index if not exists inventory_movements_store_idx
  on public.inventory_movements (store_id, created_at desc);
create index if not exists inventory_movements_transfer_item_idx
  on public.inventory_movements (transfer_item_id, created_at desc);
create index if not exists stock_transfer_photos_receipt_id_idx
  on public.stock_transfer_photos (receipt_id)
  where receipt_id is not null;

alter table public.stock_transfers enable row level security;
alter table public.stock_transfer_items enable row level security;
alter table public.stock_transfer_receipts enable row level security;
alter table public.stock_transfer_receipt_items enable row level security;
alter table public.stock_transfer_photos enable row level security;
alter table public.inventory_movements enable row level security;

revoke all on table public.stock_transfers from public, anon, authenticated;
revoke all on table public.stock_transfer_items from public, anon, authenticated;
revoke all on table public.stock_transfer_receipts from public, anon, authenticated;
revoke all on table public.stock_transfer_receipt_items from public, anon, authenticated;
revoke all on table public.stock_transfer_photos from public, anon, authenticated;
revoke all on table public.inventory_movements from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'stock-transfer-receipts',
  'stock-transfer-receipts',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.refresh_product_stock_totals(target_product_ids bigint[])
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform product.id
  from public.products product
  where product.id = any(coalesce(target_product_ids, array[]::bigint[]))
  order by product.id
  for update;

  update public.products product
  set
    stock_quantity = (
      select coalesce(sum(inventory.quantity), 0)::integer
      from public.product_store_inventory inventory
      where inventory.product_id = product.id
    ),
    updated_at = now()
  where product.id = any(coalesce(target_product_ids, array[]::bigint[]));
end;
$$;

create or replace function public.pos_stock_transfer_payload(target_transfer_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'id', transfer.id,
    'transfer_number', transfer.transfer_number,
    'status', transfer.status,
    'source_store', jsonb_build_object(
      'id', source_store.id,
      'slug', source_store.slug,
      'name', source_store.name
    ),
    'destination_store', jsonb_build_object(
      'id', destination_store.id,
      'slug', destination_store.slug,
      'name', destination_store.name
    ),
    'dispatched_by', transfer.dispatched_by,
    'dispatch_note', transfer.dispatch_note,
    'dispatched_at', transfer.dispatched_at,
    'completed_at', transfer.completed_at,
    'updated_at', transfer.updated_at,
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', item.id,
          'product_id', item.product_id,
          'sku', item.sku_snapshot,
          'name', item.name_snapshot,
          'barcode', item.barcode_snapshot,
          'variant', item.variant_snapshot,
          'dispatched_quantity', item.dispatched_quantity,
          'received_good_quantity', item.received_good_quantity,
          'received_damaged_quantity', item.received_damaged_quantity,
          'missing_quantity', item.missing_quantity,
          'returned_quantity', item.returned_quantity,
          'remaining_quantity', greatest(
            item.dispatched_quantity - item.received_good_quantity
              - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity,
            0
          ),
          'source_quantity_before', item.source_quantity_before,
          'image_url', product.image_url
        )
        order by item.id
      )
      from public.stock_transfer_items item
      join public.products product on product.id = item.product_id
      where item.transfer_id = transfer.id
    ), '[]'::jsonb),
    'receipts', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', receipt.id,
          'receipt_key', receipt.receipt_key,
          'receipt_type', receipt.receipt_type,
          'received_by', receipt.received_by,
          'note', receipt.note,
          'created_at', receipt.created_at,
          'items', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'transfer_item_id', receipt_item.transfer_item_id,
                'good_quantity', receipt_item.good_quantity,
                'damaged_quantity', receipt_item.damaged_quantity,
                'missing_quantity', receipt_item.missing_quantity,
                'returned_quantity', receipt_item.returned_quantity
              )
              order by receipt_item.transfer_item_id
            )
            from public.stock_transfer_receipt_items receipt_item
            where receipt_item.receipt_id = receipt.id
          ), '[]'::jsonb)
        )
        order by receipt.created_at
      )
      from public.stock_transfer_receipts receipt
      where receipt.transfer_id = transfer.id
    ), '[]'::jsonb),
    'photos', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', photo.id,
          'receipt_key', photo.receipt_key,
          'receipt_id', photo.receipt_id,
          'category', photo.category,
          'storage_path', photo.storage_path,
          'mime_type', photo.mime_type,
          'file_size', photo.file_size,
          'uploaded_by', photo.uploaded_by,
          'created_at', photo.created_at
        )
        order by photo.created_at
      )
      from public.stock_transfer_photos photo
      where photo.transfer_id = transfer.id
    ), '[]'::jsonb)
  )
  from public.stock_transfers transfer
  join public.stores source_store on source_store.id = transfer.source_store_id
  join public.stores destination_store on destination_store.id = transfer.destination_store_id
  where transfer.id = target_transfer_id;
$$;

create or replace function public.create_pos_stock_transfer(
  target_source_store_slug text,
  target_destination_store_slug text,
  target_items jsonb,
  target_actor_staff_name text,
  target_dispatch_note text,
  target_client_request_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_source public.stores%rowtype;
  selected_destination public.stores%rowtype;
  saved_transfer public.stock_transfers%rowtype;
  product_ids bigint[];
  item_count integer;
  product_count integer;
  request_fingerprint text;
begin
  if coalesce(btrim(target_actor_staff_name), '') = '' then
    raise exception 'Staff name is required';
  end if;
  if target_client_request_key is null then
    raise exception 'Client request key is required';
  end if;
  if jsonb_typeof(target_items) <> 'array'
    or jsonb_array_length(target_items) < 1
    or jsonb_array_length(target_items) > 500 then
    raise exception 'Transfer must contain between 1 and 500 products';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(target_items) entry
    where jsonb_typeof(entry -> 'product_id') <> 'number'
      or jsonb_typeof(entry -> 'quantity') <> 'number'
      or (entry ->> 'product_id')::numeric <> trunc((entry ->> 'product_id')::numeric)
      or (entry ->> 'quantity')::numeric <> trunc((entry ->> 'quantity')::numeric)
  ) then
    raise exception 'Product IDs and transfer quantities must be whole numbers';
  end if;

  select pg_catalog.md5(
    concat_ws(
      '|',
      btrim(target_source_store_slug),
      btrim(target_destination_store_slug),
      btrim(target_actor_staff_name),
      coalesce(nullif(btrim(target_dispatch_note), ''), ''),
      coalesce(jsonb_agg(
        jsonb_build_object('product_id', parsed.product_id, 'quantity', parsed.quantity)
        order by parsed.product_id
      ), '[]'::jsonb)::text
    )
  )
  into request_fingerprint
  from jsonb_to_recordset(target_items) as parsed(product_id bigint, quantity integer);

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stock-transfer:' || target_client_request_key::text, 0)
  );

  select transfer.*
  into saved_transfer
  from public.stock_transfers transfer
  where transfer.client_request_key = target_client_request_key;

  if saved_transfer.id is not null then
    if saved_transfer.request_fingerprint <> request_fingerprint then
      raise exception 'Client request key was already used for a different transfer';
    end if;
    return public.pos_stock_transfer_payload(saved_transfer.id);
  end if;

  select store.*
  into selected_source
  from public.stores store
  where store.slug = btrim(target_source_store_slug)
    and store.is_active = true
    and store.slug = any(array['park-ridge', 'fairfield', 'north-lakes', 'toowong']);

  select store.*
  into selected_destination
  from public.stores store
  where store.slug = btrim(target_destination_store_slug)
    and store.is_active = true
    and store.slug = any(array['park-ridge', 'fairfield', 'north-lakes', 'toowong']);

  if selected_source.id is null or selected_destination.id is null then
    raise exception 'A valid POS source and destination store are required';
  end if;
  if selected_source.id = selected_destination.id then
    raise exception 'Source and destination stores must be different';
  end if;

  select
    count(*),
    count(distinct parsed.product_id),
    array_agg(parsed.product_id order by parsed.product_id)
  into item_count, product_count, product_ids
  from jsonb_to_recordset(target_items) as parsed(product_id bigint, quantity integer)
  where parsed.product_id is not null
    and parsed.quantity is not null
    and parsed.quantity > 0
    and parsed.quantity <= 1000000;

  if item_count <> jsonb_array_length(target_items)
    or product_count <> item_count then
    raise exception 'Every transfer product must be unique and have a positive whole quantity';
  end if;

  perform product.id
  from public.products product
  where product.id = any(product_ids)
    and product.is_pos_visible = true;

  get diagnostics product_count = row_count;
  if product_count <> item_count then
    raise exception 'One or more transfer products are unavailable in POS';
  end if;

  insert into public.product_store_inventory (product_id, store_id, quantity, updated_at)
  select product_row.product_id, store_row.store_id, 0, now()
  from unnest(product_ids) as product_row(product_id)
  cross join unnest(array[selected_source.id, selected_destination.id]) as store_row(store_id)
  on conflict (product_id, store_id) do nothing;

  perform inventory.id
  from public.product_store_inventory inventory
  where inventory.product_id = any(product_ids)
    and inventory.store_id = any(array[selected_source.id, selected_destination.id])
  order by inventory.product_id, inventory.store_id
  for update;

  if exists (
    select 1
    from jsonb_to_recordset(target_items) as parsed(product_id bigint, quantity integer)
    join public.product_store_inventory inventory
      on inventory.product_id = parsed.product_id
      and inventory.store_id = selected_source.id
    where inventory.quantity < parsed.quantity
  ) then
    raise exception 'One or more products do not have enough source-store inventory';
  end if;

  insert into public.stock_transfers (
    client_request_key,
    request_fingerprint,
    source_store_id,
    destination_store_id,
    status,
    dispatched_by,
    dispatch_note,
    dispatched_at,
    updated_at
  )
  values (
    target_client_request_key,
    request_fingerprint,
    selected_source.id,
    selected_destination.id,
    'in_transit',
    btrim(target_actor_staff_name),
    nullif(btrim(target_dispatch_note), ''),
    now(),
    now()
  )
  returning * into saved_transfer;

  insert into public.stock_transfer_items (
    transfer_id,
    product_id,
    sku_snapshot,
    name_snapshot,
    barcode_snapshot,
    variant_snapshot,
    dispatched_quantity,
    source_quantity_before
  )
  select
    saved_transfer.id,
    product.id,
    product.sku,
    product.name,
    product.upc,
    nullif(concat_ws(' / ', product.variant_name, product.variant_color), ''),
    parsed.quantity,
    inventory.quantity
  from jsonb_to_recordset(target_items) as parsed(product_id bigint, quantity integer)
  join public.products product on product.id = parsed.product_id
  join public.product_store_inventory inventory
    on inventory.product_id = product.id
    and inventory.store_id = selected_source.id
  order by product.id;

  update public.product_store_inventory inventory
  set
    quantity = inventory.quantity - parsed.quantity,
    updated_at = now()
  from jsonb_to_recordset(target_items) as parsed(product_id bigint, quantity integer)
  where inventory.product_id = parsed.product_id
    and inventory.store_id = selected_source.id;

  insert into public.inventory_movements (
    movement_key,
    movement_type,
    product_id,
    store_id,
    quantity_delta,
    quantity_before,
    quantity_after,
    transfer_id,
    transfer_item_id,
    actor_staff_name
  )
  select
    'transfer:' || saved_transfer.id || ':out:' || item.id,
    'transfer_out',
    item.product_id,
    selected_source.id,
    -item.dispatched_quantity,
    item.source_quantity_before,
    inventory.quantity,
    saved_transfer.id,
    item.id,
    btrim(target_actor_staff_name)
  from public.stock_transfer_items item
  join public.product_store_inventory inventory
    on inventory.product_id = item.product_id
    and inventory.store_id = selected_source.id
  where item.transfer_id = saved_transfer.id;

  perform public.refresh_product_stock_totals(product_ids);

  return public.pos_stock_transfer_payload(saved_transfer.id);
end;
$$;

create or replace function public.receive_pos_stock_transfer(
  target_transfer_id bigint,
  target_receipt_key uuid,
  target_lines jsonb,
  target_finalize boolean,
  target_actor_staff_name text,
  target_note text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_transfer public.stock_transfers%rowtype;
  saved_receipt public.stock_transfer_receipts%rowtype;
  submitted_count integer;
  distinct_count integer;
  matched_count integer;
  remaining_total integer;
  issue_total integer;
  good_total integer;
  product_ids bigint[];
  request_fingerprint text;
begin
  if coalesce(btrim(target_actor_staff_name), '') = '' then
    raise exception 'Staff name is required';
  end if;
  if target_receipt_key is null then
    raise exception 'Receipt key is required';
  end if;
  if jsonb_typeof(target_lines) <> 'array' or jsonb_array_length(target_lines) > 500 then
    raise exception 'Receipt lines must be an array with no more than 500 products';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(target_lines) entry
    where jsonb_typeof(entry -> 'transfer_item_id') <> 'number'
      or (entry ->> 'transfer_item_id')::numeric <> trunc((entry ->> 'transfer_item_id')::numeric)
      or (
        entry ? 'good_quantity'
        and entry -> 'good_quantity' <> 'null'::jsonb
        and (
          jsonb_typeof(entry -> 'good_quantity') <> 'number'
          or (entry ->> 'good_quantity')::numeric <> trunc((entry ->> 'good_quantity')::numeric)
        )
      )
      or (
        entry ? 'damaged_quantity'
        and entry -> 'damaged_quantity' <> 'null'::jsonb
        and (
          jsonb_typeof(entry -> 'damaged_quantity') <> 'number'
          or (entry ->> 'damaged_quantity')::numeric <> trunc((entry ->> 'damaged_quantity')::numeric)
        )
      )
  ) then
    raise exception 'Receipt product IDs and quantities must be whole numbers';
  end if;

  select pg_catalog.md5(
    concat_ws(
      '|',
      target_transfer_id::text,
      coalesce(target_finalize, false)::text,
      btrim(target_actor_staff_name),
      coalesce(nullif(btrim(target_note), ''), ''),
      coalesce(jsonb_agg(
        jsonb_build_object(
          'transfer_item_id', parsed.transfer_item_id,
          'good_quantity', coalesce(parsed.good_quantity, 0),
          'damaged_quantity', coalesce(parsed.damaged_quantity, 0)
        )
        order by parsed.transfer_item_id
      ), '[]'::jsonb)::text
    )
  )
  into request_fingerprint
  from jsonb_to_recordset(target_lines) as parsed(
    transfer_item_id bigint,
    good_quantity integer,
    damaged_quantity integer
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stock-transfer-receipt:' || target_receipt_key::text, 0)
  );

  select receipt.*
  into saved_receipt
  from public.stock_transfer_receipts receipt
  where receipt.receipt_key = target_receipt_key;

  if saved_receipt.id is not null then
    if saved_receipt.transfer_id <> target_transfer_id then
      raise exception 'Receipt key belongs to another transfer';
    end if;
    if saved_receipt.receipt_type <> 'receive'
      or saved_receipt.request_fingerprint <> request_fingerprint then
      raise exception 'Receipt key was already used for a different operation';
    end if;
    return public.pos_stock_transfer_payload(target_transfer_id);
  end if;

  select transfer.*
  into selected_transfer
  from public.stock_transfers transfer
  where transfer.id = target_transfer_id
  for update;

  if selected_transfer.id is null then
    raise exception 'Transfer not found';
  end if;
  if selected_transfer.status not in ('in_transit', 'partially_received') then
    raise exception 'Transfer is not available to receive';
  end if;

  if not exists (
    select 1
    from public.stock_transfer_photos photo
    where photo.transfer_id = selected_transfer.id
      and photo.receipt_key = target_receipt_key
  ) then
    raise exception 'At least one receipt photo must be uploaded before receiving';
  end if;

  perform item.id
  from public.stock_transfer_items item
  where item.transfer_id = selected_transfer.id
  order by item.id
  for update;

  select
    count(*),
    count(distinct parsed.transfer_item_id)
  into submitted_count, distinct_count
  from jsonb_to_recordset(target_lines) as parsed(
    transfer_item_id bigint,
    good_quantity integer,
    damaged_quantity integer
  )
  where parsed.transfer_item_id is not null
    and coalesce(parsed.good_quantity, 0) >= 0
    and coalesce(parsed.damaged_quantity, 0) >= 0
    and coalesce(parsed.good_quantity, 0) + coalesce(parsed.damaged_quantity, 0) > 0;

  if submitted_count <> jsonb_array_length(target_lines)
    or distinct_count <> submitted_count then
    raise exception 'Receipt lines must be unique and contain a positive good or damaged quantity';
  end if;
  if not coalesce(target_finalize, false) and submitted_count = 0 then
    raise exception 'A partial receipt must contain at least one received product';
  end if;

  select count(*)
  into matched_count
  from jsonb_to_recordset(target_lines) as parsed(
    transfer_item_id bigint,
    good_quantity integer,
    damaged_quantity integer
  )
  join public.stock_transfer_items item
    on item.id = parsed.transfer_item_id
    and item.transfer_id = selected_transfer.id;

  if matched_count <> submitted_count then
    raise exception 'One or more receipt products do not belong to this transfer';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(target_lines) as parsed(
      transfer_item_id bigint,
      good_quantity integer,
      damaged_quantity integer
    )
    join public.stock_transfer_items item on item.id = parsed.transfer_item_id
    where coalesce(parsed.good_quantity, 0) + coalesce(parsed.damaged_quantity, 0)
      > item.dispatched_quantity - item.received_good_quantity
        - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
  ) then
    raise exception 'Received quantity exceeds the remaining transfer quantity';
  end if;

  insert into public.stock_transfer_receipts (
    transfer_id,
    receipt_key,
    request_fingerprint,
    receipt_type,
    received_by,
    note
  )
  values (
    selected_transfer.id,
    target_receipt_key,
    request_fingerprint,
    'receive',
    btrim(target_actor_staff_name),
    nullif(btrim(target_note), '')
  )
  returning * into saved_receipt;

  insert into public.stock_transfer_receipt_items (
    receipt_id,
    transfer_item_id,
    good_quantity,
    damaged_quantity,
    missing_quantity,
    returned_quantity
  )
  select
    saved_receipt.id,
    item.id,
    coalesce(parsed.good_quantity, 0),
    coalesce(parsed.damaged_quantity, 0),
    case
      when coalesce(target_finalize, false) then greatest(
        item.dispatched_quantity - item.received_good_quantity
          - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
          - coalesce(parsed.good_quantity, 0) - coalesce(parsed.damaged_quantity, 0),
        0
      )
      else 0
    end,
    0
  from public.stock_transfer_items item
  left join jsonb_to_recordset(target_lines) as parsed(
    transfer_item_id bigint,
    good_quantity integer,
    damaged_quantity integer
  ) on parsed.transfer_item_id = item.id
  where item.transfer_id = selected_transfer.id
    and (
      coalesce(parsed.good_quantity, 0) + coalesce(parsed.damaged_quantity, 0) > 0
      or (
        coalesce(target_finalize, false)
        and item.dispatched_quantity - item.received_good_quantity
          - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity > 0
      )
    )
  order by item.id;

  update public.stock_transfer_items item
  set
    received_good_quantity = item.received_good_quantity + receipt_item.good_quantity,
    received_damaged_quantity = item.received_damaged_quantity + receipt_item.damaged_quantity,
    missing_quantity = item.missing_quantity + receipt_item.missing_quantity,
    updated_at = now()
  from public.stock_transfer_receipt_items receipt_item
  where receipt_item.receipt_id = saved_receipt.id
    and receipt_item.transfer_item_id = item.id;

  select
    coalesce(sum(receipt_item.good_quantity), 0)::integer,
    array_agg(distinct item.product_id order by item.product_id)
      filter (where receipt_item.good_quantity > 0)
  into good_total, product_ids
  from public.stock_transfer_receipt_items receipt_item
  join public.stock_transfer_items item on item.id = receipt_item.transfer_item_id
  where receipt_item.receipt_id = saved_receipt.id;

  if good_total > 0 then
    insert into public.product_store_inventory (product_id, store_id, quantity, updated_at)
    select product_row.product_id, selected_transfer.destination_store_id, 0, now()
    from unnest(product_ids) as product_row(product_id)
    on conflict (product_id, store_id) do nothing;

    perform inventory.id
    from public.product_store_inventory inventory
    where inventory.product_id = any(product_ids)
      and inventory.store_id = selected_transfer.destination_store_id
    order by inventory.product_id
    for update;

    update public.product_store_inventory inventory
    set
      quantity = inventory.quantity + totals.good_quantity,
      updated_at = now()
    from (
      select item.product_id, sum(receipt_item.good_quantity)::integer as good_quantity
      from public.stock_transfer_receipt_items receipt_item
      join public.stock_transfer_items item on item.id = receipt_item.transfer_item_id
      where receipt_item.receipt_id = saved_receipt.id
        and receipt_item.good_quantity > 0
      group by item.product_id
    ) totals
    where inventory.product_id = totals.product_id
      and inventory.store_id = selected_transfer.destination_store_id;

    insert into public.inventory_movements (
      movement_key,
      movement_type,
      product_id,
      store_id,
      quantity_delta,
      quantity_before,
      quantity_after,
      transfer_id,
      transfer_item_id,
      receipt_id,
      actor_staff_name
    )
    select
      'transfer:' || selected_transfer.id || ':receipt:' || saved_receipt.id || ':in:' || item.id,
      'transfer_in',
      item.product_id,
      selected_transfer.destination_store_id,
      receipt_item.good_quantity,
      inventory.quantity - receipt_item.good_quantity,
      inventory.quantity,
      selected_transfer.id,
      item.id,
      saved_receipt.id,
      btrim(target_actor_staff_name)
    from public.stock_transfer_receipt_items receipt_item
    join public.stock_transfer_items item on item.id = receipt_item.transfer_item_id
    join public.product_store_inventory inventory
      on inventory.product_id = item.product_id
      and inventory.store_id = selected_transfer.destination_store_id
    where receipt_item.receipt_id = saved_receipt.id
      and receipt_item.good_quantity > 0;

    perform public.refresh_product_stock_totals(product_ids);
  end if;

  update public.stock_transfer_photos photo
  set receipt_id = saved_receipt.id
  where photo.transfer_id = selected_transfer.id
    and photo.receipt_key = target_receipt_key
    and photo.receipt_id is null;

  select
    coalesce(sum(
      item.dispatched_quantity - item.received_good_quantity
        - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
    ), 0)::integer,
    coalesce(sum(item.received_damaged_quantity + item.missing_quantity), 0)::integer
  into remaining_total, issue_total
  from public.stock_transfer_items item
  where item.transfer_id = selected_transfer.id;

  update public.stock_transfers transfer
  set
    status = case
      when remaining_total > 0 then 'partially_received'
      when issue_total > 0 then 'completed_with_issues'
      else 'completed'
    end,
    completed_at = case when remaining_total = 0 then now() else null end,
    updated_at = now()
  where transfer.id = selected_transfer.id;

  return public.pos_stock_transfer_payload(selected_transfer.id);
end;
$$;

create or replace function public.return_pos_stock_transfer(
  target_transfer_id bigint,
  target_receipt_key uuid,
  target_actor_staff_name text,
  target_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_transfer public.stock_transfers%rowtype;
  saved_receipt public.stock_transfer_receipts%rowtype;
  remaining_total integer;
  product_ids bigint[];
  request_fingerprint text;
begin
  if coalesce(btrim(target_actor_staff_name), '') = '' then
    raise exception 'Staff name is required';
  end if;
  if coalesce(btrim(target_reason), '') = '' then
    raise exception 'Return reason is required';
  end if;
  if target_receipt_key is null then
    raise exception 'Receipt key is required';
  end if;

  request_fingerprint := pg_catalog.md5(
    concat_ws(
      '|',
      target_transfer_id::text,
      btrim(target_actor_staff_name),
      btrim(target_reason)
    )
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('stock-transfer-return:' || target_receipt_key::text, 0)
  );

  select receipt.*
  into saved_receipt
  from public.stock_transfer_receipts receipt
  where receipt.receipt_key = target_receipt_key;

  if saved_receipt.id is not null then
    if saved_receipt.transfer_id <> target_transfer_id then
      raise exception 'Receipt key belongs to another transfer';
    end if;
    if saved_receipt.receipt_type <> 'return'
      or saved_receipt.request_fingerprint <> request_fingerprint then
      raise exception 'Receipt key was already used for a different operation';
    end if;
    return public.pos_stock_transfer_payload(target_transfer_id);
  end if;

  select transfer.*
  into selected_transfer
  from public.stock_transfers transfer
  where transfer.id = target_transfer_id
  for update;

  if selected_transfer.id is null then
    raise exception 'Transfer not found';
  end if;
  if selected_transfer.status not in ('in_transit', 'partially_received') then
    raise exception 'Transfer has no stock available to return';
  end if;

  if not exists (
    select 1
    from public.stock_transfer_photos photo
    where photo.transfer_id = selected_transfer.id
      and photo.receipt_key = target_receipt_key
  ) then
    raise exception 'At least one return photo must be uploaded before returning stock';
  end if;

  perform item.id
  from public.stock_transfer_items item
  where item.transfer_id = selected_transfer.id
  order by item.id
  for update;

  select
    coalesce(sum(
      item.dispatched_quantity - item.received_good_quantity
        - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
    ), 0)::integer,
    array_agg(distinct item.product_id order by item.product_id)
  into remaining_total, product_ids
  from public.stock_transfer_items item
  where item.transfer_id = selected_transfer.id
    and item.dispatched_quantity - item.received_good_quantity
      - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity > 0;

  if remaining_total <= 0 then
    raise exception 'Transfer has no remaining stock to return';
  end if;

  insert into public.stock_transfer_receipts (
    transfer_id,
    receipt_key,
    request_fingerprint,
    receipt_type,
    received_by,
    note
  )
  values (
    selected_transfer.id,
    target_receipt_key,
    request_fingerprint,
    'return',
    btrim(target_actor_staff_name),
    btrim(target_reason)
  )
  returning * into saved_receipt;

  insert into public.stock_transfer_receipt_items (
    receipt_id,
    transfer_item_id,
    returned_quantity
  )
  select
    saved_receipt.id,
    item.id,
    item.dispatched_quantity - item.received_good_quantity
      - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
  from public.stock_transfer_items item
  where item.transfer_id = selected_transfer.id
    and item.dispatched_quantity - item.received_good_quantity
      - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity > 0
  order by item.id;

  update public.stock_transfer_items item
  set
    returned_quantity = item.returned_quantity + receipt_item.returned_quantity,
    updated_at = now()
  from public.stock_transfer_receipt_items receipt_item
  where receipt_item.receipt_id = saved_receipt.id
    and receipt_item.transfer_item_id = item.id;

  insert into public.product_store_inventory (product_id, store_id, quantity, updated_at)
  select product_row.product_id, selected_transfer.source_store_id, 0, now()
  from unnest(product_ids) as product_row(product_id)
  on conflict (product_id, store_id) do nothing;

  perform inventory.id
  from public.product_store_inventory inventory
  where inventory.product_id = any(product_ids)
    and inventory.store_id = selected_transfer.source_store_id
  order by inventory.product_id
  for update;

  update public.product_store_inventory inventory
  set
    quantity = inventory.quantity + totals.returned_quantity,
    updated_at = now()
  from (
    select item.product_id, sum(receipt_item.returned_quantity)::integer as returned_quantity
    from public.stock_transfer_receipt_items receipt_item
    join public.stock_transfer_items item on item.id = receipt_item.transfer_item_id
    where receipt_item.receipt_id = saved_receipt.id
      and receipt_item.returned_quantity > 0
    group by item.product_id
  ) totals
  where inventory.product_id = totals.product_id
    and inventory.store_id = selected_transfer.source_store_id;

  insert into public.inventory_movements (
    movement_key,
    movement_type,
    product_id,
    store_id,
    quantity_delta,
    quantity_before,
    quantity_after,
    transfer_id,
    transfer_item_id,
    receipt_id,
    actor_staff_name
  )
  select
    'transfer:' || selected_transfer.id || ':receipt:' || saved_receipt.id || ':return:' || item.id,
    'transfer_return',
    item.product_id,
    selected_transfer.source_store_id,
    receipt_item.returned_quantity,
    inventory.quantity - receipt_item.returned_quantity,
    inventory.quantity,
    selected_transfer.id,
    item.id,
    saved_receipt.id,
    btrim(target_actor_staff_name)
  from public.stock_transfer_receipt_items receipt_item
  join public.stock_transfer_items item on item.id = receipt_item.transfer_item_id
  join public.product_store_inventory inventory
    on inventory.product_id = item.product_id
    and inventory.store_id = selected_transfer.source_store_id
  where receipt_item.receipt_id = saved_receipt.id
    and receipt_item.returned_quantity > 0;

  update public.stock_transfer_photos photo
  set receipt_id = saved_receipt.id
  where photo.transfer_id = selected_transfer.id
    and photo.receipt_key = target_receipt_key
    and photo.receipt_id is null;

  update public.stock_transfers transfer
  set
    status = 'returned',
    completed_at = now(),
    updated_at = now()
  where transfer.id = selected_transfer.id;

  perform public.refresh_product_stock_totals(product_ids);

  return public.pos_stock_transfer_payload(selected_transfer.id);
end;
$$;

create or replace function public.list_pos_stock_transfers(
  target_status text,
  target_store_slug text,
  target_search_query text,
  target_limit integer
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(to_jsonb(listed) order by listed.dispatched_at desc), '[]'::jsonb)
  from (
    select
      transfer.id,
      transfer.transfer_number,
      transfer.status,
      source_store.slug as source_store_slug,
      source_store.name as source_store_name,
      destination_store.slug as destination_store_slug,
      destination_store.name as destination_store_name,
      transfer.dispatched_by,
      transfer.dispatch_note,
      transfer.dispatched_at,
      transfer.completed_at,
      item_totals.product_count,
      item_totals.dispatched_quantity,
      item_totals.received_good_quantity,
      item_totals.issue_quantity,
      item_totals.remaining_quantity,
      photo_totals.photo_count
    from public.stock_transfers transfer
    join public.stores source_store on source_store.id = transfer.source_store_id
    join public.stores destination_store on destination_store.id = transfer.destination_store_id
    cross join lateral (
      select
        count(*)::integer as product_count,
        coalesce(sum(item.dispatched_quantity), 0)::integer as dispatched_quantity,
        coalesce(sum(item.received_good_quantity), 0)::integer as received_good_quantity,
        coalesce(sum(item.received_damaged_quantity + item.missing_quantity), 0)::integer as issue_quantity,
        coalesce(sum(
          item.dispatched_quantity - item.received_good_quantity
            - item.received_damaged_quantity - item.missing_quantity - item.returned_quantity
        ), 0)::integer as remaining_quantity
      from public.stock_transfer_items item
      where item.transfer_id = transfer.id
    ) item_totals
    cross join lateral (
      select count(*)::integer as photo_count
      from public.stock_transfer_photos photo
      where photo.transfer_id = transfer.id
    ) photo_totals
    where (
      coalesce(nullif(btrim(target_status), ''), 'all') = 'all'
      or (btrim(target_status) = 'open' and transfer.status in ('in_transit', 'partially_received'))
      or transfer.status = btrim(target_status)
    )
      and (
        coalesce(nullif(btrim(target_store_slug), ''), 'all') = 'all'
        or source_store.slug = btrim(target_store_slug)
        or destination_store.slug = btrim(target_store_slug)
      )
      and (
        coalesce(nullif(btrim(target_search_query), ''), '') = ''
        or transfer.transfer_number ilike '%' || btrim(target_search_query) || '%'
        or transfer.dispatched_by ilike '%' || btrim(target_search_query) || '%'
        or exists (
          select 1
          from public.stock_transfer_items search_item
          where search_item.transfer_id = transfer.id
            and (
              search_item.sku_snapshot ilike '%' || btrim(target_search_query) || '%'
              or search_item.name_snapshot ilike '%' || btrim(target_search_query) || '%'
              or coalesce(search_item.barcode_snapshot, '') ilike '%' || btrim(target_search_query) || '%'
            )
        )
      )
    order by transfer.dispatched_at desc
    limit least(greatest(coalesce(target_limit, 100), 1), 200)
  ) listed;
$$;

create or replace function public.list_pos_transfer_stores()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(
    jsonb_build_object('id', store.id, 'slug', store.slug, 'name', store.name)
    order by array_position(array['park-ridge', 'north-lakes', 'fairfield', 'toowong'], store.slug)
  ), '[]'::jsonb)
  from public.stores store
  where store.is_active = true
    and store.slug = any(array['park-ridge', 'north-lakes', 'fairfield', 'toowong']);
$$;

create or replace function public.register_pos_stock_transfer_photo(
  target_transfer_id bigint,
  target_receipt_key uuid,
  target_category text,
  target_storage_path text,
  target_mime_type text,
  target_file_size integer,
  target_actor_staff_name text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_transfer public.stock_transfers%rowtype;
  existing_receipt public.stock_transfer_receipts%rowtype;
  saved_photo public.stock_transfer_photos%rowtype;
begin
  if target_receipt_key is null then
    raise exception 'Receipt key is required';
  end if;
  if coalesce(btrim(target_actor_staff_name), '') = '' then
    raise exception 'Staff name is required';
  end if;
  if target_category not in ('receipt', 'issue', 'return') then
    raise exception 'Photo category is invalid';
  end if;
  if target_mime_type not in ('image/jpeg', 'image/png', 'image/webp')
    or target_file_size is null
    or target_file_size < 1
    or target_file_size > 5242880 then
    raise exception 'Photo must be JPEG, PNG or WebP and no larger than 5 MB';
  end if;
  if coalesce(target_storage_path, '') not like
    target_transfer_id::text || '/' || target_receipt_key::text || '/%' then
    raise exception 'Photo storage path does not match the transfer receipt';
  end if;

  select transfer.*
  into selected_transfer
  from public.stock_transfers transfer
  where transfer.id = target_transfer_id;

  if selected_transfer.id is null then
    raise exception 'Transfer not found';
  end if;

  select receipt.*
  into existing_receipt
  from public.stock_transfer_receipts receipt
  where receipt.receipt_key = target_receipt_key;

  if existing_receipt.id is not null and existing_receipt.transfer_id <> selected_transfer.id then
    raise exception 'Receipt key belongs to another transfer';
  end if;
  if existing_receipt.id is null
    and selected_transfer.status not in ('in_transit', 'partially_received') then
    raise exception 'Transfer is no longer available for new receipt photos';
  end if;
  if exists (
    select 1
    from public.stock_transfer_photos photo
    where photo.receipt_key = target_receipt_key
      and photo.transfer_id <> selected_transfer.id
  ) then
    raise exception 'Receipt key belongs to another transfer';
  end if;

  insert into public.stock_transfer_photos (
    transfer_id,
    receipt_key,
    receipt_id,
    category,
    storage_path,
    mime_type,
    file_size,
    uploaded_by
  )
  values (
    selected_transfer.id,
    target_receipt_key,
    existing_receipt.id,
    target_category,
    target_storage_path,
    target_mime_type,
    target_file_size,
    btrim(target_actor_staff_name)
  )
  returning * into saved_photo;

  return jsonb_build_object(
    'id', saved_photo.id,
    'transfer_id', saved_photo.transfer_id,
    'receipt_key', saved_photo.receipt_key,
    'category', saved_photo.category,
    'storage_path', saved_photo.storage_path,
    'mime_type', saved_photo.mime_type,
    'file_size', saved_photo.file_size,
    'uploaded_by', saved_photo.uploaded_by,
    'created_at', saved_photo.created_at
  );
end;
$$;

revoke all on sequence public.stock_transfer_number_seq from public, anon, authenticated;

grant all on table public.stock_transfers to service_role;
grant all on table public.stock_transfer_items to service_role;
grant all on table public.stock_transfer_receipts to service_role;
grant all on table public.stock_transfer_receipt_items to service_role;
grant all on table public.stock_transfer_photos to service_role;
grant all on table public.inventory_movements to service_role;
grant usage, select on sequence public.stock_transfer_number_seq to service_role;

revoke execute on function public.refresh_product_stock_totals(bigint[]) from public, anon, authenticated;
revoke execute on function public.pos_stock_transfer_payload(bigint) from public, anon, authenticated;
revoke execute on function public.create_pos_stock_transfer(text, text, jsonb, text, text, uuid) from public, anon, authenticated;
revoke execute on function public.receive_pos_stock_transfer(bigint, uuid, jsonb, boolean, text, text) from public, anon, authenticated;
revoke execute on function public.return_pos_stock_transfer(bigint, uuid, text, text) from public, anon, authenticated;
revoke execute on function public.list_pos_stock_transfers(text, text, text, integer) from public, anon, authenticated;
revoke execute on function public.list_pos_transfer_stores() from public, anon, authenticated;
revoke execute on function public.register_pos_stock_transfer_photo(bigint, uuid, text, text, text, integer, text) from public, anon, authenticated;

grant execute on function public.refresh_product_stock_totals(bigint[]) to service_role;
grant execute on function public.pos_stock_transfer_payload(bigint) to service_role;
grant execute on function public.create_pos_stock_transfer(text, text, jsonb, text, text, uuid) to service_role;
grant execute on function public.receive_pos_stock_transfer(bigint, uuid, jsonb, boolean, text, text) to service_role;
grant execute on function public.return_pos_stock_transfer(bigint, uuid, text, text) to service_role;
grant execute on function public.list_pos_stock_transfers(text, text, text, integer) to service_role;
grant execute on function public.list_pos_transfer_stores() to service_role;
grant execute on function public.register_pos_stock_transfer_photo(bigint, uuid, text, text, text, integer, text) to service_role;
