-- A completed used-device purchase is a signed acquisition, not an editable
-- form submission.  The PDF and signature live in a private bucket while this
-- table freezes the exact snapshot, terms and SHA-256 of what was signed.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'used-device-documents',
  'used-device-documents',
  false,
  5242880,
  array['application/pdf','image/png','image/jpeg']
)
on conflict (id) do nothing;

create table if not exists public.pos_used_device_buyback_terms (
  version text primary key,
  body text not null,
  active boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.pos_used_device_buyback_terms (version, body, active)
values ('v1', $terms$I confirm and declare that:

1. I am the legal owner of the device, or I have the legal owner's authority to sell it to TechM8.

2. The device is not lost, stolen, leased, subject to finance, network blocked, or otherwise restricted from sale. All information and identification I supplied is true and accurate.

3. The IMEI or serial number and the condition shown in this agreement identify the device I am selling. I have disclosed any known faults, damage, missing parts, and ownership details.

4. I have removed activation locks, accounts, SIM cards and memory cards. I understand that TechM8 may erase any remaining data and I am responsible for keeping my own backup.

5. Once TechM8 pays the purchase amount recorded in this agreement, ownership of the device transfers to TechM8. TechM8 may inspect, repair, refurbish, resell, recycle or dispose of it.

6. I consent to TechM8 retaining this signed agreement, the recorded identification details and the evidence photographs for transaction, fraud-prevention and legal record-keeping purposes.$terms$, true)
on conflict (version) do nothing;

create table if not exists public.pos_used_device_buyback_documents (
  id bigint generated by default as identity primary key,
  document_code text not null unique,
  acquisition_id bigint not null unique references public.pos_used_device_acquisitions(id) on delete restrict,
  device_id bigint not null unique references public.pos_used_devices(id) on delete restrict,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  pdf_path text not null unique,
  pdf_sha256 text not null check (pdf_sha256 ~ '^[0-9a-f]{64}$'),
  signature_path text not null unique,
  signed_seller_name text not null check (char_length(signed_seller_name) between 1 and 120),
  terms_version text not null references public.pos_used_device_buyback_terms(version),
  terms_text text not null,
  document_snapshot jsonb not null,
  witnessed_by text not null,
  signed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists pos_used_device_buyback_terms_one_active_idx
  on public.pos_used_device_buyback_terms (active)
  where active;

create index if not exists pos_used_device_buyback_documents_store_idx
  on public.pos_used_device_buyback_documents (store_id, signed_at desc);
create index if not exists pos_used_device_buyback_documents_terms_idx
  on public.pos_used_device_buyback_documents (terms_version);

create table if not exists public.pos_used_device_document_access_log (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.pos_used_device_buyback_documents(id) on delete restrict,
  device_id bigint not null references public.pos_used_devices(id) on delete restrict,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  viewed_by text not null,
  viewed_at timestamptz not null default now()
);

create index if not exists pos_used_device_document_access_document_idx
  on public.pos_used_device_document_access_log (document_id, viewed_at desc);
create index if not exists pos_used_device_document_access_device_idx
  on public.pos_used_device_document_access_log (device_id, viewed_at desc);
create index if not exists pos_used_device_document_access_store_idx
  on public.pos_used_device_document_access_log (store_id, viewed_at desc);

alter table public.pos_used_device_buyback_terms enable row level security;
alter table public.pos_used_device_buyback_documents enable row level security;
alter table public.pos_used_device_document_access_log enable row level security;

revoke all on public.pos_used_device_buyback_terms from public, anon, authenticated;
revoke all on public.pos_used_device_buyback_documents from public, anon, authenticated;
revoke all on public.pos_used_device_document_access_log from public, anon, authenticated;
grant select on public.pos_used_device_buyback_terms to service_role;
grant select, insert on public.pos_used_device_buyback_documents to service_role;
grant select, insert on public.pos_used_device_document_access_log to service_role;

create or replace function public.reject_pos_used_device_document_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'Signed buyback documents are immutable';
end;
$$;

drop trigger if exists pos_used_device_buyback_document_immutable on public.pos_used_device_buyback_documents;
create trigger pos_used_device_buyback_document_immutable
before update or delete on public.pos_used_device_buyback_documents
for each row execute function public.reject_pos_used_device_document_change();

-- Used by the signing screen before the PDF is generated. The wrapper below
-- independently selects the active row again so a stale or invented version
-- can never be attached to a purchase.
create or replace function public.get_pos_used_device_buyback_terms(
  session_token text,
  target_store_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  terms_row public.pos_used_device_buyback_terms%rowtype;
begin
  actor := public.pos_authorized_actor(session_token, target_store_code, null);
  select * into terms_row
  from public.pos_used_device_buyback_terms
  where active
  order by created_at desc
  limit 1;
  if not found then raise exception 'No active buyback agreement terms'; end if;
  return jsonb_build_object('ok', true, 'version', terms_row.version, 'body', terms_row.body);
end;
$$;

-- create_pos_used_device_acquisition remains the single source of truth for
-- all purchasing rules. This wrapper runs it inside the same transaction and
-- refuses to commit the acquisition unless its immutable signed document and
-- seller ID photograph are present too.
create or replace function public.create_pos_used_device_acquisition_with_document(
  session_token text,
  payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
  document_payload jsonb := payload->'signed_document';
  device_row public.pos_used_devices%rowtype;
  acquisition_row public.pos_used_device_acquisitions%rowtype;
  terms_row public.pos_used_device_buyback_terms%rowtype;
  inserted public.pos_used_device_buyback_documents%rowtype;
  document_code_value text := trim(coalesce(document_payload->>'document_code', ''));
  signed_name_value text := trim(coalesce(document_payload->>'signed_seller_name', ''));
  pdf_path_value text := trim(coalesce(document_payload->>'pdf_path', ''));
  signature_path_value text := trim(coalesce(document_payload->>'signature_path', ''));
  pdf_sha_value text := lower(trim(coalesce(document_payload->>'pdf_sha256', '')));
  id_photo_count integer;
begin
  if jsonb_typeof(payload) <> 'object' or jsonb_typeof(document_payload) <> 'object' then
    raise exception 'A signed buyback document is required';
  end if;
  if document_code_value !~ '^BBD-[A-Z0-9-]{12,80}$' then raise exception 'Invalid buyback document reference'; end if;
  if signed_name_value = '' then raise exception 'The seller must type their name and sign'; end if;
  if char_length(signed_name_value) > 120 then raise exception 'The seller name cannot exceed 120 characters'; end if;
  if lower(regexp_replace(signed_name_value, '\s+', '', 'g')) <>
     lower(regexp_replace(trim(coalesce(payload->>'seller_name', '')), '\s+', '', 'g')) then
    raise exception 'The signature name must match the seller name';
  end if;
  if pdf_path_value = '' or signature_path_value = '' then raise exception 'Signed PDF and signature files are required'; end if;
  if pdf_sha_value !~ '^[0-9a-f]{64}$' then raise exception 'Invalid signed PDF fingerprint'; end if;
  if jsonb_typeof(document_payload->'document_snapshot') <> 'object' then raise exception 'Signed document snapshot is required'; end if;

  select * into terms_row
  from public.pos_used_device_buyback_terms
  where active and version = trim(coalesce(document_payload->>'terms_version', ''))
  order by created_at desc
  limit 1;
  if not found then raise exception 'The buyback agreement terms changed. Review and sign again'; end if;

  result := public.create_pos_used_device_acquisition(session_token, payload - 'signed_document');

  select * into device_row
  from public.pos_used_devices
  where device_code = result #>> '{device,device_code}'
  for update;
  if not found then raise exception 'The purchased device could not be linked to its agreement'; end if;

  select * into acquisition_row
  from public.pos_used_device_acquisitions
  where id = device_row.acquisition_id;

  select count(*) into id_photo_count
  from public.pos_used_device_updates update_row
  where update_row.device_id = device_row.id
    and update_row.kind = 'photo'
    and update_row.stage = 'seller_id';
  if id_photo_count < 1 then raise exception 'Photograph the seller ID before completing the purchase'; end if;

  insert into public.pos_used_device_buyback_documents (
    document_code, acquisition_id, device_id, store_id, pdf_path,
    pdf_sha256, signature_path, signed_seller_name, terms_version,
    terms_text, document_snapshot, witnessed_by
  ) values (
    document_code_value, acquisition_row.id, device_row.id, device_row.store_id,
    pdf_path_value, pdf_sha_value, signature_path_value, signed_name_value,
    terms_row.version, terms_row.body, document_payload->'document_snapshot',
    acquisition_row.acquired_by
  ) returning * into inserted;

  return result || jsonb_build_object('document', jsonb_build_object(
    'document_code', inserted.document_code,
    'signed_seller_name', inserted.signed_seller_name,
    'signed_at', inserted.signed_at,
    'pdf_sha256', inserted.pdf_sha256
  ));
end;
$$;

create or replace function public.get_pos_used_device_buyback_documents(
  session_token text,
  target_store_code text,
  target_device_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  device_row public.pos_used_devices%rowtype;
  acquisition_row public.pos_used_device_acquisitions%rowtype;
  documents_payload jsonb;
  id_photos_payload jsonb;
begin
  actor := public.pos_authorized_actor(session_token, target_store_code, null);
  select * into device_row
  from public.pos_used_devices
  where device_code = trim(coalesce(target_device_code, ''));
  if not found then raise exception 'Used device not found'; end if;
  if device_row.store_id <> nullif(actor->>'store_id', '')::bigint then raise exception 'Used device belongs to another store'; end if;

  select * into acquisition_row from public.pos_used_device_acquisitions where id = device_row.acquisition_id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'document_code', document_row.document_code,
    'pdf_path', document_row.pdf_path,
    'pdf_sha256', document_row.pdf_sha256,
    'signature_path', document_row.signature_path,
    'signed_seller_name', document_row.signed_seller_name,
    'terms_version', document_row.terms_version,
    'witnessed_by', document_row.witnessed_by,
    'signed_at', document_row.signed_at
  ) order by document_row.signed_at desc), '[]'::jsonb)
  into documents_payload
  from public.pos_used_device_buyback_documents document_row
  where document_row.device_id = device_row.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', update_row.id,
    'file_name', update_row.file_name,
    'storage_path', update_row.storage_path,
    'created_at', update_row.created_at
  ) order by update_row.created_at), '[]'::jsonb)
  into id_photos_payload
  from public.pos_used_device_updates update_row
  where update_row.device_id = device_row.id
    and update_row.kind = 'photo'
    and update_row.stage = 'seller_id';

  insert into public.pos_used_device_document_access_log (
    document_id, device_id, store_id, viewed_by
  )
  select document_row.id, device_row.id, device_row.store_id, actor->>'staff_name'
  from public.pos_used_device_buyback_documents document_row
  where document_row.device_id = device_row.id;

  return jsonb_build_object(
    'ok', true,
    'device_code', device_row.device_code,
    'seller_id', jsonb_build_object(
      'type', acquisition_row.seller_id_type,
      'reference', acquisition_row.seller_id_reference
    ),
    'documents', documents_payload,
    'id_photos', id_photos_payload
  );
end;
$$;

revoke all on function public.reject_pos_used_device_document_change() from public, anon, authenticated;
revoke all on function public.get_pos_used_device_buyback_terms(text, text) from public, anon, authenticated;
revoke all on function public.create_pos_used_device_acquisition_with_document(text, jsonb) from public, anon, authenticated;
revoke all on function public.get_pos_used_device_buyback_documents(text, text, text) from public, anon, authenticated;
grant execute on function public.get_pos_used_device_buyback_terms(text, text) to service_role;
grant execute on function public.create_pos_used_device_acquisition_with_document(text, jsonb) to service_role;
grant execute on function public.get_pos_used_device_buyback_documents(text, text, text) to service_role;

comment on table public.pos_used_device_buyback_documents is
  'Immutable signed buyback agreements. The snapshot and PDF hash freeze exactly what the seller signed.';
comment on table public.pos_used_device_document_access_log is
  'Audit trail for staff access to signed buyback agreements and seller ID evidence.';
