-- Monthly sales target per store. Admin sets it on the Sales Overview page; the
-- POS Today card shows it against the store's month-to-date takings, plus the
-- signed-in staff member's points for the month (Google reviews + device and
-- accessory bundles). Takings use the same cash-basis ledger as the admin
-- overview, so "This Month" there and the POS progress always agree.

create table if not exists public.pos_store_sales_targets (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  target_month date not null,
  sales_target numeric(12,2) not null check (sales_target > 0 and sales_target <= 99999999),
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pos_store_sales_targets_first_day_check
    check (target_month = date_trunc('month', target_month)::date),
  constraint pos_store_sales_targets_store_month_unique unique (store_id, target_month)
);

drop trigger if exists pos_store_sales_targets_set_updated_at on public.pos_store_sales_targets;
create trigger pos_store_sales_targets_set_updated_at
before update on public.pos_store_sales_targets
for each row execute function public.set_updated_at();

alter table public.pos_store_sales_targets enable row level security;
revoke all on public.pos_store_sales_targets from public, anon, authenticated;
grant select, insert, update, delete on public.pos_store_sales_targets to service_role;

create or replace function public.pos_store_month_sales_progress(
  target_store_id bigint,
  target_business_date date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  date_value date := coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date);
  month_value date := date_trunc('month', coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date))::date;
  month_end_value date;
  days_left_value integer;
  net_sales_value numeric(12,2) := 0;
  target_row public.pos_store_sales_targets%rowtype;
  remaining_value numeric(12,2);
begin
  month_end_value := (month_value + interval '1 month - 1 day')::date;
  days_left_value := greatest(1, month_end_value - date_value + 1);

  select coalesce(sum(movement.amount), 0)
  into net_sales_value
  from public.pos_takings_line_movements(array[target_store_id], month_value, date_value) movement;

  select * into target_row
  from public.pos_store_sales_targets sales_target_row
  where sales_target_row.store_id = target_store_id
    and sales_target_row.target_month = month_value;

  if target_row.id is not null then
    remaining_value := greatest(0, target_row.sales_target - net_sales_value);
  end if;

  return jsonb_build_object(
    'month', to_char(month_value, 'YYYY-MM'),
    'date_from', month_value,
    'date_to', date_value,
    'days_in_month', extract(day from month_end_value)::integer,
    'days_left', days_left_value,
    'net_sales', net_sales_value,
    'target', target_row.sales_target,
    'remaining', remaining_value,
    'percent', case when target_row.id is not null
      then round(net_sales_value / target_row.sales_target * 100, 1) end,
    'daily_needed', case when target_row.id is not null
      then round(remaining_value / days_left_value, 2) end,
    'updated_by', target_row.updated_by,
    'updated_at', target_row.updated_at
  );
end;
$$;

-- Same rules as the admin staff points report: reviews and paid device +
-- accessory invoices across every store this month.
create or replace function public.pos_staff_month_points(
  target_staff_name text,
  target_business_date date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  staff_key text := lower(trim(coalesce(target_staff_name, '')));
  date_value date := coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date);
  month_value date := date_trunc('month', coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date))::date;
  review_count_value integer := 0;
  review_points_value integer := 0;
  bundle_order_value integer := 0;
  device_value integer := 0;
  accessory_value integer := 0;
  bundle_points_value integer := 0;
begin
  if staff_key = '' then raise exception 'Staff member is required'; end if;

  select count(*)::integer, coalesce(sum(review_event.points), 0)::integer
  into review_count_value, review_points_value
  from public.pos_google_review_events review_event
  where review_event.normalized_staff_name = staff_key
    and review_event.business_date between month_value and date_value;

  select
    coalesce(sum(bundle.bundle_order_count), 0)::integer,
    coalesce(sum(bundle.device_count), 0)::integer,
    coalesce(sum(bundle.accessory_count), 0)::integer,
    coalesce(sum(bundle.bundle_points), 0)::integer
  into bundle_order_value, device_value, accessory_value, bundle_points_value
  from public.store_locations store_location
  cross join lateral public.pos_bundle_score_metrics(store_location.id, month_value, date_value, staff_key) bundle;

  return jsonb_build_object(
    'month', to_char(month_value, 'YYYY-MM'),
    'date_from', month_value,
    'date_to', date_value,
    'google_review_count', review_count_value,
    'google_review_points', review_points_value,
    'bundle_order_count', bundle_order_value,
    'bundle_device_count', device_value,
    'bundle_accessory_count', accessory_value,
    'bundle_points', bundle_points_value,
    'total_points', review_points_value + bundle_points_value
  );
end;
$$;

-- Month figures stay live even after the day's score is finalized.
create or replace function public.pos_today_progress_month_figures(
  target_store_id bigint,
  target_staff_name text,
  target_business_date date
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'monthly_hourly_sales', public.pos_staff_month_hourly_sales(target_staff_name, target_business_date),
    'store_month_sales', public.pos_store_month_sales_progress(target_store_id, target_business_date),
    'staff_month_points', public.pos_staff_month_points(target_staff_name, target_business_date)
  );
$$;

create or replace function public.get_pos_today_progress(
  session_token text,
  target_store_code text,
  target_staff_name text,
  target_business_date date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  staff_value text := trim(coalesce(target_staff_name, ''));
  date_value date := coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date);
  finalized_result public.pos_daily_target_results%rowtype;
  has_open_shift boolean := false;
  progress_payload jsonb;
  month_figures jsonb;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if staff_value = '' then raise exception 'Staff member is required'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  month_figures := public.pos_today_progress_month_figures(selected_store.id, staff_value, date_value);

  select exists (
    select 1
    from public.pos_store_shifts shift_record
    where shift_record.store_id = selected_store.id
      and shift_record.business_date = date_value
      and shift_record.status = 'open'
  ) into has_open_shift;

  if not has_open_shift then
    select * into finalized_result
    from public.pos_daily_target_results result
    where result.store_id = selected_store.id
      and result.business_date = date_value
      and result.normalized_staff_name = lower(staff_value)
    order by result.finalized_at desc
    limit 1;

    if found then
      return finalized_result.progress_payload || jsonb_build_object(
        'status', 'finalized',
        'finalized_at', finalized_result.finalized_at,
        'finalized_by', finalized_result.finalized_by,
        'shift_code', finalized_result.shift_code
      ) || month_figures;
    end if;
  end if;

  progress_payload := public.pos_today_progress_payload(selected_store.id, date_value, staff_value);
  return progress_payload || jsonb_build_object('status', 'projected') || month_figures;
end;
$$;

-- The review response replaces the POS card, so it carries the month figures
-- too (the new review is already in the month total).
create or replace function public.record_pos_google_review(
  session_token text,
  target_store_code text,
  target_staff_name text,
  event_code text,
  customer_name text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  date_value date := (now() at time zone 'Australia/Brisbane')::date;
  event_code_value text := trim(coalesce(event_code, ''));
  customer_value text := trim(coalesce(record_pos_google_review.customer_name, ''));
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if event_code_value = '' then raise exception 'Review event id is required'; end if;
  if customer_value = '' then raise exception 'Customer name is required for a Google review'; end if;
  if length(customer_value) > 120 then raise exception 'Customer name is too long'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true
    and lower(trim(staff.display_name)) = lower(trim(coalesce(target_staff_name, '')))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  if not exists (
    select 1 from public.pos_store_shifts shift_record
    where shift_record.store_id = selected_store.id
      and shift_record.business_date = date_value
      and shift_record.status = 'open'
  ) then
    raise exception 'Google reviews can only be recorded during an open shift';
  end if;

  if exists (
    select 1 from public.pos_daily_target_results result
    where result.store_id = selected_store.id
      and result.business_date = date_value
      and result.normalized_staff_name = lower(trim(selected_staff.display_name))
  ) then
    raise exception 'Today score has already been finalized';
  end if;

  insert into public.pos_google_review_events (
    event_code, store_id, business_date, staff_name, points, customer_name
  ) values (
    event_code_value, selected_store.id, date_value, selected_staff.display_name, 5, customer_value
  )
  on conflict on constraint pos_google_review_events_event_code_key do nothing;

  return public.pos_today_progress_payload(selected_store.id, date_value, selected_staff.display_name)
    || public.pos_today_progress_month_figures(selected_store.id, selected_staff.display_name, date_value);
end;
$$;

create or replace function public.get_admin_store_sales_targets(
  session_token text,
  target_month_start date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  today_value date := (now() at time zone 'Australia/Brisbane')::date;
  month_value date := date_trunc('month', coalesce(target_month_start, (now() at time zone 'Australia/Brisbane')::date))::date;
  month_end_value date;
  sales_to_value date;
  result_payload jsonb;
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  month_end_value := (month_value + interval '1 month - 1 day')::date;
  sales_to_value := least(month_end_value, today_value);

  with selected_stores as materialized (
    select
      store_location.id,
      store_location.store_code,
      store_location.store_name,
      coalesce(array_position(array['parkridge','fairfield','northlakes','toowong','brassall']::text[], store_location.store_code), 99) as display_order
    from public.store_locations store_location
    where store_location.active
      and store_location.store_code <> 'warehouse'
  ),
  -- A future month has no takings yet; the ledger returns nothing when
  -- the start date is after the end date.
  store_sales as (
    select movement.store_id, coalesce(sum(movement.amount), 0)::numeric(12,2) as net_sales
    from public.pos_takings_line_movements(array(select selected_store.id from selected_stores selected_store), month_value, sales_to_value) movement
    group by movement.store_id
  )
  select jsonb_build_object(
    'ok', true,
    'month', to_char(month_value, 'YYYY-MM'),
    'month_start', month_value,
    'month_end', month_end_value,
    'sales_to', case when sales_to_value >= month_value then sales_to_value end,
    'days_in_month', extract(day from month_end_value)::integer,
    'days_elapsed', greatest(0, sales_to_value - month_value + 1),
    'stores', coalesce(jsonb_agg(jsonb_build_object(
      'store_code', selected_store.store_code,
      'store_name', selected_store.store_name,
      'sales_target', sales_target_row.sales_target,
      'net_sales', coalesce(store_sale.net_sales, 0),
      'updated_by', sales_target_row.updated_by,
      'updated_at', sales_target_row.updated_at
    ) order by selected_store.display_order, selected_store.store_name), '[]'::jsonb)
  )
  into result_payload
  from selected_stores selected_store
  left join store_sales store_sale on store_sale.store_id = selected_store.id
  left join public.pos_store_sales_targets sales_target_row
    on sales_target_row.store_id = selected_store.id
   and sales_target_row.target_month = month_value;

  return result_payload;
end;
$$;

-- An empty or zero amount removes the store's target for that month.
create or replace function public.set_admin_store_sales_target(
  session_token text,
  target_store_code text,
  target_month_start date,
  target_amount numeric
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  month_value date;
  amount_value numeric(12,2) := round(target_amount, 2);
  actor_value text;
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  if target_month_start is null then raise exception 'Month is required'; end if;
  if amount_value < 0 then raise exception 'Target cannot be negative'; end if;
  if amount_value > 99999999 then raise exception 'Target is too large'; end if;
  month_value := date_trunc('month', target_month_start)::date;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  actor_value := coalesce(nullif(trim(public.admin_session_actor_name(session_token)), ''), 'Admin portal');

  if coalesce(amount_value, 0) = 0 then
    delete from public.pos_store_sales_targets sales_target_row
    where sales_target_row.store_id = selected_store.id
      and sales_target_row.target_month = month_value;
  else
    insert into public.pos_store_sales_targets (store_id, target_month, sales_target, updated_by)
    values (selected_store.id, month_value, amount_value, actor_value)
    on conflict on constraint pos_store_sales_targets_store_month_unique
    do update set sales_target = excluded.sales_target, updated_by = excluded.updated_by;
  end if;

  return public.get_admin_store_sales_targets(session_token, month_value);
end;
$$;

revoke all on function public.pos_store_month_sales_progress(bigint, date) from public, anon, authenticated;
revoke all on function public.pos_staff_month_points(text, date) from public, anon, authenticated;
revoke all on function public.pos_today_progress_month_figures(bigint, text, date) from public, anon, authenticated;
grant execute on function public.pos_store_month_sales_progress(bigint, date) to service_role;
grant execute on function public.pos_staff_month_points(text, date) to service_role;
grant execute on function public.pos_today_progress_month_figures(bigint, text, date) to service_role;

-- Admin RPCs are called from the browser with the anon key and gated on the
-- admin session, like get_admin_sales_overview.
revoke all on function public.get_admin_store_sales_targets(text, date) from public;
revoke all on function public.set_admin_store_sales_target(text, text, date, numeric) from public;
grant execute on function public.get_admin_store_sales_targets(text, date) to anon, authenticated, service_role;
grant execute on function public.set_admin_store_sales_target(text, text, date, numeric) to anon, authenticated, service_role;
