-- What a device was like when it was bought is a record, not a draft.
--
-- The inspection answered at the counter lived in the same column the shop
-- floor kept editing afterwards, so "touch: fail" at purchase could become
-- "touch: pass" a week later and the purchase record silently changed with it.
-- The same inspection then decided whether the device could be sold, so the
-- only way to sell a repaired device was to rewrite what it had been bought as.
--
-- Two records now, with two jobs:
--
--   at purchase   - the inspection, battery health and condition recorded at
--                   the counter. Locked by trigger the moment the row exists;
--                   nothing, including the owner, can rewrite it.
--   pre-sale test - a fresh run of the same checklist once the device has been
--                   cleaned up or repaired. Append-only: every run is kept, and
--                   the latest one is what decides whether it can be sold and
--                   what the website says about it.
--
-- A listed device that fails a retest is taken off sale in the same step.
--
-- Function bodies are normalised to LF before patching, because these bodies
-- carry a mix of CRLF and LF from earlier edits.

-- 1. The purchase-time battery and condition, next to the purchase inspection.
alter table public.pos_used_devices
  add column if not exists intake_battery_health integer
    check (intake_battery_health is null or intake_battery_health between 0 and 100),
  add column if not exists intake_condition_grade text
    check (intake_condition_grade is null or intake_condition_grade in ('As New', 'Good', 'Fair', 'Poor', 'Faulty'));

-- Existing devices: where a later correction is on the ledger, its "previous"
-- value is what the device was bought as. Otherwise the current value is the
-- best record there is.
update public.pos_used_devices device
set intake_battery_health = coalesce(
      (select (ledger.transaction_payload->>'previous_battery_health')::integer
       from public.pos_used_device_transactions ledger
       where ledger.device_id = device.id
         and ledger.transaction_type = 'detail_change'
         and ledger.transaction_payload ? 'previous_battery_health'
       order by ledger.created_at, ledger.id
       limit 1),
      device.battery_health),
    intake_condition_grade = coalesce(
      (select ledger.transaction_payload->>'previous_condition_grade'
       from public.pos_used_device_transactions ledger
       where ledger.device_id = device.id
         and ledger.transaction_type = 'detail_change'
         and ledger.transaction_payload ? 'previous_condition_grade'
       order by ledger.created_at, ledger.id
       limit 1),
      device.condition_grade)
where device.intake_condition_grade is null;

-- 2. The lock. It sits on the table rather than in any one function, so no
--    code path -- present or future -- can rewrite the purchase record.
create or replace function public.lock_pos_used_device_intake_record()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.intake_battery_health := new.battery_health;
    new.intake_condition_grade := new.condition_grade;
    return new;
  end if;
  if new.inspection is distinct from old.inspection
    or new.intake_battery_health is distinct from old.intake_battery_health
    or new.intake_condition_grade is distinct from old.intake_condition_grade then
    raise exception 'What a device was like when it was bought is locked. Record a pre-sale test instead';
  end if;
  return new;
end;
$$;

drop trigger if exists pos_used_devices_lock_intake_record on public.pos_used_devices;
create trigger pos_used_devices_lock_intake_record
before insert or update on public.pos_used_devices
for each row execute function public.lock_pos_used_device_intake_record();

comment on column public.pos_used_devices.inspection is
  'The inspection recorded at purchase. Locked by pos_used_devices_lock_intake_record; sellability comes from pos_used_device_sale_tests.';

-- 3. Pre-sale test runs.
alter table public.pos_used_device_transactions
  drop constraint if exists pos_used_device_transactions_transaction_type_check;

alter table public.pos_used_device_transactions
  add constraint pos_used_device_transactions_transaction_type_check
  check (transaction_type in (
    'acquisition', 'status_change', 'price_change', 'sale', 'refund_return',
    'returned_to_seller', 'disposal', 'detail_change', 'transfer_out',
    'transfer_in', 'transfer_cancelled', 'sale_test'
  ));

create table if not exists public.pos_used_device_sale_tests (
  id bigint generated by default as identity primary key,
  test_code text not null unique,
  device_id bigint not null references public.pos_used_devices(id) on delete restrict,
  answers jsonb not null check (jsonb_typeof(answers) = 'object'),
  battery_health integer check (battery_health is null or battery_health between 0 and 100),
  notes text not null default '' check (length(notes) <= 1000),
  passed boolean not null,
  failed_count integer not null default 0,
  tested_by text not null,
  tested_by_admin boolean not null default false,
  tested_at timestamptz not null default now()
);

create index if not exists pos_used_device_sale_tests_device_idx
  on public.pos_used_device_sale_tests (device_id, tested_at desc, id desc);

alter table public.pos_used_device_sale_tests enable row level security;
revoke all on public.pos_used_device_sale_tests from public, anon, authenticated;
grant select, insert on public.pos_used_device_sale_tests to service_role;

comment on table public.pos_used_device_sale_tests is
  'Pre-sale test runs, append-only. The latest run for a device decides whether it can be sold.';

create or replace function public.pos_used_device_latest_sale_test_answers(target_device_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select test.answers
    from public.pos_used_device_sale_tests test
    where test.device_id = target_device_id
    order by test.tested_at desc, test.id desc
    limit 1
  ), '{}'::jsonb);
$$;

-- Re-evaluated against today's checklist, so a check added after the test was
-- run is still asked for.
create or replace function public.pos_used_device_sale_test_passed(target_device_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.pos_used_device_sale_tests test where test.device_id = target_device_id
  ) and public.pos_used_device_inspection_complete(
    (select device.category from public.pos_used_devices device where device.id = target_device_id),
    public.pos_used_device_latest_sale_test_answers(target_device_id)
  );
$$;

revoke all on function public.pos_used_device_latest_sale_test_answers(bigint) from public, anon, authenticated;
revoke all on function public.pos_used_device_sale_test_passed(bigint) from public, anon, authenticated;
grant execute on function public.pos_used_device_latest_sale_test_answers(bigint) to service_role;
grant execute on function public.pos_used_device_sale_test_passed(bigint) to service_role;

-- 4. Reading and recording tests. Staff for their own store, admin for any,
--    through the same authorisation the device photos use.
create or replace function public.get_pos_used_device_sale_tests(
  session_token text,
  target_store_code text,
  target_device_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  device_row public.pos_used_devices%rowtype;
  checklist_payload jsonb;
  tests_payload jsonb;
begin
  context := public.authorize_pos_used_device_evidence(session_token, target_store_code, target_device_code);
  select * into device_row from public.pos_used_devices where id = (context->>'device_id')::bigint;

  select coalesce(jsonb_agg(jsonb_build_object('key', item.item_key, 'label', item.label)
    order by item.position, item.id), '[]'::jsonb) into checklist_payload
  from public.pos_used_device_inspection_items item
  where item.active and item.category = device_row.category;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', test.test_code,
    'answers', test.answers,
    'battery_health', test.battery_health,
    'notes', test.notes,
    'passed', test.passed,
    'failed_count', test.failed_count,
    'tested_by', test.tested_by,
    'tested_by_admin', test.tested_by_admin,
    'tested_at', test.tested_at
  ) order by test.tested_at desc, test.id desc), '[]'::jsonb) into tests_payload
  from public.pos_used_device_sale_tests test
  where test.device_id = device_row.id;

  return jsonb_build_object(
    'ok', true,
    'device_code', device_row.device_code,
    'category', device_row.category,
    'status', device_row.status,
    'checklist', checklist_payload,
    'intake', jsonb_build_object(
      'inspection', device_row.inspection,
      'battery_health', device_row.intake_battery_health,
      'condition_grade', device_row.intake_condition_grade,
      'acquired_at', device_row.acquired_at,
      'acquired_by', device_row.acquired_by
    ),
    'tests', tests_payload,
    'passed', public.pos_used_device_sale_test_passed(device_row.id),
    'writable', device_row.status in ('inspection', 'ready_for_sale')
  );
end;
$$;

create or replace function public.record_pos_used_device_sale_test(
  session_token text,
  target_store_code text,
  target_device_code text,
  payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  device_row public.pos_used_devices%rowtype;
  checklist_row record;
  answer_value text;
  answers_value jsonb := '{}'::jsonb;
  missing_count integer := 0;
  failed_count_value integer := 0;
  passed_value boolean;
  battery_value integer;
  notes_value text := trim(coalesce(payload->>'notes', ''));
  test_code_value text := 'TEST-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12));
  actor_name text;
  withdrawn boolean := false;
  previous_battery integer;
begin
  context := public.authorize_pos_used_device_evidence(session_token, target_store_code, target_device_code);
  actor_name := coalesce(nullif(context->>'author', ''), 'Staff');

  select * into device_row from public.pos_used_devices
  where id = (context->>'device_id')::bigint
  for update;
  if device_row.status not in ('inspection', 'ready_for_sale') then
    raise exception 'Only a device that is in stock can be tested';
  end if;
  if jsonb_typeof(payload->'answers') is distinct from 'object' then
    raise exception 'Record an answer for every check';
  end if;
  if length(notes_value) > 1000 then raise exception 'The test notes are too long'; end if;

  begin
    battery_value := nullif(trim(coalesce(payload->>'battery_health', '')), '')::integer;
  exception when invalid_text_representation then
    raise exception 'Battery health is a number from 0 to 100';
  end;
  if battery_value is not null and (battery_value < 0 or battery_value > 100) then
    raise exception 'Battery health is a number from 0 to 100';
  end if;

  -- A test is a complete run of today's checklist. Keys that are not on it
  -- are dropped rather than stored.
  for checklist_row in
    select item.item_key
    from public.pos_used_device_inspection_items item
    where item.active and item.category = device_row.category
    order by item.position, item.id
  loop
    answer_value := lower(coalesce(payload->'answers'->>checklist_row.item_key, ''));
    if answer_value not in ('pass', 'fail', 'na') then
      missing_count := missing_count + 1;
    else
      answers_value := answers_value || jsonb_build_object(checklist_row.item_key, answer_value);
      if answer_value = 'fail' then failed_count_value := failed_count_value + 1; end if;
    end if;
  end loop;
  if missing_count > 0 then
    raise exception '% check% still to answer. Every check needs Pass, Fail or N/A',
      missing_count, case when missing_count = 1 then ' is' else 's are' end;
  end if;
  passed_value := failed_count_value = 0;

  insert into public.pos_used_device_sale_tests (
    test_code, device_id, answers, battery_health, notes, passed, failed_count,
    tested_by, tested_by_admin
  ) values (
    test_code_value, device_row.id, answers_value, battery_value, notes_value, passed_value,
    failed_count_value, actor_name, coalesce((context->>'is_admin')::boolean, false)
  );

  -- The battery measured now is what a buyer gets, so it becomes the device's
  -- current reading. The purchase-time reading stays in intake_battery_health.
  previous_battery := device_row.battery_health;
  if battery_value is not null and battery_value is distinct from previous_battery then
    update public.pos_used_devices
    set battery_health = battery_value, updated_by = actor_name
    where id = device_row.id;
  end if;

  -- Something on the shelf that no longer passes is not for sale.
  if not passed_value and device_row.status = 'ready_for_sale' then
    update public.pos_used_devices
    set status = 'inspection', updated_by = actor_name
    where id = device_row.id;
    withdrawn := true;
    insert into public.pos_used_device_transactions (
      transaction_code, device_id, store_id, transaction_type, from_status, to_status,
      amount, staff_name, notes, transaction_payload
    ) values (
      'UDTX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)),
      device_row.id, device_row.store_id, 'status_change', 'ready_for_sale', 'inspection',
      0, actor_name, 'Taken off sale: failed its pre-sale retest',
      jsonb_build_object('test_code', test_code_value)
    );
  end if;

  insert into public.pos_used_device_transactions (
    transaction_code, device_id, store_id, transaction_type, from_status, to_status,
    amount, staff_name, notes, transaction_payload
  ) values (
    'UDTX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)),
    device_row.id, device_row.store_id, 'sale_test', device_row.status,
    case when withdrawn then 'inspection' else device_row.status end,
    0, actor_name,
    case when passed_value then 'Pre-sale test passed'
      else format('Pre-sale test failed: %s check%s', failed_count_value,
        case when failed_count_value = 1 then '' else 's' end) end,
    jsonb_strip_nulls(jsonb_build_object(
      'test_code', test_code_value,
      'passed', passed_value,
      'failed_count', failed_count_value,
      'battery_health', battery_value,
      'previous_battery_health', case when battery_value is distinct from previous_battery then previous_battery end
    ))
  );

  return jsonb_build_object(
    'ok', true,
    'test_code', test_code_value,
    'passed', passed_value,
    'failed_count', failed_count_value,
    'withdrawn', withdrawn
  );
end;
$$;

revoke all on function public.get_pos_used_device_sale_tests(text, text, text) from public;
revoke all on function public.record_pos_used_device_sale_test(text, text, text, jsonb) from public;
grant execute on function public.get_pos_used_device_sale_tests(text, text, text) to anon, authenticated, service_role;
grant execute on function public.record_pos_used_device_sale_test(text, text, text, jsonb) to anon, authenticated, service_role;

comment on function public.get_pos_used_device_sale_tests(text, text, text) is
  'The locked purchase-time inspection and every pre-sale test run for one device. Staff for their own store, admin for any.';
comment on function public.record_pos_used_device_sale_test(text, text, text, jsonb) is
  'Records one complete pre-sale test run. Never touches the purchase-time inspection; takes a listed device off sale when it fails.';

-- 5. The shop floor can no longer rewrite the purchase inspection, and
--    "ready for sale" now means "passed its pre-sale test".
do $migration$
declare
  definition text;
  patched text;
  previous text;
begin
  select replace(pg_get_functiondef(oid), chr(13), '') into definition
  from pg_proc
  where proname = 'update_pos_used_device' and pronamespace = 'public'::regnamespace;
  if definition is null then raise exception 'update_pos_used_device was not found'; end if;

  patched := definition;

  previous := patched;
  patched := replace(
    patched,
    $anchor$  inspection_value := case
    when jsonb_typeof(payload->'inspection') = 'object' then payload->'inspection'
    else device_row.inspection
  end;$anchor$,
    $replacement$  -- The purchase inspection is locked; a caller cannot replace it here.
  inspection_value := device_row.inspection;$replacement$
  );
  if patched = previous then
    raise exception 'pre-sale test patch: the inspection assignment anchor was not found';
  end if;

  previous := patched;
  patched := replace(
    patched,
    $anchor$    or not public.pos_used_device_inspection_complete(device_row.category, inspection_value)$anchor$,
    $replacement$    or not public.pos_used_device_sale_test_passed(device_row.id)$replacement$
  );
  if patched = previous then
    raise exception 'pre-sale test patch: the ready gate anchor was not found';
  end if;

  previous := patched;
  patched := replace(
    patched,
    $anchor$'Device cannot be marked ready until all checks pass'$anchor$,
    $replacement$'Device cannot be marked ready until it passes a pre-sale test and the lock, data and stolen checks are done'$replacement$
  );
  if patched = previous then
    raise exception 'pre-sale test patch: the ready message anchor was not found';
  end if;

  execute patched;
end;
$migration$;

-- 6. What stands between a device and the website, reading the pre-sale test.
create or replace function public.pos_used_device_listing_blockers(target_device_id bigint)
returns text[]
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  device_row public.pos_used_devices%rowtype;
  blockers text[] := array[]::text[];
  latest_answers jsonb;
  outstanding integer;
begin
  select * into device_row from public.pos_used_devices where id = target_device_id;
  if not found then return array['This device no longer exists']; end if;
  if device_row.status = 'sold' then return array['This device has been sold']; end if;
  if device_row.status in ('returned_to_seller', 'disposed') then
    return array['This device is closed and no longer in stock'];
  end if;

  if not exists (select 1 from public.pos_used_device_sale_tests test where test.device_id = device_row.id) then
    blockers := array_append(blockers, 'No pre-sale test has been recorded yet');
  else
    latest_answers := public.pos_used_device_latest_sale_test_answers(device_row.id);
    select count(*) into outstanding
    from public.pos_used_device_inspection_items item
    where item.active
      and item.category = device_row.category
      and lower(coalesce(latest_answers->>item.item_key, '')) not in ('pass', 'na');
    if outstanding > 0 then
      blockers := array_append(blockers, format('The latest pre-sale test has %s check%s not passed', outstanding,
        case when outstanding = 1 then '' else 's' end));
    end if;
  end if;

  if device_row.clean_check_status not in ('Clean', 'Not Applicable') then
    blockers := array_append(blockers, format('The lost or stolen check is still %s', lower(device_row.clean_check_status)));
  end if;
  if not device_row.activation_lock_removed then
    blockers := array_append(blockers, 'Activation locks are not confirmed removed');
  end if;
  if not device_row.data_erased_confirmed then
    blockers := array_append(blockers, 'Customer data is not confirmed erased');
  end if;
  if device_row.evidence_required and not exists (
    select 1 from public.pos_used_device_updates entry
    where entry.device_id = device_row.id and entry.kind = 'photo' and entry.stage = 'listing'
  ) then
    blockers := array_append(blockers, 'No listing photo has been added');
  end if;

  return blockers;
end;
$$;

-- 7. The website says how many checks the device passed before sale, not what
--    it was like when it came in.
do $migration$
declare
  definition text;
  patched text;
begin
  select replace(pg_get_functiondef(oid), chr(13), '') into definition
  from pg_proc
  where proname = 'pos_used_device_listing_payload' and pronamespace = 'public'::regnamespace;
  if definition is null then raise exception 'pos_used_device_listing_payload was not found'; end if;

  patched := replace(
    definition,
    $anchor$    and lower(coalesce(device_row.inspection->>item.item_key, '')) = 'pass';$anchor$,
    $replacement$    and lower(coalesce(public.pos_used_device_latest_sale_test_answers(device_row.id)->>item.item_key, '')) = 'pass';$replacement$
  );
  if patched = definition then
    raise exception 'pre-sale test patch: the listing payload anchor was not found';
  end if;

  execute patched;
end;
$migration$;

-- 8. Both device views carry the purchase-time battery and condition beside
--    the current ones.
do $migration$
declare
  fn text;
  definition text;
  patched text;
begin
  foreach fn in array array['pos_used_device_payload', 'get_admin_used_device_detail'] loop
    select replace(pg_get_functiondef(oid), chr(13), '') into definition
    from pg_proc
    where proname = fn and pronamespace = 'public'::regnamespace;
    if definition is null then raise exception '% was not found', fn; end if;

    patched := replace(
      definition,
      $anchor$'battery_health', device_row.battery_health,$anchor$,
      $replacement$'battery_health', device_row.battery_health,
      'intake_battery_health', device_row.intake_battery_health,
      'intake_condition_grade', device_row.intake_condition_grade,$replacement$
    );
    if patched = definition then
      raise exception 'pre-sale test patch: the % battery anchor was not found', fn;
    end if;
    execute patched;
  end loop;
end;
$migration$;
