alter table public.pos_customers
  alter column store_id drop not null;

alter table public.pos_customers
  add column if not exists source_system text not null default 'pos',
  add column if not exists source_store_name text not null default '',
  add column if not exists source_customer_code text not null default '',
  add column if not exists address1 text not null default '',
  add column if not exists address2 text not null default '',
  add column if not exists postcode text not null default '',
  add column if not exists city text not null default '',
  add column if not exists state text not null default '',
  add column if not exists country text not null default '',
  add column if not exists driving_licence text not null default '',
  add column if not exists referred_by text not null default '',
  add column if not exists contact_person text not null default '',
  add column if not exists legacy_ticket_count integer not null default 0,
  add column if not exists legacy_tickets_amount numeric(14, 2) not null default 0,
  add column if not exists legacy_amount_receivable numeric(14, 2) not null default 0;

create table if not exists public.pos_customer_sources (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.pos_customers(id) on delete cascade,
  source_system text not null,
  source_store_name text not null default '',
  source_customer_code text not null,
  source_payload jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  unique (source_system, source_store_name, source_customer_code)
);

create index if not exists pos_customers_global_name_idx
on public.pos_customers (lower(first_name), lower(last_name))
where active = true;

create index if not exists pos_customers_global_phone_idx
on public.pos_customers (normalized_phone)
where active = true and normalized_phone <> '';

create index if not exists pos_customers_global_email_idx
on public.pos_customers (lower(email))
where active = true and email <> '';

create index if not exists pos_customer_sources_customer_idx
on public.pos_customer_sources (customer_id);

create index if not exists pos_customer_sources_code_idx
on public.pos_customer_sources (source_customer_code);

alter table public.pos_customer_sources enable row level security;

revoke all on public.pos_customer_sources from public, anon, authenticated;
grant select, insert, update, delete on public.pos_customer_sources to service_role;

create or replace function public.pos_customer_payload(customer_row public.pos_customers)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', customer_row.customer_code,
    'first_name', customer_row.first_name,
    'last_name', customer_row.last_name,
    'company', customer_row.company,
    'phone', customer_row.phone,
    'alert_number', customer_row.alert_number,
    'email', customer_row.email,
    'group', customer_row.customer_group,
    'notes', customer_row.notes,
    'address1', customer_row.address1,
    'address2', customer_row.address2,
    'postcode', customer_row.postcode,
    'city', customer_row.city,
    'state', customer_row.state,
    'country', customer_row.country,
    'created_by', customer_row.created_by,
    'updated_by', customer_row.updated_by,
    'created_at', customer_row.created_at,
    'updated_at', customer_row.updated_at
  );
$$;

create or replace function public.search_pos_customers(
  session_token text,
  target_store_code text,
  search_query text default '',
  result_limit integer default 100
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  customers_payload jsonb;
  query_value text := trim(coalesce(search_query, ''));
  query_lower text := lower(trim(coalesce(search_query, '')));
  phone_query text := regexp_replace(coalesce(search_query, ''), '[^0-9]', '', 'g');
  safe_limit integer := least(greatest(coalesce(result_limit, 100), 1), 500);
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select coalesce(jsonb_agg(
    public.pos_customer_payload(customer.customer_row)
    order by customer.search_rank,
      (customer.customer_row).first_name,
      (customer.customer_row).last_name,
      (customer.customer_row).updated_at desc
  ), '[]'::jsonb)
  into customers_payload
  from (
    select customer as customer_row,
      case
        when query_value = '' then 10
        when lower(concat_ws(' ', customer.first_name, customer.last_name)) = query_lower then 0
        when phone_query <> '' and customer.normalized_phone = phone_query then 0
        when lower(customer.email) = query_lower then 0
        when lower(concat_ws(' ', customer.first_name, customer.last_name)) like query_lower || '%' then 1
        when phone_query <> '' and customer.normalized_phone like phone_query || '%' then 1
        else 2
      end as search_rank
    from public.pos_customers customer
    where customer.active = true
      and (
        query_value = ''
        or customer.first_name ilike '%' || query_value || '%'
        or customer.last_name ilike '%' || query_value || '%'
        or concat_ws(' ', customer.first_name, customer.last_name) ilike '%' || query_value || '%'
        or customer.company ilike '%' || query_value || '%'
        or customer.phone ilike '%' || query_value || '%'
        or customer.alert_number ilike '%' || query_value || '%'
        or customer.email ilike '%' || query_value || '%'
        or customer.customer_code ilike '%' || query_value || '%'
        or (phone_query <> '' and customer.normalized_phone like '%' || phone_query || '%')
        or exists (
          select 1
          from public.pos_customer_sources source
          where source.customer_id = customer.id
            and source.source_customer_code ilike '%' || query_value || '%'
        )
      )
    order by search_rank, customer.first_name, customer.last_name, customer.updated_at desc
    limit safe_limit
  ) customer;

  return jsonb_build_object('ok', true, 'customers', customers_payload);
end;
$$;

create or replace function public.upsert_pos_customer(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  customer_row public.pos_customers%rowtype;
  customer_code_value text;
  first_name_value text := coalesce(trim(payload->>'first_name'), '');
  phone_value text := coalesce(trim(payload->>'phone'), '');
  alert_value text := coalesce(trim(payload->>'alert_number'), '');
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if jsonb_typeof(payload) <> 'object' then raise exception 'Customer payload must be an object'; end if;
  if first_name_value = '' then raise exception 'First name is required'; end if;
  if phone_value = '' and alert_value = '' then raise exception 'At least one phone number is required'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(payload->>'store_code'), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  customer_code_value := coalesce(nullif(trim(payload->>'id'), ''), 'CUS-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint);

  select * into customer_row
  from public.pos_customers customer
  where customer.customer_code = customer_code_value
  for update;

  if found then
    update public.pos_customers
    set
      first_name = first_name_value,
      last_name = coalesce(trim(payload->>'last_name'), ''),
      company = coalesce(trim(payload->>'company'), ''),
      phone = phone_value,
      normalized_phone = regexp_replace(phone_value, '[^0-9]', '', 'g'),
      alert_number = alert_value,
      email = lower(coalesce(trim(payload->>'email'), '')),
      customer_group = coalesce(nullif(trim(payload->>'group'), ''), 'Regular Customer'),
      notes = coalesce(trim(payload->>'notes'), ''),
      updated_by = selected_staff.display_name,
      active = true
    where customer_code = customer_code_value
    returning * into customer_row;
  else
    insert into public.pos_customers (
      customer_code, store_id, first_name, last_name, company, phone, normalized_phone,
      alert_number, email, customer_group, notes, created_by, updated_by
    ) values (
      customer_code_value, selected_store.id, first_name_value,
      coalesce(trim(payload->>'last_name'), ''), coalesce(trim(payload->>'company'), ''),
      phone_value, regexp_replace(phone_value, '[^0-9]', '', 'g'), alert_value,
      lower(coalesce(trim(payload->>'email'), '')),
      coalesce(nullif(trim(payload->>'group'), ''), 'Regular Customer'),
      coalesce(trim(payload->>'notes'), ''), selected_staff.display_name, selected_staff.display_name
    ) returning * into customer_row;
  end if;

  return jsonb_build_object('ok', true, 'customer', public.pos_customer_payload(customer_row));
end;
$$;

revoke execute on function public.pos_customer_payload(public.pos_customers) from public, anon, authenticated;
revoke execute on function public.search_pos_customers(text, text, text, integer) from public;
revoke execute on function public.upsert_pos_customer(text, jsonb) from public;

grant execute on function public.search_pos_customers(text, text, text, integer) to anon, authenticated, service_role;
grant execute on function public.upsert_pos_customer(text, jsonb) to anon, authenticated, service_role;

comment on table public.pos_customer_sources is
  'Protected source records for imported customer masters. Browser roles cannot read this table.';

comment on column public.pos_customers.store_id is
  'Home or creation store only. Customer records are shared across all active POS stores.';
