-- Link NL sales lines to the existing North Lakes LCD tracker.
create table if not exists public.nl_accessory_names (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.store_locations(id) on delete cascade,
  name text not null,
  normalized_name text not null,
  active boolean not null default true,
  saved_by_staff_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nl_accessory_names_name_check check (length(trim(name)) between 1 and 160),
  constraint nl_accessory_names_normalized_name_check check (length(trim(normalized_name)) between 1 and 160),
  constraint nl_accessory_names_unique unique (store_id, normalized_name)
);

drop trigger if exists nl_accessory_names_set_updated_at on public.nl_accessory_names;
create trigger nl_accessory_names_set_updated_at
before update on public.nl_accessory_names
for each row execute function public.set_updated_at();

alter table public.nl_accessory_names enable row level security;

drop policy if exists nl_accessory_names_no_direct_access on public.nl_accessory_names;
create policy nl_accessory_names_no_direct_access
on public.nl_accessory_names
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.nl_accessory_names from anon, authenticated;

alter table public.nl_sales_items
  add column if not exists category text not null default 'accessory',
  add column if not exists lcd_inventory_item_id bigint references public.lcd_inventory_items(id),
  add column if not exists lcd_model_name text not null default '',
  add column if not exists lcd_variant_name text not null default '',
  add column if not exists stock_action text not null default '',
  add column if not exists stock_before integer,
  add column if not exists stock_after integer;

alter table public.nl_sales_items
  drop constraint if exists nl_sales_items_category_check,
  add constraint nl_sales_items_category_check
    check (category in ('accessory', 'repair')),
  drop constraint if exists nl_sales_items_stock_action_check,
  add constraint nl_sales_items_stock_action_check
    check (stock_action in ('', 'sold', 'send_to_other', 'faulty', 'broken')),
  drop constraint if exists nl_sales_items_repair_fields_check,
  add constraint nl_sales_items_repair_fields_check
    check (
      (category = 'accessory' and lcd_inventory_item_id is null and stock_action = '')
      or
      (category = 'repair' and lcd_inventory_item_id is not null
        and length(trim(lcd_model_name)) > 0
        and length(trim(lcd_variant_name)) > 0
        and stock_action in ('sold', 'send_to_other', 'faulty', 'broken'))
    ),
  drop constraint if exists nl_sales_items_stock_snapshot_check,
  add constraint nl_sales_items_stock_snapshot_check
    check (
      (stock_before is null and stock_after is null)
      or
      (stock_before is not null and stock_after is not null
        and stock_before >= 0 and stock_after >= 0 and stock_after <= stock_before)
    );

create index if not exists nl_sales_items_lcd_inventory_item_idx
on public.nl_sales_items (lcd_inventory_item_id)
where lcd_inventory_item_id is not null;

create or replace function public.get_nl_sales_report_json(target_report_id bigint)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', report.id,
    'report_date', report.report_date,
    'store_name', report.store_name,
    'status', report.status,
    'started_by_staff_name', report.started_by_staff_name,
    'submitted_by_staff_name', report.submitted_by_staff_name,
    'submitted_at', report.submitted_at,
    'confirmed_at', report.confirmed_at,
    'settled_at', report.settled_at,
    'updated_at', report.updated_at,
    'sales_total_inc_gst', coalesce((
      select round(sum(item.sale_unit_price_inc_gst * item.quantity), 2)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
    ), 0),
    'sales_gst', coalesce((
      select round(sum(item.sale_unit_price_inc_gst * item.quantity) / 11, 2)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
    ), 0),
    'payable_total_inc_gst', coalesce((
      select round(sum(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity), 2)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
        and item.cost_unit_price_ex_gst is not null
    ), 0),
    'payable_cost_ex_gst', coalesce((
      select round(sum(item.cost_unit_price_ex_gst * item.quantity), 2)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
        and item.cost_unit_price_ex_gst is not null
    ), 0),
    'payable_gst', coalesce((
      select round(sum(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity) / 11, 2)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
        and item.cost_unit_price_ex_gst is not null
    ), 0),
    'pending_cost_count', (
      select count(*)
      from public.nl_sales_items item
      where item.report_id = report.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
        and item.cost_unit_price_ex_gst is null
    ),
    'stock_adjustment_count', (
      select count(*)
      from public.nl_sales_items item
      where item.report_id = report.id
        and item.category = 'repair'
        and item.stock_action <> 'sold'
    ),
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', item.id,
        'line_order', item.line_order,
        'category', item.category,
        'product_name', item.product_name,
        'quantity', item.quantity,
        'sale_unit_price_inc_gst', item.sale_unit_price_inc_gst,
        'sale_total_inc_gst', case
          when item.category = 'repair' and item.stock_action <> 'sold' then 0
          else round(item.sale_unit_price_inc_gst * item.quantity, 2)
        end,
        'invoice_number', item.invoice_number,
        'sale_notes', item.sale_notes,
        'entered_by_staff_name', item.entered_by_staff_name,
        'lcd_inventory_item_id', item.lcd_inventory_item_id,
        'lcd_model_name', item.lcd_model_name,
        'lcd_variant_name', item.lcd_variant_name,
        'stock_action', item.stock_action,
        'stock_before', item.stock_before,
        'stock_after', item.stock_after,
        'is_billable', (item.category = 'accessory' or item.stock_action = 'sold'),
        'cost_unit_price_ex_gst', case
          when item.category = 'repair' and item.stock_action <> 'sold' then null
          else item.cost_unit_price_ex_gst
        end,
        'cost_unit_price_inc_gst', case
          when item.category = 'repair' and item.stock_action <> 'sold' then null
          when item.cost_unit_price_ex_gst is null then null
          else round(item.cost_unit_price_ex_gst * 1.10, 2)
        end,
        'cost_total_inc_gst', case
          when item.category = 'repair' and item.stock_action <> 'sold' then null
          when item.cost_unit_price_ex_gst is null then null
          else round(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity, 2)
        end,
        'cost_notes', item.cost_notes,
        'cost_updated_at', item.cost_updated_at
      ) order by item.line_order, item.id)
      from public.nl_sales_items item
      where item.report_id = report.id
    ), '[]'::jsonb)
  )
  from public.nl_sales_reports report
  where report.id = target_report_id;
$$;

create or replace function public.get_nl_sales_report_partner_json(target_report_id bigint)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  with base as (
    select public.get_nl_sales_report_json(target_report_id) as payload
  ), redacted_items as (
    select coalesce(jsonb_agg(
      (item.value
        - 'cost_unit_price_ex_gst'
        - 'cost_unit_price_inc_gst'
        - 'cost_total_inc_gst'
        - 'cost_notes'
        - 'cost_updated_at')
      || jsonb_build_object(
        'cost_unit_price_ex_gst', null,
        'cost_unit_price_inc_gst', null,
        'cost_total_inc_gst', null,
        'cost_notes', '',
        'cost_updated_at', null
      )
      order by (item.value->>'line_order')::integer
    ), '[]'::jsonb) as payload
    from base
    cross join lateral jsonb_array_elements(coalesce(base.payload->'items', '[]'::jsonb)) item
  )
  select case
    when base.payload->>'status' in ('confirmed', 'settled') then base.payload
    else base.payload || jsonb_build_object(
      'payable_total_inc_gst', 0,
      'payable_cost_ex_gst', 0,
      'payable_gst', 0,
      'items', redacted_items.payload
    )
  end
  from base
  cross join redacted_items;
$$;

create or replace function public.get_nl_report_entry_config(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  config_row public.nl_report_config%rowtype;
  session_row public.nl_report_sessions%rowtype;
  draft_dates_json jsonb;
  accessory_names_json jsonb;
  lcd_items_json jsonb;
begin
  if not public.is_valid_nl_report_session(session_token) then
    raise exception 'Invalid NL report session';
  end if;

  select * into session_row
  from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and expires_at > now();

  select * into config_row
  from public.nl_report_config
  where id = 1;

  select coalesce(jsonb_agg(report.report_date order by report.report_date desc), '[]'::jsonb)
  into draft_dates_json
  from public.nl_sales_reports report
  where report.store_id = session_row.store_id
    and report.status = 'draft';

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', accessory.id,
    'name', accessory.name
  ) order by lower(accessory.name), accessory.id), '[]'::jsonb)
  into accessory_names_json
  from public.nl_accessory_names accessory
  where accessory.store_id = session_row.store_id
    and accessory.active = true;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', lcd.id,
    'model_name', lcd.model_name,
    'variant_name', lcd.variant_name,
    'category_key', lcd.category_key,
    'current_qty', lcd.current_qty
  ) order by lcd.category_key, lower(lcd.model_name), lower(lcd.variant_name), lcd.id), '[]'::jsonb)
  into lcd_items_json
  from public.lcd_inventory_items lcd
  where lcd.store_id = session_row.store_id
    and lcd.active = true;

  return jsonb_build_object(
    'ok', true,
    'today', (now() at time zone 'Australia/Brisbane')::date,
    'backfill_date_from', config_row.backfill_date_from,
    'backfill_date_to', config_row.backfill_date_to,
    'draft_dates', draft_dates_json,
    'accessory_names', accessory_names_json,
    'lcd_items', lcd_items_json
  );
end;
$$;

create or replace function public.save_nl_accessory_name(session_token text, accessory_name text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_row public.nl_report_sessions%rowtype;
  cleaned_name text;
  normalized_value text;
  saved_row public.nl_accessory_names%rowtype;
begin
  if not public.is_valid_nl_report_session(session_token) then
    raise exception 'Invalid NL report session';
  end if;

  select * into session_row
  from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and expires_at > now();

  cleaned_name := regexp_replace(trim(coalesce(accessory_name, '')), '\s+', ' ', 'g');
  normalized_value := lower(cleaned_name);

  if length(cleaned_name) < 1 or length(cleaned_name) > 160 then
    raise exception 'Accessory name must be between 1 and 160 characters';
  end if;

  insert into public.nl_accessory_names (
    store_id,
    name,
    normalized_name,
    active,
    saved_by_staff_name
  )
  values (
    session_row.store_id,
    cleaned_name,
    normalized_value,
    true,
    session_row.staff_name
  )
  on conflict (store_id, normalized_name)
  do update set
    name = excluded.name,
    active = true,
    saved_by_staff_name = excluded.saved_by_staff_name,
    updated_at = now()
  returning * into saved_row;

  return jsonb_build_object(
    'ok', true,
    'accessory', jsonb_build_object('id', saved_row.id, 'name', saved_row.name)
  );
end;
$$;

create or replace function public.save_nl_sales_report_unrestricted_internal(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_row public.nl_report_sessions%rowtype;
  selected_store public.store_locations%rowtype;
  report_row public.nl_sales_reports%rowtype;
  inventory_row public.lcd_inventory_items%rowtype;
  target_date_value date;
  items_json jsonb;
  item_json jsonb;
  item_index integer := 0;
  item_quantity integer;
  item_sale_price numeric(12,2);
  item_category text;
  item_stock_action text;
  item_inventory_id bigint;
  item_product_name text;
begin
  if not public.is_valid_nl_report_session(session_token) then
    raise exception 'Invalid NL report session';
  end if;
  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Payload must be an object';
  end if;

  select * into session_row
  from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and expires_at > now();

  select * into selected_store
  from public.store_locations
  where id = session_row.store_id;

  target_date_value := coalesce(
    nullif(payload->>'report_date', '')::date,
    (now() at time zone 'Australia/Brisbane')::date
  );
  items_json := coalesce(payload->'items', '[]'::jsonb);

  if jsonb_typeof(items_json) <> 'array' then
    raise exception 'Items must be an array';
  end if;
  if jsonb_array_length(items_json) > 500 then
    raise exception 'A report cannot contain more than 500 items';
  end if;

  select * into report_row
  from public.nl_sales_reports
  where store_id = session_row.store_id
    and report_date = target_date_value
  for update;

  if not found then
    insert into public.nl_sales_reports (
      report_date,
      store_id,
      store_name,
      started_by_staff_id,
      started_by_staff_name
    )
    values (
      target_date_value,
      session_row.store_id,
      selected_store.store_name,
      session_row.staff_id,
      session_row.staff_name
    )
    returning * into report_row;
  elsif report_row.status <> 'draft' then
    raise exception 'This report has already been submitted and is read-only';
  end if;

  delete from public.nl_sales_items
  where report_id = report_row.id;

  for item_json in select value from jsonb_array_elements(items_json) loop
    item_index := item_index + 1;
    item_category := lower(coalesce(nullif(trim(item_json->>'category'), ''), 'accessory'));
    item_stock_action := '';
    item_inventory_id := null;
    inventory_row := null;

    if item_category not in ('accessory', 'repair') then
      raise exception 'Choose Accessories or Repair on line %', item_index;
    end if;

    begin
      item_quantity := coalesce(nullif(item_json->>'quantity', '')::integer, 1);
      item_sale_price := nullif(item_json->>'sale_unit_price_inc_gst', '')::numeric(12,2);
    exception when others then
      raise exception 'Invalid quantity or sale price on line %', item_index;
    end;

    if item_quantity <= 0 then
      raise exception 'Quantity must be greater than zero on line %', item_index;
    end if;

    if item_category = 'accessory' then
      item_product_name := regexp_replace(trim(coalesce(item_json->>'product_name', '')), '\s+', ' ', 'g');
      if item_product_name = '' then
        raise exception 'Product name is required on line %', item_index;
      end if;
      if length(item_product_name) > 250 then
        raise exception 'Product name is too long on line %', item_index;
      end if;
    else
      begin
        item_inventory_id := nullif(item_json->>'lcd_inventory_item_id', '')::bigint;
      exception when others then
        raise exception 'Choose a valid LCD Tracker item on line %', item_index;
      end;

      item_stock_action := lower(coalesce(trim(item_json->>'stock_action'), ''));
      if item_inventory_id is null then
        raise exception 'Choose a model and part on line %', item_index;
      end if;
      if item_stock_action not in ('sold', 'send_to_other', 'faulty', 'broken') then
        raise exception 'Choose a valid stock action on line %', item_index;
      end if;

      select * into inventory_row
      from public.lcd_inventory_items
      where id = item_inventory_id
        and store_id = session_row.store_id
        and active = true;

      if not found then
        raise exception 'LCD Tracker item not found for North Lakes on line %', item_index;
      end if;

      item_product_name := inventory_row.model_name || ' - ' || inventory_row.variant_name ||
        case item_stock_action
          when 'sold' then ' Repair'
          when 'send_to_other' then ' - Send To Other'
          when 'faulty' then ' - Faulty'
          when 'broken' then ' - Broken'
        end;

      if item_stock_action <> 'sold' then
        item_sale_price := 0;
      end if;
    end if;

    if item_sale_price is null or item_sale_price < 0 then
      raise exception 'Sale price is required on line %', item_index;
    end if;

    insert into public.nl_sales_items (
      report_id,
      line_order,
      category,
      product_name,
      quantity,
      sale_unit_price_inc_gst,
      invoice_number,
      sale_notes,
      entered_by_staff_name,
      lcd_inventory_item_id,
      lcd_model_name,
      lcd_variant_name,
      stock_action,
      stock_before,
      stock_after
    )
    values (
      report_row.id,
      item_index,
      item_category,
      item_product_name,
      item_quantity,
      item_sale_price,
      coalesce(trim(item_json->>'invoice_number'), ''),
      coalesce(trim(item_json->>'sale_notes'), ''),
      session_row.staff_name,
      item_inventory_id,
      case when item_category = 'repair' then inventory_row.model_name else '' end,
      case when item_category = 'repair' then inventory_row.variant_name else '' end,
      item_stock_action,
      null,
      null
    );
  end loop;

  update public.nl_sales_reports
  set updated_at = now()
  where id = report_row.id;

  return jsonb_build_object(
    'ok', true,
    'report', public.get_nl_sales_report_partner_json(report_row.id)
  );
end;
$$;

create or replace function public.submit_nl_sales_report_unrestricted_internal(
  session_token text,
  target_date text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_row public.nl_report_sessions%rowtype;
  report_row public.nl_sales_reports%rowtype;
  inventory_row public.lcd_inventory_items%rowtype;
  item_row public.nl_sales_items%rowtype;
  target_date_value date;
begin
  if not public.is_valid_nl_report_session(session_token) then
    raise exception 'Invalid NL report session';
  end if;

  select * into session_row
  from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex')
    and expires_at > now();

  target_date_value := coalesce(
    nullif(target_date, '')::date,
    (now() at time zone 'Australia/Brisbane')::date
  );

  select * into report_row
  from public.nl_sales_reports
  where store_id = session_row.store_id
    and report_date = target_date_value
  for update;

  if not found then
    raise exception 'Save the report before submitting it';
  end if;
  if report_row.status <> 'draft' then
    raise exception 'This report has already been submitted';
  end if;

  for item_row in
    select *
    from public.nl_sales_items
    where report_id = report_row.id
      and category = 'repair'
    order by line_order, id
  loop
    select * into inventory_row
    from public.lcd_inventory_items
    where id = item_row.lcd_inventory_item_id
      and store_id = session_row.store_id
      and active = true
    for update;

    if not found then
      raise exception 'LCD Tracker item is no longer available: % / %', item_row.lcd_model_name, item_row.lcd_variant_name;
    end if;
    if inventory_row.current_qty < item_row.quantity then
      raise exception 'Not enough stock for % (%). Available: %, required: %',
        inventory_row.model_name,
        inventory_row.variant_name,
        inventory_row.current_qty,
        item_row.quantity;
    end if;

    update public.lcd_inventory_items
    set current_qty = current_qty - item_row.quantity
    where id = inventory_row.id;

    update public.nl_sales_items
    set
      stock_before = inventory_row.current_qty,
      stock_after = inventory_row.current_qty - item_row.quantity,
      lcd_model_name = inventory_row.model_name,
      lcd_variant_name = inventory_row.variant_name,
      updated_at = now()
    where id = item_row.id;
  end loop;

  update public.nl_sales_reports
  set
    status = case when exists (
      select 1
      from public.nl_sales_items item
      where item.report_id = report_row.id
        and (item.category = 'accessory' or item.stock_action = 'sold')
        and item.cost_unit_price_ex_gst is null
    ) then 'pricing_pending' else 'priced' end,
    submitted_by_staff_name = session_row.staff_name,
    submitted_at = now(),
    updated_at = now()
  where id = report_row.id;

  return jsonb_build_object(
    'ok', true,
    'report', public.get_nl_sales_report_partner_json(report_row.id)
  );
end;
$$;

create or replace function public.save_nl_report_costs(
  session_token text,
  target_report_id bigint,
  costs jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  report_row public.nl_sales_reports%rowtype;
  item_row public.nl_sales_items%rowtype;
  cost_json jsonb;
  item_id_value bigint;
  cost_value numeric(12,2);
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;
  if jsonb_typeof(costs) <> 'array' then
    raise exception 'Costs must be an array';
  end if;

  select * into report_row
  from public.nl_sales_reports
  where id = target_report_id
  for update;

  if not found then
    raise exception 'NL report not found';
  end if;
  if report_row.status in ('draft', 'confirmed', 'settled') then
    raise exception 'Costs can only be edited after submission and before confirmation';
  end if;

  for cost_json in select value from jsonb_array_elements(costs) loop
    item_id_value := nullif(cost_json->>'item_id', '')::bigint;
    cost_value := nullif(cost_json->>'cost_unit_price_ex_gst', '')::numeric(12,2);

    if item_id_value is null then
      raise exception 'Item id is required';
    end if;
    if cost_value is not null and cost_value < 0 then
      raise exception 'Cost price cannot be negative';
    end if;

    select * into item_row
    from public.nl_sales_items
    where id = item_id_value
      and report_id = target_report_id;

    if not found then
      raise exception 'NL report item not found';
    end if;

    if item_row.category = 'repair' and item_row.stock_action <> 'sold' then
      update public.nl_sales_items
      set cost_unit_price_ex_gst = null,
          cost_notes = '',
          cost_updated_at = null
      where id = item_id_value;
    else
      update public.nl_sales_items
      set cost_unit_price_ex_gst = cost_value,
          cost_notes = coalesce(trim(cost_json->>'cost_notes'), ''),
          cost_updated_at = now()
      where id = item_id_value;
    end if;
  end loop;

  update public.nl_sales_reports
  set status = case when exists (
    select 1
    from public.nl_sales_items item
    where item.report_id = target_report_id
      and (item.category = 'accessory' or item.stock_action = 'sold')
      and item.cost_unit_price_ex_gst is null
  ) then 'pricing_pending' else 'priced' end
  where id = target_report_id;

  return jsonb_build_object(
    'ok', true,
    'report', public.get_nl_sales_report_json(target_report_id)
  );
end;
$$;

revoke all on function public.save_nl_accessory_name(text, text)
from public, anon, authenticated;
grant execute on function public.save_nl_accessory_name(text, text)
to anon, authenticated;

revoke all on function public.get_nl_sales_report_json(bigint)
from public, anon, authenticated;
revoke all on function public.get_nl_sales_report_partner_json(bigint)
from public, anon, authenticated;
revoke all on function public.save_nl_sales_report_unrestricted_internal(text, jsonb)
from public, anon, authenticated;
revoke all on function public.submit_nl_sales_report_unrestricted_internal(text, text)
from public, anon, authenticated;

revoke all on function public.get_nl_report_entry_config(text) from public;
revoke all on function public.save_nl_report_costs(text, bigint, jsonb) from public;
grant execute on function public.get_nl_report_entry_config(text) to anon, authenticated;
grant execute on function public.save_nl_report_costs(text, bigint, jsonb) to anon, authenticated;
