create table if not exists public.pos_sales_orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  business_date date not null,
  staff_name text not null,
  shift_id text,
  customer_name text not null default 'Walk-in Customer',
  customer_phone text not null default '',
  customer_email text not null default '',
  payment_method text not null,
  total numeric(12,2) not null check (total >= 0),
  order_payload jsonb not null,
  receipt_email_count integer not null default 0 check (receipt_email_count >= 0),
  last_receipt_email text not null default '',
  receipt_emailed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pos_sales_orders_store_date_idx
on public.pos_sales_orders (store_id, business_date desc, created_at desc);

drop trigger if exists pos_sales_orders_set_updated_at on public.pos_sales_orders;
create trigger pos_sales_orders_set_updated_at
before update on public.pos_sales_orders
for each row
execute function public.set_updated_at();

alter table public.pos_sales_orders enable row level security;

revoke all on public.pos_sales_orders from public, anon, authenticated;
grant select, insert, update on public.pos_sales_orders to service_role;

create or replace function public.pos_sales_order_payload(order_row public.pos_sales_orders)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select order_row.order_payload || jsonb_build_object(
    'id', order_row.order_code,
    'store_db_code', store_location.store_code,
    'store_name', store_location.store_name,
    'business_date', order_row.business_date,
    'staff_name', order_row.staff_name,
    'customer_name', order_row.customer_name,
    'customer_phone', order_row.customer_phone,
    'customer_email', order_row.customer_email,
    'payment_method', order_row.payment_method,
    'total', order_row.total,
    'receipt_email_count', order_row.receipt_email_count,
    'last_receipt_email', order_row.last_receipt_email,
    'receipt_emailed_at', order_row.receipt_emailed_at,
    'created_at', order_row.created_at,
    'database_saved_at', order_row.updated_at,
    'sync_pending', false
  )
  from public.store_locations store_location
  where store_location.id = order_row.store_id;
$$;

create or replace function public.save_pos_sales_order(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  saved_order public.pos_sales_orders%rowtype;
  order_code_value text;
  created_at_value timestamptz;
  business_date_value date;
  total_value numeric(12,2);
  payment_total numeric(12,2);
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  if jsonb_typeof(payload) <> 'object' then
    raise exception 'Order payload must be a JSON object';
  end if;

  order_code_value := coalesce(trim(payload->>'id'), '');
  if order_code_value = '' then
    raise exception 'Order id is required';
  end if;

  if jsonb_typeof(payload->'items') <> 'array' or jsonb_array_length(payload->'items') = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  if jsonb_typeof(payload->'payments') <> 'array' or jsonb_array_length(payload->'payments') = 0 then
    raise exception 'Order must contain at least one payment';
  end if;

  total_value := round(coalesce(nullif(payload->>'total', '')::numeric, 0), 2);
  if total_value < 0 then
    raise exception 'Order total cannot be negative';
  end if;

  select round(coalesce(sum(coalesce(nullif(payment->>'amount', '')::numeric, 0)), 0), 2)
  into payment_total
  from jsonb_array_elements(payload->'payments') payment;

  if payment_total < total_value then
    raise exception 'Payment total is less than order total';
  end if;

  select *
  into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and (
      lower(regexp_replace(store_location.store_code, '[^a-z0-9]', '', 'g')) =
        lower(regexp_replace(coalesce(payload->>'store_db_code', payload->>'store_id', ''), '[^a-z0-9]', '', 'g'))
      or upper(store_location.store_code) = upper(coalesce(payload->>'store_code', ''))
    )
  limit 1;

  if not found then
    raise exception 'Store not found';
  end if;

  select *
  into selected_staff
  from public.staff_directory staff
  where staff.active = true
    and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;

  if not found then
    raise exception 'Staff member not found';
  end if;

  created_at_value := coalesce(nullif(payload->>'created_at', '')::timestamptz, now());
  business_date_value := coalesce(
    nullif(payload->>'business_date', '')::date,
    (created_at_value at time zone 'Australia/Brisbane')::date
  );

  insert into public.pos_sales_orders (
    order_code,
    store_id,
    business_date,
    staff_name,
    shift_id,
    customer_name,
    customer_phone,
    customer_email,
    payment_method,
    total,
    order_payload,
    created_at
  )
  values (
    order_code_value,
    selected_store.id,
    business_date_value,
    selected_staff.display_name,
    nullif(trim(payload->>'shift_id'), ''),
    coalesce(nullif(trim(payload->>'customer_name'), ''), 'Walk-in Customer'),
    coalesce(trim(payload->>'customer_phone'), ''),
    coalesce(trim(payload->>'customer_email'), ''),
    coalesce(nullif(trim(payload->>'payment_method'), ''), 'Unknown'),
    total_value,
    payload || jsonb_build_object('sync_pending', false),
    created_at_value
  )
  on conflict (order_code) do update
  set
    store_id = excluded.store_id,
    business_date = excluded.business_date,
    staff_name = excluded.staff_name,
    shift_id = excluded.shift_id,
    customer_name = excluded.customer_name,
    customer_phone = excluded.customer_phone,
    customer_email = excluded.customer_email,
    payment_method = excluded.payment_method,
    total = excluded.total,
    order_payload = excluded.order_payload,
    updated_at = now()
  returning * into saved_order;

  return jsonb_build_object(
    'ok', true,
    'order', public.pos_sales_order_payload(saved_order)
  );
end;
$$;

create or replace function public.get_pos_sales_order(session_token text, target_order_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_order public.pos_sales_orders%rowtype;
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  select *
  into selected_order
  from public.pos_sales_orders sales_order
  where sales_order.order_code = coalesce(trim(target_order_code), '');

  if not found then
    raise exception 'Order not found';
  end if;

  return jsonb_build_object(
    'ok', true,
    'order', public.pos_sales_order_payload(selected_order)
  );
end;
$$;

create or replace function public.mark_pos_receipt_emailed(
  session_token text,
  target_order_code text,
  recipient_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_valid_staff_session(session_token) then
    raise exception 'Invalid session';
  end if;

  update public.pos_sales_orders
  set
    receipt_email_count = receipt_email_count + 1,
    last_receipt_email = lower(coalesce(trim(recipient_email), '')),
    receipt_emailed_at = now(),
    updated_at = now()
  where order_code = coalesce(trim(target_order_code), '');

  if not found then
    raise exception 'Order not found';
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

revoke execute on function public.pos_sales_order_payload(public.pos_sales_orders) from public;
revoke execute on function public.save_pos_sales_order(text, jsonb) from public;
revoke execute on function public.get_pos_sales_order(text, text) from public;
revoke execute on function public.mark_pos_receipt_emailed(text, text, text) from public;

grant execute on function public.save_pos_sales_order(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.get_pos_sales_order(text, text) to anon, authenticated, service_role;
grant execute on function public.mark_pos_receipt_emailed(text, text, text) to anon, authenticated, service_role;
