create table if not exists public.crazyparts_run_requests (
  id bigint generated by default as identity primary key,
  family text not null references public.crazyparts_update_status(family),
  brand text not null,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  message text not null default 'Waiting for this computer to start the update.',
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create unique index if not exists crazyparts_one_active_request_per_family
on public.crazyparts_run_requests (family)
where status in ('queued', 'running');

create index if not exists crazyparts_run_requests_queue_idx
on public.crazyparts_run_requests (status, requested_at);

create index if not exists crazyparts_run_requests_family_idx
on public.crazyparts_run_requests (family);

alter table public.crazyparts_run_requests enable row level security;

revoke all on table public.crazyparts_run_requests from anon, authenticated;
revoke all on sequence public.crazyparts_run_requests_id_seq from anon, authenticated;
grant all on table public.crazyparts_run_requests to service_role;
grant usage, select on sequence public.crazyparts_run_requests_id_seq to service_role;

drop policy if exists "Crazy Parts run requests stay private" on public.crazyparts_run_requests;
create policy "Crazy Parts run requests stay private"
on public.crazyparts_run_requests
for all
to anon, authenticated
using (false)
with check (false);

create or replace function public.request_crazyparts_price_update(
  session_token text,
  target_family text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_brand text;
  existing_request public.crazyparts_run_requests%rowtype;
  created_request public.crazyparts_run_requests%rowtype;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  select brand
  into selected_brand
  from public.crazyparts_update_status
  where family = target_family;

  if not found then
    raise exception 'Unsupported price update family';
  end if;

  select *
  into existing_request
  from public.crazyparts_run_requests
  where family = target_family
    and status in ('queued', 'running')
  order by requested_at desc
  limit 1;

  if found then
    return jsonb_build_object(
      'ok', true,
      'already_active', true,
      'request_id', existing_request.id,
      'status', existing_request.status,
      'message', existing_request.message
    );
  end if;

  insert into public.crazyparts_run_requests (family, brand)
  values (target_family, selected_brand)
  returning * into created_request;

  return jsonb_build_object(
    'ok', true,
    'already_active', false,
    'request_id', created_request.id,
    'status', created_request.status,
    'message', created_request.message
  );
exception
  when unique_violation then
    select *
    into existing_request
    from public.crazyparts_run_requests
    where family = target_family
      and status in ('queued', 'running')
    order by requested_at desc
    limit 1;

    return jsonb_build_object(
      'ok', true,
      'already_active', true,
      'request_id', existing_request.id,
      'status', existing_request.status,
      'message', existing_request.message
    );
end;
$$;

create or replace function public.get_crazyparts_run_requests(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  request_rows jsonb;
begin
  if not public.is_valid_admin_session(session_token) then
    raise exception 'Invalid admin session';
  end if;

  select coalesce(jsonb_agg(to_jsonb(latest_request)), '[]'::jsonb)
  into request_rows
  from (
    select distinct on (family)
      id,
      family,
      brand,
      status,
      message,
      requested_at,
      started_at,
      completed_at
    from public.crazyparts_run_requests
    order by family, requested_at desc
  ) as latest_request;

  return jsonb_build_object('ok', true, 'requests', request_rows);
end;
$$;

revoke all on function public.request_crazyparts_price_update(text, text) from public;
revoke all on function public.get_crazyparts_run_requests(text) from public;
grant execute on function public.request_crazyparts_price_update(text, text) to anon, authenticated, service_role;
grant execute on function public.get_crazyparts_run_requests(text) to anon, authenticated, service_role;
