-- Store credit is a customer liability, not a Cash/Card refund or receipt.
-- Account rows serialize concurrent spends; entries preserve the audit trail.
create table if not exists public.pos_store_credit_accounts (
  customer_id bigint primary key references public.pos_customers(id) on delete restrict,
  balance numeric(12,2) not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_store_credit_entries (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.pos_customers(id) on delete restrict,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  refund_id bigint unique references public.pos_sales_refunds(id) on delete restrict,
  payment_id bigint unique references public.pos_sales_order_payments(id) on delete restrict,
  amount numeric(12,2) not null check (amount <> 0),
  balance_after numeric(12,2) not null check (balance_after >= 0),
  staff_name text not null,
  created_at timestamptz not null default now(),
  constraint pos_store_credit_entries_one_source check ((refund_id is not null) <> (payment_id is not null)),
  constraint pos_store_credit_entries_direction check (
    (refund_id is not null and amount > 0) or (payment_id is not null and amount < 0)
  )
);

create index if not exists pos_store_credit_entries_customer_date_idx
  on public.pos_store_credit_entries (customer_id, created_at desc);

alter table public.pos_store_credit_accounts enable row level security;
alter table public.pos_store_credit_entries enable row level security;
revoke all on public.pos_store_credit_accounts from public, anon, authenticated;
revoke all on public.pos_store_credit_entries from public, anon, authenticated;
grant select, insert, update on public.pos_store_credit_accounts to service_role;
grant select, insert on public.pos_store_credit_entries to service_role;

create or replace function public.pos_store_credit_customer_for_order(
  order_row public.pos_sales_orders,
  target_customer_code text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer_row public.pos_customers%rowtype;
  order_phone text := regexp_replace(coalesce(order_row.customer_phone, ''), '[^0-9]', '', 'g');
  customer_phone text;
  alert_phone text;
  invoice_name text := lower(trim(coalesce(order_row.customer_name, '')));
  account_name text;
begin
  if coalesce(trim(target_customer_code), '') = '' then
    raise exception 'Select a customer account before using Store Credit';
  end if;
  select * into customer_row
  from public.pos_customers customer
  where customer.customer_code = trim(target_customer_code) and customer.active;
  if not found then raise exception 'Store Credit customer account was not found'; end if;

  customer_phone := regexp_replace(coalesce(customer_row.phone, ''), '[^0-9]', '', 'g');
  alert_phone := regexp_replace(coalesce(customer_row.alert_number, ''), '[^0-9]', '', 'g');
  if order_phone <> '' and not (
    (length(order_phone) >= 9 and (
      (length(customer_phone) >= 9 and right(order_phone, 9) = right(customer_phone, 9))
      or (length(alert_phone) >= 9 and right(order_phone, 9) = right(alert_phone, 9))
    ))
    or (length(order_phone) < 9 and order_phone in (customer_phone, alert_phone))
  ) then
    raise exception 'Selected customer phone does not match this invoice';
  end if;

  account_name := lower(trim(concat_ws(' ', customer_row.first_name, customer_row.last_name)));
  if order_phone = '' and invoice_name not in ('', 'walk-in customer')
    and invoice_name <> account_name then
    raise exception 'Selected customer name does not match this invoice';
  end if;
  return customer_row.id;
end;
$$;

create or replace function public.record_pos_store_credit_refund()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_row public.pos_sales_orders%rowtype;
  customer_id_value bigint;
  new_balance numeric(12,2);
begin
  if lower(trim(new.method)) <> 'store credit' then return new; end if;
  select * into order_row from public.pos_sales_orders where id = new.sales_order_id;
  customer_id_value := public.pos_store_credit_customer_for_order(
    order_row, new.refund_payload->>'customer_code'
  );
  insert into public.pos_store_credit_accounts(customer_id, balance)
  values (customer_id_value, new.amount)
  on conflict (customer_id) do update set
    balance = public.pos_store_credit_accounts.balance + excluded.balance,
    updated_at = now()
  returning balance into new_balance;
  insert into public.pos_store_credit_entries(
    customer_id, store_id, refund_id, amount, balance_after, staff_name
  ) values (
    customer_id_value, new.store_id, new.id, new.amount, new_balance, new.staff_name
  );
  return new;
end;
$$;

create or replace function public.spend_pos_store_credit_payment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  order_row public.pos_sales_orders%rowtype;
  customer_id_value bigint;
  new_balance numeric(12,2);
begin
  if lower(trim(new.method)) <> 'store credit' then return new; end if;
  select * into order_row from public.pos_sales_orders where id = new.sales_order_id;
  customer_id_value := public.pos_store_credit_customer_for_order(
    order_row, order_row.order_payload->>'customer_code'
  );
  update public.pos_store_credit_accounts account
  set balance = account.balance - new.amount, updated_at = now()
  where account.customer_id = customer_id_value and account.balance >= new.amount
  returning balance into new_balance;
  if not found then raise exception 'Not enough Store Credit balance for this payment'; end if;
  insert into public.pos_store_credit_entries(
    customer_id, store_id, payment_id, amount, balance_after, staff_name
  ) values (
    customer_id_value, order_row.store_id, new.id, -new.amount, new_balance,
    coalesce(nullif(new.staff_name, ''), order_row.staff_name)
  );
  return new;
end;
$$;

drop trigger if exists record_pos_store_credit_refund_trigger on public.pos_sales_refunds;
create trigger record_pos_store_credit_refund_trigger
after insert on public.pos_sales_refunds
for each row execute function public.record_pos_store_credit_refund();

drop trigger if exists spend_pos_store_credit_payment_trigger on public.pos_sales_order_payments;
create trigger spend_pos_store_credit_payment_trigger
after insert on public.pos_sales_order_payments
for each row execute function public.spend_pos_store_credit_payment();

create or replace function public.get_pos_store_credit_balance(
  session_token text,
  target_store_code text,
  target_customer_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer_row public.pos_customers%rowtype;
  balance_value numeric(12,2);
begin
  perform public.pos_authorized_actor(session_token, target_store_code, null);
  select * into customer_row from public.pos_customers customer
  where customer.customer_code = coalesce(trim(target_customer_code), '') and customer.active;
  if not found then raise exception 'Customer account was not found'; end if;
  select coalesce(account.balance, 0) into balance_value
  from public.pos_store_credit_accounts account where account.customer_id = customer_row.id;
  return jsonb_build_object(
    'ok', true,
    'customer_code', customer_row.customer_code,
    'customer_name', trim(concat_ws(' ', customer_row.first_name, customer_row.last_name)),
    'customer_phone', customer_row.phone,
    'balance', coalesce(balance_value, 0)
  );
end;
$$;

revoke all on function public.pos_store_credit_customer_for_order(public.pos_sales_orders,text)
  from public, anon, authenticated;
revoke all on function public.record_pos_store_credit_refund() from public, anon, authenticated;
revoke all on function public.spend_pos_store_credit_payment() from public, anon, authenticated;
revoke all on function public.get_pos_store_credit_balance(text,text,text)
  from public, anon, authenticated;
grant execute on function public.get_pos_store_credit_balance(text,text,text) to service_role;

comment on table public.pos_store_credit_accounts is
  'Customer-wide Store Credit balance shared across all TechM8 stores; only the database triggers change it.';
comment on table public.pos_store_credit_entries is
  'Immutable issue and spend audit trail tied to refund and payment rows.';

-- A balance payment on an older invoice may not yet have an account code.
-- Bind it to the verified customer before the payment trigger spends credit.
create or replace function public.add_pos_sales_order_payment_for_store(
  session_token text,
  payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  shift_context jsonb;
  selected_order public.pos_sales_orders%rowtype;
  sanitized_payload jsonb;
  order_code_value text := coalesce(trim(payload->>'order_id'), trim(payload->>'id'), '');
  credit_customer_code text := coalesce(trim(payload->>'customer_code'), '');
begin
  if jsonb_typeof(payload) <> 'object' then raise exception 'Payment payload must be an object'; end if;
  shift_context := public.pos_open_shift_context(
    session_token, payload->>'store_code', payload->>'shift_id', payload->>'staff_name', true
  );
  select * into selected_order
  from public.pos_sales_orders sales_order
  where sales_order.order_code = order_code_value
    and sales_order.store_id = nullif(shift_context->>'store_id', '')::bigint
  for update;
  if not found then raise exception 'Invoice not found in the current store'; end if;

  if exists (
    select 1 from jsonb_array_elements(coalesce(payload->'payments', '[]'::jsonb)) payment
    where lower(trim(payment->>'method')) = 'store credit'
  ) then
    perform public.pos_store_credit_customer_for_order(selected_order, credit_customer_code);
    if nullif(selected_order.order_payload->>'customer_code', '') is not null
      and selected_order.order_payload->>'customer_code' <> credit_customer_code then
      raise exception 'This invoice is already linked to another customer account';
    end if;
    update public.pos_sales_orders
    set order_payload = order_payload || jsonb_build_object('customer_code', credit_customer_code)
    where id = selected_order.id;
  end if;

  sanitized_payload := payload || jsonb_build_object(
    'store_code', shift_context->>'store_code',
    'staff_name', shift_context->>'staff_name',
    'shift_id', shift_context->>'shift_id',
    'business_date', shift_context->>'business_date',
    'taken_at', now()
  );
  return public.add_pos_sales_order_payment(session_token, sanitized_payload);
end;
$$;

-- Keep financial takings separate from the customer's credit liability.
alter function public.get_pos_shift_payment_totals(text,text)
  rename to get_pos_shift_payment_totals_before_store_credit;
create function public.get_pos_shift_payment_totals(session_token text, target_shift_code text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  result_payload jsonb;
  credit_received numeric(12,2);
begin
  result_payload := public.get_pos_shift_payment_totals_before_store_credit(session_token, target_shift_code);
  select coalesce(sum((entry->>'received')::numeric), 0) into credit_received
  from jsonb_array_elements(result_payload->'payment_totals') entry
  where lower(trim(entry->>'method')) = 'store credit';
  return jsonb_set(
    jsonb_set(result_payload, '{payment_totals}', coalesce((
      select jsonb_agg(entry) from jsonb_array_elements(result_payload->'payment_totals') entry
      where lower(trim(entry->>'method')) <> 'store credit'
    ), '[]'::jsonb)),
    '{gross_sales}', to_jsonb((result_payload->>'gross_sales')::numeric - credit_received)
  );
end;
$$;
revoke all on function public.get_pos_shift_payment_totals(text,text) from public,anon,authenticated;
grant execute on function public.get_pos_shift_payment_totals(text,text) to service_role;

alter function public.get_pos_performance_report(text,text,date,date,integer)
  rename to get_pos_performance_report_before_store_credit;
create function public.get_pos_performance_report(
  session_token text, target_store_code text, date_from date default null,
  date_to date default null, order_limit integer default 300
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  result_payload jsonb;
  credit_issued numeric(12,2);
  credit_redeemed numeric(12,2);
  totals jsonb;
begin
  result_payload := public.get_pos_performance_report_before_store_credit(
    session_token, target_store_code, date_from, date_to, order_limit
  );
  select
    coalesce(sum((entry->>'received')::numeric), 0),
    coalesce(sum((entry->>'refunded')::numeric), 0)
  into credit_redeemed, credit_issued
  from jsonb_array_elements(result_payload->'payment_totals') entry
  where lower(trim(entry->>'method')) = 'store credit';
  totals := result_payload->'totals';
  totals := totals || jsonb_build_object(
    'received', (totals->>'received')::numeric - credit_redeemed,
    'refunded', (totals->>'refunded')::numeric - credit_issued,
    'net', (totals->>'net')::numeric - credit_redeemed + credit_issued,
    'store_credit_issued', credit_issued,
    'store_credit_redeemed', credit_redeemed
  );
  return jsonb_set(result_payload, '{totals}', totals);
end;
$$;
revoke all on function public.get_pos_performance_report(text,text,date,date,integer)
  from public,anon,authenticated;
grant execute on function public.get_pos_performance_report(text,text,date,date,integer) to service_role;

alter function public.get_admin_sales_overview(text,date,date)
  rename to get_admin_sales_overview_before_store_credit;
create function public.get_admin_sales_overview(
  session_token text, date_from date default null, date_to date default null
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  result_payload jsonb;
  store_row jsonb;
  adjusted_stores jsonb := '[]'::jsonb;
  credit_by_store numeric(12,2);
  total_credit numeric(12,2) := 0;
  from_value date := coalesce(date_from, (now() at time zone 'Australia/Brisbane')::date);
  to_value date := coalesce(date_to, date_from, (now() at time zone 'Australia/Brisbane')::date);
begin
  result_payload := public.get_admin_sales_overview_before_store_credit(session_token, date_from, date_to);
  for store_row in select value from jsonb_array_elements(result_payload->'stores') loop
    select coalesce(sum(payment.amount), 0) into credit_by_store
    from public.pos_sales_order_payments payment
    join public.pos_sales_orders sales_order on sales_order.id = payment.sales_order_id
    join public.store_locations store on store.id = sales_order.store_id
    where store.store_code = store_row->>'store_code'
      and lower(trim(payment.method)) = 'store credit'
      and coalesce(payment.business_date, (payment.created_at at time zone 'Australia/Brisbane')::date)
          between from_value and to_value;
    total_credit := total_credit + credit_by_store;
    adjusted_stores := adjusted_stores || jsonb_build_array(
      jsonb_set(store_row, '{payments_received}',
        to_jsonb((store_row->>'payments_received')::numeric - credit_by_store))
    );
  end loop;
  result_payload := jsonb_set(result_payload, '{stores}', adjusted_stores);
  return jsonb_set(result_payload, '{totals,payments_received}',
    to_jsonb((result_payload #>> '{totals,payments_received}')::numeric - total_credit));
end;
$$;
revoke all on function public.get_admin_sales_overview(text,date,date) from public,anon,authenticated;
grant execute on function public.get_admin_sales_overview(text,date,date) to anon,authenticated,service_role;
