-- Staff pick the payment method by hand at checkout, and picking the wrong one
-- has so far only been fixable by refunding the whole invoice and ringing it up
-- again. That burns an invoice number, invents a refund that never happened,
-- and throws the day's takings out on both methods at once. It has already been
-- done five times.
--
-- The money itself is never wrong in these cases: it went through the right
-- terminal, the POS just recorded the wrong label. So this corrects the label
-- and nothing else. The amount cannot change here: if the amount is wrong, real
-- money has to move and that must stay a refund or a top-up payment.

create table if not exists public.pos_payment_method_corrections (
  id bigint generated by default as identity primary key,
  correction_code text not null unique,
  sales_order_payment_id bigint not null references public.pos_sales_order_payments(id) on delete restrict,
  sales_order_id bigint not null references public.pos_sales_orders(id) on delete restrict,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  from_method text not null,
  to_method text not null,
  amount numeric(12,2) not null,
  reason text not null,
  corrected_by text not null,
  corrected_at timestamptz not null default now(),
  shift_code text,
  shift_snapshot_patched boolean not null default false,
  constraint pos_payment_method_corrections_reason_check check (btrim(reason) <> ''),
  constraint pos_payment_method_corrections_change_check check (from_method <> to_method)
);

create index if not exists pos_payment_method_corrections_order_idx
  on public.pos_payment_method_corrections (sales_order_id, corrected_at desc);

alter table public.pos_payment_method_corrections enable row level security;
revoke all on public.pos_payment_method_corrections from public, anon, authenticated;
grant select, insert on public.pos_payment_method_corrections to service_role;

comment on table public.pos_payment_method_corrections is
  'Audit of payment method label corrections. The amount is never altered by a correction.';

-- Maps a stored method label to the key used inside a shift''s frozen totals.
create or replace function public.pos_payment_method_key(method_label text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case btrim(coalesce(method_label, ''))
    when 'Cash' then 'cash'
    when 'Card' then 'card'
    when 'Afterpay' then 'afterpay'
    when 'CNYpay' then 'cnyPay'
    when 'Bank Transfer' then 'bankTransfer'
    else null
  end;
$$;

create or replace function public.correct_pos_payment_method(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  selected_order public.pos_sales_orders%rowtype;
  payment_row public.pos_sales_order_payments%rowtype;
  shift_row public.pos_store_shifts%rowtype;
  to_method text := btrim(coalesce(payload->>'to_method', ''));
  reason_value text := btrim(coalesce(payload->>'reason', ''));
  order_code_value text := btrim(coalesce(payload->>'order_id', ''));
  payment_number_value integer := nullif(payload->>'payment_number', '')::integer;
  from_key text;
  to_key text;
  patched boolean := false;
  new_system jsonb;
  new_differences jsonb;
  correction_code_value text;
begin
  if jsonb_typeof(payload) <> 'object' then raise exception 'Correction payload must be an object'; end if;

  actor := public.pos_authorized_actor(
    session_token,
    coalesce(payload->>'store_code', payload->>'store_id'),
    payload->>'staff_name'
  );

  if order_code_value = '' then raise exception 'Invoice is required'; end if;
  if payment_number_value is null then raise exception 'Payment line is required'; end if;
  if reason_value = '' then raise exception 'A reason is required to correct a payment method'; end if;
  if length(reason_value) > 500 then raise exception 'Reason cannot exceed 500 characters'; end if;

  to_key := public.pos_payment_method_key(to_method);
  if to_key is null then raise exception 'Unknown payment method: %', to_method; end if;

  select * into selected_order
  from public.pos_sales_orders sales_order
  where sales_order.order_code = order_code_value
    and sales_order.store_id = nullif(actor->>'store_id', '')::bigint
  for update;
  if not found then raise exception 'Invoice not found in the current store'; end if;

  select * into payment_row
  from public.pos_sales_order_payments payment
  where payment.sales_order_id = selected_order.id
    and payment.payment_number = payment_number_value
  for update;
  if not found then raise exception 'Payment line not found on this invoice'; end if;

  from_key := public.pos_payment_method_key(payment_row.method);
  if from_key is null then
    -- Imported history uses labels this POS never wrote, including combined
    -- ones like 'Tyro, Cash'. Those are not safe to relabel.
    raise exception 'This payment was imported and cannot be corrected here';
  end if;
  if from_key = to_key then raise exception 'That is already the payment method'; end if;

  update public.pos_sales_order_payments
  set method = to_method
  where id = payment_row.id;

  -- The invoice keeps a readable summary of how it was paid.
  update public.pos_sales_orders
  set payment_method = (
        select string_agg(distinct payment.method, ' + ' order by payment.method)
        from public.pos_sales_order_payments payment
        where payment.sales_order_id = selected_order.id
      ),
      updated_at = now()
  where id = selected_order.id;

  -- A shift that has already been closed keeps a frozen snapshot of what the
  -- system thought it took. Leaving it stale would mean the day could never be
  -- reconciled again, so it is corrected too and the patch is recorded.
  if payment_row.shift_id is not null then
    select * into shift_row
    from public.pos_store_shifts
    where shift_code = payment_row.shift_id
    for update;

    if found and jsonb_typeof(shift_row.system_totals) = 'object'
       and shift_row.system_totals ? from_key and shift_row.system_totals ? to_key then
      new_system := shift_row.system_totals
        || jsonb_build_object(from_key, round(coalesce((shift_row.system_totals->>from_key)::numeric, 0) - payment_row.amount, 2))
        || jsonb_build_object(to_key, round(coalesce((shift_row.system_totals->>to_key)::numeric, 0) + payment_row.amount, 2));

      new_differences := coalesce(shift_row.differences, '{}'::jsonb);
      if jsonb_typeof(shift_row.actual_totals) = 'object' then
        -- differences is actual minus system; recompute rather than nudge.
        new_differences := new_differences
          || jsonb_build_object(from_key, round(
               coalesce((shift_row.actual_totals->>from_key)::numeric, 0)
               - coalesce((new_system->>from_key)::numeric, 0), 2))
          || jsonb_build_object(to_key, round(
               coalesce((shift_row.actual_totals->>to_key)::numeric, 0)
               - coalesce((new_system->>to_key)::numeric, 0), 2));
      end if;

      update public.pos_store_shifts
      set system_totals = new_system,
          differences = new_differences,
          updated_at = now()
      where id = shift_row.id;
      patched := true;
    end if;
  end if;

  correction_code_value := 'PMC-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16));

  insert into public.pos_payment_method_corrections (
    correction_code, sales_order_payment_id, sales_order_id, store_id,
    from_method, to_method, amount, reason, corrected_by, shift_code, shift_snapshot_patched
  ) values (
    correction_code_value, payment_row.id, selected_order.id, selected_order.store_id,
    payment_row.method, to_method, payment_row.amount, reason_value,
    actor->>'staff_name', payment_row.shift_id, patched
  );

  select * into selected_order from public.pos_sales_orders where id = selected_order.id;

  return jsonb_build_object(
    'ok', true,
    'correction_code', correction_code_value,
    'from_method', payment_row.method,
    'to_method', to_method,
    'amount', payment_row.amount,
    'shift_snapshot_patched', patched,
    'order', public.pos_sales_order_payload(selected_order)
  );
end;
$$;

revoke all on function public.correct_pos_payment_method(text, jsonb) from public, anon, authenticated;
revoke all on function public.pos_payment_method_key(text) from public, anon, authenticated;
grant execute on function public.correct_pos_payment_method(text, jsonb) to service_role;
grant execute on function public.pos_payment_method_key(text) to service_role;
