-- The inspection checklist becomes shared data instead of a number.
--
-- The ready-for-sale gate counted answers: at least eight of them had to say
-- pass or N/A. A phone checklist has twenty-three items, so a caller that
-- skipped the POS could shelf a phone after answering eight. The checklist now
-- lives in the database, one row per item per category, and every item for the
-- device's category must be answered before it can be sold.
--
-- The POS reads the same rows, so the paper form, the screen and the gate
-- cannot drift apart. The lists here are the ones the POS was already drawing,
-- taken from TECHM8_Buyback_Device_Inspection_Form.pdf.

create table public.pos_used_device_inspection_items (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('Phone', 'Tablet', 'Laptop', 'Watch', 'Game Console', 'Other')),
  item_key text not null,
  label text not null,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (category, item_key)
);

create index pos_used_device_inspection_items_category_idx
  on public.pos_used_device_inspection_items (category, position)
  where active;

alter table public.pos_used_device_inspection_items enable row level security;
revoke all on public.pos_used_device_inspection_items from public, anon, authenticated;
grant select on public.pos_used_device_inspection_items to service_role;

insert into public.pos_used_device_inspection_items (category, item_key, label, position) values
  ('Phone', 'power', 'Power and boot', 10),
  ('Phone', 'touch', 'Touch working', 20),
  ('Phone', 'display_lcd', 'LCD / display working', 30),
  ('Phone', 'back_glass', 'Back glass intact', 40),
  ('Phone', 'housing', 'Housing and frame intact', 50),
  ('Phone', 'power_button', 'Power button working', 60),
  ('Phone', 'volume_buttons', 'Volume buttons working', 70),
  ('Phone', 'vibrate', 'Vibrate switch / haptics', 80),
  ('Phone', 'fingerprint', 'Fingerprint scanner', 90),
  ('Phone', 'face_id', 'Face ID working', 100),
  ('Phone', 'charging_port', 'Charging port working', 110),
  ('Phone', 'ear_speaker', 'Ear speaker working', 120),
  ('Phone', 'loudspeaker', 'Loudspeaker working', 130),
  ('Phone', 'mic', 'Microphone working', 140),
  ('Phone', 'proximity', 'Proximity sensor working', 150),
  ('Phone', 'rear_camera', 'Rear camera working', 160),
  ('Phone', 'front_camera', 'Front camera working', 170),
  ('Phone', 'flash', 'Torch / flash working', 180),
  ('Phone', 'sim_reader', 'SIM card reader working', 190),
  ('Phone', 'wifi', 'Wi-Fi working', 200),
  ('Phone', 'bluetooth', 'Bluetooth working', 210),
  ('Phone', 'battery', 'Battery charging and health', 220),
  ('Phone', 'liquid', 'Liquid damage indicators', 230),
  ('Tablet', 'power', 'Power and boot', 10),
  ('Tablet', 'touch', 'Touch working', 20),
  ('Tablet', 'display_lcd', 'LCD / display working', 30),
  ('Tablet', 'back_glass', 'Back glass intact', 40),
  ('Tablet', 'housing', 'Housing and frame intact', 50),
  ('Tablet', 'power_button', 'Power button working', 60),
  ('Tablet', 'volume_buttons', 'Volume buttons working', 70),
  ('Tablet', 'vibrate', 'Vibrate switch / haptics', 80),
  ('Tablet', 'fingerprint', 'Fingerprint scanner', 90),
  ('Tablet', 'face_id', 'Face ID working', 100),
  ('Tablet', 'charging_port', 'Charging port working', 110),
  ('Tablet', 'ear_speaker', 'Ear speaker working', 120),
  ('Tablet', 'loudspeaker', 'Loudspeaker working', 130),
  ('Tablet', 'mic', 'Microphone working', 140),
  ('Tablet', 'proximity', 'Proximity sensor working', 150),
  ('Tablet', 'rear_camera', 'Rear camera working', 160),
  ('Tablet', 'front_camera', 'Front camera working', 170),
  ('Tablet', 'flash', 'Torch / flash working', 180),
  ('Tablet', 'sim_reader', 'SIM card reader working', 190),
  ('Tablet', 'wifi', 'Wi-Fi working', 200),
  ('Tablet', 'bluetooth', 'Bluetooth working', 210),
  ('Tablet', 'battery', 'Battery charging and health', 220),
  ('Tablet', 'liquid', 'Liquid damage indicators', 230),
  ('Laptop', 'power', 'Power and boot', 10),
  ('Laptop', 'os_boot', 'Boot / operating system', 20),
  ('Laptop', 'display_lcd', 'Screen / display condition', 30),
  ('Laptop', 'touchscreen', 'Touchscreen (if fitted)', 40),
  ('Laptop', 'keyboard', 'Keyboard working', 50),
  ('Laptop', 'touchpad', 'Touch pad working', 60),
  ('Laptop', 'camera', 'Camera working', 70),
  ('Laptop', 'mic', 'Microphone working', 80),
  ('Laptop', 'speakers', 'Speakers working', 90),
  ('Laptop', 'wifi', 'Wi-Fi working', 100),
  ('Laptop', 'bluetooth', 'Bluetooth working', 110),
  ('Laptop', 'ports_io', 'USB / I/O ports', 120),
  ('Laptop', 'charging_port', 'Charging port and charger detection', 130),
  ('Laptop', 'battery', 'Battery health and charging', 140),
  ('Laptop', 'storage_check', 'Storage check', 150),
  ('Laptop', 'fans_thermal', 'Fan / thermal condition', 160),
  ('Laptop', 'hinges_housing', 'Hinges and housing condition', 170),
  ('Laptop', 'liquid', 'Liquid damage indicators', 180),
  ('Watch', 'power', 'Power and boot', 10),
  ('Watch', 'display_lcd', 'Display working', 20),
  ('Watch', 'touch', 'Touch working', 30),
  ('Watch', 'housing', 'Housing and glass intact', 40),
  ('Watch', 'buttons_crown', 'Buttons / crown working', 50),
  ('Watch', 'charging_port', 'Charging contacts working', 60),
  ('Watch', 'sensors', 'Heart rate and sensors', 70),
  ('Watch', 'speakers', 'Speaker and microphone', 80),
  ('Watch', 'bluetooth', 'Bluetooth / Wi-Fi pairing', 90),
  ('Watch', 'battery', 'Battery charging and health', 100),
  ('Watch', 'band', 'Band / strap present', 110),
  ('Watch', 'liquid', 'Liquid damage indicators', 120),
  ('Game Console', 'power', 'Power and boot', 10),
  ('Game Console', 'os_boot', 'Boot / system software', 20),
  ('Game Console', 'video_output', 'Video output working', 30),
  ('Game Console', 'controller_ports', 'Controller ports and pairing', 40),
  ('Game Console', 'disc_drive', 'Disc drive working (if fitted)', 50),
  ('Game Console', 'storage_check', 'Storage check', 60),
  ('Game Console', 'wifi', 'Wi-Fi / network working', 70),
  ('Game Console', 'fans_thermal', 'Fan / thermal condition', 80),
  ('Game Console', 'housing', 'Housing condition', 90),
  ('Game Console', 'accessories', 'Controller and cables present', 100),
  ('Game Console', 'liquid', 'Liquid damage indicators', 110),
  ('Other', 'power', 'Power and boot', 10),
  ('Other', 'display_lcd', 'Display working (if fitted)', 20),
  ('Other', 'housing', 'Housing condition', 30),
  ('Other', 'buttons_crown', 'Buttons and controls', 40),
  ('Other', 'charging_port', 'Charging port working', 50),
  ('Other', 'speakers', 'Audio working', 60),
  ('Other', 'bluetooth', 'Wireless connectivity', 70),
  ('Other', 'battery', 'Battery charging and health', 80),
  ('Other', 'accessories', 'Accessories present', 90),
  ('Other', 'liquid', 'Liquid damage indicators', 100);

-- Every active item for this category, answered pass or N/A. Anything else --
-- a fail, a blank, or a missing key -- keeps the device off the shelf.
create or replace function public.pos_used_device_inspection_complete(device_category text, answers jsonb)
returns boolean
language sql
stable
set search_path = ''
as $$
  select not exists (
    select 1
    from public.pos_used_device_inspection_items item
    where item.active
      and item.category = device_category
      and lower(coalesce(answers->>item.item_key, '')) not in ('pass', 'na')
  );
$$;

create or replace function public.get_pos_used_device_inspection_items(session_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select coalesce(jsonb_object_agg(category, items), '{}'::jsonb) into result
  from (
    select item.category,
      jsonb_agg(jsonb_build_object('key', item.item_key, 'label', item.label) order by item.position, item.id) as items
    from public.pos_used_device_inspection_items item
    where item.active
    group by item.category
  ) grouped;
  return jsonb_build_object('ok', true, 'checklists', result);
end;
$$;

revoke all on function public.pos_used_device_inspection_complete(text, jsonb) from public, anon, authenticated;
revoke all on function public.get_pos_used_device_inspection_items(text) from public, anon, authenticated;
grant execute on function public.pos_used_device_inspection_complete(text, jsonb) to service_role;
grant execute on function public.get_pos_used_device_inspection_items(text) to anon, authenticated, service_role;

-- Replace the count-based gate in update_pos_used_device with the checklist.
do $migration$
declare
  definition text;
  patched text;
begin
  select pg_get_functiondef(oid) into definition
  from pg_proc
  where proname = 'update_pos_used_device' and pronamespace = 'public'::regnamespace;
  if definition is null then raise exception 'update_pos_used_device was not found'; end if;

  patched := replace(
    definition,
    $anchor$    or (select count(*) from jsonb_each_text(inspection_value) result where lower(result.value) in ('pass', 'na')) < 8
    or exists (select 1 from jsonb_each_text(inspection_value) result where lower(result.value) not in ('pass', 'na'))$anchor$,
    $replacement$    or not public.pos_used_device_inspection_complete(device_row.category, inspection_value)$replacement$
  );
  if patched = definition then
    raise exception 'inspection checklist patch: the answer-count anchor was not found';
  end if;
  execute patched;
end;
$migration$;

comment on table public.pos_used_device_inspection_items is
  'The buyback inspection checklist, one row per item per category. The POS renders these and the ready-for-sale gate requires all of them.';
