create table if not exists public.pos_customers (
  id bigint generated by default as identity primary key,
  customer_code text not null unique,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  first_name text not null,
  last_name text not null default '',
  company text not null default '',
  phone text not null default '',
  normalized_phone text not null default '',
  alert_number text not null default '',
  email text not null default '',
  customer_group text not null default 'Regular Customer',
  notes text not null default '',
  created_by text not null,
  updated_by text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pos_customers_store_name_idx
on public.pos_customers (store_id, lower(first_name), lower(last_name))
where active = true;

create index if not exists pos_customers_store_phone_idx
on public.pos_customers (store_id, normalized_phone)
where active = true and normalized_phone <> '';

drop trigger if exists pos_customers_set_updated_at on public.pos_customers;
create trigger pos_customers_set_updated_at
before update on public.pos_customers
for each row execute function public.set_updated_at();

create table if not exists public.pos_held_carts (
  id bigint generated by default as identity primary key,
  hold_code text not null unique,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  customer_name text not null default 'Walk-in Customer',
  cart_payload jsonb not null,
  held_by text not null,
  status text not null default 'active' check (status in ('active', 'restored', 'discarded')),
  restored_by text,
  restored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pos_held_carts_store_active_idx
on public.pos_held_carts (store_id, created_at desc)
where status = 'active';

drop trigger if exists pos_held_carts_set_updated_at on public.pos_held_carts;
create trigger pos_held_carts_set_updated_at
before update on public.pos_held_carts
for each row execute function public.set_updated_at();

create table if not exists public.pos_store_shifts (
  id bigint generated by default as identity primary key,
  shift_code text not null unique,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  business_date date not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  opened_by text not null,
  current_staff_name text not null,
  last_staff_name text not null,
  opening_cash_total numeric(12,2) not null default 0 check (opening_cash_total >= 0),
  opening_counts jsonb not null default '{}'::jsonb,
  opening_confirmed_at timestamptz,
  system_totals jsonb not null default '{}'::jsonb,
  actual_totals jsonb not null default '{}'::jsonb,
  differences jsonb not null default '{}'::jsonb,
  closing_cash_total numeric(12,2),
  closing_counts jsonb not null default '{}'::jsonb,
  closed_by text,
  opened_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists pos_store_shifts_one_open_per_store_idx
on public.pos_store_shifts (store_id)
where status = 'open';

create index if not exists pos_store_shifts_store_date_idx
on public.pos_store_shifts (store_id, business_date desc, opened_at desc);

drop trigger if exists pos_store_shifts_set_updated_at on public.pos_store_shifts;
create trigger pos_store_shifts_set_updated_at
before update on public.pos_store_shifts
for each row execute function public.set_updated_at();

alter table public.pos_customers enable row level security;
alter table public.pos_held_carts enable row level security;
alter table public.pos_store_shifts enable row level security;

revoke all on public.pos_customers from public, anon, authenticated;
revoke all on public.pos_held_carts from public, anon, authenticated;
revoke all on public.pos_store_shifts from public, anon, authenticated;

grant select, insert, update on public.pos_customers to service_role;
grant select, insert, update on public.pos_held_carts to service_role;
grant select, insert, update on public.pos_store_shifts to service_role;

create or replace function public.pos_customer_payload(customer_row public.pos_customers)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', customer_row.customer_code,
    'first_name', customer_row.first_name,
    'last_name', customer_row.last_name,
    'company', customer_row.company,
    'phone', customer_row.phone,
    'alert_number', customer_row.alert_number,
    'email', customer_row.email,
    'group', customer_row.customer_group,
    'notes', customer_row.notes,
    'created_by', customer_row.created_by,
    'updated_by', customer_row.updated_by,
    'created_at', customer_row.created_at,
    'updated_at', customer_row.updated_at
  );
$$;

create or replace function public.search_pos_customers(
  session_token text,
  target_store_code text,
  search_query text default '',
  result_limit integer default 500
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  customers_payload jsonb;
  query_value text := trim(coalesce(search_query, ''));
  phone_query text := regexp_replace(coalesce(search_query, ''), '[^0-9]', '', 'g');
  safe_limit integer := least(greatest(coalesce(result_limit, 500), 1), 500);
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select coalesce(jsonb_agg(public.pos_customer_payload(customer) order by customer.updated_at desc), '[]'::jsonb)
  into customers_payload
  from (
    select customer.*
    from public.pos_customers customer
    where customer.store_id = selected_store.id
      and customer.active = true
      and (
        query_value = ''
        or customer.first_name ilike '%' || query_value || '%'
        or customer.last_name ilike '%' || query_value || '%'
        or concat_ws(' ', customer.first_name, customer.last_name) ilike '%' || query_value || '%'
        or customer.company ilike '%' || query_value || '%'
        or customer.phone ilike '%' || query_value || '%'
        or customer.alert_number ilike '%' || query_value || '%'
        or customer.email ilike '%' || query_value || '%'
        or (phone_query <> '' and customer.normalized_phone like '%' || phone_query || '%')
      )
    order by customer.updated_at desc
    limit safe_limit
  ) customer;

  return jsonb_build_object('ok', true, 'customers', customers_payload);
end;
$$;

create or replace function public.upsert_pos_customer(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  customer_row public.pos_customers%rowtype;
  customer_code_value text;
  first_name_value text := coalesce(trim(payload->>'first_name'), '');
  phone_value text := coalesce(trim(payload->>'phone'), '');
  alert_value text := coalesce(trim(payload->>'alert_number'), '');
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if jsonb_typeof(payload) <> 'object' then raise exception 'Customer payload must be an object'; end if;
  if first_name_value = '' then raise exception 'First name is required'; end if;
  if phone_value = '' and alert_value = '' then raise exception 'At least one phone number is required'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(payload->>'store_code'), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  customer_code_value := coalesce(nullif(trim(payload->>'id'), ''), 'CUS-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint);

  select * into customer_row
  from public.pos_customers customer
  where customer.customer_code = customer_code_value
  for update;

  if found then
    if customer_row.store_id <> selected_store.id then raise exception 'Customer belongs to another store'; end if;
    update public.pos_customers
    set
      first_name = first_name_value,
      last_name = coalesce(trim(payload->>'last_name'), ''),
      company = coalesce(trim(payload->>'company'), ''),
      phone = phone_value,
      normalized_phone = regexp_replace(phone_value, '[^0-9]', '', 'g'),
      alert_number = alert_value,
      email = lower(coalesce(trim(payload->>'email'), '')),
      customer_group = coalesce(nullif(trim(payload->>'group'), ''), 'Regular Customer'),
      notes = coalesce(trim(payload->>'notes'), ''),
      updated_by = selected_staff.display_name,
      active = true
    where customer_code = customer_code_value
    returning * into customer_row;
  else
    insert into public.pos_customers (
      customer_code, store_id, first_name, last_name, company, phone, normalized_phone,
      alert_number, email, customer_group, notes, created_by, updated_by
    ) values (
      customer_code_value, selected_store.id, first_name_value,
      coalesce(trim(payload->>'last_name'), ''), coalesce(trim(payload->>'company'), ''),
      phone_value, regexp_replace(phone_value, '[^0-9]', '', 'g'), alert_value,
      lower(coalesce(trim(payload->>'email'), '')),
      coalesce(nullif(trim(payload->>'group'), ''), 'Regular Customer'),
      coalesce(trim(payload->>'notes'), ''), selected_staff.display_name, selected_staff.display_name
    ) returning * into customer_row;
  end if;

  return jsonb_build_object('ok', true, 'customer', public.pos_customer_payload(customer_row));
end;
$$;

create or replace function public.pos_held_cart_payload(hold_row public.pos_held_carts)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select hold_row.cart_payload || jsonb_build_object(
    'id', hold_row.hold_code,
    'customer', hold_row.customer_name,
    'held_by', hold_row.held_by,
    'status', hold_row.status,
    'created_at', hold_row.created_at,
    'updated_at', hold_row.updated_at
  );
$$;

create or replace function public.get_pos_held_carts(session_token text, target_store_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  carts_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select coalesce(jsonb_agg(public.pos_held_cart_payload(held_cart) order by held_cart.created_at desc), '[]'::jsonb)
  into carts_payload
  from public.pos_held_carts held_cart
  where held_cart.store_id = selected_store.id and held_cart.status = 'active';

  return jsonb_build_object('ok', true, 'holds', carts_payload);
end;
$$;

create or replace function public.save_pos_held_cart(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  hold_row public.pos_held_carts%rowtype;
  hold_code_value text;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if jsonb_typeof(payload) <> 'object' then raise exception 'Held cart payload must be an object'; end if;
  if jsonb_typeof(payload->'items') <> 'array' or jsonb_array_length(payload->'items') = 0 then
    raise exception 'Held cart must contain at least one item';
  end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(payload->>'store_code'), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  hold_code_value := coalesce(nullif(trim(payload->>'id'), ''), 'HOLD-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint);
  insert into public.pos_held_carts (
    hold_code, store_id, customer_name, cart_payload, held_by, status
  ) values (
    hold_code_value, selected_store.id,
    coalesce(nullif(trim(payload->>'customer'), ''), 'Walk-in Customer'),
    payload, selected_staff.display_name, 'active'
  )
  on conflict (hold_code) do update set
    customer_name = excluded.customer_name,
    cart_payload = excluded.cart_payload,
    held_by = excluded.held_by,
    status = 'active',
    restored_by = null,
    restored_at = null
  where public.pos_held_carts.store_id = excluded.store_id
  returning * into hold_row;

  if not found then raise exception 'Held cart belongs to another store'; end if;
  return jsonb_build_object('ok', true, 'hold', public.pos_held_cart_payload(hold_row));
end;
$$;

create or replace function public.restore_pos_held_cart(
  session_token text,
  target_store_code text,
  target_hold_code text,
  staff_name text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  hold_row public.pos_held_carts%rowtype;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(staff_name), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  update public.pos_held_carts
  set status = 'restored', restored_by = selected_staff.display_name, restored_at = now()
  where hold_code = coalesce(trim(target_hold_code), '')
    and store_id = selected_store.id
    and status = 'active'
  returning * into hold_row;

  if not found then raise exception 'Held cart is no longer available'; end if;
  return jsonb_build_object('ok', true, 'hold', public.pos_held_cart_payload(hold_row));
end;
$$;

create or replace function public.pos_store_shift_payload(shift_row public.pos_store_shifts)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', shift_row.shift_code,
    'business_date', shift_row.business_date,
    'status', shift_row.status,
    'opened_by', shift_row.opened_by,
    'current_staff_name', shift_row.current_staff_name,
    'last_staff_name', shift_row.last_staff_name,
    'opening_cash_total', shift_row.opening_cash_total,
    'opening_counts', shift_row.opening_counts,
    'opening_confirmed_at', shift_row.opening_confirmed_at,
    'system_totals', shift_row.system_totals,
    'actual_totals', shift_row.actual_totals,
    'differences', shift_row.differences,
    'closing_cash_total', shift_row.closing_cash_total,
    'closing_counts', shift_row.closing_counts,
    'closed_by', shift_row.closed_by,
    'opened_at', shift_row.opened_at,
    'last_seen_at', shift_row.last_seen_at,
    'closed_at', shift_row.closed_at
  );
$$;

create or replace function public.get_pos_store_shift(session_token text, target_store_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  shift_row public.pos_store_shifts%rowtype;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into shift_row
  from public.pos_store_shifts shift_record
  where shift_record.store_id = selected_store.id and shift_record.status = 'open'
  limit 1;

  return jsonb_build_object(
    'ok', true,
    'shift', case when found then public.pos_store_shift_payload(shift_row) else null end
  );
end;
$$;

create or replace function public.open_pos_store_shift(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  shift_row public.pos_store_shifts%rowtype;
  shift_code_value text;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if jsonb_typeof(payload) <> 'object' then raise exception 'Shift payload must be an object'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(payload->>'store_code'), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  perform pg_catalog.pg_advisory_xact_lock(selected_store.id);
  select * into shift_row
  from public.pos_store_shifts shift_record
  where shift_record.store_id = selected_store.id and shift_record.status = 'open'
  for update;

  if found then
    update public.pos_store_shifts
    set current_staff_name = selected_staff.display_name,
        last_staff_name = selected_staff.display_name,
        last_seen_at = now()
    where id = shift_row.id
    returning * into shift_row;
  else
    shift_code_value := coalesce(nullif(trim(payload->>'id'), ''), 'SHIFT-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint);
    insert into public.pos_store_shifts (
      shift_code, store_id, business_date, opened_by, current_staff_name, last_staff_name, opened_at, last_seen_at
    ) values (
      shift_code_value, selected_store.id,
      coalesce(nullif(payload->>'business_date', '')::date, (now() at time zone 'Australia/Brisbane')::date),
      selected_staff.display_name, selected_staff.display_name, selected_staff.display_name,
      coalesce(nullif(payload->>'opened_at', '')::timestamptz, now()), now()
    ) returning * into shift_row;
  end if;

  return jsonb_build_object('ok', true, 'shift', public.pos_store_shift_payload(shift_row));
end;
$$;

create or replace function public.save_pos_shift_opening(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_staff public.staff_directory%rowtype;
  shift_row public.pos_store_shifts%rowtype;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  select * into shift_row
  from public.pos_store_shifts shift_record
  where shift_record.shift_code = coalesce(trim(payload->>'shift_id'), '') and shift_record.status = 'open'
  for update;
  if not found then raise exception 'Open shift not found'; end if;

  if shift_row.opening_confirmed_at is null then
    update public.pos_store_shifts
    set opening_cash_total = round(greatest(coalesce(nullif(payload->>'total', '')::numeric, 0), 0), 2),
        opening_counts = coalesce(payload->'counts', '{}'::jsonb),
        opening_confirmed_at = now(),
        current_staff_name = selected_staff.display_name,
        last_staff_name = selected_staff.display_name,
        last_seen_at = now()
    where id = shift_row.id
    returning * into shift_row;
  end if;

  return jsonb_build_object('ok', true, 'shift', public.pos_store_shift_payload(shift_row));
end;
$$;

create or replace function public.close_pos_store_shift(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_staff public.staff_directory%rowtype;
  shift_row public.pos_store_shifts%rowtype;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true and lower(staff.display_name) = lower(coalesce(trim(payload->>'staff_name'), ''))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  update public.pos_store_shifts
  set status = 'closed',
      current_staff_name = selected_staff.display_name,
      last_staff_name = selected_staff.display_name,
      system_totals = coalesce(payload->'system', '{}'::jsonb),
      actual_totals = coalesce(payload->'actual', '{}'::jsonb),
      differences = coalesce(payload->'differences', '{}'::jsonb),
      closing_cash_total = round(greatest(coalesce(nullif(payload->>'closing_cash_total', '')::numeric, 0), 0), 2),
      closing_counts = coalesce(payload->'cash_counts', '{}'::jsonb),
      closed_by = selected_staff.display_name,
      closed_at = now(),
      last_seen_at = now()
  where shift_code = coalesce(trim(payload->>'shift_id'), '') and status = 'open'
  returning * into shift_row;

  if not found then raise exception 'Open shift not found'; end if;
  return jsonb_build_object('ok', true, 'shift', public.pos_store_shift_payload(shift_row));
end;
$$;

create or replace function public.get_pos_shift_payment_totals(session_token text, target_shift_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  shift_row public.pos_store_shifts%rowtype;
  totals_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;

  select * into shift_row
  from public.pos_store_shifts shift_record
  where shift_record.shift_code = coalesce(trim(target_shift_code), '')
  limit 1;
  if not found then raise exception 'Shift not found'; end if;

  with received as (
    select payment.method, round(sum(payment.amount), 2) as amount
    from public.pos_sales_order_payments payment
    join public.pos_sales_orders sales_order on sales_order.id = payment.sales_order_id
    where sales_order.store_id = shift_row.store_id
      and sales_order.shift_id = shift_row.shift_code
    group by payment.method
  ),
  refunded as (
    select refund.method, round(sum(refund.amount), 2) as amount
    from public.pos_sales_refunds refund
    where refund.store_id = shift_row.store_id
      and refund.created_at >= shift_row.opened_at
      and (shift_row.closed_at is null or refund.created_at <= shift_row.closed_at)
    group by refund.method
  ),
  methods as (
    select method from received
    union
    select method from refunded
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'method', methods.method,
    'received', coalesce(received.amount, 0),
    'refunded', coalesce(refunded.amount, 0),
    'amount', coalesce(received.amount, 0) - coalesce(refunded.amount, 0)
  ) order by methods.method), '[]'::jsonb)
  into totals_payload
  from methods
  left join received on received.method = methods.method
  left join refunded on refunded.method = methods.method;

  return jsonb_build_object(
    'ok', true,
    'shift_id', shift_row.shift_code,
    'payment_totals', totals_payload,
    'order_count', (
      select count(*) from public.pos_sales_orders sales_order
      where sales_order.store_id = shift_row.store_id and sales_order.shift_id = shift_row.shift_code
    ),
    'gross_sales', (
      select coalesce(sum(sales_order.total), 0) from public.pos_sales_orders sales_order
      where sales_order.store_id = shift_row.store_id and sales_order.shift_id = shift_row.shift_code
    )
  );
end;
$$;

create or replace function public.get_pos_sales_report(
  session_token text,
  target_store_code text,
  date_from date,
  date_to date,
  target_staff_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  from_value date := coalesce(date_from, (now() at time zone 'Australia/Brisbane')::date);
  to_value date := coalesce(date_to, date_from, (now() at time zone 'Australia/Brisbane')::date);
  staff_value text := nullif(trim(coalesce(target_staff_name, '')), '');
  report_payload jsonb;
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if from_value > to_value then raise exception 'Start date must not be after end date'; end if;
  if to_value - from_value > 366 then raise exception 'Report range cannot exceed 367 days'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  with sale_orders as (
    select sales_order.*
    from public.pos_sales_orders sales_order
    where sales_order.store_id = selected_store.id
      and sales_order.business_date between from_value and to_value
      and (staff_value is null or lower(sales_order.staff_name) = lower(staff_value))
  ),
  refund_rows as (
    select refund.*, (refund.created_at at time zone 'Australia/Brisbane')::date as business_date
    from public.pos_sales_refunds refund
    where refund.store_id = selected_store.id
      and (refund.created_at at time zone 'Australia/Brisbane')::date between from_value and to_value
      and (staff_value is null or lower(refund.staff_name) = lower(staff_value))
  ),
  sale_lines as (
    select sales_line.*
    from public.pos_sales_order_lines sales_line
    join sale_orders sales_order on sales_order.id = sales_line.sales_order_id
  ),
  refunded_lines as (
    select refund_line.amount, sales_line.line_type, sales_line.category, sales_line.quantity
    from public.pos_sales_refund_lines refund_line
    join refund_rows refund on refund.id = refund_line.refund_id
    join public.pos_sales_order_lines sales_line on sales_line.id = refund_line.sales_order_line_id
  ),
  summary as (
    select
      coalesce((select sum(total) from sale_orders), 0)::numeric(12,2) as gross_sales,
      coalesce((select sum(amount) from refund_rows), 0)::numeric(12,2) as refunds,
      coalesce((select count(*) from sale_orders), 0)::integer as invoice_count,
      coalesce((select count(*) from refund_rows), 0)::integer as refund_count,
      coalesce((select sum(quantity) from sale_lines), 0)::integer as item_units
  )
  select jsonb_build_object(
    'ok', true,
    'store_code', selected_store.store_code,
    'store_name', selected_store.store_name,
    'date_from', from_value,
    'date_to', to_value,
    'staff_name', staff_value,
    'summary', jsonb_build_object(
      'gross_sales', summary.gross_sales,
      'refunds', summary.refunds,
      'net_sales', summary.gross_sales - summary.refunds,
      'gst', round((summary.gross_sales - summary.refunds) / 11, 2),
      'invoice_count', summary.invoice_count,
      'refund_count', summary.refund_count,
      'item_units', summary.item_units,
      'average_sale', case when summary.invoice_count > 0 then round(summary.gross_sales / summary.invoice_count, 2) else 0 end
    ),
    'payment_totals', (
      select coalesce(jsonb_agg(jsonb_build_object('method', payment.method, 'amount', payment.amount) order by payment.amount desc), '[]'::jsonb)
      from (
        select order_payment.method, round(sum(order_payment.amount), 2) as amount
        from public.pos_sales_order_payments order_payment
        join sale_orders sales_order on sales_order.id = order_payment.sales_order_id
        group by order_payment.method
      ) payment
    ),
    'refund_method_totals', (
      select coalesce(jsonb_agg(jsonb_build_object('method', refund.method, 'amount', refund.amount) order by refund.amount desc), '[]'::jsonb)
      from (
        select refund_row.method, round(sum(refund_row.amount), 2) as amount
        from refund_rows refund_row
        group by refund_row.method
      ) refund
    ),
    'sale_type_totals', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'type', line_type.line_type,
        'gross', line_type.gross,
        'refunds', line_type.refunds,
        'net', line_type.gross - line_type.refunds,
        'units', line_type.units
      ) order by line_type.gross - line_type.refunds desc), '[]'::jsonb)
      from (
        select type_key.line_type,
          coalesce((select sum(line_total) from sale_lines where sale_lines.line_type = type_key.line_type), 0)::numeric(12,2) as gross,
          coalesce((select sum(amount) from refunded_lines where refunded_lines.line_type = type_key.line_type), 0)::numeric(12,2) as refunds,
          coalesce((select sum(quantity) from sale_lines where sale_lines.line_type = type_key.line_type), 0)::integer as units
        from (
          select line_type from sale_lines
          union
          select line_type from refunded_lines
        ) type_key
      ) line_type
    ),
    'category_totals', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'category', category.category,
        'gross', category.gross,
        'refunds', category.refunds,
        'net', category.gross - category.refunds,
        'units', category.units
      ) order by category.gross - category.refunds desc), '[]'::jsonb)
      from (
        select category_key.category,
          coalesce((select sum(line_total) from sale_lines where coalesce(nullif(trim(sale_lines.category), ''), 'Uncategorized') = category_key.category), 0)::numeric(12,2) as gross,
          coalesce((select sum(amount) from refunded_lines where coalesce(nullif(trim(refunded_lines.category), ''), 'Uncategorized') = category_key.category), 0)::numeric(12,2) as refunds,
          coalesce((select sum(quantity) from sale_lines where coalesce(nullif(trim(sale_lines.category), ''), 'Uncategorized') = category_key.category), 0)::integer as units
        from (
          select coalesce(nullif(trim(category), ''), 'Uncategorized') as category from sale_lines
          union
          select coalesce(nullif(trim(category), ''), 'Uncategorized') as category from refunded_lines
        ) category_key
      ) category
    ),
    'staff_totals', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'staff_name', staff.staff_name,
        'gross', staff.gross,
        'refunds', staff.refunds,
        'net', staff.gross - staff.refunds,
        'invoice_count', staff.invoice_count,
        'refund_count', staff.refund_count
      ) order by staff.gross - staff.refunds desc), '[]'::jsonb)
      from (
        select staff_key.staff_name,
          coalesce((select sum(total) from sale_orders where sale_orders.staff_name = staff_key.staff_name), 0)::numeric(12,2) as gross,
          coalesce((select sum(amount) from refund_rows where refund_rows.staff_name = staff_key.staff_name), 0)::numeric(12,2) as refunds,
          coalesce((select count(*) from sale_orders where sale_orders.staff_name = staff_key.staff_name), 0)::integer as invoice_count,
          coalesce((select count(*) from refund_rows where refund_rows.staff_name = staff_key.staff_name), 0)::integer as refund_count
        from (
          select staff_name from sale_orders
          union
          select staff_name from refund_rows
        ) staff_key
      ) staff
    ),
    'daily_totals', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'date', daily.business_date,
        'gross', daily.gross,
        'refunds', daily.refunds,
        'net', daily.gross - daily.refunds,
        'invoice_count', daily.invoice_count
      ) order by daily.business_date), '[]'::jsonb)
      from (
        select date_key.business_date,
          coalesce((select sum(total) from sale_orders where sale_orders.business_date = date_key.business_date), 0)::numeric(12,2) as gross,
          coalesce((select sum(amount) from refund_rows where refund_rows.business_date = date_key.business_date), 0)::numeric(12,2) as refunds,
          coalesce((select count(*) from sale_orders where sale_orders.business_date = date_key.business_date), 0)::integer as invoice_count
        from (
          select business_date from sale_orders
          union
          select business_date from refund_rows
        ) date_key
      ) daily
    )
  ) into report_payload
  from summary;

  return report_payload;
end;
$$;

revoke execute on function public.pos_customer_payload(public.pos_customers) from public, anon, authenticated;
revoke execute on function public.pos_held_cart_payload(public.pos_held_carts) from public, anon, authenticated;
revoke execute on function public.pos_store_shift_payload(public.pos_store_shifts) from public, anon, authenticated;
revoke execute on function public.search_pos_customers(text, text, text, integer) from public;
revoke execute on function public.upsert_pos_customer(text, jsonb) from public;
revoke execute on function public.get_pos_held_carts(text, text) from public;
revoke execute on function public.save_pos_held_cart(text, jsonb) from public;
revoke execute on function public.restore_pos_held_cart(text, text, text, text) from public;
revoke execute on function public.get_pos_store_shift(text, text) from public;
revoke execute on function public.open_pos_store_shift(text, jsonb) from public;
revoke execute on function public.save_pos_shift_opening(text, jsonb) from public;
revoke execute on function public.close_pos_store_shift(text, jsonb) from public;
revoke execute on function public.get_pos_shift_payment_totals(text, text) from public;
revoke execute on function public.get_pos_sales_report(text, text, date, date, text) from public;

grant execute on function public.search_pos_customers(text, text, text, integer) to anon, authenticated, service_role;
grant execute on function public.upsert_pos_customer(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.get_pos_held_carts(text, text) to anon, authenticated, service_role;
grant execute on function public.save_pos_held_cart(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.restore_pos_held_cart(text, text, text, text) to anon, authenticated, service_role;
grant execute on function public.get_pos_store_shift(text, text) to anon, authenticated, service_role;
grant execute on function public.open_pos_store_shift(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.save_pos_shift_opening(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.close_pos_store_shift(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.get_pos_shift_payment_totals(text, text) to anon, authenticated, service_role;
grant execute on function public.get_pos_sales_report(text, text, date, date, text) to anon, authenticated, service_role;
