-- Publishing a device to the public website.
--
-- The website catalogue lives in a different Supabase project, so there is no
-- transaction that can span the two. Writing straight across would mean a
-- half-published device whenever the network blinked. Instead the POS records
-- an intention -- publish, withdraw, sold -- and a worker carries it over and
-- reports back. A device that fails to publish stays queued and visibly failed
-- rather than silently disagreeing with the shop floor.
--
-- Only one intention per device is ever pending: a later one replaces the
-- earlier one, and `source_version` from a sequence lets the website reject a
-- slow retry that would otherwise undo a newer state.

create sequence public.pos_used_device_publish_version_seq;

alter table public.pos_used_devices
  add column website_status text not null default 'not_published'
    check (website_status in ('not_published', 'queued', 'published', 'withdrawn', 'failed')),
  add column website_slug text not null default '',
  add column website_synced_at timestamptz;

create table public.pos_used_device_publish_queue (
  id bigint generated by default as identity primary key,
  device_id bigint not null references public.pos_used_devices(id) on delete restrict,
  device_code text not null,
  action text not null check (action in ('publish', 'withdraw', 'sold')),
  source_version bigint not null,
  requested_by text not null default 'system',
  requested_at timestamptz not null default now(),
  claimed_at timestamptz,
  attempts integer not null default 0,
  last_error text not null default '',
  completed_at timestamptz
);

create unique index pos_used_device_publish_queue_pending_idx
  on public.pos_used_device_publish_queue (device_id)
  where completed_at is null;

create index pos_used_device_publish_queue_ready_idx
  on public.pos_used_device_publish_queue (requested_at)
  where completed_at is null;

alter table public.pos_used_device_publish_queue enable row level security;
revoke all on public.pos_used_device_publish_queue from public, anon, authenticated;
grant all on public.pos_used_device_publish_queue to service_role;

-- Marketing copy that a person should be able to change without a migration.
create table public.pos_used_device_listing_copy (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.pos_used_device_listing_copy (key, value) values
  ('condition.As New', 'As new. No visible marks.'),
  ('condition.Good', 'Good condition. Light signs of use.'),
  ('condition.Fair', 'Fair condition. Visible marks from normal use.'),
  ('condition.Poor', 'Heavy cosmetic wear. Fully working and tested.'),
  ('condition.Faulty', 'Sold as is, with known faults. Ask us before you buy.'),
  ('closing', 'Every second-hand device is tested in store against our full inspection checklist, reset, and cleared of the previous owner''s account before it goes on sale.');

alter table public.pos_used_device_listing_copy enable row level security;
revoke all on public.pos_used_device_listing_copy from public, anon, authenticated;
grant all on public.pos_used_device_listing_copy to service_role;

-- The public description, built from the inspection record.
--
-- This function decides what the world sees, so it reads only the fields that
-- are safe to show. It never touches the IMEI, the serial number, the seller,
-- the purchase price, or the internal memo.
create or replace function public.pos_used_device_listing_payload(target_device_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  device_row public.pos_used_devices%rowtype;
  store_row public.store_locations%rowtype;
  checklist_total integer;
  checklist_passed integer;
  highlights jsonb := '[]'::jsonb;
  condition_line text;
  closing_line text;
  description_text text;
  title_text text;
  images_payload jsonb;
begin
  select * into device_row from public.pos_used_devices where id = target_device_id;
  if not found then raise exception 'Used device not found'; end if;
  select * into store_row from public.store_locations where id = device_row.store_id;

  select count(*) into checklist_total
  from public.pos_used_device_inspection_items item
  where item.active and item.category = device_row.category;

  select count(*) into checklist_passed
  from public.pos_used_device_inspection_items item
  where item.active and item.category = device_row.category
    and lower(coalesce(device_row.inspection->>item.item_key, '')) = 'pass';

  select coalesce(value, 'Tested in store before sale.') into condition_line
  from public.pos_used_device_listing_copy where key = 'condition.' || device_row.condition_grade;
  select coalesce(value, '') into closing_line
  from public.pos_used_device_listing_copy where key = 'closing';

  if checklist_total > 0 then
    highlights := highlights || to_jsonb(format('%s of %s inspection checks passed', checklist_passed, checklist_total));
  end if;
  if device_row.battery_health is not null then
    highlights := highlights || to_jsonb(format('Battery health %s%%', device_row.battery_health));
  end if;
  if device_row.storage <> '' then
    highlights := highlights || to_jsonb(device_row.storage || ' storage');
  end if;
  if device_row.data_erased_confirmed then
    highlights := highlights || to_jsonb('Wiped and reset, ready to set up'::text);
  end if;
  if device_row.activation_lock_removed then
    highlights := highlights || to_jsonb('No previous owner account attached'::text);
  end if;
  if store_row.store_name is not null then
    highlights := highlights || to_jsonb('In stock at ' || store_row.store_name);
  end if;

  title_text := btrim(regexp_replace(
    concat_ws(' ', device_row.brand, device_row.model, nullif(device_row.storage, ''), nullif(device_row.color, '')),
    '\s+', ' ', 'g'));

  description_text := btrim(concat_ws(E'\n\n', condition_line, nullif(closing_line, '')));

  -- Numbered in a subquery: a window function cannot live inside the aggregate
  -- that collects it.
  select coalesce(jsonb_agg(jsonb_build_object(
    'storage_path', ordered.storage_path,
    'position', ordered.position
  ) order by ordered.position), '[]'::jsonb) into images_payload
  from (
    select entry.storage_path,
           row_number() over (order by entry.created_at, entry.id) as position
    from public.pos_used_device_updates entry
    where entry.device_id = device_row.id and entry.kind = 'photo' and entry.stage = 'listing'
  ) ordered;

  return jsonb_build_object(
    'device_code', device_row.device_code,
    'device_category', device_row.category,
    'store_code', coalesce(store_row.store_code, ''),
    'title', title_text,
    'brand', device_row.brand,
    'model', device_row.model,
    'storage', device_row.storage,
    'color', device_row.color,
    'condition_grade', device_row.condition_grade,
    'condition_summary', condition_line,
    'battery_health', device_row.battery_health,
    'price', device_row.sale_price,
    'description', description_text,
    'highlights', highlights,
    'images', images_payload,
    'website_status', device_row.website_status,
    'website_slug', device_row.website_slug
  );
end;
$$;

-- Queues the intention only. Marking the device `queued` is the caller's job,
-- so the trigger below can do it on the row it is already writing instead of
-- updating the same row from inside its own trigger.
create or replace function public.enqueue_pos_used_device_publish(
  target_device_id bigint,
  target_device_code text,
  target_action text,
  actor_name text default 'system'
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  version_value bigint := nextval('public.pos_used_device_publish_version_seq');
  queue_id bigint;
begin
  if target_action not in ('publish', 'withdraw', 'sold') then raise exception 'Invalid publish action'; end if;

  -- One pending intention per device. A newer one replaces whatever was
  -- waiting, so a device that goes ready then sold in a minute publishes once.
  insert into public.pos_used_device_publish_queue (device_id, device_code, action, source_version, requested_by)
  values (target_device_id, target_device_code, target_action, version_value, coalesce(nullif(actor_name, ''), 'system'))
  on conflict (device_id) where completed_at is null
  do update set
    action = excluded.action,
    source_version = excluded.source_version,
    requested_by = excluded.requested_by,
    requested_at = now(),
    claimed_at = null,
    attempts = 0,
    last_error = ''
  returning id into queue_id;

  return queue_id;
end;
$$;

-- Status and price changes drive the website by themselves. Staff do not have
-- to remember to take a sold device down.
create or replace function public.queue_pos_used_device_website_sync()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  action_value text;
begin
  if new.status = 'sold' and old.status <> 'sold' then
    action_value := 'sold';
  elsif new.status = 'ready_for_sale'
    and (old.status <> 'ready_for_sale' or new.sale_price is distinct from old.sale_price) then
    -- Newly on the shelf, or a change the public page needs to show.
    action_value := 'publish';
  elsif old.status = 'ready_for_sale' and new.status <> 'ready_for_sale' then
    action_value := 'withdraw';
  else
    return new;
  end if;

  perform public.enqueue_pos_used_device_publish(new.id, new.device_code, action_value, new.updated_by);
  new.website_status := 'queued';
  return new;
end;
$$;

drop trigger if exists pos_used_devices_queue_website_sync on public.pos_used_devices;
create trigger pos_used_devices_queue_website_sync
before update of status, sale_price on public.pos_used_devices
for each row execute function public.queue_pos_used_device_website_sync();

-- The worker's two calls: take work, then say what happened.
create or replace function public.claim_pos_used_device_publish_batch(batch_limit integer default 10)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  safe_limit integer := least(greatest(coalesce(batch_limit, 10), 1), 50);
  result jsonb;
begin
  with claimed as (
    update public.pos_used_device_publish_queue queue
    set claimed_at = now(), attempts = queue.attempts + 1
    where queue.id in (
      select inner_queue.id
      from public.pos_used_device_publish_queue inner_queue
      where inner_queue.completed_at is null
        and inner_queue.attempts < 5
        and (inner_queue.claimed_at is null or inner_queue.claimed_at < now() - interval '5 minutes')
      order by inner_queue.requested_at
      limit safe_limit
      for update skip locked
    )
    returning queue.*
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'queue_id', claimed.id,
    'action', claimed.action,
    'source_version', claimed.source_version,
    'attempts', claimed.attempts,
    'listing', public.pos_used_device_listing_payload(claimed.device_id)
  ) order by claimed.requested_at), '[]'::jsonb) into result
  from claimed;

  return jsonb_build_object('ok', true, 'items', result);
end;
$$;

create or replace function public.complete_pos_used_device_publish(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  queue_id bigint := nullif(payload->>'queue_id', '')::bigint;
  succeeded boolean := lower(coalesce(payload->>'ok', 'false')) = 'true';
  slug_value text := trim(coalesce(payload->>'slug', ''));
  error_value text := left(trim(coalesce(payload->>'error', '')), 500);
  queue_row public.pos_used_device_publish_queue%rowtype;
begin
  select * into queue_row from public.pos_used_device_publish_queue where id = queue_id for update;
  if not found then raise exception 'Publish request not found'; end if;
  if queue_row.completed_at is not null then
    return jsonb_build_object('ok', true, 'already_completed', true);
  end if;

  if succeeded then
    update public.pos_used_device_publish_queue
    set completed_at = now(), last_error = ''
    where id = queue_row.id;

    update public.pos_used_devices
    set website_status = case queue_row.action when 'publish' then 'published' else 'withdrawn' end,
        website_slug = case when slug_value <> '' then slug_value else website_slug end,
        website_synced_at = now()
    where id = queue_row.device_id;
    return jsonb_build_object('ok', true, 'completed', true);
  end if;

  update public.pos_used_device_publish_queue
  set last_error = error_value, claimed_at = null
  where id = queue_row.id;

  -- Five tries is enough to distinguish a blip from a broken listing.
  if queue_row.attempts >= 5 then
    update public.pos_used_devices set website_status = 'failed' where id = queue_row.device_id;
  end if;
  return jsonb_build_object('ok', true, 'completed', false, 'attempts', queue_row.attempts);
end;
$$;

-- The POS button: publish or take down this one device now.
create or replace function public.request_pos_used_device_publish(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  device_row public.pos_used_devices%rowtype;
  action_value text := coalesce(nullif(trim(payload->>'action'), ''), 'publish');
begin
  context := public.authorize_pos_used_device_evidence(
    session_token, payload->>'store_code', payload->>'device_code');
  select * into device_row from public.pos_used_devices where id = (context->>'device_id')::bigint;

  if action_value not in ('publish', 'withdraw') then raise exception 'Invalid publish action'; end if;
  if action_value = 'publish' then
    if device_row.status <> 'ready_for_sale' then
      raise exception 'Only a device that is ready for sale can go on the website';
    end if;
    if not exists (
      select 1 from public.pos_used_device_updates entry
      where entry.device_id = device_row.id and entry.kind = 'photo' and entry.stage = 'listing'
    ) then
      raise exception 'Add at least one listing photo before publishing';
    end if;
  end if;

  perform public.enqueue_pos_used_device_publish(
    device_row.id, device_row.device_code, action_value, context->>'author');
  update public.pos_used_devices set website_status = 'queued' where id = device_row.id;
  return jsonb_build_object('ok', true, 'device_code', device_row.device_code, 'website_status', 'queued');
end;
$$;

-- What the POS shows against a device: where it stands on the website, and the
-- reason if the last attempt did not get there.
create or replace function public.get_pos_used_device_website_status(session_token text, store_code text, device_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  device_row public.pos_used_devices%rowtype;
  queue_row public.pos_used_device_publish_queue%rowtype;
begin
  context := public.authorize_pos_used_device_evidence(session_token, store_code, device_code);
  select * into device_row from public.pos_used_devices where id = (context->>'device_id')::bigint;
  select * into queue_row from public.pos_used_device_publish_queue
  where device_id = device_row.id and completed_at is null
  order by requested_at desc limit 1;

  return jsonb_build_object(
    'ok', true,
    'website_status', device_row.website_status,
    'website_slug', device_row.website_slug,
    'website_synced_at', device_row.website_synced_at,
    'listing_photo_count', (
      select count(*) from public.pos_used_device_updates entry
      where entry.device_id = device_row.id and entry.kind = 'photo' and entry.stage = 'listing'
    ),
    'can_publish', device_row.status = 'ready_for_sale',
    'pending', case when queue_row.id is null then null else jsonb_build_object(
      'action', queue_row.action,
      'requested_at', queue_row.requested_at,
      'attempts', queue_row.attempts,
      'last_error', queue_row.last_error
    ) end
  );
end;
$$;

revoke all on function public.get_pos_used_device_website_status(text, text, text) from public, anon, authenticated;
grant execute on function public.get_pos_used_device_website_status(text, text, text) to service_role;

revoke all on function public.pos_used_device_listing_payload(bigint) from public, anon, authenticated;
revoke all on function public.enqueue_pos_used_device_publish(bigint, text, text, text) from public, anon, authenticated;
revoke all on function public.queue_pos_used_device_website_sync() from public, anon, authenticated;
revoke all on function public.claim_pos_used_device_publish_batch(integer) from public, anon, authenticated;
revoke all on function public.complete_pos_used_device_publish(jsonb) from public, anon, authenticated;
revoke all on function public.request_pos_used_device_publish(text, jsonb) from public, anon, authenticated;

grant execute on function public.pos_used_device_listing_payload(bigint) to service_role;
grant execute on function public.enqueue_pos_used_device_publish(bigint, text, text, text) to service_role;
grant execute on function public.claim_pos_used_device_publish_batch(integer) to service_role;
grant execute on function public.complete_pos_used_device_publish(jsonb) to service_role;
grant execute on function public.request_pos_used_device_publish(text, jsonb) to service_role;

comment on table public.pos_used_device_publish_queue is
  'One pending website intention per device. The worker in pos-used-device-publish drains it; source_version lets the website reject a stale retry.';

comment on function public.pos_used_device_listing_payload(bigint) is
  'Everything the public listing shows, built from the inspection record. Deliberately reads no IMEI, serial number, seller detail, purchase price or internal memo.';
