-- Inter-store used-device transfer, and a network view of every store's stock.
--
-- Two things staff could not do before this:
--
--   1. Move a second-hand device to another store. Stock Transfer only moves
--      counted product lines (model + variant + quantity). A used device is a
--      single serialised item with its own history, so it could not ride on a
--      quantity line, and there was no other route. Devices moved physically
--      and the register silently went stale.
--   2. See what the other stores are holding. Every used-device read was
--      hard-scoped to one store, so a customer asking "do you have a 13 Pro
--      Max?" could only be answered for the store standing in front of them.
--
-- HOW THE TRANSFER IS MADE TRUSTWORTHY
--
-- Ownership moves on RECEIPT, never on dispatch. Between the two the device is
-- in transit: the sending store can no longer sell it, publish it or send it
-- again, and the receiving store does not own it yet. Nothing is ever in two
-- places, and nothing is in no place.
--
-- Each transfer freezes a `device_snapshot` at dispatch: what was handed over,
-- by IMEI, condition, battery and price, as it read at that moment. Editing the
-- device afterwards cannot rewrite what the transfer says was sent. If a phone
-- arrives in worse condition than it left, the snapshot is the evidence.
--
-- Both ends write to pos_used_device_transactions, the same ledger the buyback
-- and the sale write to, so one device's whole life reads in one place:
-- transfer_out at the sender, transfer_in at the receiver, transfer_cancelled
-- if it is recalled.
--
-- Only the sending store can send or cancel; only the receiving store can
-- receive. That is enforced in the database, not in the page, so it holds no
-- matter who calls it.
--
-- WHAT THE NETWORK VIEW DELIBERATELY DOES NOT SHOW
--
-- Staff at Toowong can see Park Ridge's devices, their prices, their condition
-- and their store notes -- including devices still on the bench, because the
-- question "is one in the group anywhere" has to be answerable before it is
-- tested. They cannot see who sold it, that person's phone, address or ID, or
-- what the store paid. Seller identity is another store's customer's private
-- data, and purchase cost is already hidden from staff by
-- 20260912030000_hide_used_device_cost_from_staff. Widening the view must not
-- quietly widen either of those.

-- ---------------------------------------------------------------------------
-- 1. The ledger learns the three transfer events.
-- ---------------------------------------------------------------------------
alter table public.pos_used_device_transactions
  drop constraint if exists pos_used_device_transactions_transaction_type_check;

alter table public.pos_used_device_transactions
  add constraint pos_used_device_transactions_transaction_type_check
  check (transaction_type in (
    'acquisition', 'status_change', 'price_change', 'sale', 'refund_return',
    'returned_to_seller', 'disposal', 'detail_change',
    'transfer_out', 'transfer_in', 'transfer_cancelled'
  ));

-- ---------------------------------------------------------------------------
-- 2. The transfer record.
-- ---------------------------------------------------------------------------
create table if not exists public.pos_used_device_transfers (
  id bigint generated by default as identity primary key,
  transfer_code text not null unique,
  device_id bigint not null references public.pos_used_devices(id) on delete restrict,
  from_store_id bigint not null references public.store_locations(id) on delete restrict,
  to_store_id bigint not null references public.store_locations(id) on delete restrict,
  status text not null check (status in ('in_transit', 'received', 'cancelled')),
  -- What was actually handed over, frozen at dispatch. A later edit to the
  -- device cannot change this.
  device_snapshot jsonb not null,
  sent_by text not null,
  sent_at timestamptz not null default now(),
  sent_note text not null default '',
  received_by text,
  received_at timestamptz,
  received_note text not null default '',
  receipt_photo_url text not null default '',
  cancelled_by text,
  cancelled_at timestamptz,
  cancel_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pos_used_device_transfers_distinct_stores check (from_store_id <> to_store_id)
);

-- A device can only be on one journey at a time. This is what stops a device
-- being sent to two stores at once.
create unique index if not exists pos_used_device_transfers_one_active_idx
on public.pos_used_device_transfers (device_id)
where status = 'in_transit';

create index if not exists pos_used_device_transfers_to_store_idx
on public.pos_used_device_transfers (to_store_id, status, sent_at desc);

create index if not exists pos_used_device_transfers_from_store_idx
on public.pos_used_device_transfers (from_store_id, status, sent_at desc);

create index if not exists pos_used_device_transfers_device_idx
on public.pos_used_device_transfers (device_id, sent_at desc);

comment on table public.pos_used_device_transfers is
  'Store-to-store movement of a single second-hand device. Ownership changes on receipt, not dispatch; device_snapshot freezes what was sent.';

-- ---------------------------------------------------------------------------
-- 3. Payload shapers.
-- ---------------------------------------------------------------------------

-- What one store is allowed to see of another store's device: enough to answer
-- a customer and to ask for it, and nothing about the seller or the cost.
create or replace function public.pos_used_device_network_payload(device_row public.pos_used_devices)
returns jsonb
language sql
stable
set search_path = ''
as $network_payload$
  select jsonb_build_object(
    'id', device_row.device_code,
    'device_code', device_row.device_code,
    'store_code', store_location.store_code,
    'store_name', store_location.store_name,
    'category', device_row.category,
    'brand', device_row.brand,
    'model', device_row.model,
    'variant', device_row.variant,
    'color', device_row.color,
    'storage', device_row.storage,
    'imei', device_row.imei,
    'serial_number', device_row.serial_number,
    'condition_grade', device_row.condition_grade,
    'battery_health', device_row.battery_health,
    'clean_check_status', device_row.clean_check_status,
    'sale_price', device_row.sale_price,
    'status', device_row.status,
    -- The store's own memo. This is where "not tested yet", "screen has a
    -- scratch", "waiting on a back cover" lives, and it is the reason another
    -- store can judge whether to ask for it.
    'notes', device_row.notes,
    'photo_urls', device_row.photo_urls,
    'website_status', device_row.website_status,
    'acquired_at', device_row.acquired_at,
    'ready_at', device_row.ready_at,
    'updated_at', device_row.updated_at,
    'transfer', case
      when active_transfer.id is null then null
      else jsonb_build_object(
        'transfer_code', active_transfer.transfer_code,
        'status', active_transfer.status,
        'from_store_code', from_store.store_code,
        'from_store_name', from_store.store_name,
        'to_store_code', to_store.store_code,
        'to_store_name', to_store.store_name,
        'sent_by', active_transfer.sent_by,
        'sent_at', active_transfer.sent_at,
        'sent_note', active_transfer.sent_note
      )
    end
  )
  from public.store_locations store_location
  left join lateral (
    select transfer.*
    from public.pos_used_device_transfers transfer
    where transfer.device_id = device_row.id and transfer.status = 'in_transit'
    limit 1
  ) active_transfer on true
  left join public.store_locations from_store on from_store.id = active_transfer.from_store_id
  left join public.store_locations to_store on to_store.id = active_transfer.to_store_id
  where store_location.id = device_row.store_id;
$network_payload$;

create or replace function public.pos_used_device_transfer_payload(transfer_row public.pos_used_device_transfers)
returns jsonb
language sql
stable
set search_path = ''
as $transfer_payload$
  select jsonb_build_object(
    'id', transfer_row.transfer_code,
    'transfer_code', transfer_row.transfer_code,
    'status', transfer_row.status,
    'device_code', device.device_code,
    'from_store_code', from_store.store_code,
    'from_store_name', from_store.store_name,
    'to_store_code', to_store.store_code,
    'to_store_name', to_store.store_name,
    'sent_by', transfer_row.sent_by,
    'sent_at', transfer_row.sent_at,
    'sent_note', transfer_row.sent_note,
    'received_by', transfer_row.received_by,
    'received_at', transfer_row.received_at,
    'received_note', transfer_row.received_note,
    'receipt_photo_url', transfer_row.receipt_photo_url,
    'cancelled_by', transfer_row.cancelled_by,
    'cancelled_at', transfer_row.cancelled_at,
    'cancel_reason', transfer_row.cancel_reason,
    -- What was sent, as it read at dispatch.
    'device_snapshot', transfer_row.device_snapshot,
    -- What the device reads now, so a receiving store can compare the two.
    'device_now', jsonb_build_object(
      'brand', device.brand,
      'model', device.model,
      'variant', device.variant,
      'color', device.color,
      'storage', device.storage,
      'imei', device.imei,
      'serial_number', device.serial_number,
      'condition_grade', device.condition_grade,
      'battery_health', device.battery_health,
      'sale_price', device.sale_price,
      'status', device.status,
      'notes', device.notes,
      'photo_urls', device.photo_urls
    ),
    'created_at', transfer_row.created_at,
    'updated_at', transfer_row.updated_at
  )
  from public.pos_used_devices device
  join public.store_locations from_store on from_store.id = transfer_row.from_store_id
  join public.store_locations to_store on to_store.id = transfer_row.to_store_id
  where device.id = transfer_row.device_id;
$transfer_payload$;

-- ---------------------------------------------------------------------------
-- 4. The network view.
-- ---------------------------------------------------------------------------
create or replace function public.search_pos_used_device_network(
  session_token text,
  actor_store_code text,
  search_query text default '',
  target_status text default '',
  result_limit integer default 200
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $network_search$
declare
  actor jsonb;
  query_value text := trim(coalesce(search_query, ''));
  status_value text := trim(coalesce(target_status, ''));
  safe_limit integer := least(greatest(coalesce(result_limit, 200), 1), 500);
  devices_payload jsonb;
begin
  -- The caller is authorised against their OWN store, exactly as before. That
  -- is what proves they are staff. The widened read that follows is the point
  -- of this function, and it is limited to the reduced payload above.
  actor := public.pos_authorized_actor(session_token, actor_store_code, null);
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;

  if status_value <> '' and status_value not in
    ('inspection', 'ready_for_sale', 'sold', 'returned_to_seller', 'disposed') then
    raise exception 'Invalid device status';
  end if;

  select coalesce(
    jsonb_agg(public.pos_used_device_network_payload(device) order by
      -- Own store first: the fastest answer is the one in this building.
      case when device.store_id = (actor->>'store_id')::bigint then 0 else 1 end,
      case device.status when 'ready_for_sale' then 1 when 'inspection' then 2 else 3 end,
      device.sale_price
    ),
    '[]'::jsonb
  ) into devices_payload
  from (
    select used_device.*
    from public.pos_used_devices used_device
    join public.store_locations store_location on store_location.id = used_device.store_id
    where store_location.active = true
      and (
        case
          -- Default view is what is physically sitting in a store, tested or
          -- not. Sold and written-off devices are only shown when asked for.
          when status_value = '' then used_device.status in ('inspection', 'ready_for_sale')
          else used_device.status = status_value
        end
      )
      and (
        query_value = ''
        or used_device.device_code ilike '%' || query_value || '%'
        or used_device.brand ilike '%' || query_value || '%'
        or used_device.model ilike '%' || query_value || '%'
        or used_device.variant ilike '%' || query_value || '%'
        or used_device.color ilike '%' || query_value || '%'
        or used_device.storage ilike '%' || query_value || '%'
        or used_device.imei ilike '%' || query_value || '%'
        or used_device.serial_number ilike '%' || query_value || '%'
        or store_location.store_name ilike '%' || query_value || '%'
        or (used_device.brand || ' ' || used_device.model || ' ' || used_device.storage)
             ilike '%' || query_value || '%'
      )
    order by used_device.updated_at desc
    limit safe_limit
  ) device;

  return jsonb_build_object(
    'ok', true,
    'store_code', actor->>'store_code',
    'store_name', actor->>'store_name',
    'devices', devices_payload,
    'stores', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'store_code', summary.store_code,
        'store_name', summary.store_name,
        'ready_count', summary.ready_count,
        'inspection_count', summary.inspection_count,
        'stock_retail', summary.stock_retail
      ) order by summary.store_name), '[]'::jsonb)
      from (
        select store_location.store_code,
               store_location.store_name,
               count(*) filter (where used_device.status = 'ready_for_sale') as ready_count,
               count(*) filter (where used_device.status = 'inspection') as inspection_count,
               coalesce(sum(used_device.sale_price)
                 filter (where used_device.status in ('inspection', 'ready_for_sale')), 0) as stock_retail
        from public.store_locations store_location
        left join public.pos_used_devices used_device
          on used_device.store_id = store_location.id
         and used_device.status in ('inspection', 'ready_for_sale')
        where store_location.active = true and store_location.store_code <> 'warehouse'
        group by store_location.store_code, store_location.store_name
      ) summary
    )
  );
end;
$network_search$;

-- ---------------------------------------------------------------------------
-- 5. Send.
-- ---------------------------------------------------------------------------
create or replace function public.send_pos_used_device_transfer(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $send_transfer$
declare
  actor jsonb;
  from_store_id bigint;
  to_store public.store_locations%rowtype;
  device_row public.pos_used_devices%rowtype;
  transfer_row public.pos_used_device_transfers%rowtype;
  note_value text := left(btrim(coalesce(payload->>'note', '')), 500);
begin
  if jsonb_typeof(payload) <> 'object' then raise exception 'Payload must be an object'; end if;

  actor := public.pos_authorized_actor(
    session_token,
    coalesce(payload->>'store_code', ''),
    nullif(btrim(coalesce(payload->>'staff_name', '')), '')
  );
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  from_store_id := (actor->>'store_id')::bigint;

  select * into to_store
  from public.store_locations
  where active = true
    and store_code <> 'warehouse'
    and store_code = lower(btrim(coalesce(payload->>'to_store_code', '')));
  if not found then raise exception 'Destination store not found'; end if;
  if to_store.id = from_store_id then raise exception 'A device cannot be sent to the store it is already in'; end if;

  select * into device_row
  from public.pos_used_devices
  where device_code = btrim(coalesce(payload->>'device_code', ''))
  for update;
  if not found then raise exception 'Used device not found'; end if;

  -- Only the store holding the device may send it.
  if device_row.store_id <> from_store_id then
    raise exception 'This device is held by another store, so it cannot be sent from here';
  end if;

  if device_row.status not in ('inspection', 'ready_for_sale') then
    raise exception 'Only a device still in stock can be transferred. This one is %',
      replace(device_row.status, '_', ' ');
  end if;

  if exists (
    select 1 from public.pos_used_device_transfers
    where device_id = device_row.id and status = 'in_transit'
  ) then
    raise exception 'This device is already in transit';
  end if;

  insert into public.pos_used_device_transfers (
    transfer_code, device_id, from_store_id, to_store_id, status,
    device_snapshot, sent_by, sent_note
  ) values (
    'DTR-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12)),
    device_row.id,
    from_store_id,
    to_store.id,
    'in_transit',
    jsonb_build_object(
      'device_code', device_row.device_code,
      'category', device_row.category,
      'brand', device_row.brand,
      'model', device_row.model,
      'variant', device_row.variant,
      'color', device_row.color,
      'storage', device_row.storage,
      'imei', device_row.imei,
      'serial_number', device_row.serial_number,
      'condition_grade', device_row.condition_grade,
      'battery_health', device_row.battery_health,
      'clean_check_status', device_row.clean_check_status,
      'sale_price', device_row.sale_price,
      'status', device_row.status,
      'notes', device_row.notes,
      'photo_urls', device_row.photo_urls,
      'snapshot_taken_at', now()
    ),
    actor->>'staff_name',
    note_value
  ) returning * into transfer_row;

  -- The device stays owned by the sender until the other end accepts it, but
  -- it is withdrawn from sale immediately: it is not on this shelf any more.
  if device_row.status = 'ready_for_sale' then
    update public.pos_used_devices
    set status = 'inspection', ready_at = null, updated_by = actor->>'staff_name', updated_at = now()
    where id = device_row.id
    returning * into device_row;
  end if;

  insert into public.pos_used_device_transactions (
    transaction_code, device_id, store_id, transaction_type, from_status, to_status,
    amount, payment_method, staff_name, counterparty_name, counterparty_phone,
    notes, transaction_payload
  ) values (
    'UDTX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)),
    device_row.id, from_store_id, 'transfer_out', device_row.status, device_row.status,
    0, '', actor->>'staff_name', to_store.store_name, '',
    case when note_value = '' then 'Sent to ' || to_store.store_name
         else 'Sent to ' || to_store.store_name || ': ' || note_value end,
    jsonb_build_object(
      'transfer_code', transfer_row.transfer_code,
      'to_store_code', to_store.store_code,
      'device_snapshot', transfer_row.device_snapshot
    )
  );

  return jsonb_build_object(
    'ok', true,
    'transfer', public.pos_used_device_transfer_payload(transfer_row)
  );
end;
$send_transfer$;

-- ---------------------------------------------------------------------------
-- 6. Receive. This is the moment ownership moves.
-- ---------------------------------------------------------------------------
create or replace function public.receive_pos_used_device_transfer(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $receive_transfer$
declare
  actor jsonb;
  receiving_store_id bigint;
  transfer_row public.pos_used_device_transfers%rowtype;
  device_row public.pos_used_devices%rowtype;
  from_store public.store_locations%rowtype;
  note_value text := left(btrim(coalesce(payload->>'note', '')), 500);
begin
  if jsonb_typeof(payload) <> 'object' then raise exception 'Payload must be an object'; end if;

  actor := public.pos_authorized_actor(
    session_token,
    coalesce(payload->>'store_code', ''),
    nullif(btrim(coalesce(payload->>'staff_name', '')), '')
  );
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  receiving_store_id := (actor->>'store_id')::bigint;

  select * into transfer_row
  from public.pos_used_device_transfers
  where transfer_code = btrim(coalesce(payload->>'transfer_code', ''))
  for update;
  if not found then raise exception 'Transfer not found'; end if;

  if transfer_row.status <> 'in_transit' then
    raise exception 'This transfer was already %', transfer_row.status;
  end if;

  -- Only the destination can accept it. A store cannot receive a device into
  -- itself that was never sent to it.
  if transfer_row.to_store_id <> receiving_store_id then
    raise exception 'This transfer was not sent to your store';
  end if;

  select * into from_store from public.store_locations where id = transfer_row.from_store_id;

  select * into device_row
  from public.pos_used_devices
  where id = transfer_row.device_id
  for update;
  if not found then raise exception 'Used device not found'; end if;

  update public.pos_used_device_transfers
  set status = 'received',
      received_by = actor->>'staff_name',
      received_at = now(),
      received_note = note_value,
      receipt_photo_url = left(btrim(coalesce(payload->>'receipt_photo_url', '')), 500),
      updated_at = now()
  where id = transfer_row.id
  returning * into transfer_row;

  -- The device is now this store's. It lands on the bench, not the shelf: the
  -- receiving store confirms condition before it sells something it has not
  -- looked at.
  update public.pos_used_devices
  set store_id = receiving_store_id,
      status = 'inspection',
      ready_at = null,
      updated_by = actor->>'staff_name',
      updated_at = now()
  where id = device_row.id
  returning * into device_row;

  insert into public.pos_used_device_transactions (
    transaction_code, device_id, store_id, transaction_type, from_status, to_status,
    amount, payment_method, staff_name, counterparty_name, counterparty_phone,
    notes, transaction_payload
  ) values (
    'UDTX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)),
    device_row.id, receiving_store_id, 'transfer_in', 'inspection', device_row.status,
    0, '', actor->>'staff_name', from_store.store_name, '',
    case when note_value = '' then 'Received from ' || from_store.store_name
         else 'Received from ' || from_store.store_name || ': ' || note_value end,
    jsonb_build_object(
      'transfer_code', transfer_row.transfer_code,
      'from_store_code', from_store.store_code,
      'device_snapshot', transfer_row.device_snapshot,
      'receipt_photo_url', transfer_row.receipt_photo_url
    )
  );

  return jsonb_build_object(
    'ok', true,
    'transfer', public.pos_used_device_transfer_payload(transfer_row)
  );
end;
$receive_transfer$;

-- ---------------------------------------------------------------------------
-- 7. Cancel, for when the device never actually left.
-- ---------------------------------------------------------------------------
create or replace function public.cancel_pos_used_device_transfer(session_token text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $cancel_transfer$
declare
  actor jsonb;
  acting_store_id bigint;
  transfer_row public.pos_used_device_transfers%rowtype;
  device_row public.pos_used_devices%rowtype;
  to_store public.store_locations%rowtype;
  reason_value text := left(btrim(coalesce(payload->>'reason', '')), 500);
begin
  if jsonb_typeof(payload) <> 'object' then raise exception 'Payload must be an object'; end if;

  actor := public.pos_authorized_actor(
    session_token,
    coalesce(payload->>'store_code', ''),
    nullif(btrim(coalesce(payload->>'staff_name', '')), '')
  );
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  acting_store_id := (actor->>'store_id')::bigint;

  select * into transfer_row
  from public.pos_used_device_transfers
  where transfer_code = btrim(coalesce(payload->>'transfer_code', ''))
  for update;
  if not found then raise exception 'Transfer not found'; end if;
  if transfer_row.status <> 'in_transit' then
    raise exception 'This transfer was already %', transfer_row.status;
  end if;

  -- Only the store that sent it can recall it. Letting the destination cancel
  -- would let a store make a device it is holding disappear from the sender's
  -- books.
  if transfer_row.from_store_id <> acting_store_id then
    raise exception 'Only the sending store can cancel this transfer';
  end if;
  if reason_value = '' then raise exception 'A reason is required to cancel a transfer'; end if;

  select * into to_store from public.store_locations where id = transfer_row.to_store_id;

  update public.pos_used_device_transfers
  set status = 'cancelled',
      cancelled_by = actor->>'staff_name',
      cancelled_at = now(),
      cancel_reason = reason_value,
      updated_at = now()
  where id = transfer_row.id
  returning * into transfer_row;

  select * into device_row from public.pos_used_devices where id = transfer_row.device_id;

  insert into public.pos_used_device_transactions (
    transaction_code, device_id, store_id, transaction_type, from_status, to_status,
    amount, payment_method, staff_name, counterparty_name, counterparty_phone,
    notes, transaction_payload
  ) values (
    'UDTX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)),
    device_row.id, acting_store_id, 'transfer_cancelled', device_row.status, device_row.status,
    0, '', actor->>'staff_name', to_store.store_name, '',
    'Transfer to ' || to_store.store_name || ' cancelled: ' || reason_value,
    jsonb_build_object(
      'transfer_code', transfer_row.transfer_code,
      'to_store_code', to_store.store_code
    )
  );

  return jsonb_build_object(
    'ok', true,
    'transfer', public.pos_used_device_transfer_payload(transfer_row)
  );
end;
$cancel_transfer$;

-- ---------------------------------------------------------------------------
-- 8. The list a store works from.
-- ---------------------------------------------------------------------------
create or replace function public.get_pos_used_device_transfers(
  session_token text,
  target_store_code text,
  target_status text default '',
  result_limit integer default 100
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $list_transfers$
declare
  actor jsonb;
  store_id_value bigint;
  status_value text := trim(coalesce(target_status, ''));
  safe_limit integer := least(greatest(coalesce(result_limit, 100), 1), 300);
  transfers_payload jsonb;
begin
  actor := public.pos_authorized_actor(session_token, target_store_code, null);
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  store_id_value := (actor->>'store_id')::bigint;

  if status_value <> '' and status_value not in ('in_transit', 'received', 'cancelled') then
    raise exception 'Invalid transfer status';
  end if;

  select coalesce(
    jsonb_agg(public.pos_used_device_transfer_payload(transfer) order by
      -- What needs doing first: devices waiting to be accepted here.
      case when transfer.status = 'in_transit' and transfer.to_store_id = store_id_value then 0
           when transfer.status = 'in_transit' then 1
           else 2 end,
      transfer.sent_at desc
    ),
    '[]'::jsonb
  ) into transfers_payload
  from (
    select transfer_row.*
    from public.pos_used_device_transfers transfer_row
    where (transfer_row.from_store_id = store_id_value or transfer_row.to_store_id = store_id_value)
      and (status_value = '' or transfer_row.status = status_value)
    order by transfer_row.sent_at desc
    limit safe_limit
  ) transfer;

  return jsonb_build_object(
    'ok', true,
    'store_code', actor->>'store_code',
    'store_name', actor->>'store_name',
    'transfers', transfers_payload,
    'summary', (
      select jsonb_build_object(
        'incoming_count', count(*) filter (
          where status = 'in_transit' and to_store_id = store_id_value),
        'outgoing_count', count(*) filter (
          where status = 'in_transit' and from_store_id = store_id_value)
      )
      from public.pos_used_device_transfers
      where from_store_id = store_id_value or to_store_id = store_id_value
    )
  );
end;
$list_transfers$;

-- ---------------------------------------------------------------------------
-- 9. A device in transit cannot be sold.
--
-- Without this the sending store could still ring up a phone that is in a bag
-- on its way to another store. The sale trigger is the only place a used device
-- becomes a sale line, so the guard belongs there rather than in the page.
-- ---------------------------------------------------------------------------
do $patch_sale_guard$
declare
  definition text;
  patched text;
begin
  select pg_get_functiondef(oid) into definition
  from pg_proc
  where proname = 'prepare_pos_used_device_sale_line' and pronamespace = 'public'::regnamespace;
  if definition is null then raise exception 'prepare_pos_used_device_sale_line was not found'; end if;

  patched := replace(
    definition,
    $anchor$if device_row.status <> 'ready_for_sale' then raise exception 'Used device is no longer available for sale'; end if;$anchor$,
    $replacement$if device_row.status <> 'ready_for_sale' then raise exception 'Used device is no longer available for sale'; end if;
  if exists (
    select 1 from public.pos_used_device_transfers device_transfer
    where device_transfer.device_id = device_row.id and device_transfer.status = 'in_transit'
  ) then
    raise exception 'This device is in transit to another store and cannot be sold';
  end if;$replacement$
  );
  if patched = definition then
    raise exception 'used device transfer: the sale-guard anchor was not found';
  end if;
  execute patched;
end;
$patch_sale_guard$;

-- ---------------------------------------------------------------------------
-- 10. Grants. Browser-called through the edge function, which forwards the
--     staff session; every function above gates on that session itself.
-- ---------------------------------------------------------------------------
revoke all on function public.search_pos_used_device_network(text, text, text, text, integer) from public;
revoke all on function public.send_pos_used_device_transfer(text, jsonb) from public;
revoke all on function public.receive_pos_used_device_transfer(text, jsonb) from public;
revoke all on function public.cancel_pos_used_device_transfer(text, jsonb) from public;
revoke all on function public.get_pos_used_device_transfers(text, text, text, integer) from public;

grant execute on function public.search_pos_used_device_network(text, text, text, text, integer) to anon, authenticated, service_role;
grant execute on function public.send_pos_used_device_transfer(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.receive_pos_used_device_transfer(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.cancel_pos_used_device_transfer(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.get_pos_used_device_transfers(text, text, text, integer) to anon, authenticated, service_role;

grant execute on function public.pos_used_device_network_payload(public.pos_used_devices) to anon, authenticated, service_role;
grant execute on function public.pos_used_device_transfer_payload(public.pos_used_device_transfers) to anon, authenticated, service_role;

alter table public.pos_used_device_transfers enable row level security;

comment on function public.search_pos_used_device_network(text, text, text, text, integer) is
  'Every active store''s second-hand stock, including devices still being inspected. Deliberately excludes seller identity and purchase cost.';
comment on function public.send_pos_used_device_transfer(text, jsonb) is
  'Sends one used device to another store. Ownership does not move until the destination receives it.';
comment on function public.receive_pos_used_device_transfer(text, jsonb) is
  'Destination-only. Moves the device into the receiving store and puts it back on the bench.';
