-- Replace the legacy sales/repair/glass bonus board with the staff scorecard.
-- Google reviews are confirmed manually; device bundles are derived from paid invoices.

alter table public.pos_daily_targets
  add column if not exists points_target integer not null default 70
  check (points_target >= 0);

create table if not exists public.pos_monthly_targets (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  target_month date not null,
  staff_name text not null default '',
  normalized_staff_name text generated always as (lower(trim(staff_name))) stored,
  points_target integer not null check (points_target >= 0),
  updated_by text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pos_monthly_targets_first_day_check
    check (target_month = date_trunc('month', target_month)::date)
);

create unique index if not exists pos_monthly_targets_scope_unique
on public.pos_monthly_targets (store_id, target_month, normalized_staff_name)
where active = true;

create index if not exists pos_monthly_targets_lookup_idx
on public.pos_monthly_targets (store_id, target_month, normalized_staff_name)
where active = true;

drop trigger if exists pos_monthly_targets_set_updated_at on public.pos_monthly_targets;
create trigger pos_monthly_targets_set_updated_at
before update on public.pos_monthly_targets
for each row execute function public.set_updated_at();

create table if not exists public.pos_google_review_events (
  id bigint generated by default as identity primary key,
  event_code text not null unique,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  business_date date not null,
  staff_name text not null,
  normalized_staff_name text generated always as (lower(trim(staff_name))) stored,
  points integer not null default 5 check (points = 5),
  created_at timestamptz not null default now(),
  constraint pos_google_review_events_staff_required check (trim(staff_name) <> ''),
  constraint pos_google_review_events_code_required check (trim(event_code) <> '')
);

create index if not exists pos_google_review_events_progress_idx
on public.pos_google_review_events (store_id, business_date, normalized_staff_name, created_at);

alter table public.pos_monthly_targets enable row level security;
alter table public.pos_google_review_events enable row level security;

revoke all on public.pos_monthly_targets from public, anon, authenticated;
revoke all on public.pos_google_review_events from public, anon, authenticated;
grant select, insert, update on public.pos_monthly_targets to service_role;
grant select, insert on public.pos_google_review_events to service_role;

create or replace function public.pos_bundle_score_metrics(
  target_store_id bigint,
  date_from date,
  date_to date,
  target_staff_name text
)
returns table (
  bundle_order_count integer,
  device_count integer,
  accessory_count integer,
  bundle_points integer
)
language sql
stable
security definer
set search_path = ''
as $$
  with sale_orders as (
    select sales_order.id
    from public.pos_sales_orders sales_order
    where sales_order.store_id = target_store_id
      and sales_order.business_date between date_from and date_to
      and lower(trim(sales_order.staff_name)) = lower(trim(target_staff_name))
  ),
  line_refunds as (
    select
      refund_line.sales_order_line_id,
      sum(refund_line.amount)::numeric(12,2) as refunded_amount
    from public.pos_sales_refund_lines refund_line
    join public.pos_sales_refunds refund on refund.id = refund_line.refund_id
    join sale_orders sales_order on sales_order.id = refund.sales_order_id
    where (refund.created_at at time zone 'Australia/Brisbane')::date between date_from and date_to
    group by refund_line.sales_order_line_id
  ),
  net_lines as (
    select
      sales_line.sales_order_id,
      sales_line.line_type,
      sales_line.category,
      sales_line.line_payload,
      greatest(0, sales_line.quantity - case
        when coalesce(line_refund.refunded_amount, 0) >= sales_line.line_total then sales_line.quantity
        when sales_line.unit_price > 0 and coalesce(line_refund.refunded_amount, 0) > 0 then least(
          sales_line.quantity,
          greatest(1, round(line_refund.refunded_amount / sales_line.unit_price)::integer)
        )
        else 0
      end)::integer as net_quantity
    from public.pos_sales_order_lines sales_line
    join sale_orders sales_order on sales_order.id = sales_line.sales_order_id
    left join line_refunds line_refund on line_refund.sales_order_line_id = sales_line.id
  ),
  classified_lines as (
    select
      net_line.*,
      (
        lower(coalesce(net_line.line_payload->>'is_used_device', 'false')) = 'true'
        or regexp_replace(lower(trim(net_line.category)), '[^a-z0-9]+', '', 'g') in (
          'device', 'devices', 'useddevice', 'useddevices', 'refurbisheddevice',
          'refurbisheddevices', 'mobilephone', 'mobilephones'
        )
      ) as is_device
    from net_lines net_line
    where net_line.net_quantity > 0
  ),
  order_units as (
    select
      classified_line.sales_order_id,
      coalesce(sum(classified_line.net_quantity) filter (where classified_line.is_device), 0)::integer as device_units,
      coalesce(sum(classified_line.net_quantity) filter (
        where not classified_line.is_device and classified_line.line_type = 'product'
      ), 0)::integer as accessory_units
    from classified_lines classified_line
    group by classified_line.sales_order_id
  ),
  qualifying_orders as (
    select *
    from order_units
    where device_units > 0 and accessory_units > 0
  )
  select
    count(*)::integer,
    coalesce(sum(qualifying_order.device_units), 0)::integer,
    coalesce(sum(qualifying_order.accessory_units), 0)::integer,
    coalesce(sum((qualifying_order.device_units + qualifying_order.accessory_units) * 5), 0)::integer
  from qualifying_orders qualifying_order;
$$;

create or replace function public.pos_today_progress_payload(
  target_store_id bigint,
  target_business_date date,
  target_staff_name text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_daily_target public.pos_daily_targets%rowtype;
  selected_monthly_target public.pos_monthly_targets%rowtype;
  staff_value text := trim(coalesce(target_staff_name, ''));
  date_value date := coalesce(target_business_date, (now() at time zone 'Australia/Brisbane')::date);
  month_value date;
  month_end_value date;
  remaining_days integer := 1;
  daily_points_target_value integer := 70;
  monthly_points_target_value integer := 0;
  monthly_earned_before_value integer := 0;
  monthly_remaining_points_value integer := 0;
  target_scope_value text := 'system_default';
  target_updated_by_value text := 'System default';
  review_count_value integer := 0;
  review_points_value integer := 0;
  bundle_today record;
  bundle_month record;
  progress_payload jsonb;
begin
  if target_store_id is null then raise exception 'Store is required'; end if;
  if staff_value = '' then raise exception 'Staff member is required'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.id = target_store_id
    and store_location.active = true
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  month_value := date_trunc('month', date_value)::date;
  month_end_value := (date_trunc('month', date_value) + interval '1 month - 1 day')::date;
  remaining_days := greatest(1, month_end_value - date_value + 1);

  select * into selected_daily_target
  from public.pos_daily_targets target
  where target.store_id = selected_store.id
    and target.active = true
    and target.business_date = date_value
    and (target.normalized_staff_name = '' or target.normalized_staff_name = lower(staff_value))
  order by (target.normalized_staff_name <> '') desc, target.updated_at desc
  limit 1;

  if found then
    daily_points_target_value := selected_daily_target.points_target;
    target_scope_value := case
      when selected_daily_target.normalized_staff_name <> '' then 'staff_date'
      else 'store_date'
    end;
    target_updated_by_value := selected_daily_target.updated_by;
  else
    select * into selected_monthly_target
    from public.pos_monthly_targets target
    where target.store_id = selected_store.id
      and target.active = true
      and target.target_month = month_value
      and (target.normalized_staff_name = '' or target.normalized_staff_name = lower(staff_value))
    order by (target.normalized_staff_name <> '') desc, target.updated_at desc
    limit 1;

    if found then
      monthly_points_target_value := selected_monthly_target.points_target;

      select coalesce(sum(review_event.points), 0)::integer
      into monthly_earned_before_value
      from public.pos_google_review_events review_event
      where review_event.store_id = selected_store.id
        and review_event.business_date between month_value and date_value - 1
        and review_event.normalized_staff_name = lower(staff_value);

      select * into bundle_month
      from public.pos_bundle_score_metrics(selected_store.id, month_value, date_value - 1, staff_value);

      monthly_earned_before_value := monthly_earned_before_value + coalesce(bundle_month.bundle_points, 0);
      monthly_remaining_points_value := greatest(0, monthly_points_target_value - monthly_earned_before_value);
      daily_points_target_value := case
        when monthly_remaining_points_value = 0 then 0
        else (ceil((monthly_remaining_points_value::numeric / remaining_days) / 5) * 5)::integer
      end;
      target_scope_value := case
        when selected_monthly_target.normalized_staff_name <> '' then 'staff_month'
        else 'store_month'
      end;
      target_updated_by_value := selected_monthly_target.updated_by;
    else
      select * into selected_daily_target
      from public.pos_daily_targets target
      where target.store_id = selected_store.id
        and target.active = true
        and target.business_date is null
        and (target.normalized_staff_name = '' or target.normalized_staff_name = lower(staff_value))
      order by (target.normalized_staff_name <> '') desc, target.updated_at desc
      limit 1;

      if found then
        daily_points_target_value := selected_daily_target.points_target;
        target_scope_value := case
          when selected_daily_target.normalized_staff_name <> '' then 'staff_default'
          else 'store_default'
        end;
        target_updated_by_value := selected_daily_target.updated_by;
      end if;
    end if;
  end if;

  select count(*)::integer, coalesce(sum(review_event.points), 0)::integer
  into review_count_value, review_points_value
  from public.pos_google_review_events review_event
  where review_event.store_id = selected_store.id
    and review_event.business_date = date_value
    and review_event.normalized_staff_name = lower(staff_value);

  select * into bundle_today
  from public.pos_bundle_score_metrics(selected_store.id, date_value, date_value, staff_value);

  with sale_orders as (
    select sales_order.*
    from public.pos_sales_orders sales_order
    where sales_order.store_id = selected_store.id
      and sales_order.business_date = date_value
      and lower(trim(sales_order.staff_name)) = lower(staff_value)
  ),
  sale_summary as (
    select
      coalesce(sum(sales_order.total), 0)::numeric(12,2) as gross_sales,
      count(*)::integer as invoice_count
    from sale_orders sales_order
  ),
  attributed_refunds as (
    select refund.*
    from public.pos_sales_refunds refund
    join public.pos_sales_orders original_order on original_order.id = refund.sales_order_id
    where refund.store_id = selected_store.id
      and (refund.created_at at time zone 'Australia/Brisbane')::date = date_value
      and lower(trim(original_order.staff_name)) = lower(staff_value)
  ),
  refund_summary as (
    select
      coalesce(sum(refund.amount), 0)::numeric(12,2) as refund_amount,
      count(*)::integer as refund_count
    from attributed_refunds refund
  ),
  repair_summary as (
    select count(*)::integer as completed_count
    from public.pos_repair_tickets repair_ticket
    where repair_ticket.store_id = selected_store.id
      and repair_ticket.ready_for_pickup_at is not null
      and (repair_ticket.ready_for_pickup_at at time zone 'Australia/Brisbane')::date = date_value
      and lower(public.pos_repair_completion_staff(repair_ticket)) = lower(staff_value)
      and coalesce(repair_ticket.resolution, 'repaired') = 'repaired'
  )
  select jsonb_build_object(
    'ok', true,
    'status', 'projected',
    'store_code', selected_store.store_code,
    'store_name', selected_store.store_name,
    'business_date', date_value,
    'staff_name', staff_value,
    'target_scope', target_scope_value,
    'target', jsonb_build_object(
      'points', daily_points_target_value,
      'source', target_scope_value,
      'updated_by', target_updated_by_value,
      'monthly_points', monthly_points_target_value,
      'monthly_earned_before_today', monthly_earned_before_value,
      'monthly_remaining_points', monthly_remaining_points_value,
      'remaining_days', remaining_days,
      'review_points_per_item', 5,
      'device_points_per_item', 5,
      'accessory_points_per_item', 5
    ),
    'metrics', jsonb_build_object(
      'google_review_count', review_count_value,
      'google_review_points', review_points_value,
      'bundle_order_count', coalesce(bundle_today.bundle_order_count, 0),
      'bundle_device_count', coalesce(bundle_today.device_count, 0),
      'bundle_accessory_count', coalesce(bundle_today.accessory_count, 0),
      'bundle_points', coalesce(bundle_today.bundle_points, 0),
      'gross_sales', sale_summary.gross_sales,
      'refunds', refund_summary.refund_amount,
      'net_sales', sale_summary.gross_sales - refund_summary.refund_amount,
      'invoice_count', sale_summary.invoice_count,
      'refund_count', refund_summary.refund_count,
      'average_sale', case
        when sale_summary.invoice_count > 0 then round(sale_summary.gross_sales / sale_summary.invoice_count, 2)
        else 0
      end,
      'repair_count', repair_summary.completed_count
    ),
    'score', jsonb_build_object(
      'earned_points', review_points_value + coalesce(bundle_today.bundle_points, 0),
      'max_points', daily_points_target_value,
      'remaining_points', greatest(0, daily_points_target_value - review_points_value - coalesce(bundle_today.bundle_points, 0)),
      'projected_bonus', 0
    ),
    'last_updated_at', now()
  ) into progress_payload
  from sale_summary, refund_summary, repair_summary;

  return progress_payload;
end;
$$;

create or replace function public.record_pos_google_review(
  session_token text,
  target_store_code text,
  target_staff_name text,
  event_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_store public.store_locations%rowtype;
  selected_staff public.staff_directory%rowtype;
  date_value date := (now() at time zone 'Australia/Brisbane')::date;
  event_code_value text := trim(coalesce(event_code, ''));
begin
  if not public.is_valid_staff_session(session_token) then raise exception 'Invalid session'; end if;
  if event_code_value = '' then raise exception 'Review event id is required'; end if;

  select * into selected_store
  from public.store_locations store_location
  where store_location.active = true
    and store_location.store_code = coalesce(trim(target_store_code), '')
    and store_location.store_code <> 'warehouse';
  if not found then raise exception 'Store not found'; end if;

  select * into selected_staff
  from public.staff_directory staff
  where staff.active = true
    and lower(trim(staff.display_name)) = lower(trim(coalesce(target_staff_name, '')))
  limit 1;
  if not found then raise exception 'Staff member not found'; end if;

  if not exists (
    select 1
    from public.pos_store_shifts shift_record
    where shift_record.store_id = selected_store.id
      and shift_record.business_date = date_value
      and shift_record.status = 'open'
  ) then
    raise exception 'Google reviews can only be recorded during an open shift';
  end if;

  if exists (
    select 1
    from public.pos_daily_target_results result
    where result.store_id = selected_store.id
      and result.business_date = date_value
      and result.normalized_staff_name = lower(trim(selected_staff.display_name))
  ) then
    raise exception 'Today score has already been finalized';
  end if;

  insert into public.pos_google_review_events (
    event_code,
    store_id,
    business_date,
    staff_name,
    points
  ) values (
    event_code_value,
    selected_store.id,
    date_value,
    selected_staff.display_name,
    5
  )
  on conflict on constraint pos_google_review_events_event_code_key do nothing;

  return public.pos_today_progress_payload(selected_store.id, date_value, selected_staff.display_name);
end;
$$;

create or replace function public.finalize_pos_daily_target_results()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  staff_record record;
  progress_payload jsonb;
begin
  if new.status <> 'closed' or old.status = 'closed' then return new; end if;

  for staff_record in
    select distinct staff_name
    from (
      select trim(sales_order.staff_name) as staff_name
      from public.pos_sales_orders sales_order
      where sales_order.store_id = new.store_id
        and sales_order.business_date = new.business_date
      union all
      select public.pos_repair_completion_staff(repair_ticket) as staff_name
      from public.pos_repair_tickets repair_ticket
      where repair_ticket.store_id = new.store_id
        and repair_ticket.ready_for_pickup_at is not null
        and (repair_ticket.ready_for_pickup_at at time zone 'Australia/Brisbane')::date = new.business_date
        and coalesce(repair_ticket.resolution, 'repaired') = 'repaired'
      union all
      select trim(review_event.staff_name) as staff_name
      from public.pos_google_review_events review_event
      where review_event.store_id = new.store_id
        and review_event.business_date = new.business_date
      union all select trim(new.opened_by)
      union all select trim(new.current_staff_name)
      union all select trim(new.last_staff_name)
      union all select trim(coalesce(new.closed_by, ''))
    ) staff_names
    where staff_name <> ''
  loop
    progress_payload := public.pos_today_progress_payload(new.store_id, new.business_date, staff_record.staff_name);
    progress_payload := progress_payload || jsonb_build_object(
      'status', 'finalized',
      'finalized_at', coalesce(new.closed_at, now()),
      'finalized_by', coalesce(new.closed_by, new.last_staff_name),
      'shift_code', new.shift_code
    );

    insert into public.pos_daily_target_results (
      store_id,
      business_date,
      staff_name,
      shift_code,
      progress_payload,
      finalized_by,
      finalized_at
    ) values (
      new.store_id,
      new.business_date,
      staff_record.staff_name,
      new.shift_code,
      progress_payload,
      coalesce(new.closed_by, new.last_staff_name),
      coalesce(new.closed_at, now())
    )
    on conflict (store_id, business_date, normalized_staff_name)
    do update set
      staff_name = excluded.staff_name,
      shift_code = excluded.shift_code,
      progress_payload = excluded.progress_payload,
      finalized_by = excluded.finalized_by,
      finalized_at = excluded.finalized_at,
      updated_at = now();
  end loop;

  return new;
end;
$$;

revoke execute on function public.pos_bundle_score_metrics(bigint, date, date, text) from public, anon, authenticated;
revoke execute on function public.pos_today_progress_payload(bigint, date, text) from public, anon, authenticated;
revoke execute on function public.record_pos_google_review(text, text, text, text) from public, anon, authenticated;
revoke execute on function public.finalize_pos_daily_target_results() from public, anon, authenticated;

grant execute on function public.record_pos_google_review(text, text, text, text) to anon, authenticated, service_role;
