-- Photographic evidence and a running memo for second-hand devices.
--
-- The buyback register was text-only: `photo_urls` existed on the device row
-- but nothing ever wrote to it, and the single `notes` field was overwritten by
-- every save. This adds the same append-only comment/photo store the repair
-- board already uses, with a stage on each entry so intake evidence, seller ID,
-- refurbishment work and listing photos stay separable.
--
-- Intake photos are taken before the money moves. The POS uploads them against
-- a client-generated `intake_key` while the purchase form is still open, and
-- the acquisition claims them in the same transaction that pays the seller, so
-- a purchase without evidence cannot be saved at all.
--
-- Seller ID images are deliberately kept in their own bucket, are readable only
-- through an admin session, and every read is logged.

create table public.pos_used_device_updates (
  id uuid primary key,
  device_id bigint not null references public.pos_used_devices(id) on delete restrict,
  kind text not null check (kind in ('comment', 'photo')),
  stage text not null check (stage in ('intake', 'seller_id', 'refurb', 'listing')),
  body text not null default '' check (length(body) <= 5000),
  storage_path text unique,
  file_name text,
  author text not null,
  created_at timestamptz not null default now(),
  check ((kind = 'comment' and length(btrim(body)) > 0 and storage_path is null)
    or (kind = 'photo' and storage_path is not null))
);

create index pos_used_device_updates_device_date_idx
  on public.pos_used_device_updates (device_id, created_at desc);

create index pos_used_device_updates_stage_idx
  on public.pos_used_device_updates (device_id, stage)
  where kind = 'photo';

-- Evidence photographed before the device record exists. A row is claimed by
-- the acquisition that consumes it and is never reused.
create table public.pos_used_device_intake_uploads (
  id uuid primary key,
  store_id bigint not null references public.store_locations(id) on delete restrict,
  intake_key uuid not null,
  stage text not null check (stage in ('intake', 'seller_id')),
  storage_path text not null unique,
  file_name text,
  author text not null,
  created_at timestamptz not null default now(),
  claimed_device_id bigint references public.pos_used_devices(id) on delete restrict
);

create index pos_used_device_intake_uploads_open_idx
  on public.pos_used_device_intake_uploads (intake_key)
  where claimed_device_id is null;

-- Who looked at a seller's identity document, and when.
create table public.pos_used_device_id_photo_views (
  id bigint generated by default as identity primary key,
  update_id uuid not null references public.pos_used_device_updates(id) on delete restrict,
  viewer text not null,
  viewed_at timestamptz not null default now()
);

create index pos_used_device_id_photo_views_update_idx
  on public.pos_used_device_id_photo_views (update_id, viewed_at desc);

alter table public.pos_used_device_updates enable row level security;
alter table public.pos_used_device_intake_uploads enable row level security;
alter table public.pos_used_device_id_photo_views enable row level security;

revoke all on public.pos_used_device_updates from public, anon, authenticated;
revoke all on public.pos_used_device_intake_uploads from public, anon, authenticated;
revoke all on public.pos_used_device_id_photo_views from public, anon, authenticated;

grant all on public.pos_used_device_updates to service_role;
grant all on public.pos_used_device_intake_uploads to service_role;
grant all on public.pos_used_device_id_photo_views to service_role;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('used-device-photos', 'used-device-photos', false, 3145728, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('used-device-id-photos', 'used-device-id-photos', false, 3145728, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

-- Devices bought before evidence was collectable are exempt from the gates
-- below. Everything bought from here on carries its own proof.
alter table public.pos_used_devices
  add column evidence_required boolean not null default true;

update public.pos_used_devices set evidence_required = false;

-- Both portals use this gate. The browser supplies neither the author nor the
-- device id, and only an admin session may see identity documents.
create or replace function public.authorize_pos_used_device_evidence(session_token text, store_code text, device_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  device public.pos_used_devices%rowtype;
  admin_name text;
begin
  select * into device
  from public.pos_used_devices used_device
  where used_device.device_code = authorize_pos_used_device_evidence.device_code;
  if not found then raise exception 'Used device not found'; end if;
  if not exists (
    select 1 from public.store_locations store
    where store.id = device.store_id and store.store_code = authorize_pos_used_device_evidence.store_code
  ) then raise exception 'Used device belongs to another store'; end if;

  select coalesce(nullif(staff.display_name, ''), admin.login_email) into admin_name
    from public.admin_sessions sessions
    join public.admin_users admin on admin.id = sessions.admin_user_id
    left join public.staff_directory staff on lower(staff.email) = lower(admin.login_email) and staff.active
    where sessions.expires_at > now() and admin.active
      and extensions.crypt(session_token, sessions.session_hash) = sessions.session_hash
    limit 1;

  if admin_name is null then
    actor := public.pos_authorized_actor(session_token, store_code, null);
    if (actor->>'store_id')::bigint <> device.store_id then raise exception 'Store access denied'; end if;
    return jsonb_build_object(
      'ok', true, 'device_id', device.id, 'store_id', device.store_id,
      'author', actor->>'staff_name', 'is_admin', false,
      'writable', device.status not in ('returned_to_seller', 'disposed')
    );
  end if;

  return jsonb_build_object(
    'ok', true, 'device_id', device.id, 'store_id', device.store_id,
    'author', admin_name, 'is_admin', true,
    'writable', device.status not in ('returned_to_seller', 'disposed')
  );
end;
$$;

create or replace function public.get_pos_used_device_updates(session_token text, store_code text, device_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  is_admin boolean;
  result jsonb;
begin
  context := public.authorize_pos_used_device_evidence(session_token, store_code, device_code);
  is_admin := coalesce((context->>'is_admin')::boolean, false);

  -- Reading an identity document is itself an event worth recording.
  if is_admin then
    insert into public.pos_used_device_id_photo_views (update_id, viewer)
    select entry.id, context->>'author'
    from public.pos_used_device_updates entry
    where entry.device_id = (context->>'device_id')::bigint
      and entry.kind = 'photo'
      and entry.stage = 'seller_id';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', entry.id, 'kind', entry.kind, 'stage', entry.stage, 'body', entry.body,
    'storage_path', entry.storage_path, 'file_name', entry.file_name,
    'author', entry.author, 'created_at', entry.created_at
  ) order by entry.created_at desc, entry.id), '[]'::jsonb) into result
  from public.pos_used_device_updates entry
  where entry.device_id = (context->>'device_id')::bigint
    and (is_admin or entry.stage <> 'seller_id');

  return jsonb_build_object(
    'ok', true,
    'updates', result,
    'writable', context->'writable',
    'is_admin', is_admin
  );
end;
$$;

create or replace function public.add_pos_used_device_update(session_token text, store_code text, device_code text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  context jsonb;
  update_id uuid := (payload->>'id')::uuid;
  device_id_value bigint;
  stage_value text := coalesce(nullif(btrim(payload->>'stage'), ''), 'refurb');
  existing public.pos_used_device_updates%rowtype;
  path_value text;
  expected_bucket text;
begin
  context := public.authorize_pos_used_device_evidence(session_token, store_code, device_code);
  if not (context->>'writable')::boolean then raise exception 'Closed device records are read-only'; end if;
  device_id_value := (context->>'device_id')::bigint;
  perform id from public.pos_used_devices where id = device_id_value for update;

  if stage_value not in ('intake', 'seller_id', 'refurb', 'listing') then raise exception 'Invalid evidence stage'; end if;

  select * into existing from public.pos_used_device_updates where id = update_id;
  if found then
    if existing.device_id <> device_id_value
      or existing.author <> context->>'author'
      or existing.kind <> payload->>'kind'
      or existing.stage <> stage_value then raise exception 'Update ID already used'; end if;
    return jsonb_build_object('ok', true, 'id', existing.id);
  end if;

  if payload->>'kind' = 'photo' then
    path_value := payload->>'storage_path';
    if path_value is distinct from ((context->>'store_id') || '/' || device_id_value || '/' || update_id || '.jpg') then
      raise exception 'Invalid used device photo path';
    end if;
    expected_bucket := case when stage_value = 'seller_id' then 'used-device-id-photos' else 'used-device-photos' end;
    if not exists (select 1 from storage.objects where bucket_id = expected_bucket and name = path_value) then
      raise exception 'Photo upload is missing';
    end if;
  elsif payload->>'kind' is distinct from 'comment' then
    raise exception 'Invalid update type';
  end if;

  insert into public.pos_used_device_updates(id, device_id, kind, stage, body, storage_path, file_name, author)
  values (
    update_id, device_id_value, payload->>'kind', stage_value,
    btrim(coalesce(payload->>'body', '')), path_value,
    left(coalesce(payload->>'file_name', ''), 180), context->>'author'
  );
  return jsonb_build_object('ok', true, 'id', update_id);
end;
$$;

-- Evidence taken while the purchase form is still open, before a device record
-- exists to attach it to.
create or replace function public.stage_pos_used_device_intake_upload(session_token text, store_code text, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  upload_id uuid := (payload->>'id')::uuid;
  intake_key_value uuid := (payload->>'intake_key')::uuid;
  stage_value text := coalesce(nullif(btrim(payload->>'stage'), ''), 'intake');
  store_id_value bigint;
  path_value text := payload->>'storage_path';
  expected_bucket text;
  existing public.pos_used_device_intake_uploads%rowtype;
begin
  actor := public.pos_authorized_actor(session_token, store_code, null);
  store_id_value := (actor->>'store_id')::bigint;
  if upload_id is null or intake_key_value is null then raise exception 'Upload and intake ID are required'; end if;
  if stage_value not in ('intake', 'seller_id') then raise exception 'Invalid intake evidence stage'; end if;

  select * into existing from public.pos_used_device_intake_uploads where id = upload_id;
  if found then
    if existing.store_id <> store_id_value or existing.intake_key <> intake_key_value or existing.stage <> stage_value then
      raise exception 'Upload ID already used';
    end if;
    return jsonb_build_object('ok', true, 'id', existing.id);
  end if;

  if path_value is distinct from (store_id_value || '/' || intake_key_value || '/' || upload_id || '.jpg') then
    raise exception 'Invalid intake photo path';
  end if;
  expected_bucket := case when stage_value = 'seller_id' then 'used-device-id-photos' else 'used-device-photos' end;
  if not exists (select 1 from storage.objects where bucket_id = expected_bucket and name = path_value) then
    raise exception 'Photo upload is missing';
  end if;

  insert into public.pos_used_device_intake_uploads(id, store_id, intake_key, stage, storage_path, file_name, author)
  values (
    upload_id, store_id_value, intake_key_value, stage_value, path_value,
    left(coalesce(payload->>'file_name', ''), 180), actor->>'staff_name'
  );
  return jsonb_build_object('ok', true, 'id', upload_id);
end;
$$;

create or replace function public.get_pos_used_device_intake_uploads(session_token text, store_code text, intake_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor jsonb;
  result jsonb;
begin
  actor := public.pos_authorized_actor(session_token, store_code, null);
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', upload.id, 'stage', upload.stage, 'storage_path', upload.storage_path,
    'file_name', upload.file_name, 'author', upload.author, 'created_at', upload.created_at
  ) order by upload.created_at), '[]'::jsonb) into result
  from public.pos_used_device_intake_uploads upload
  where upload.intake_key = get_pos_used_device_intake_uploads.intake_key::uuid
    and upload.store_id = (actor->>'store_id')::bigint
    and upload.claimed_device_id is null;
  return jsonb_build_object('ok', true, 'uploads', result);
end;
$$;

-- Abandoned intake photos: rows are removed here and the returned paths are
-- deleted from storage by the caller.
create or replace function public.purge_pos_used_device_intake_uploads(older_than interval default interval '7 days')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed jsonb;
begin
  with deleted as (
    delete from public.pos_used_device_intake_uploads upload
    where upload.claimed_device_id is null
      and upload.created_at < now() - older_than
    returning upload.stage, upload.storage_path
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'bucket', case when deleted.stage = 'seller_id' then 'used-device-id-photos' else 'used-device-photos' end,
    'storage_path', deleted.storage_path
  )), '[]'::jsonb) into removed
  from deleted;
  return jsonb_build_object('ok', true, 'removed', removed);
end;
$$;

revoke all on function public.authorize_pos_used_device_evidence(text, text, text) from public, anon, authenticated;
revoke all on function public.get_pos_used_device_updates(text, text, text) from public, anon, authenticated;
revoke all on function public.add_pos_used_device_update(text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.stage_pos_used_device_intake_upload(text, text, jsonb) from public, anon, authenticated;
revoke all on function public.get_pos_used_device_intake_uploads(text, text, text) from public, anon, authenticated;
revoke all on function public.purge_pos_used_device_intake_uploads(interval) from public, anon, authenticated;

grant execute on function public.authorize_pos_used_device_evidence(text, text, text) to service_role;
grant execute on function public.get_pos_used_device_updates(text, text, text) to service_role;
grant execute on function public.add_pos_used_device_update(text, text, text, jsonb) to service_role;
grant execute on function public.stage_pos_used_device_intake_upload(text, text, jsonb) to service_role;
grant execute on function public.get_pos_used_device_intake_uploads(text, text, text) to service_role;
grant execute on function public.purge_pos_used_device_intake_uploads(interval) to service_role;

comment on table public.pos_used_device_updates is
  'Append-only comments and photographic evidence for a second-hand device. `stage` separates intake proof, seller identity, refurbishment work and listing photos.';

comment on table public.pos_used_device_intake_uploads is
  'Evidence photographed during a purchase, before the device record exists. Claimed by the acquisition that consumes it.';

comment on table public.pos_used_device_id_photo_views is
  'Every read of a seller identity document, with the admin who read it.';
