create table if not exists public.nl_report_config (
  id integer primary key default 1 check (id = 1),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

insert into public.nl_report_config (id, password_hash)
values (1, extensions.crypt('4509', extensions.gen_salt('bf', 12)))
on conflict (id) do nothing;

create table if not exists public.nl_report_sessions (
  id bigint generated by default as identity primary key,
  session_hash text not null unique,
  store_id bigint not null references public.store_locations(id),
  staff_id bigint not null references public.staff_directory(id),
  staff_name text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists nl_report_sessions_expires_at_idx on public.nl_report_sessions (expires_at);
create index if not exists nl_report_sessions_store_id_idx on public.nl_report_sessions (store_id);
create index if not exists nl_report_sessions_staff_id_idx on public.nl_report_sessions (staff_id);

create table if not exists public.nl_sales_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  store_id bigint not null references public.store_locations(id),
  store_name text not null,
  status text not null default 'draft',
  started_by_staff_id bigint not null references public.staff_directory(id),
  started_by_staff_name text not null,
  submitted_by_staff_name text not null default '',
  submitted_at timestamptz,
  confirmed_at timestamptz,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nl_sales_reports_store_date_unique unique (store_id, report_date),
  constraint nl_sales_reports_status_check check (status in ('draft', 'submitted', 'pricing_pending', 'priced', 'confirmed', 'settled'))
);

create index if not exists nl_sales_reports_date_idx on public.nl_sales_reports (report_date desc, store_id);
create index if not exists nl_sales_reports_started_by_staff_id_idx on public.nl_sales_reports (started_by_staff_id);

create table if not exists public.nl_sales_items (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.nl_sales_reports(id) on delete cascade,
  line_order integer not null default 1,
  product_name text not null,
  quantity integer not null default 1,
  sale_unit_price_inc_gst numeric(12,2) not null,
  invoice_number text not null default '',
  sale_notes text not null default '',
  entered_by_staff_name text not null,
  cost_unit_price_ex_gst numeric(12,2),
  cost_notes text not null default '',
  cost_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nl_sales_items_quantity_check check (quantity > 0),
  constraint nl_sales_items_sale_price_check check (sale_unit_price_inc_gst >= 0),
  constraint nl_sales_items_cost_price_check check (cost_unit_price_ex_gst is null or cost_unit_price_ex_gst >= 0)
);

create index if not exists nl_sales_items_report_idx on public.nl_sales_items (report_id, line_order, id);

drop trigger if exists nl_report_config_set_updated_at on public.nl_report_config;
create trigger nl_report_config_set_updated_at before update on public.nl_report_config
for each row execute function public.set_updated_at();
drop trigger if exists nl_sales_reports_set_updated_at on public.nl_sales_reports;
create trigger nl_sales_reports_set_updated_at before update on public.nl_sales_reports
for each row execute function public.set_updated_at();
drop trigger if exists nl_sales_items_set_updated_at on public.nl_sales_items;
create trigger nl_sales_items_set_updated_at before update on public.nl_sales_items
for each row execute function public.set_updated_at();

alter table public.nl_report_config enable row level security;
alter table public.nl_report_sessions enable row level security;
alter table public.nl_sales_reports enable row level security;
alter table public.nl_sales_items enable row level security;

drop policy if exists nl_report_config_no_direct_access on public.nl_report_config;
create policy nl_report_config_no_direct_access on public.nl_report_config for all to anon, authenticated using (false) with check (false);
drop policy if exists nl_report_sessions_no_direct_access on public.nl_report_sessions;
create policy nl_report_sessions_no_direct_access on public.nl_report_sessions for all to anon, authenticated using (false) with check (false);
drop policy if exists nl_sales_reports_no_direct_access on public.nl_sales_reports;
create policy nl_sales_reports_no_direct_access on public.nl_sales_reports for all to anon, authenticated using (false) with check (false);
drop policy if exists nl_sales_items_no_direct_access on public.nl_sales_items;
create policy nl_sales_items_no_direct_access on public.nl_sales_items for all to anon, authenticated using (false) with check (false);

revoke all on table public.nl_report_config from anon, authenticated;
revoke all on table public.nl_report_sessions from anon, authenticated;
revoke all on table public.nl_sales_reports from anon, authenticated;
revoke all on table public.nl_sales_items from anon, authenticated;

create or replace function public.is_valid_nl_report_session(session_token text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if coalesce(session_token, '') = '' then return false; end if;
  delete from public.nl_report_sessions where expires_at <= now();
  return exists (
    select 1 from public.nl_report_sessions
    where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex') and expires_at > now()
  );
end;
$$;

create or replace function public.create_nl_report_session(staff_session_token text, input_password text, target_staff_name text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  selected_staff public.staff_directory%rowtype;
  selected_store public.store_locations%rowtype;
  stored_hash text;
  raw_token text;
begin
  if not public.is_valid_staff_session(staff_session_token) then raise exception 'Invalid staff session'; end if;
  select password_hash into stored_hash from public.nl_report_config where id = 1;
  if stored_hash is null or extensions.crypt(coalesce(input_password, ''), stored_hash) <> stored_hash then
    raise exception 'Incorrect NL report password';
  end if;
  select * into selected_staff from public.staff_directory
  where active = true and display_name = coalesce(trim(target_staff_name), '');
  if not found then raise exception 'Staff member not found'; end if;
  select * into selected_store from public.store_locations where active = true and store_code = 'northlakes';
  if not found then raise exception 'North Lakes store not found'; end if;
  delete from public.nl_report_sessions where expires_at <= now();
  raw_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.nl_report_sessions (session_hash, store_id, staff_id, staff_name, expires_at)
  values (encode(extensions.digest(raw_token, 'sha256'), 'hex'), selected_store.id, selected_staff.id,
    selected_staff.display_name, now() + interval '12 hours');
  return jsonb_build_object('ok', true, 'session_token', raw_token, 'staff_name', selected_staff.display_name,
    'store_code', selected_store.store_code, 'store_name', selected_store.store_name,
    'expires_at', now() + interval '12 hours');
end;
$$;

create or replace function public.verify_nl_report_session(session_token text)
returns jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object('ok', public.is_valid_nl_report_session(session_token));
$$;

create or replace function public.revoke_nl_report_session(session_token text)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  delete from public.nl_report_sessions
  where session_hash = encode(extensions.digest(coalesce(session_token, ''), 'sha256'), 'hex');
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.get_nl_sales_report_json(target_report_id bigint)
returns jsonb language sql security definer set search_path = public as $$
  select jsonb_build_object(
    'id', report.id, 'report_date', report.report_date, 'store_name', report.store_name,
    'status', report.status, 'started_by_staff_name', report.started_by_staff_name,
    'submitted_by_staff_name', report.submitted_by_staff_name, 'submitted_at', report.submitted_at,
    'confirmed_at', report.confirmed_at, 'settled_at', report.settled_at, 'updated_at', report.updated_at,
    'sales_total_inc_gst', coalesce((select round(sum(item.sale_unit_price_inc_gst * item.quantity), 2)
      from public.nl_sales_items item where item.report_id = report.id), 0),
    'sales_gst', coalesce((select round(sum(item.sale_unit_price_inc_gst * item.quantity) / 11, 2)
      from public.nl_sales_items item where item.report_id = report.id), 0),
    'payable_total_inc_gst', coalesce((select round(sum(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity), 2)
      from public.nl_sales_items item where item.report_id = report.id and item.cost_unit_price_ex_gst is not null), 0),
    'payable_cost_ex_gst', coalesce((select round(sum(item.cost_unit_price_ex_gst * item.quantity), 2)
      from public.nl_sales_items item where item.report_id = report.id and item.cost_unit_price_ex_gst is not null), 0),
    'payable_gst', coalesce((select round(sum(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity) / 11, 2)
      from public.nl_sales_items item where item.report_id = report.id and item.cost_unit_price_ex_gst is not null), 0),
    'pending_cost_count', (select count(*) from public.nl_sales_items item
      where item.report_id = report.id and item.cost_unit_price_ex_gst is null),
    'items', coalesce((select jsonb_agg(jsonb_build_object(
      'id', item.id, 'line_order', item.line_order, 'product_name', item.product_name,
      'quantity', item.quantity, 'sale_unit_price_inc_gst', item.sale_unit_price_inc_gst,
      'sale_total_inc_gst', round(item.sale_unit_price_inc_gst * item.quantity, 2),
      'invoice_number', item.invoice_number, 'sale_notes', item.sale_notes,
      'entered_by_staff_name', item.entered_by_staff_name,
      'cost_unit_price_ex_gst', item.cost_unit_price_ex_gst,
      'cost_unit_price_inc_gst', case when item.cost_unit_price_ex_gst is null then null else round(item.cost_unit_price_ex_gst * 1.10, 2) end,
      'cost_total_inc_gst', case when item.cost_unit_price_ex_gst is null then null else round(round(item.cost_unit_price_ex_gst * 1.10, 2) * item.quantity, 2) end,
      'cost_notes', item.cost_notes, 'cost_updated_at', item.cost_updated_at
    ) order by item.line_order, item.id) from public.nl_sales_items item where item.report_id = report.id), '[]'::jsonb)
  ) from public.nl_sales_reports report where report.id = target_report_id;
$$;

create or replace function public.get_nl_sales_report_partner_json(target_report_id bigint)
returns jsonb language sql security definer set search_path = public as $$
  with base as (
    select public.get_nl_sales_report_json(target_report_id) as payload
  ), redacted_items as (
    select coalesce(jsonb_agg(
      (item.value
        - 'cost_unit_price_ex_gst'
        - 'cost_unit_price_inc_gst'
        - 'cost_total_inc_gst'
        - 'cost_notes'
        - 'cost_updated_at')
      || jsonb_build_object(
        'cost_unit_price_ex_gst', null,
        'cost_unit_price_inc_gst', null,
        'cost_total_inc_gst', null,
        'cost_notes', '',
        'cost_updated_at', null
      )
      order by (item.value->>'line_order')::integer
    ), '[]'::jsonb) as payload
    from base
    cross join lateral jsonb_array_elements(coalesce(base.payload->'items', '[]'::jsonb)) item
  )
  select case
    when base.payload->>'status' in ('confirmed', 'settled') then base.payload
    else base.payload || jsonb_build_object(
      'payable_total_inc_gst', 0,
      'payable_cost_ex_gst', 0,
      'payable_gst', 0,
      'pending_cost_count', jsonb_array_length(coalesce(base.payload->'items', '[]'::jsonb)),
      'items', redacted_items.payload
    )
  end
  from base cross join redacted_items;
$$;

create or replace function public.get_nl_sales_report(session_token text, target_date text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  session_row public.nl_report_sessions%rowtype;
  selected_report_id bigint;
  target_date_value date;
begin
  if not public.is_valid_nl_report_session(session_token) then raise exception 'Invalid NL report session'; end if;
  select * into session_row from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex') and expires_at > now();
  target_date_value := coalesce(nullif(target_date, '')::date, (now() at time zone 'Australia/Brisbane')::date);
  select id into selected_report_id from public.nl_sales_reports
  where store_id = session_row.store_id and report_date = target_date_value;
  return jsonb_build_object('ok', true, 'staff_name', session_row.staff_name, 'report_date', target_date_value,
    'report', case when selected_report_id is null then null else public.get_nl_sales_report_partner_json(selected_report_id) end);
end;
$$;

create or replace function public.save_nl_sales_report(session_token text, payload jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  session_row public.nl_report_sessions%rowtype;
  selected_store public.store_locations%rowtype;
  report_row public.nl_sales_reports%rowtype;
  target_date_value date;
  items_json jsonb;
  item_json jsonb;
  item_index integer := 0;
  item_quantity integer;
  item_sale_price numeric(12,2);
begin
  if not public.is_valid_nl_report_session(session_token) then raise exception 'Invalid NL report session'; end if;
  if jsonb_typeof(payload) <> 'object' then raise exception 'Payload must be an object'; end if;
  select * into session_row from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex') and expires_at > now();
  select * into selected_store from public.store_locations where id = session_row.store_id;
  target_date_value := coalesce(nullif(payload->>'report_date', '')::date, (now() at time zone 'Australia/Brisbane')::date);
  items_json := coalesce(payload->'items', '[]'::jsonb);
  if jsonb_typeof(items_json) <> 'array' then raise exception 'Items must be an array'; end if;
  if jsonb_array_length(items_json) > 500 then raise exception 'A report cannot contain more than 500 items'; end if;
  select * into report_row from public.nl_sales_reports
  where store_id = session_row.store_id and report_date = target_date_value for update;
  if not found then
    insert into public.nl_sales_reports (report_date, store_id, store_name, started_by_staff_id, started_by_staff_name)
    values (target_date_value, session_row.store_id, selected_store.store_name, session_row.staff_id, session_row.staff_name)
    returning * into report_row;
  elsif report_row.status <> 'draft' then
    raise exception 'This report has already been submitted and is read-only';
  end if;
  delete from public.nl_sales_items where report_id = report_row.id;
  for item_json in select value from jsonb_array_elements(items_json) loop
    item_index := item_index + 1;
    if coalesce(trim(item_json->>'product_name'), '') = '' then raise exception 'Product name is required on line %', item_index; end if;
    begin
      item_quantity := coalesce(nullif(item_json->>'quantity', '')::integer, 1);
      item_sale_price := nullif(item_json->>'sale_unit_price_inc_gst', '')::numeric(12,2);
    exception when others then raise exception 'Invalid quantity or sale price on line %', item_index;
    end;
    if item_quantity <= 0 then raise exception 'Quantity must be greater than zero on line %', item_index; end if;
    if item_sale_price is null or item_sale_price < 0 then raise exception 'Sale price is required on line %', item_index; end if;
    insert into public.nl_sales_items (report_id, line_order, product_name, quantity, sale_unit_price_inc_gst,
      invoice_number, sale_notes, entered_by_staff_name)
    values (report_row.id, item_index, trim(item_json->>'product_name'), item_quantity, item_sale_price,
      coalesce(trim(item_json->>'invoice_number'), ''), coalesce(trim(item_json->>'sale_notes'), ''), session_row.staff_name);
  end loop;
  update public.nl_sales_reports set updated_at = now() where id = report_row.id;
  return jsonb_build_object('ok', true, 'report', public.get_nl_sales_report_json(report_row.id));
end;
$$;

create or replace function public.submit_nl_sales_report(session_token text, target_date text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  session_row public.nl_report_sessions%rowtype;
  report_row public.nl_sales_reports%rowtype;
  target_date_value date;
begin
  if not public.is_valid_nl_report_session(session_token) then raise exception 'Invalid NL report session'; end if;
  select * into session_row from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex') and expires_at > now();
  target_date_value := coalesce(nullif(target_date, '')::date, (now() at time zone 'Australia/Brisbane')::date);
  select * into report_row from public.nl_sales_reports
  where store_id = session_row.store_id and report_date = target_date_value for update;
  if not found then raise exception 'Save the report before submitting it'; end if;
  if report_row.status <> 'draft' then raise exception 'This report has already been submitted'; end if;
  update public.nl_sales_reports set
    status = case when exists (select 1 from public.nl_sales_items item
      where item.report_id = report_row.id and item.cost_unit_price_ex_gst is null) then 'pricing_pending' else 'priced' end,
    submitted_by_staff_name = session_row.staff_name, submitted_at = now()
  where id = report_row.id;
  return jsonb_build_object('ok', true, 'report', public.get_nl_sales_report_json(report_row.id));
end;
$$;

create or replace function public.list_nl_sales_reports(session_token text, date_from text default null, date_to text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  session_row public.nl_report_sessions%rowtype;
  from_date_value date;
  to_date_value date;
  reports_json jsonb;
begin
  if not public.is_valid_nl_report_session(session_token) then raise exception 'Invalid NL report session'; end if;
  select * into session_row from public.nl_report_sessions
  where session_hash = encode(extensions.digest(session_token, 'sha256'), 'hex') and expires_at > now();
  to_date_value := coalesce(nullif(date_to, '')::date, (now() at time zone 'Australia/Brisbane')::date);
  from_date_value := coalesce(nullif(date_from, '')::date, date_trunc('month', to_date_value)::date);
  if from_date_value > to_date_value then raise exception 'From date cannot be after to date'; end if;
  if to_date_value - from_date_value > 366 then raise exception 'Date range cannot exceed 366 days'; end if;
  select coalesce(jsonb_agg(public.get_nl_sales_report_partner_json(report.id) order by report.report_date desc, report.id desc), '[]'::jsonb)
  into reports_json from public.nl_sales_reports report
  where report.store_id = session_row.store_id and report.report_date between from_date_value and to_date_value;
  return jsonb_build_object('ok', true, 'reports', reports_json);
end;
$$;

create or replace function public.get_nl_sales_reports_admin(session_token text, date_from text default null, date_to text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  from_date_value date;
  to_date_value date;
  reports_json jsonb;
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  to_date_value := coalesce(nullif(date_to, '')::date, (now() at time zone 'Australia/Brisbane')::date);
  from_date_value := coalesce(nullif(date_from, '')::date, date_trunc('month', to_date_value)::date);
  if from_date_value > to_date_value then raise exception 'From date cannot be after to date'; end if;
  if to_date_value - from_date_value > 366 then raise exception 'Date range cannot exceed 366 days'; end if;
  select coalesce(jsonb_agg(public.get_nl_sales_report_json(report.id) order by report.report_date desc, report.id desc), '[]'::jsonb)
  into reports_json from public.nl_sales_reports report
  join public.store_locations store on store.id = report.store_id
  where store.store_code = 'northlakes' and report.report_date between from_date_value and to_date_value;
  return jsonb_build_object('ok', true, 'reports', reports_json);
end;
$$;

create or replace function public.save_nl_report_costs(session_token text, target_report_id bigint, costs jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  report_row public.nl_sales_reports%rowtype;
  cost_json jsonb;
  item_id_value bigint;
  cost_value numeric(12,2);
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  if jsonb_typeof(costs) <> 'array' then raise exception 'Costs must be an array'; end if;
  select * into report_row from public.nl_sales_reports where id = target_report_id for update;
  if not found then raise exception 'NL report not found'; end if;
  if report_row.status in ('draft', 'confirmed', 'settled') then
    raise exception 'Costs can only be edited after submission and before confirmation';
  end if;
  for cost_json in select value from jsonb_array_elements(costs) loop
    item_id_value := nullif(cost_json->>'item_id', '')::bigint;
    cost_value := nullif(cost_json->>'cost_unit_price_ex_gst', '')::numeric(12,2);
    if item_id_value is null then raise exception 'Item id is required'; end if;
    if cost_value is not null and cost_value < 0 then raise exception 'Cost price cannot be negative'; end if;
    update public.nl_sales_items set cost_unit_price_ex_gst = cost_value,
      cost_notes = coalesce(trim(cost_json->>'cost_notes'), ''), cost_updated_at = now()
    where id = item_id_value and report_id = target_report_id;
    if not found then raise exception 'NL report item not found'; end if;
  end loop;
  update public.nl_sales_reports set status = case when exists (
    select 1 from public.nl_sales_items item where item.report_id = target_report_id and item.cost_unit_price_ex_gst is null
  ) then 'pricing_pending' else 'priced' end where id = target_report_id;
  return jsonb_build_object('ok', true, 'report', public.get_nl_sales_report_json(target_report_id));
end;
$$;

create or replace function public.update_nl_report_status(session_token text, target_report_id bigint, target_status text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  report_row public.nl_sales_reports%rowtype;
  next_status text;
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  next_status := lower(coalesce(trim(target_status), ''));
  select * into report_row from public.nl_sales_reports where id = target_report_id for update;
  if not found then raise exception 'NL report not found'; end if;
  if next_status = 'confirmed' then
    if report_row.status <> 'priced' then raise exception 'Every product needs a cost before confirmation'; end if;
    update public.nl_sales_reports set status = 'confirmed', confirmed_at = now() where id = target_report_id;
  elsif next_status = 'settled' then
    if report_row.status <> 'confirmed' then raise exception 'Confirm the report before marking it settled'; end if;
    update public.nl_sales_reports set status = 'settled', settled_at = now() where id = target_report_id;
  else
    raise exception 'Unsupported NL report status';
  end if;
  return jsonb_build_object('ok', true, 'report', public.get_nl_sales_report_json(target_report_id));
end;
$$;

create or replace function public.change_nl_report_password(session_token text, new_password text)
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  if not public.is_valid_admin_session(session_token) then raise exception 'Invalid admin session'; end if;
  if length(coalesce(trim(new_password), '')) < 4 then raise exception 'NL password must be at least 4 characters'; end if;
  update public.nl_report_config set password_hash = extensions.crypt(trim(new_password), extensions.gen_salt('bf', 12)) where id = 1;
  delete from public.nl_report_sessions;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.is_valid_nl_report_session(text) from public;
revoke all on function public.is_valid_nl_report_session(text) from anon, authenticated;
revoke all on function public.create_nl_report_session(text, text, text) from public;
revoke all on function public.verify_nl_report_session(text) from public;
revoke all on function public.revoke_nl_report_session(text) from public;
revoke all on function public.get_nl_sales_report_json(bigint) from public;
revoke all on function public.get_nl_sales_report_json(bigint) from anon, authenticated;
revoke all on function public.get_nl_sales_report_partner_json(bigint) from public;
revoke all on function public.get_nl_sales_report_partner_json(bigint) from anon, authenticated;
revoke all on function public.get_nl_sales_report(text, text) from public;
revoke all on function public.save_nl_sales_report(text, jsonb) from public;
revoke all on function public.submit_nl_sales_report(text, text) from public;
revoke all on function public.list_nl_sales_reports(text, text, text) from public;
revoke all on function public.get_nl_sales_reports_admin(text, text, text) from public;
revoke all on function public.save_nl_report_costs(text, bigint, jsonb) from public;
revoke all on function public.update_nl_report_status(text, bigint, text) from public;
revoke all on function public.change_nl_report_password(text, text) from public;

grant execute on function public.create_nl_report_session(text, text, text) to anon, authenticated;
grant execute on function public.verify_nl_report_session(text) to anon, authenticated;
grant execute on function public.revoke_nl_report_session(text) to anon, authenticated;
grant execute on function public.get_nl_sales_report(text, text) to anon, authenticated;
grant execute on function public.save_nl_sales_report(text, jsonb) to anon, authenticated;
grant execute on function public.submit_nl_sales_report(text, text) to anon, authenticated;
grant execute on function public.list_nl_sales_reports(text, text, text) to anon, authenticated;
grant execute on function public.get_nl_sales_reports_admin(text, text, text) to anon, authenticated;
grant execute on function public.save_nl_report_costs(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.update_nl_report_status(text, bigint, text) to anon, authenticated;
grant execute on function public.change_nl_report_password(text, text) to anon, authenticated;
